### ISSUE TITLE
Pandoc throws an error on valid latex

### ISSUE THREAD

**Issue by chiffa** [jgm/pandoc#3571] opened 2017-04-13 22:41 UTC
Upon transcoding latex to docx pandoc throws an error on a valid latex. 

Example of the (trimmed down file that is throwing the error) https://gist.github.com/chiffa/0f28ce4a69c0b2971ee85b4c05f66ece

command used to verify that the file works well:
`latex sample.tex`

command that led to the pandoc error: 
`pandoc -o sample.docx sample.tex`

Error contents:
```
Error at "input" (line 23, column 19):
unexpected end of input
expecting "\\"
q \sim \sum_{i=1}^{N} \frac{X_i^2}{\sigma_i^2},
                  ^
CallStack (from HasCallStack):
  error, called at src\Text\Pandoc\Error.hs:66:13 in pandoc-1.19.2.1-Be69MBOQd0gL4B1ReVbdJK:Text.Pandoc.Error
```

System information: 
Windows 10 Version 1703, build 15063.138
MiKTeX-pdfTex 2.9.6000 (1.40.17) (MiKTex 2,9 64-bit)
Pandoc 1.19.2.1

Might be related to #2114

**Comment by jgm** [comment] 2017-04-15 09:43
Closing as a duplicate of #982

**Closed by jgm** 2017-04-15 09:43 UTC
Labels: format:LaTeX, reader
