### ISSUE TITLE
LaTeX phantom sections generated by `pandoc --file-scope -t latex` don't align with start of file's content

### ISSUE THREAD

**Issue by max-heller** [jgm/pandoc#9200] opened 2023-11-18 19:42 UTC
**Explain the problem.**

When using `--file-scope` and `-t latex`, the phantom sections generated for each input file are placed before the start of the file's content. Links to these sections go to the end of the content immediately before the file's content instead of to the beginning of the file's content.

Clicking the "two" link in `output.pdf` generated by the following commands goes to the middle of the first page instead of the top of the second as it should:

```sh
echo "# Chapter One\n[two](two.md)" > one.md
echo "# Chapter Two" > two.md
pandoc -t latex --file-scope one.md two.md -o output.pdf -V documentclass=report
```

The corresponding LaTeX being generated (with `pandoc -t latex --file-scope one.md two.md`) is:

```tex
\phantomsection\label{one.md}
\section{Chapter One}\label{one.md__chapter-one}

\hyperref[two.md]{two}

\phantomsection\label{two.md}
\section{Chapter Two}\label{two.md__chapter-two}
```

Placing the `\phantomsection`s after the first line of content from each file instead of before each file overshoots in the other direction, linking to the part of the page after the chapter title.

Instead of generating a `\phantomsection` for files containing a heading at the start, maybe the file-level `\label` should be attached to the first heading?
This approach fixes the link:

```tex
\section{Chapter One}\label{one.md__chapter-one}\label{one.md}

\hyperref[two.md]{two}

\section{Chapter Two}\label{two.md__chapter-two}\label{two.md}
```

**Pandoc version?**

pandoc 3.1.9, MacOS 14.1

**Comment by jgm** [comment] 2023-11-18 23:13
The problem is that a file could have *any* sort of content. It might start with a heading, but it might not.  For example,  it might start with a three-page long verbatim environment.  So it's hard to see what the right *general* solution is.

**Comment by max-heller** [comment] 2023-11-18 23:43
> The problem is that a file could have _any_ sort of content. It might start with a heading, but it might not. For example, it might start with a three-page long verbatim environment. So it's hard to see what the right _general_ solution is.

Would you be opposed to fixing the (at least in my use case common) case where a file begins with a heading and falling back to the `\phantomsection` approach otherwise?

**Comment by jgm** [comment] 2023-11-19 18:08
I can look into that.

**Comment by jgm** [comment] 2024-04-21 05:04
Commit 30442b7f9d27150c249a8381fe8a5ca5a460db63 removes the addition of a special Div and identifier for the content from a file when `--file-scope` is used.  Hence closing this issue as no longer relevant.

In this case you could just link to `#one.md__chapter-one` and it should work properly.

**Closed by jgm** 2024-04-21 05:04 UTC
Labels: bug
