### ISSUE TITLE
Internal links sometimes incorrectly written with Org

### ISSUE THREAD

**Issue by tecosaur** [jgm/pandoc#6598] opened 2020-08-06 19:00 UTC
Hello,

Consider this simple markdown to org conversion, where we have an internal link to the heading `Demo`.

##### demo.md (in)

```md
See [Demo](#demo)

<a id="demo"></a>
# Demo
blah
```

##### demo.org (out)

```org
See [[#demo][Demo]]

* Demo
:PROPERTIES:
:CUSTOM_ID: demo
:END:
blah
```

This works perfectly. No problem at all.

...however, if you don't like the custom ID block, you can remove it by setting the `attr` of the heading to the `nullAttr` in a filter (see: [this line](https://github.com/jgm/pandoc/blob/57417feaf425d1943f9503f669ccba37898e395f/src/Text/Pandoc/Writers/Org.hs#L138) of Org.hs).

Now that the custom IDs have gone away as desired, the link syntax should change - as we no longer want to refer to a custom-id, a headline such as `#demo` should become `*Demo` - as `*<headline>` is Org's headline reference syntax (see 4.8 in the manual).

Pandoc currently does not do this, leading to broken links.

_pandoc 2.10_

**Comment by tarleb** [comment] 2020-08-06 20:06
How should the org writer know which header to link to if the ID is gone?

But since you are already using a filter, you could use the filter to also change the links.

**Comment by tecosaur** [comment] 2020-08-06 20:16
> How should the org writer know which header to link to if the ID is gone?

I haven't a clue, other than my brief perusal I have no understanding of the internals of org-mode, I just raised the 2nd most 'obvious' solution to me, since the 1st didn't (see below).

> But since you are already using a filter, you could use the filter to also change the links.

Ah yes, that's what I thought too - however, it seems that if I change the link (in a filter) to say `*Demo`, pandoc writes `[[file:*Demo][Demo]]` which is also incorrect and doesn't work.

**Comment by tarleb** [comment] 2020-08-06 20:23
Try this (untested):

``` lua
function Link (link)
  if link.target:sub(1,1) == '#' then
    return pandoc.List{pandoc.RawInline('org', '[[*' .. link.target:sub(2) .. '][')}
      .. link.content
      .. pandoc.List{pandoc.RawInline('org', ']]'}
  end
end

**Comment by tecosaur** [comment] 2020-08-06 20:40
Ah, so that doesn't quite work with multi-word links I'm afraid. Since pandoc transforms the heading text to get the link value, and the transformation appears to be non-bijective, it does not seem possible to fetch the headline value without pulling it from pandoc's conversion of headline-to-link somehow.

Take this example
```md
<a id="another-test"></a>
# Another test
```
This will, with your filter, will be transformed to
```org
[[*another-test][Another Test]]
* Another Test
```
Since `another-test` != `Another Test`, this will fail.

That said, without being sure of how pandoc forms the link values - it looks like it may be possible to use the link text instead.

**Comment by tarleb** [comment] 2020-08-06 21:45
You are correct, this was intended to get you started, not to work as a full solution.

Let's revisit the first question I asked: "How should the org writer know which header to link to if the ID is gone?" You said you don't know, and neither do I. Without an ID, there is no way of knowing where to link to. So one would have to replace the link before deleting the IDs.

1. Collect all header ids and map to header title;
2. Modify links by looking up ids and use title to create new link;
3. Delete header IDs.

This is out of scope for the org writer, thus closing. But you *can* write a filter for that. If you need more help with the filter, best to ask on pandoc-discuss (or maybe StackOverflow).

**Closed by tarleb** 2020-08-06 21:45 UTC
Labels: format:Org-mode, writer

**Comment by tecosaur** [comment] 2020-08-07 04:01
I see. To revisit as you have
> How should the org writer know which header to link to if the ID is gone?

Opening this issue I assumed/hoped that there would be some internal object from the link creation which the org writer could access - making resolving this as simple as a quick check.

I'm surprised to hear that it's possible to "Collect all header ids and map to header title" before processing any of the links - I thought a filter just worked through the AST in-order. I guess I've missed a way of defining multiple passes in a single filter.
I'll ask the mailing list that I guess. Thanks for considering this issue.

**Comment by tarleb** [comment] 2020-08-07 09:23
I gave it a go, here's what I came up with: https://gist.github.com/tarleb/1a78c3aacf917f362805ee1404689dbe

**Comment by tecosaur** [comment] 2020-08-07 13:01
Oh, fantastic! - much obliged. I just gave this a go and it seems to work nicely.
