### ISSUE TITLE
Update org-mode citations to org-cite

### ISSUE THREAD

**Issue by bdarcus** [jgm/pandoc#7329] opened 2021-05-29 16:15 UTC
With the forthcoming (soon) merger of native org-mode citations, I thought I'd add an issue.

My understanding is pandoc currently has support for the draft syntax that Richard and others worked on a few years ago.

The final version, by comparison:

1. tightens up the syntax ("cite:" is no longer optional)
2. removes the pandoc-inspired suppress-author variant on individual references; instead ...
3. adds citation level styles and variants

So final syntax (edited):

``` org
[cite/style/variant:global prefix ;cite prefix @key1 cite suffix;@key2; global suffix]
```

Example for an in-text citation, with `text` shortcut:

``` org
[cite/t:see @doe p.23]
```

I think internally, style/variant is in fact just "style" and export processors just split that string.

Here's the source code:

https://code.orgmode.org/bzg/org-mode/src/master/lisp/org-element.el#L2776

Here's a style mapping table @denismaier and I proposed:

https://gist.github.com/bdarcus/cd59dd2d54462cc8c2f0b737b2a1522c

... which is implemented in these export processors (where you can see the style -> command mappings directly):

1. [oc-biblatex](https://code.orgmode.org/bzg/org-mode/src/master/lisp/oc-biblatex.el)
2. [oc-natbib](https://code.orgmode.org/bzg/org-mode/src/master/lisp/oc-natbib.el)
3. [oc-csl](https://code.orgmode.org/bzg/org-mode/src/master/lisp/oc-csl.el)

Aside: it would be cool, and I hope someone does this at some point, to either adapt 3 to allow the pandoc citeproc as backend, or simply create a new processor based in it.

Upshot: pandoc citeproc would probably want to support these styles:

- `noauthor` (na); aka "suppress-author"
- `text` (t)

... and whatever else makes sense. For example, I added `locators` based on discussions here.

Important caveat: the style/variant feature does not hardcode any specific values. But I worked with the author on the ones included with the bundled export processors (oc-natbib, oc-biblatex, oc-csl), so they are consistent.

**Comment by bdarcus** [comment] 2021-07-09 09:39
Just by way of update, @jgm, org-cite is now in org-mode master.

**Comment by jgm** [comment] 2021-07-09 19:26
cc @tarleb

**Comment by a-fent** [comment] 2021-07-30 15:47
Would be great to see this updated. As a note, with my current Pandoc (2.13) there appear to be some inconsistencies between how pandoc-style cites and [cite: style are handled

`[First proposed in @foo_1999; developed in @bar_2001 22-23; see also @qux_2002]`

Produces (correctly, I think ) when processed with `--biblatex`
`\autocites[First proposed in][]{foo_1999}[developed in][
22-23]{bar_2001}[see also][]{qux_2002}`

Whereas 

`[cite: First proposed in @foo_1999; developed in @bar_2001 22-23; see also @qux_2002]`

Produces (with `--biblatex`)

`\textcite[First proposed in][]{foo_1999}, \textcite[developed in][ 22-23]{bar_2001}, \textcite[see also][]{qux_2002}`

As well as a slightly odd representation in markdown. This is, as I understand it, incompatible with the way the new org-mode code will treat it, i.e. something like the first (autocites).

**Comment by bdarcus** [comment] 2021-07-30 15:51
It's true `oc-biblatex` does prefer the style-agnostic commands, like autocite and friends, just to ensure greater portability of documents across the export backends.

As in, if you export to html using csl, you should get similar results as with biblatex.

But that's a minor issue; probably the bigger one I guess pandoc doesn't yet understand org-cite "styles" or "variants".

**Comment by denismaier** [comment] 2021-08-09 08:49
> Whereas
> 
> `[cite: First proposed in @foo_1999; developed in @bar_2001 22-23; see also @qux_2002]`
> 
> Produces (with `--biblatex`)
> 
> `\textcite[First proposed in][]{foo_1999}, \textcite[developed in][ 22-23]{bar_2001}, \textcite[see also][]{qux_2002}`

Currently, you'd still have to use the older berkeley-style citation syntax, so 

```
[(cite): First proposed in @foo_1999; developed in @bar_2001 22-23; see also @qux_2002]
```

**Comment by denismaier** [comment] 2021-08-09 08:56
@jgm @tarleb 
I've had a look at the relevant sections in org-mode reader. IIUC, [the reader](https://github.com/jgm/pandoc/blob/c0b68b2030ecdb4ad006443a56ce99aebc92fbc5/src/Text/Pandoc/Readers/Org/Inlines.hs#L162) defines three different citation formats that it tries in the following order:

1. Regular Berkeley style citations
2. Pandoc org citations
3. Org ref citations
4. Textual Berkeley style citations

Is the idea that all those options stay in there, with the new syntax being added? Like so:

```Haskell
cite :: PandocMonad m => OrgParser m (F Inlines)
cite = try $ orgCite <|> do
  guardEnabled Ext_citations
  (cs, raw) <- withRaw $ choice
               [ berkeleyCite 
               , pandocOrgCite
               , orgRefCite
               , berkeleyTextualCite
               ]
  return $ flip B.cite (B.text raw) <$> cs
```

 Or should that all be superseded by the new citation syntax?

**Comment by bdarcus** [comment] 2021-08-09 15:41
> Or should that all be superseded by the new citation syntax?

A very interesting question.

I tend to think yes, as it's a more general model, and would ease maintenance going forward.

But I'm sure not everyone would agree, and it's up to John in the end.

Certainly it should replace the draft syntax though; the two "Berkeley" variants?

I believe there may be some minor conflict between org-cite and org-ref. If that's the case and one had to make a choice, seems org-cite makes more sense, particularly given John has already rewritten org-ref (complete with a conversion script) for org-cite.

**Comment by jgm** [comment] 2021-08-09 17:49
@tarleb is the one to ask about this; I have never used citations with org and I don't know what's best.

**Comment by tecosaur** [comment] 2021-11-30 14:17
Based on the dark spot in @tarleb's commit activity, I have a suspicion the previous ping may have slipped by.

For what it's worth, as part of the Org mode project and a denizen of the mailing list, I have 2c to add:
This is now **the** citation syntax for Org, and I think it would make a lot of sense to be treated as such.

**Comment by tecosaur** [comment] 2021-11-30 14:20
Oh, and in case it's of any help implementing this, I did a bit of [an explainer of the new syntax](https://blog.tecosaur.com/tmio/2021-07-31-citations.html#cite-syntax) on my Org blog

![image](https://blog.tecosaur.com/tmio/figures/citation-structure-full.svg)

**Comment by tarleb** [comment] 2021-11-30 15:01
Nice, thanks! I did indeed miss that.

I'm still quite busy with improvements to Lua, figures, and tables. However, I'd be more than happy to help someone make the necessary changes, which would probably include a short intro to the current code.

**Comment by bdarcus** [comment] 2021-11-30 15:23
> This is now **the** citation syntax for Org, and I think it would make a lot of sense to be treated as such.

I agree: a single syntax for org (org-cite), a single syntax for pandoc markdown (pandoc), and robust conversion between them.

**Comment by denismaier** [comment] 2021-11-30 15:46
Not that I knew Haskell well enough, but looking into this is still on my todo list. So @tarleb ...

**Comment by tarleb** [comment] 2021-11-30 15:58
That's the nice thing about Haskell, it tells you if things look wrong and nudges programmers into the right direction. I mean, when I wrote the org reader I didn't understand half the things I was using at first.

If you're up for it, I'd be happy to setup another zoom call and do a Tour de Source.

**Comment by jgm** [comment] 2021-11-30 16:31
@tecosaur - the picture is great, but a formal grammar would be even nicer.
This would help us answer questions like:

- which elements are required, and which are optional?
- what characters are allowed in a citation key?
- how exactly is the locator distinguished from the suffix?
- what if you want a literal semicolon in a prefix - can it be backslash-escaped?

Given a formal grammar, it should be fairly easy to write the Haskell parser for this format.

**Comment by tecosaur** [comment] 2021-11-30 17:20
As of yet, https://orgmode.org/worg/dev/org-syntax.html has not been updated yet for citations. I'll contact the ML about that, but I've written a draft based on my understanding of the syntax and a little look at `org-element.el`.

There will likely be some tweaks that need to be made, but this should be broadly correct. The character classes for `KEYPREFIX` and `KEYSUFFIX` are basically the area I'm uncertain about. The structure described should be accurate.

Hopefully this is enough to allow for work to commence.

-----

Currently not documented, but from the implementation it looks something like this:

    [cite CITESTYLE: GLOBALPREFIX KEYCITES GLOBALSUFFIX]

The only mandatory component, `KEYCITES` consists of one or more instances of the pattern, separated by semicolons.

    KEYPREFIX @KEY KEYSUFFIX

`KEY` can be made of any word-constituent character, `-`, `.`, `:`, `?`, `!`, `` ` ``, `'`, `/`, `*`, `@`, `+`, `|`, `(`, `)`, `{`, `}`, `<`, `>`, `&`, `_`, `^`, `$`, `#`, `%`, `%`, or `~`.

I have not yet confirmed what `KEYPREFIX` and `KEYSUFFIX` may contain, but as a starting point, any of the characters allowed in `KEY` except `@` plus whitespace would seem fairly safe. `KEYSUFFIX` must start with a whitespace character to be able to be differentiated from `KEY`.

`CITESTYLE` consists of a main `STYLE` and any number of `VARIANT`s (including zero), prefixed by forwards slashes in the following pattern

    /STYLE/VARIANT/VARIANT/VARIANT

`STYLE` and `VARIANT` can be made of any alphanumeric character, `_`, or `-`.

`GLOBALPREFIX` and `GLOBALSUFFIX` can contain the same characters as `KEYPREFIX` and `KEYSUFFIX`, however `GLOBALPREFIX` must end with a semicolon, and `GLOBALSUFFIX` must start with a semicolon.

"cite" and `CITESTYLE`, `KEYCITES` and `GLOBALSUFFIX` are *not* separated by whitespace. Neither are `KEYPREFIX`, `@KEY`, or `KEYSUFFIX` separated by whitespace.

**Comment by denismaier** [comment] 2021-11-30 17:35
Don't forget that `cite` is now mandatory.

**Comment by tecosaur** [comment] 2021-11-30 17:38
It may not be obvious, but `[cite ... ]` is the template. All-caps are for the components, of which only `KEYCITES` is mandatory.

**Comment by denismaier** [comment] 2021-11-30 17:44
Yes. I just wanted to point out that unlike in the earlier wip-cite syntax there are no shortcuts anymore.

**Comment by jgm** [comment] 2021-11-30 20:57
What are the differences from the "Berkeley syntax" we now handle, described [here](https://pandoc.org/org.html)?
Should we continue to recognize the Berkeley syntax as well as the new one?

**Comment by bdarcus** [comment] 2021-11-30 21:25
> What are the differences from the "Berkeley syntax" we now handle, described [here](https://pandoc.org/org.html)? 

I think I itemized them in the main post.

This from doc you linked to is valid:

```org
[cite: See; @Mandelkern1981; and @Watson1953]
```

... and so this is correct, but incomplete:

```org
[cite: PREFIX; INDIVIDUAL-REFERENCE; ... INDIVIDUAL-REFERENCE; SUFFIX]
```

The addition is the optional style/variant syntax:

```org
[cite/text/caps:@doe]
```

This is no longer supported:

```org
[(cite): See; @Mandelkern1981; and @Watson1953]
```

In fact, parenthetical is just default, sans style or variant.

> Should we continue to recognize the Berkeley syntax as well as the new one?

I doubt it, but only you can know.

**Comment by denismaier** [comment] 2021-11-30 21:31
Also, as I've said above: no shorthands anymore. I.e., https://pandoc.org/org.html#simple-in-text-citation is not valid anymore.

**Comment by tarleb** [comment] 2021-11-30 21:32
> Should we continue to recognize the Berkeley syntax as well as the new one?

It's uptake had been minimal, it should be ok to drop the old syntax.

**Comment by bdarcus** [comment] 2021-12-01 13:22
> So in lisp, here the style is the `car` of the result, and the variants are the `cdr`:

I'm sure teco will add an update when done, but this is wrong. There is only one variant allowed, though a slash can be used within it.

**Comment by tecosaur** [comment] 2021-12-01 13:41
I've got some feedback from the ML. I'll try to update my draft in light of that tonight, and comment here when I've done so.

**Comment by tecosaur** [comment] 2021-12-02 06:51
**Updated draft**

---

Citations follow the pattern

    [cite CITESTYLE: GLOBALPREFIX KEYCITES GLOBALSUFFIX]

where "cite" and `CITESTYLE`, `KEYCITES` and `GLOBALSUFFIX` are *not* separated by whitespace. Whitespace after the leading colon or before the closing square bracket is not significant. All other whitespace is significant.

The only mandatory component, `KEYCITES` consists of one or more instances of the following pattern, separated by semicolons,

    KEYPREFIX @KEY KEYSUFFIX

where `KEYPREFIX`, `@KEY`, and `KEYSUFFIX` are *not* separated by whitespace.

`KEY` can be made of any word-constituent character, `-`, `.`, `:`, `?`, `!`, `` ` ``, `'`, `/`, `*`, `@`, `+`, `|`, `(`, `)`, `{`, `}`, `<`, `>`, `&`, `_`, `^`, `$`, `#`, `%`, or `~`.

`KEYPREFIX` and `KEYSUFFIX` are optional and can contain any characters other than a semicolon (`;`), so long as square brackets are balanced. `KEYPREFIX` cannot contain any subsequence that forms a `KEY`.

Hence, a minimal citation is formed by the pattern `[cite:@KEY]`.

`CITESTYLE` consists of a main `STYLE` and optionally a `VARIANT`. Both the `STYLE` and `VARIANT` are prefixed by a forwards slash.

    /STYLE/VARIANT

`STYLE` and `VARIANT` can be made of any alphanumeric character, `_`, or `-`. Additionally, `VARIANT` can itself contain forward slashes (`/`) .

`GLOBALPREFIX` and `GLOBALSUFFIX` can contain the same characters as `KEYPREFIX` and `KEYSUFFIX`. In the same manner as instances of the `KEYCITES` pattern, `KEYCITES`, `GLOBALPREFIX`, and `GLOBALSUFFIX` must be separated by semicolons.

**Comment by jgm** [comment] 2021-12-02 16:50
Condensing this with quasi-regex notation, I get
```
CITATION := '[' 'cite' CITESTYLE ':' WS GLOBALPREFIX? ITEMS GLOBALSUFFIX? WS ']'
CITESTYLE := '/' STYLE ('/' VARIANT)?
STYLE := [:alphanum:_-]+
VARIANT := [:alphanum:_/-]+
GLOBALPREFIX := AFFIX ';'
GLOBALSUFFIX := ';' AFFIX
AFFIX = ([^;\[\]]+ | INBALANCEDBRACKETS)*
ITEMS := ITEM (';' ITEM)*
ITEM := PREFIX? KEY SUFFIX?
PREFIX := AFFIX (not containing any subsequence that forms a key)
SUFFIX := AFFIX
```
Let me know if this seems right.

**Comment by jgm** [comment] 2021-12-02 16:52
In parsing this with pandoc, we'd presumably need to combine the global prefix/suffix with the first/last item prefix/suffix, since we don't have a separate notion of global prefix.

**Comment by denismaier** [comment] 2021-12-02 16:56
> In parsing this with pandoc, we'd presumably need to combine the global prefix/suffix with the first/last item prefix/suffix, since we don't have a separate notion of global prefix.

Would be good to have one though. WDYT?

**Comment by bdarcus** [comment] 2021-12-02 16:57
> In parsing this with pandoc, we'd presumably need to combine the global prefix/suffix with the first/last item prefix/suffix, since we don't have a separate notion of global prefix.

Yes, I believe that's the case.

FWIW, I think that global/local affix design came from biblatex, and it seems to me the primary use case are examples like this:

```org
A citation [cite:see ; @smith20;@doe].
```

As in, where the order of the prefix in this case is important, but the citations might be resorted by the style.

**Comment by tecosaur** [comment] 2021-12-02 17:10
Thanks John, I'll comment on your quasi-regex line by line.

```
CITATION := '[' 'cite' CITESTYLE ':' WS GLOBALPREFIX? ITEMS GLOBALSUFFIX? WS ']'
```

This looks correct, I'll just note that  `CITESTYLE` can be absent (in which case a default will be used).

`CITESTYLE`, `STYLE`, and `VARIANT` all look correct.

```
WS := [:space:]*
```

Yep. I don't know if this captures this, but newlines are allowed, you just can't have empty lines. This does apply beyond just `WS` though (along with all other inline Org elements). I imagine this is already taken care of in paragraph parsing.

```
GLOBALPREFIX := AFFIX ';'
GLOBALSUFFIX := ';' AFFIX
```

It looks like `;` isn't being treated as part of the actual content, which is correct.

...and everything else looks good to me too :slightly_smiling_face:.

**Comment by tecosaur** [comment] 2021-12-02 17:33
Oh, I forgot to answer your questions.

> Is it right that a key can contain an interior @, like @foo@bar?

Indeed.

> Is there any way to escape characters, e.g. to include an unbalanced [ in a prefix?

As the moment, I don't think so.

**Comment by jgm** [comment] 2021-12-11 17:55
I've updated my grammar above.

**Comment by jgm** [comment] 2021-12-11 17:58
Reproducing the style mapping here for convenience:

|               |                      |             |            |
|---------------|----------------------|-------------|------------|
| noauthor (na) | bare                 | citeyear    |            |
| noauthor (na) |                      | citeyearpar | autocite\* |
| locators (l)  | bare-caps (bc)       |             | Notecite   |
| locators (l)  | bare (b)             |             | notecite   |
| locators (l)  | caps (bc)            |             | Pnotecite  |
| locators (l)  |                      |             | pnotecite  |
| nocite (n)    |                      | nocite      | nocite     |
| text (t)      | bare (b)             | citealp     |            |
| text (t)      | caps (c)             | Citep       | Textcite   |
| text (t)      | full (f)             | citep\*     |            |
| text (t)      | bare-caps (bc)       | Citealp     |            |
| text (t)      | bare-full (bf)       | citealp\*   |            |
| text (t)      | caps-full (cf)       | Citep\*     |            |
| text (t)      | bare-caps-full (bcf) | Citealp\*   |            |
| text (t)      |                      |             | textcite   |
| (default)     | caps (c)             | Citep       | Autocite   |
| (default)     | bare (b)             | citealp     | cite       |
| (default)     | bare-caps (bc)       | Citealp     | Cite       |
| (default)     | full (f)             | citep\*     |            |
| (default)     | bare-full (bf)       | citealp     |            |
| (default)     | caps-full (cf)       | Citep\*     |            |
| (default)     | bare-caps-full (bcf) | Citealp\*   |            |
| (default)     |                      | citep       | autocite   |

**Comment by jgm** [comment] 2021-12-11 18:04
@tarleb it would be great to get your feedback on this. Changes to both the org reader and org writer would be needed.  We'd change the writer to output the new official org citation syntax.  The reader, as noted above, currently supports several different citation formats, which it tries in order.  The consensus in the discussion above seems to be that we should just support the official citation syntax (but this would break some earlier documents).  Parsing code would need to be written, but this should be fairly straightforward given the grammar and guide in the previous comment.

**Comment by tarleb** [comment] 2021-12-11 20:36
I'm on board with replacing most of the current code. I think org-ref citations should continue to be supported, but everything else is best replaced.

I could look into this after the holidays or early next year; of course, I won't mind the slightest if someone else finds some time before that.

**Comment by bdarcus** [comment] 2021-12-11 20:39
> I think org-ref citations should continue to be supported.

Which version?

Org-ref 3 adds a completely new syntax, that is basically the same model as org-cite, with trivial differences.

My suggestion is you don't support that, but only the legacy syntax.

**Comment by jgm** [comment] 2021-12-13 07:43
I've pushed preliminary support for this in the org writer, but it would be nice to have a little suite of test cases for markdown -> org citations.  Does anyone want to suggest some good tests?

**Comment by bdarcus** [comment] 2021-12-13 13:09
> I've pushed preliminary support for this in the org writer, but it would be nice to have a little suite of test cases for markdown -> org citations. Does anyone want to suggest some good tests?

Here's what I just tested with, and all of which worked as expected.

```console

- @test
- [@test]
- [-@test]
- [see @test p. 12]
- [@test1;@test2]
- [see @test1; @test2]
```

Perhaps @denismaier  or @tecosaur have some ideas for other, possibly tougher, tests?

**Comment by jgm** [comment] 2021-12-13 17:50
OK, I'm working on adding tests.
One question that arises is how locators are distinguished from suffixes.
Pandoc has code for extracting a locator from the beginning of a suffix; this is locale-specific, so in German you can say `S.` instead of `p.` for example.  But I don't know if org's treatment of this just assumes English abbreviations or is locale specific?  If locale specific, is the locale derived from the CSL style or a hardcoded list associated with some `lang` metadata field?

**Comment by jgm** [comment] 2021-12-13 20:11
Let me know if all of these tests look okay:
```
% pandoc -f markdown -t org
- @item1
- @item1 [p. 12]
- @item1 [p.12; see also @item2]
- [@item1]
- [-@item1]
- [see @item1 p. 12]
- [see @item1, p. 12]
- [see @item1, p. 12 and *passim*]
- [@item1;@item2]
- [see @item1; @item2]
^D
- [cite/t:@item1]
- [cite/t:@item1 p. 12]
- [cite/t:@item1 p.12; see also @item2]
- [cite:@item1]
- [cite/na:@item1]
- [cite:see @item1 p. 12]
- [cite:see @item1 p. 12]
- [cite:see @item1 p. 12 and /passim/]
- [cite:@item1; @item2]
- [cite:see @item1; @item2]
```

**Comment by jgm** [comment] 2021-12-14 19:35
OK, I've updated the org reader too.
Leaving this open pending testing with real-world cases....

**Comment by bdarcus** [comment] 2021-12-21 16:22
Just confirming that I converted some old markdown documents I had to org, and the results where perfect.

**Closed** 2021-12-21 17:09 UTC
Labels: format:Org-mode, reader, writer

**Comment by andersjohansson** [comment] 2022-03-10 19:42
This is great! I believe it would be reasonable to also convert a `#+printbibliography:` statement (used by the citation processor in org mode to insert a bibliography) to a `refs` div.

Otherwise, I can now go from native citations in org mode to active Zotero citations in odt/docx with the help of [Zotero Better Bibtex's Pandoc lua filter](https://retorque.re/zotero-better-bibtex/exporting/pandoc/), [ox-pandoc](https://github.com/emacsorphanage/ox-pandoc) and some very minor glue code in Emacs:

```emacs-lisp
(use-package ox-pandoc
  :custom (org-pandoc-options-for-odt
           '((lua-filter . "/home/aj/lib/bbt-pandoc-zotero.lua")
             (metadata . "zotero_author_in_text=true"))))

(org-cite-register-processor 'pandoc
  :export-citation #'oc-pandoc-export-citation
  :export-bibliography #'oc-pandoc-export-bibliography)

(defun oc-pandoc-export-citation (citation _style _ _info)
  "Export CITATION object in org format."
  (org-element-citation-interpreter
   citation
   (mapconcat (lambda (r) (org-element-citation-reference-interpreter r nil))
              (org-cite-get-references citation))))

(defun oc-pandoc-export-bibliography (_k _f _s _p _b _i)
  "Generate a #+print_bibliography:"
  "#+print_bibliography:")
```

**Comment by jgm** [comment] 2022-03-10 21:16
I'll suppport `#+print_bibliography:` to a Div with id `refs`.

**Comment by aminevsaziz** [comment] 2022-10-24 01:40
> This is great! I believe it would be reasonable to also convert a `#+printbibliography:` statement (used by the citation processor in org mode to insert a bibliography) to a `refs` div.
> 
> Otherwise, I can now go from native citations in org mode to active Zotero citations in odt/docx with the help of [Zotero Better Bibtex's Pandoc lua filter](https://retorque.re/zotero-better-bibtex/exporting/pandoc/), [ox-pandoc](https://github.com/emacsorphanage/ox-pandoc) and some very minor glue code in Emacs:
> 
> ```emacs-lisp
> (use-package ox-pandoc
>   :custom (org-pandoc-options-for-odt
>            '((lua-filter . "/home/aj/lib/bbt-pandoc-zotero.lua")
>              (metadata . "zotero_author_in_text=true"))))
> 
> (org-cite-register-processor 'pandoc
>   :export-citation #'oc-pandoc-export-citation
>   :export-bibliography #'oc-pandoc-export-bibliography)
> 
> (defun oc-pandoc-export-citation (citation _style _ _info)
>   "Export CITATION object in org format."
>   (org-element-citation-interpreter
>    citation
>    (mapconcat (lambda (r) (org-element-citation-reference-interpreter r nil))
>               (org-cite-get-references citation))))
> 
> (defun oc-pandoc-export-bibliography (_k _f _s _p _b _i)
>   "Generate a #+print_bibliography:"
>   "#+print_bibliography:")
> ```

@andersjohansson there an issue with org-element-citation-interpreter it show the following error:
org-element-citation-interpreter: Wrong number of arguments: mapconcat, 2.

**Comment by Carlos-M-D** [comment] 2022-11-03 18:34
Hi everyone!
First, I want to say thanks for your work.
I have found that org `nocite` style is not working.
I have this file:
```
#+title: Pruebas Csl
#+LANGUAGE: es-ES
#+cite_export: csl apa-no-ampersand.csl

* Título 1
Aliquam erat volutpat.  Nunc eleifend leo vitae magna.  [cite:@bernhart2015 34-35].

Bernhart [cite/noauthor:@bernhart2015] dice que...
* Título 2
Pellentesque dapibus suscipit ligula.  Donec posuere augue in quam. [cite:@bernhart2015]

[cite/n:@wolf1999]

* Bibliografía

#+print_bibliography:

```

The `nocite` style for the key is rendered as a regular citation `(Wolf 1999)`. I tried both with `[cite/nocite:@wolf1999]` and `[cite/n:@wolf1999]` and both options fail. I expected a behaviour similar to [Including uncited items in the bibliography](https://pandoc.org/MANUAL.html#including-uncited-items-in-the-bibliography) (Pandoc user's guide). 

I am using pandoc 2.19.2 (`.deb` package installed from Pandoc's webpage) in a Ubuntu 20.04.1 virtual machine.
Here it is the command line order:
`pandoc test.org -o test.pdf -C -N --bibliography=references.bib -f org -t pdf`

The `bib` file looks like this:
```
@book{bernhart2015,
  title = {Essays on Literature and Music (1985-2013) by {{Walter Bernhart}}},
  author = {Bernhart, Walter and Wolf, Werner},
  date = {2015},
  series = {Word and Music Studies},
  number = {volume 14},
  publisher = {{Brill/Rodopi}},
  location = {{Leiden ; Boston}},
  abstract = {},
  isbn = {978-90-04-30270-9},
  pagetotal = {503},
  keywords = {History and criticism,Literature,Music,Music and literature},
  annotation = {OCLC: 912278282}
}

@book{wolf1999,
  title = {The Musicalization of Fiction: {{A}} Study in the Theory and History of Intermediality},
  author = {Wolf, Werner},
  date = {1999},
  series = {Internationale Forschungen Zur Allgemeinen Und Vergleichende},
  publisher = {{Rodopi}},
  location = {{Amsterdam-Atlanta}},
  isbn = {978-90-420-0457-3}
}
```

**Comment by bdarcus** [comment] 2022-11-03 18:38
The org-cite styles are not static, and I'd guess `nocite` was added after initial support here.

Not sure how @jgm wants to handle that WRT to the issue tracker.

**Comment by jgm** [comment] 2022-11-03 18:42
Better to add a new issue for this.

**Comment by Carlos-M-D** [comment] 2022-11-03 18:53
Done! <https://github.com/jgm/pandoc/issues/8419#issue-1435121833>
