### ISSUE TITLE
Markdown reader parses fenced code blocks inside lists incorrectly

### ISSUE THREAD

**Issue by link2xt** [jgm/pandoc#4970] opened 2018-10-15 08:43 UTC
Example 1:
~~~
- ```
  first
  ```

- ```
second
  ```
~~~

Result 1:
~~~
<ul>
<li><pre><code>first</code></pre></li>
<li><pre><code>second</code></pre></li>
</ul>
~~~

Example 2:
~~~
- ```
first
```
~~~

Result 2:
~~~
<ul>
<li><pre><code>first</code></pre></li>
</ul>
~~~

But if I indent code inside two list items the same way, result is incorrect, for example:
~~~
- ```
first
```

- ```
second
```
~~~

Result is:
~~~
<ul>
<li>``` first</li>
</ul>
<pre><code>
- ```
second</code></pre>
~~~

**Comment by link2xt** [comment] 2018-10-15 11:06
GitHub parser and `pandoc -f commonmark` do not seem to work with anything except
~~~
- ```
  first
  ```

- ```
  second
  ```
~~~

**Comment by jgm** [comment] 2018-11-01 04:40
Markdown allows lazy (nonindented) continuation lines in lists, but the precise rules are vague. Commonmark interprets this as allowing only lazy paragraph continuation lines, which is consistent with pandoc's current behavior.  Lines that indicate block-level structure can't omit indentation.
Closing as not a bug.

**Closed by jgm** 2018-11-01 04:40 UTC
Labels: format:Markdown, reader
