### ISSUE TITLE
ODT Title Numbering not respecting template

### ISSUE THREAD

**Issue by abudden** [jgm/pandoc#2059] opened 2015-04-08 10:18 UTC
I am using pandoc 1.13.2 with a simple ODT template.  The template is set up to use outline numbering on the Heading 1, Heading 2 and Heading 3 styles.  When I run pandoc with the following command:

    pandoc -S --reference-odt=template.odt -o test_pandoc.odt test_pandoc.txt

The generated `test_pandoc.odt` file numbers the Title as `1.` and the first Heading 1 as `2.`  If I open it in LibreOffice and *re-apply* the Title style to the title, the title number disappears and everything is then correct.  This suggests to me that pandoc is overriding the outline numbering style in some way, although this seems a little implausible.

Platform: Windows 7
Pandoc Version: 1.13.2 (installed with installer)

The example pandoc file that I'm using is below and is also available at [this link][1].  The template is available at [this link][2] and the output of pandoc is at [this link][3].

I've tried various tweaks to the template to try to stop this from happening (such as making the title outline number 10 and setting outline number 10 **not** to have a number), but it makes no difference: the template doesn't seem able to affect the title numbering.

    % This is the document title
    % 
    % 8th April 2015
    
    # First Heading 1 section - No 1.
    
    ## Should be 1.1.
    
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non odio elementum, tempor velit nec, rhoncus ante. Nam ac odio a mi facilisis rutrum. Nunc rutrum ante et est consequat, vestibulum accumsan massa commodo. Suspendisse non finibus odio. Curabitur ac nulla viverra, accumsan nibh vel, tincidunt massa. Pellentesque lorem mi, finibus ac posuere vitae, tincidunt non nisi. Cras vulputate ante sit amet lacus elementum malesuada. Mauris ac ex non ex feugiat varius quis vitae diam. Aliquam metus lectus, convallis eu pharetra vel, faucibus id elit. Cras id vulputate dui, eget pellentesque magna. In venenatis magna et mauris malesuada, ut pellentesque elit sagittis.
    
    ## Should be 1.2.
    
    Proin non diam a dui ornare hendrerit. Phasellus sollicitudin nec tortor at tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec congue velit ac magna pretium, sit amet aliquet ipsum venenatis. Donec sit amet dapibus libero. Vestibulum ultrices, diam sit amet bibendum vestibulum, dolor ex tristique purus, ac vulputate magna massa ac orci. Nullam fringilla nisl magna, a ultricies nisi tempor id. Nullam orci urna, gravida eu orci in, viverra suscipit justo. Fusce vel egestas dui, venenatis pellentesque neque. Morbi egestas erat augue, vel ultricies ligula commodo vitae.
    
    # Should be 2.
    
    ## Should be 2.1.
    
    Vestibulum erat nulla, viverra quis tempus sed, placerat ut nunc. Donec id magna at orci iaculis ultrices at vitae dui. Suspendisse sapien metus, feugiat et nulla eu, bibendum imperdiet mauris. Suspendisse diam lacus, tincidunt ut laoreet in, elementum vitae nisi. Vestibulum ac lectus nunc. Pellentesque quis urna vel magna pharetra euismod vel sit amet eros. Proin sed sollicitudin nulla. Ut eu magna lacus. Proin tincidunt pretium nulla, vitae tincidunt leo venenatis non. Aliquam maximus ligula id mattis malesuada. In hac habitasse platea dictumst.
    
    

[1]: https://github.com/abudden/issue-attach/raw/master/pandoc-odt-title/test_pandoc.txt
[2]: https://github.com/abudden/issue-attach/blob/master/pandoc-odt-title/template.odt?raw=true
[3]: https://github.com/abudden/issue-attach/blob/master/pandoc-odt-title/test_pandoc.odt?raw=true

**Comment by nkalvi** [comment] 2015-04-09 01:58
>With ODF, you use <text:h> with text:outline-level to indicate the level of the header. For paragraphs in ODF, you use the <text:p> element.

Pandoc output you included has the *Title* output as `<text:h>` element instead of `<text:p>`, hence numbering was applied to it (confirmed it by manually editing the content.xml).

When you apply the Title style to an element in LibreOffice, it is written as  `<text:p>` element.
I'm not sure what should be the correct approach - perhaps @jgm  can comment on this.
I don't see any negative consequences for writing title as `<text:p>` elements, since TOC etc. can be easily customized to include the Title style. 

BTW, in your template Title style in assigned to outline level 10 - I'm not sure whether it was intentional or not.

**Closed** 2015-04-13 04:30 UTC
