### ISSUE TITLE
pandoc 2.7.3 test suite failure

### ISSUE THREAD

**Issue by peti** [jgm/pandoc#5582] opened 2019-06-14 14:35 UTC
I'm citing from https://hydra.nixos.org/build/94680819:

~~~
    latex
      writer
        basic:                                                       OK (0.28s)
        tables:                                                      OK (0.08s)
        lhs to normal:                                               FAIL (0.08s)
          
          ------------------------------------------------------------------------
          --- lhs-test.latex
          +++ /build/pandoc-2.7.3/dist/build/pandoc/pandoc --data-dir=../data --quiet lhs-test.native --wrap=preserve -r native -s -w latex
          +  97 \OtherTok{unsplit ::}\NormalTok{ (}\DataTypeTok{Arrow}\NormalTok{ a) }\OtherTok{=>}\NormalTok{ (b }\OtherTok{{-}>}\NormalTok{ c }\OtherTok{{-}>}\NormalTok{ d) }\OtherTok{{-}>}\NormalTok{ a (b, c) d}
          -  97 \OtherTok{unsplit ::}\NormalTok{ (}\DataTypeTok{Arrow}\NormalTok{ a) }\OtherTok{=>}\NormalTok{ (b }\OtherTok{->}\NormalTok{ c }\OtherTok{->}\NormalTok{ d) }\OtherTok{->}\NormalTok{ a (b, c) d}
          +  99           \CommentTok{{-}{-} arr (\textbackslash{}op (x,y) {-}> x \textasciigrave{}op\textasciigrave{} y)}
          -  99           \CommentTok{-- arr (\textbackslash{}op (x,y) -> x `op` y)}
          ------------------------------------------------------------------------
        lhs to lhs:                                                  OK (0.07s)
      reader
        basic:                                                       OK (0.20s)
        lhs:                                                         OK (0.06s)
~~~

**Comment by jgm** [comment] 2019-06-14 15:39
That's from changes in skylighting 0.8.1.1.  You can avoid it by adding a constraint to skylighting 0.8.1.
Next pandoc release will simply require skylighting 0.8.1.1, but I'm not sure what can be done about this one.

**Comment by jgm** [comment] 2019-06-14 15:41
I could add a Hackage revision, I suppose, constraining to skylighting >= 0.8.1.1.

**Comment by juhp** [comment] 2019-06-17 17:27
I don't think that helps - since this still occurs with skylighting-0.8.1.1.
(I am reproducing in the Stackage Nightly build.)
And see https://hydra.nixos.org/build/94680819#tabs-build-deps from peti's report.

**Comment by jgm** [comment] 2019-06-21 16:49
Oh, right.  The master branch has tests adjusted for skylighting 0.8.1.1 but the 2.7.3 release has tests adjusted for skylighting 0.8.1.  We'd need to add a constraint skylighting == 0.8.1 to the metadata for the release to ensure that tests pass. Probably worth doing that, right?

**Comment by juhp** [comment] 2019-06-22 15:19
Perhaps but currently Stackage Nightly has 2.7.3 and 0.8.1.1, I believe: I revision would be more correct I suppose

**Comment by jgm** [comment] 2019-06-23 23:24
So would a revision cause problems with stackage?

**Comment by juhp** [comment] 2019-11-06 14:58
I am not entirely sure, but
https://www.stackage.org/lts-14.7/package/skylighting-0.8.2
https://www.stackage.org/lts-14.8/package/skylighting-0.8.2.1

The safest would be to release a newer pandoc-2.7.x

**Comment by jgm** [comment] 2019-11-06 16:28
I plan to release pandoc 2.8 in the next couple weeks. That should take care of it.

**Comment by Anton-Latukha** [comment] 2020-06-04 21:47
`pandoc` now is `2.9.2.1`.

The `pandoc` test suite still fails inside Nixpkgs builds, so the package still has testing disabled.

**Comment by Anton-Latukha** [comment] 2020-06-04 22:12
Maybe, looking truthfully - this just would never be resolved, since it is an old version of `pandoc`, maybe Nixpkgs should migrate on `pandoc 2.9` by default.

**Comment by jgm** [comment] 2020-06-08 00:25
Agreed, best for nixpkgs to support a more recent version. 
I'll close this.

**Closed by jgm** 2020-06-08 00:25 UTC

**Comment by Anton-Latukha** [comment] 2020-06-08 11:55
Well, actually Nix has `pandoc 2.9.2` it just called `haskellPackages.pandoc_2_9_2_1`, someone created a side package probably because of migration incompatibility, but at this point there should be a migration.

**Comment by Anton-Latukha** [comment] 2020-06-08 13:23
Also, `pandoc` is updated, now `2.9.1.1` in `nixpkgs-unstable`, so this indeed closed.
