### ISSUE TITLE
Custom styles in docx template ignored for inline elements

### ISSUE THREAD

**Issue by mjfs** [jgm/pandoc#8149] opened 2022-06-23 16:49 UTC
Pandoc (2.18) ignores custom styles defined in `docx` template when they are used for inline elements (e.g. text wrapped in span with an attribute). Custom styles work as expected for block elements (e.g. text wrapped in div with an attribute).

The cause appears to be an incorrect reading of defined styles since attribute used in span appears in the docx output as a duplicated style carrying the same name as the one in the template.

Steps to reproduce:

1. Export default template `pandoc -o custom-reference.docx --print-default-data-file reference.docx`.

2. Add a custom style to `custom-reference.docx` - e.g. set font color as red in the style definition and name it `RedText`.

3. Create a `Red-text-doc.md` with the following content: `The following text has a custom style: [red colored text]{custom-style="RedText"}`

4. Convert md to docx with `pandoc --reference-doc=custom-reference.docx Red-text-doc.md -o Red-text-doc.docx`

5. See `RedText` appearing twice in the `Red-text-doc.docx` among the defined styles - one correct version from the template and one incorrect version created during the export.

**Comment by jgm** [comment] 2022-06-23 17:06
Here's what I see when I try your experiment:

<img width="502" alt="Screen Shot 2022-06-23 at 10 04 10 AM" src="https://user-images.githubusercontent.com/3044/175354991-696e8f19-5899-43eb-9c15-37d4a7d90cb5.png">

"Red" only appears once in the list of styles.  (Note: I used "Red" instead of "RedText" but that should not matter.)

In other words: I can't reproduce this.

**Comment by tarleb** [comment] 2022-08-03 18:30
I tried to reproduce this with LibreOffice Writer, but didn't succeed there either. Thus closing.

**Closed by tarleb** 2022-08-03 18:30 UTC
Labels: format:Docx, writer
