### ISSUE TITLE
Allow us to choose whether to enable smart extension when converting to PDF via LaTeX

### ISSUE THREAD

**Issue by nrth901** [jgm/pandoc#7535] opened 2021-08-31 18:07 UTC
Since smart extension wad disabled when creating PDF via LaTeX (https://github.com/jgm/pandoc/commit/0f5c56dfb171e27745f4fe8530325223ecefe52a), an error occurs with using LuaTeX-ja package.

The PDF is created properly, but the quotation marks (e.g. ``, ''), en dash (--), and em dash (---) are output in full-width characters.

If you output to TeX and then create a PDF, the problem does not occur.
I checked the TeX output in verbose mode when creating PDF with pandoc, and it seems that the above symbols have already been converted to unicode characters (e.g. -- to –, --- to —).

When the LuaTeX-ja package is loaded, the above symbols seem to be output in full-width characters.
It is possible to change them to half-width characters by setting on LuaTeX-ja side, but it is a little inconvenient in some cases that both are used in one text file.

If it is possible, I would like to be able to select whether to enable smart extension when converting to PDF.
I would appreciate it if you could support this.

--
Versions
Pandoc: v2.14.2
LuaTex: 1.13.2
LuaTex-ja: 20210607.0

**Comment by jgm** [comment] 2021-08-31 19:56
Duplicate of #7509 ?

**Comment by nrth901** [comment] 2021-08-31 20:15
It may be generally similar.
It would be appreciated if the extension is enabled when the metadata/variable include `CJKmainfont`.

**Comment by jgm** [comment] 2021-08-31 23:35
>  It would be appreciated if the extension is enabled when the metadata/variable include CJKmainfont.

That might be a good solution.

**Comment by nrth901** [comment] 2021-09-01 01:07
Sorry, I just remembered that I often use a self-defined variable to set all the fonts I normally use for convenience, so is it possible to define a different or new variable to switch the extension if possible?

**Comment by nrth901** [comment] 2021-09-01 01:35
It may also be necessary in the case of the metadata/variable `luatexjapresetoptions`.

**Comment by jgm** [comment] 2021-09-01 04:46
Closing as a duplicate of #7509.

**Closed by jgm** 2021-09-01 04:46 UTC
Labels: bug
