### ISSUE TITLE
a way for docx source code blocks to output as code blocks in html/markdown

### ISSUE THREAD

**Issue by masters3d** [jgm/pandoc#8138] opened 2022-06-20 17:41 UTC
**Describe your proposed improvement and the problem it solves.**g

I am trying to use docx as a source but I want to also add code blocks ( no formatting ) . Seem like other folks are also trying to do the same but I have not found a solution. 

https://www.reddit.com/r/pandoc/comments/g8vgxo/how_to_convert_docx_to_markdown_with_code_blocks/

**Describe alternatives you've considered.**

maybe export with styles but I have not figured out how to mark a text as code in docx.

**Comment by masters3d** [comment] 2022-06-20 17:53
I also tried using the insert object trick here  https://stackoverflow.com/a/2653406/3705470

but it just links a .emf file to my markdown.

**Comment by jgm** [comment] 2022-06-21 19:13
Closing as duplicate of #5971.

**Closed by jgm** 2022-06-21 19:13 UTC
Labels: enhancement
