### ISSUE TITLE
Markdown reader struggles with Custom Elements as raw HTML

### ISSUE THREAD

**Issue by danisson** [jgm/pandoc#2960] opened 2016-06-02 08:40 UTC
I have been using Pandoc 1.17.0.2 and I noticed something really weird when I use [custom elements](http://w3c.github.io/webcomponents/spec/custom/).
So, given the input:

```
<a-custom-element>
    <p>*test*</p>
</a-custom-element>

<div>
    <p>*test*</p>
</div>
```

I get:

```
<p><a-custom-element> <p><em>test</em></p> </a-custom-element></p>
<div>
    <p>*test*</p>
</div>
```

by running pandoc using `markdown_strict`.

Even if this was to be unsupported I would expect the angle brackets to be escaped in the output but they end up becoming regular HTML tags.

**Comment by jgm** [comment] 2016-06-23 17:38
I get something different:
```
<a-custom-element>
<p>
<em>test</em>
</p>
<p></a-custom-element></p>
```
Are you using an old version of pandoc?

This still isn't ideal, of course.

Note that part of the problem is that pandoc has no way of knowing whether your custom element is an inline (phrasing content) tag or block-level tag.  You intend it as a block-level tag.  But pandoc just uses a hardcoded list of known block-level tags.

CommonMark has thought this issue through in a more thoroughgoing way and behaves better.
https://talk.commonmark.org/t/raw-html-blocks-proposals-comments-wanted/983

**Comment by danisson** [comment] 2016-06-25 04:47
I'm using the version I wrote on the previous post and running it on Windows.

Reading the discussion really made me see how non-trivial getting into a agreement was.
Anyway, apparently the solution was [rule 7](http://spec.commonmark.org/0.25/#html-blocks), which is rather nice.
The demo parser returns the input when given the input example.

**Comment by jgm** [comment] 2016-11-27 20:42
Short of a transition to the CommonMark rules, there's no obvious fix for this.

**Closed by jgm** 2016-11-27 20:42 UTC

**Comment by amundo** [comment] 2019-11-07 19:24
Would it be possible to treat any custom element ("a tag which contains a hyphen") which is on its own line as a block-level element by default?
