### ISSUE TITLE
markdown to docx unusually slow

### ISSUE THREAD

**Issue by garrettgman** [jgm/pandoc#2356] opened 2015-08-10 14:33 UTC
[This file](https://gist.github.com/garrettgman/ce50c30831de0346c66a) prints the numbers from 1 to 10000. It takes seconds to render to HTML or pdf:

```
pandoc foo.md -f markdown -t latex -o testdoc.pdf
pandoc foo.md -f markdown -t html -o testdoc.html
```

But it takes *eight minutes* to render to word:

```
pandoc foo.md -f markdown -t docx -o testdoc.docx
```

I notice this difference often when I use pandoc through R Markdown to report on data. If I try to do something more modest (like print the numbers from 1 to 1000) I do not notice much of a difference.

**Comment by jgm** [comment] 2015-08-10 16:30
Very strange!  It's just a giant code block.

Looking at the code for Text.Pandoc.Writers.Docx, I can't see any obvious reason why there'd be a performance problem here, so this is a puzzle that needs looking into.

**Comment by jgm** [comment] 2015-08-10 16:49
Some experiments:  I changed the file from a fenced code block to an indented one, to allow testing arbitrary numbers of lines:

```
10 lines        0.07 real         0.05 user         0.01 sys
20 lines        0.11 real         0.09 user         0.01 sys
40 lines        0.28 real         0.25 user         0.01 sys
80 lines       1.02 real         0.99 user         0.01 sys
160 lines       9.30 real         9.22 user         0.07 sys
320 lines      77.44 real        76.94 user         0.44 sys
```
I also tried a version where the code block has just one enormously long line (converting newlines into spaces), and that also takes forever.

**Comment by garrettgman** [comment] 2015-08-10 16:51
Thanks for looking into this, John. I should've mentioned that it began as an issue over at the rstudio/rmarkdonw repository, https://github.com/rstudio/rmarkdown/issues/490

**Comment by jgm** [comment] 2015-08-10 17:06
Further experiment, breaking it down to its core (now using code spans and just a string of `x`s):
```
% python -c 'print ("`" + 60000 * "x" + "`")' | pandoc -o 2356.docx
```

**Comment by jgm** [comment] 2015-08-10 17:12
Also, `--no-highlight` has no real effect.  This suggests that the problem is not specific to code spans. For a single line of unhighlighted text, not much more is going on than a single application of `formattedString` to the code.  (And this is a simple function that just puts the code in some tags.)

Confirmation:

```
$ python -c 'print ("h" + 60000 * "x" + "h")' | pandoc -o 2356.docx --no-highlight
```
also takes forever.  This should just be a single long paragraph with regular text.

**Comment by jgm** [comment] 2015-08-10 17:38
I found the cause:  commit f3aa03ee8609f26cfc3fd250a957fe4376458d97 which strips out invalid characters.  I think this can easily be fixed by doing the stripping in the XML file rather than the Pandoc structure (`bottomUp` from `Text.Pandoc.Generic` is inefficient.)

@mpickering

**Comment by jgm** [comment] 2015-08-10 17:52
@mpickering, I solved this by doing the stripping in `formattedString`, avoiding the use of `bottomUp`.

**Closed** 2015-08-10 17:51 UTC

**Comment by mpickering** [comment] 2015-08-10 19:41
Sorry! Didn't realise the files got so large.
