### ISSUE TITLE
Feature Request: Pandoc Markdown include files

### ISSUE THREAD

**Issue by iandstanley** [jgm/pandoc#6614] opened 2020-08-13 19:32 UTC
I would like to add a feature request 

In very large documents ( e.g books and large reports) it is easier to edit and work on if each chapter or section has it's own separate file

Could we extend the Pandoc markdown syntax to include an _include file_ command which would import another markdown file from the path following the comand.

I used to use this method in Latex with the command 
```
\include{file.tex}
```

I would construct the main document with a set of include statements for each chapter and LaTeX would handle the imports in to a single file before processing.

Yes pandoc can handle both LaTeX and Asciidoc which have these features but I'm moved away from LaTeX on readability grounds (and don't particularly want to try and learn another markup like asciidoc whilst writing a book - plus I don't know of this would break my inline LaTeX being completely unfamiliar with asciidoc).
 
Pandoc handles having multiple input files on the command line but with large documents when you can have dozens of chapters the command line gets exceedingly long and harder to maintain - particularly when compared to moving the include command up  prior to the previous include.

 I am currently using an external tool to preprocess the file but it complicates the build process 

thanks for reading this request
ian

**Comment by paddya** [comment] 2020-08-13 20:36
I think the [include-files](https://github.com/pandoc/lua-filters/tree/master/include-files) Lua filter does what you need.

**Comment by mb21** [comment] 2020-08-14 06:53
Mostly like a duplicate of https://github.com/jgm/pandoc/issues/553 ?

**Comment by jgm** [comment] 2020-08-15 17:39
Closing as duplicate.

**Closed by jgm** 2020-08-15 17:39 UTC
