### ISSUE TITLE
--toc-depth don't work with epub

### ISSUE THREAD

**Issue by s-nt-s** [jgm/pandoc#3408] opened 2017-02-01 21:12 UTC
Edit: Better jump to https://github.com/jgm/pandoc/issues/3408#issuecomment-277075263

Hi

`pandoc --toc-depth 3 -o /tmp/a.epub lamarea_46.html` with `pandoc 1.12.2.1` is ok, but If I upgrade to `1.19.2-1` or `1.13.2-1` no matter what I set in `--toc-depth` that the table of contents always only have the h1 items.

Thanks.

**Comment by jgm** [comment] 2017-02-02 13:00
I can't reproduce this.

**Comment by mb21** [comment] 2017-02-02 13:19
me neither...

    $ pandoc -v
    pandoc 1.19.2.1
    maurobieg 2324 (master) $ pandoc --toc-depth 3 -o foo.epub
    # h1

    foo

    ## h2


    $ unzip foo.epub -d foo
    Archive:  foo.epub
     extracting: foo/mimetype            
      inflating: foo/META-INF/container.xml  
      inflating: foo/META-INF/com.apple.ibooks.display-options.xml  
      inflating: foo/stylesheet.css      
      inflating: foo/title_page.xhtml    
      inflating: foo/content.opf         
      inflating: foo/toc.ncx             
      inflating: foo/nav.xhtml           
      inflating: foo/ch001.xhtml         


    maurobieg 2324 (master) $ cat foo/nav.xhtml 
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <meta http-equiv="Content-Style-Type" content="text/css" />
      <meta name="generator" content="pandoc" />
      <title></title>
      <link rel="stylesheet" type="text/css" href="stylesheet.css" />
    </head>
    <body>
    <div id="toc">
      <h1 id="toc-title">UNTITLED</h1>
      <ol class="toc">
        <li id="toc-li-1">
          <a href="ch001.xhtml#h1">h1</a>
          <ol class="toc">
            <li id="toc-li-2">
              <a href="ch001.xhtml#h2">h2</a>
            </li>
          </ol>
        </li>
      </ol>
    </div>
    </body>
    </html>

**Comment by ousia** [comment] 2017-02-02 20:01
@s-nt-s, neither can I reproduce the issue you comment.

Please, what do you get from this source text:

``` markdown
# h1
foo

## h2
foo

### h3
foo

#### h4
foo

### h3
foo

#### h4
foo
```

Here is what I get with mupdf:

![toc-depth](https://cloud.githubusercontent.com/assets/203767/22566023/ad774494-e98a-11e6-9bb4-ea42cec817ba.png)

And even if you get the right TOC levels, could you provide the url to the problematic HTML file?

**Comment by s-nt-s** [comment] 2017-02-02 20:34
I think the problem is to have h2 items inside a div.

For example:

ok.html is:

```html
<!DOCTYPE html>
<html lang="es">
	<head>
		<title>Example</title>
		<meta charset="utf-8"/>
	</head>
	<body>
		<h1>h1</h1>
		<p>one</p>
		<h2>h2</h2>
		<p>two</p>
	</body>
</html>
```

and ko.html is:

```html
<!DOCTYPE html>
<html lang="es">
	<head>
		<title>Example</title>
		<meta charset="utf-8"/>
	</head>
	<body>
		<h1>h1</h1>
		<div>
			<p>one</p>
			<h2>h2</h2>
			<p>two</p>
		</div>
	</body>
</html>
```

so:

```console
$ pandoc -v
pandoc 1.19.2
Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.2
Default user data directory: /home/santos/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
$ 
$ pandoc --toc-depth 2 -o ok.epub ok.html
$ pandoc --toc-depth 2 -o ko.epub ko.html
$ 
$ unzip -c ok.epub nav.xhtml 
Archive:  ok.epub
  inflating: nav.xhtml               
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta name="generator" content="pandoc" />
  <title>Example</title>
  <link rel="stylesheet" type="text/css" href="stylesheet.css" />
</head>
<body>
<div id="toc">
  <h1 id="toc-title">Example</h1>
  <ol class="toc">
    <li id="toc-li-1">
      <a href="ch001.xhtml#h1">h1</a>
      <ol class="toc">
        <li id="toc-li-2">
          <a href="ch001.xhtml#h2">h2</a>
        </li>
      </ol>
    </li>
  </ol>
</div>
</body>
</html>


$ unzip -c ko.epub nav.xhtml 
Archive:  ko.epub
  inflating: nav.xhtml               
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta name="generator" content="pandoc" />
  <title>Example</title>
  <link rel="stylesheet" type="text/css" href="stylesheet.css" />
</head>
<body>
<div id="toc">
  <h1 id="toc-title">Example</h1>
  <ol class="toc">
    <li id="toc-li-1">
      <a href="ch001.xhtml#h1">h1</a>
    </li>
  </ol>
</div>
</body>
</html>

```

**Comment by ousia** [comment] 2017-02-02 21:15
Confirmed, I can reproduce it:

```
pandoc --toc-depth 3 -o foo.epub 
h1
==

<div>

one

h2
--

two

</div>

ae
```

TOC only has the first-level title.

**Comment by mb21** [comment] 2017-02-03 08:37
Indeed, this is a duplicate of https://github.com/jgm/pandoc/issues/3057 then.

**Closed by mb21** 2017-02-03 08:37 UTC
Labels: format:EPUB, writer
