### ISSUE TITLE
Footnote in table cell breaks table layout in Beamer

### ISSUE THREAD

**Issue by CarstenGrohmann** [jgm/pandoc#8133] opened 2022-06-18 20:03 UTC
Hello PanDoc Developers,

I created a simple table with | as separator. This fit well into the layout of the beamer presentation. There was enough space to the margins. This is the first table in the example.

Then I added a footnote to all the cells in the first column except the heading. This change widens the first column so that in the last cell not all characters fit on the line and one character wraps. The third table in the example shows this behavior.

In the second table, which is identical in content to the third table, the column separators are not vertically aligned across all rows. Here, too, the first column is displayed wider than it should be. Overall, this table is narrower than the third and wider than the first. Also, this table is wider than it should be. 

![image](https://user-images.githubusercontent.com/4849907/174455358-81e55bb0-e077-4a1c-b533-f9a3160cd0db.png)

The larger spacing to the next cell of a row only affects beamer presentations. PDF files rendered from Latex look fine because they have more space for the tables.

Is this a bug or is it possible to control the spacing to the next cell after the footnote?

**Steps to reproduce:**
1. Example - see attached [example.md](https://github.com/jgm/pandoc/files/8934260/example.md)
2. Generate presentation
    ```shell
    $ pandoc --standalone --to beamer example.md --output example.pdf
    $ pandoc --standalone example.md --output example.tex && pdflatex example.tex
    ```

**Current version:**
```shell
$ pandoc -v
pandoc 2.17.1.1
Compiled with pandoc-types 1.22.2, texmath 0.12.5, skylighting 0.12.3,
citeproc 0.6.0.1, ipynb 0.2
User data directory: /home/user/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by mb21** [comment] 2022-06-19 07:52
Can you try with the latest pandoc version please?

But probably you'll just have to use a table format where you can control the widths of the columns, manually: e.g. https://pandoc.org/MANUAL.html#extension-multiline_tables

**Comment by CarstenGrohmann** [comment] 2022-06-19 09:48
The example is already attached to the issue. Please check the "example.md" link in the "Steps to Reproduce" section.

The current version is not yet available in ArchLinux. I will add an update after trying it with pandoc 2.18.

**Comment by tarleb** [comment] 2022-06-20 08:51
This was changed in 79e6f8db13ef8f0db6da8fe4e17b7626fe6ef3e9. The commit message says:

> Improve detection of pipe table line widths.
> 
> Fixed calculation of maximum column widths in pipe tables.
> It is now based on the length of the markdown line, rather
> than a "stringified" version of the parsed line.  This should
> be more predictable for users. In addition, we take into account
> double-wide characters such as emojis.
> 
> Closes #7713.

So it appears that this is intentional.

As a work-around you can specify a really large value for `--columns`, like `--columns=150`.

Alternatively, you can control relative column widths by changing the separator-line:

```
| Transaktionstyp                                           | DpS | Dauer | DpS |  Dauer |
|-------------------------------|----:|------:|----:|-------:|
| Eine Transaktion pro Query ^[`Database.atomic()`]         | 800 |  96 s |  10 | 0,12 s |
| Alle Queries eine Transaktion ^[`Database.transaction()`] | 800 |  75 s |  10 | 0,12 s |
```

**Comment by jgm** [comment] 2022-06-20 16:49
Changing the separator line is the intended method for specifying column widths explicitly in wide tables.  Is there actually a bug, then?  Things seem to be working as described in the manual.

**Comment by tarleb** [comment] 2022-06-20 17:31
I assumed this is all as designed, but wasn't sure. Thanks for confirming; closing this now.

**Closed by tarleb** 2022-06-20 17:31 UTC
Labels: format:Markdown, reader

**Comment by CarstenGrohmann** [comment] 2022-06-21 19:08
Thank you for the support. Both solutions work fine.
