### ISSUE TITLE
Found an unassigned cell 

### ISSUE THREAD

**Issue by harshdonga** [jgm/pandoc#8468] opened 2022-12-02 11:34 UTC
Encountered this log while converting pandoc AST to DOCX.

```
pandoc: Found an unassigned cell. Please report this as a bug!
CallStack (from HasCallStack):
  error, called at src/Text/Pandoc/Writers/GridTable.hs:106:15 in pandoc-2.19-inplace:Text.Pandoc.Writers.GridTable
```

**Command Used (Files attached):** 

pandoc -f json [pd.json](https://drive.google.com/file/d/1owsKa4C5UQ3ZHhm_iEaKGfjbimGZSBNB/view?usp=sharing) -t docx -o op.docx --metadata title=' ' 

**Pandoc version info**
```
pandoc 2.19
Compiled with pandoc-types 1.22.2, texmath 0.12.5.2, skylighting 0.13,
citeproc 0.8.0.1, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4
```

**OS info**
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```

**Comment by jgm** [comment] 2022-12-02 16:59
Thanks. I can reproduce this also with the current dev code.

**Comment by jgm** [comment] 2022-12-02 17:05
```
% pandoc -f native -o my.docx
[ Table
    ( "" , [ "" ] , [] )
    (Caption Nothing [])
    [ ( AlignDefault , ColWidth 0.5 )
    , ( AlignDefault , ColWidth 0.5 )
    ]
    (TableHead
       ( "" , [] , [] )
       [ Row
           ( "" , [] , [] )
           [ Cell
               ( "" , [] , [] )
               AlignDefault
               (RowSpan 0)
               (ColSpan 2)
               [ Para
                   [ Str "Abbreviations" ]
               ]
           ]
       , Row
           ( "" , [] , [] )
           [ Cell
               ( "" , [] , [] )
               AlignDefault
               (RowSpan 0)
               (ColSpan 0)
               [ Para
                   [ Str "A" ]
               ]
           , Cell
               ( "" , [] , [] )
               AlignDefault
               (RowSpan 0)
               (ColSpan 0)
               [ Para
                   [ Str "B" ]
               ]
           ]
       ])
    [ TableBody
        ( "" , [] , [] )
        (RowHeadColumns 0)
        []
        [ Row
            ( "" , [] , [] )
            [ Cell
                ( "" , [] , [] )
                AlignDefault
                (RowSpan 0)
                (ColSpan 0)
                [ Para
                    [ Str "Al" ]
                ]
            , Cell
                ( "" , [] , [] )
                AlignDefault
                (RowSpan 0)
                (ColSpan 0)
                [ Para
                    [ Str "BINAC" ]
                ]
            ]
        ]
    ]
    (TableFoot ( "" , [] , [] ) [])
]
^D

pandoc: Found an unassigned cell. Please report this as a bug!
CallStack (from HasCallStack):
  error, called at src/Text/Pandoc/Writers/GridTable.hs:106:15 in pndc-2.19.2-805f8462:Text.Pandoc.Writers.GridTable
```

**Comment by jgm** [comment] 2022-12-02 17:07
@tarleb this seems related to your pandoc-grid-tables, but I'm not sure.  The table seems okay to me; it has two header rows, one with a merged cell and one with two cells, and one body row with two cells.

**Comment by jgm** [comment] 2022-12-02 17:22
Actually this is entirely due to Text.Pandoc.Writers.GridTable (grid-tables is not involved I think).

**Comment by jgm** [comment] 2022-12-02 17:24
Even more minimal repro:
```hs
[ Table
    ( "" , [ "" ] , [] )
    (Caption Nothing [])
    [ ( AlignDefault , ColWidth 0.5 )
    , ( AlignDefault , ColWidth 0.5 )
    ]
    (TableHead
       ( "" , [] , [] )
       [ Row
           ( "" , [] , [] )
           [ Cell ( "" , [] , [] ) AlignDefault (RowSpan 0) (ColSpan 2)
               [ Para [ Str "Abbreviations" ] ]
           ]
       , Row
           ( "" , [] , [] )
           [ Cell
               ( "" , [] , [] ) AlignDefault (RowSpan 0) (ColSpan 0)
               [ Para [ Str "A" ] ]
           , Cell
               ( "" , [] , [] ) AlignDefault (RowSpan 0) (ColSpan 0)
               [ Para [ Str "B" ] ] ]
       ])
    [ ]
    (TableFoot ( "" , [] , [] ) [])
]
```

**Comment by jgm** [comment] 2022-12-02 17:25
Wait, I think the problem with this is `ColSpan 0`. Shouldn't that be `ColSpan 1`?
How did you generate this AST?

**Comment by jgm** [comment] 2022-12-02 17:25
Similarly `RowSpan` should not be 0.

In an ideal world, the types would prevent this.

**Comment by jgm** [comment] 2022-12-02 17:26
Changing these 0s to 1s fixes it.

**Comment by jgm** [comment] 2022-12-02 17:33
Since this is a badly constructed AST, we could close this as resolved.
Ideally, though, we could do a sanity check and throw a catchable exception instead of using `error`.  I'd like to reserve `error` for things that are definitely bugs in the code.  @tarleb do you see a way to do this?

**Comment by harshdonga** [comment] 2022-12-02 18:04
> Wait, I think the problem with this is `ColSpan 0`. Shouldn't that be `ColSpan 1`? How did you generate this AST?

AST was not generated through pandoc but a separate script written by me conforming to pandoc's AST.
However, it's just schema level check, inspired from [here](https://groups.google.com/u/2/g/pandoc-discuss/c/3CM3g1ZEY5s/m/xx93yZOoAQAJ)

A sanity check would be great, is there a way to perform that externally?

**Comment by tarleb** [comment] 2022-12-02 18:09
John MacFarlane ***@***.***> writes:

> Since this is a badly constructed AST, we could close this as
> resolved.
> Ideally, though, we could do a sanity check and throw a catchable
> exception instead of using error. I'd like to reserve error for
> things that are definitely bugs in the code. @tarleb do you see a way
> to do this?

The ST monad and array still confuse me at times, but that should be
doable. Maybe we should just stop throwing an error for now.

-- 
Albert Krewinkel
GPG: 8eed e3e2 e8c5 6f18 81fe  e836 388d c0b2 1f63 1124

**Comment by jgm** [comment] 2022-12-02 22:48
I pushed a commit that causes an error to be thrown at a higher level in PandocMonad, rather than with `error`.
@tarleb feel free to do something different if you like.
This required adding an UnassignedCell constructor to GridCell, which you might not like.

**Closed** 2022-12-02 22:47 UTC
Labels: bug
