### ISSUE TITLE
Error when compiling markdown -> latex -> pdf: You can't use `\vadjust' in vertical mode.

### ISSUE THREAD

**Issue by BlackEdder** [jgm/pandoc#7215] opened 2021-04-08 14:15 UTC
I am trying to convert a markdown document into latex using pandoc and then compile the latex file using pdflatex, but run into the following error during the second step:

```
! You can't use `\vadjust' in vertical mode.
l.595 \leavevmode\vadjust
                          pre{\hypertarget{ref-abdu_implications_2020}{}}%
```
It is not clear to me if this is because the latex produced by pandoc is invalid, or if it is a bug in pdflatex, but the same markdown document used to convert and compile without issue. It seems to be linked to the introduction of [vadjust in pandoc](https://github.com/jgm/pandoc/commit/53cf8295a4825297f78e20b6ce73d2da8fd7ef84)

I can ignore the error and I will still get a pdf document, but the first reference will include an errant "pre" at the start of the references:

> preAbdulrahman, Abdulkarim, Muath AlMajthoob, Abdulla I. AlAwadhi, and ...

If I edit the tex file and include an empty line between `\begin{CSLReferences}{1}{0}` and the start of the references `\leavevmode\vadjust pre{\hypertarget{ref-abdu_implications_2020}{}}%
Abdulrahman, Abdulkarim, ...` it works fine.

My pandoc (and pdflatex) versions are:

```
$ pandoc --version                                                                                                            
pandoc 2.13
Compiled with pandoc-types 1.22, texmath 0.12.2, skylighting 0.10.5.1,
citeproc 0.3.0.9, ipynb 0.1.0.1
User data directory: /home/edwin/.local/share/pandoc
Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.

$ pdflatex --version                
pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020/Arch Linux)
kpathsea version 6.3.2
```

**Comment by jgm** [comment] 2021-04-08 20:06
I'd like to be able to reproduce this, but I don't get the same error when I create PDFs with citations.  It works fine for me without the blank line after `\begin{CSLReferences}{1}{0}`.
Same pdftex version.

Can you use pandoc to create a standalone tex file `-t latex -s -C -o name.tex` and then run pdflatex directly on it?  Assuming that fails, upload the file so I can test on my tex setup?  If it fails for you and works for me, that indicates in issue in tex I think.

**Comment by dahrens** [comment] 2021-04-09 15:19
I encounter the same issue with pandoc > 2.11.4 and xelatex (XeTeX 3.14159265-2.6-0.999992 (TeX Live 2020/Arch Linux)).
Using the pandoc 2.11.4 binary release I don't have this issue. Therefore I guess that #7078 and commit 53cf829 introduced it.

Sadly my current document is far away from being a small sample, therefore I will not provide it's tex file here. Maybe @BlackEdder has a document that better suits.

**Comment by dahrens** [comment] 2021-04-09 15:37
I've started to build a minimal example - when using the default template instead of my custom one it works with the current version of pandoc as well - looks like I need to check whats wrong with it :thinking:

**Comment by BlackEdder** [comment] 2021-04-09 15:57
Thank you for looking further into this @dahrens. I had the error when using an [elsevier template](https://github.com/rstudio/rticles/blob/master/inst/rmarkdown/templates/elsevier/resources/template.tex). I did not have a chance yet to see if it is only with that template.

**Comment by dahrens** [comment] 2021-04-09 16:08
My template was outdated regarding `csl-refs` - applying the following patch solved my issue: 356795d - most likely it solves yours as well - when changing it [there](https://github.com/rstudio/rticles/blob/master/inst/rmarkdown/templates/elsevier/resources/template.tex#L142)

**Comment by mb21** [comment] 2021-04-18 07:30
Closing for now... please reopen if there's an issue with the default template.

**Closed by mb21** 2021-04-18 07:30 UTC

**Comment by BlackEdder** [comment] 2021-04-22 12:55
Just to confirm that this fixed the issue for me as well. Thank you for your help!

**Comment by kjayhan** [comment] 2023-03-14 01:56
I have a similar problem.

I can render [my CV](https://github.com/kjayhan/cv) using bookdown when I have an [earlier version of multiple-bibliographies.lua](https://github.com/kjayhan/cv/blob/main/lua/multiple-bibliographies.lua).
When I update this to [a newer version](https://github.com/pandoc/lua-filters/blob/master/multiple-bibliographies/multiple-bibliographies.lua), it throws this error: 

! You can't use `\vadjust' in vertical mode.
l.169 \leavevmode\vadjust
                          pre{\hypertarget{ref-ayhan_inter-korean_2023}{}}% 

Error: LaTeX failed to compile Kadir_Jun_Ayhan_CV.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See Kadir_Jun_Ayhan_CV.log for more info.
Execution halted

I updated pandoc to 3.1.1 including for Rstudio, but still same error.


The reason why I want to move to a newer one is because, currently my publications are in chronological order, whereas I need them in reverse chronological order.
