### ISSUE TITLE
Preserving <i>, <b> and <cite> in non-HTML formats

### ISSUE THREAD

**Issue by snan** [jgm/pandoc#6515] opened 2020-07-09 12:01 UTC
So the position seems to be that em and strong are OK for `*` and `**` but then how about this idea, as per discussed on [commonmark's issue tracker](https://github.com/commonmark/commonmark-spec/issues/652): that we can write `<i>`, `<cite>` and `<b>` and have them be understood by pandoc (as an exception to most other HTML tags just being passed through or dropped) and turned to italics and bold in other formats, like ContTeXt and LaTeX?

**Comment by mb21** [comment] 2020-07-10 07:56
For HTML input this already works...

```
echo '<i>foo</i>' | pandoc -f html -t native
[Plain [Emph [Str "foo"]]]
```

But you're talking about markdown input, or..?

```
echo '<i>foo</i>' | pandoc -f markdown -t native
[Para [RawInline (Format "html") "<i>",Str "foo",RawInline (Format "html") "</i>"]]
```

true, there it's converted to raw HTML, which will only work for HTML output and be dropped otherwise...

**Comment by snan** [comment] 2020-07-10 08:03
Yes, using a markdown source document to generate html and other output formats, including some custom lua ones.

**Comment by snan** [comment] 2020-07-10 08:14
I'm way OK with another solution to create b and i and cite too. We've [previously argued for][1] having `*` and `**` _always_ be i and b.

[1]: https://github.com/jgm/pandoc/issues/4297#issuecomment-534752313

**Comment by mb21** [comment] 2020-07-10 11:59
> I just want to find some way to not generate `In <em>Hamlet</em>`

ah, you can write a [lua filter](https://pandoc.org/lua-filters.html) to change the native `Emph [Str "foo"]` into `RawInline (Format "html") "<i>",Str "foo",RawInline (Format "html") "</i>"]`... or post-process the HTML...

**Comment by snan** [comment] 2020-07-10 12:16
What I want is the opposite; to write markdown that fits on all kinds of
markdown sites (that don't all use pandoc)—and I can do that with the
`<i>` and `<b>` most places—and then still have pandoc turn `<i>` into
italic or `<b>` into bold when I want to generate ConTeXt.

So I guess one workaround there is to preprocess it before I pass it to
pandoc.

Also I love markdown but this is such a weird part of the language.

**Comment by mb21** [comment] 2020-07-10 12:40
haha, I don't get it. If you want to use portable markdown, just use `*` and `**`...? some markdown processors will convert to `<em>`, and a few weird ones might convert to `<i>`... so yes, you can post-process the HTML then I guess..?

**Comment by snan** [comment] 2020-07-10 12:49
If I write `_Taraxacum officinale_ grows from unbranched taproots` and
that gets turned into `<em>Taraxacum officinale</em> grows from
unbranched taproots`, that's wrong. It's not emphasis.

**Comment by mb21** [comment] 2020-07-10 13:21
Ah, so this is a duplicate of https://github.com/jgm/pandoc/issues/4297 ?

**Comment by snan** [comment] 2020-07-10 13:28
It's another solution to the same problem!

**Comment by tarleb** [comment] 2020-07-10 17:43
If I understand correctly, then you want to write `<i>Saccharomyces cervisiae</i>` and have it appear verbatim in HTML, but as "normal" emphasized text in other formats, correct? This would be doable with a Lua filter. Another filter-based solution would be to write `[Escherichia coli]{.species}`. The corresponding filter would be

```lua
function Span (span)
  if not span.classes:includes 'species' then return nil end
  if FORMAT:match 'html' then
    return {pandoc.RawInline('html', '<i>')} .. span.content .. {pandoc.RawInline('html', '</i>')}
  else
    return pandoc.Emph(span.content)
  end
end
```

**Comment by tarleb** [comment] 2020-07-10 18:56
For completeness, here's a filter which allows using `<i>` as an alternative to `*` or `_`.

``` lua
if FORMAT:match 'html' then
  return {}
end

local List = require 'pandoc.List'

function is_italics_start(inln)
  return inln.t == 'RawInline'
    and inln.format:match 'html'
    and inln.text:match '<i>'
end

function is_italics_end(inln)
  return inln.t == 'RawInline'
    and inln.format:match 'html'
    and inln.text:match '</i>'
end

function Inlines (inlns)
  local result = List()
  local italics = nil
  for _, inln in ipairs(inlns) do
    if is_italics_start(inln) then
      italics = List()
    elseif is_italics_end(inln) then
      result:insert(pandoc.Emph(italics))
      italics = nil
    elseif italics then
      italics:insert(inln)
    else
      result:insert(inln)
    end
  end
  return result
end
```

Any additional discussions should happen on the pandoc-discuss mailing list.

**Closed by tarleb** 2020-07-10 18:56 UTC
Labels: closing candidate
