### ISSUE TITLE
Grid table output adds unwanted line breaks mid-word

### ISSUE THREAD

**Issue by jack-kirton** [jgm/pandoc#6498] opened 2020-07-01 17:02 UTC
Pandoc version: 2.9.2.1

When pandoc outputs a grid table, it can cause unwanted line breaks in the middle of words in a cell.
Using [table-test.txt](https://github.com/jgm/pandoc/files/4859235/table-test.txt) as markdown input with the command `pandoc --from=markdown --to=markdown table-test.txt` splits words in the headers of the first three columns.

I believe this is because pandoc is trying to keep the column width ratio the same but reducing the total table width so some words must be split to fit within the new cell size. This is, however, purely speculation.

**Comment by jgm** [comment] 2020-07-01 19:48
You are correct in your speculation.

The main issue is that this table exceeds the default column width.  So when pandoc renders it (within the default column width), everything gets squished.  One solution is to specify `--columns=132` when converting.

**Comment by tarleb** [comment] 2021-05-06 16:47
I believe this is intended behavior. Hence closing.

**Closed by tarleb** 2021-05-06 16:47 UTC
Labels: format:Markdown, writer
