### ISSUE TITLE
memory overflow

### ISSUE THREAD

**Issue by Dibal** [jgm/pandoc#5078] opened 2018-11-14 19:25 UTC
In  the past Pandoc handled big text files (> 600 pages) and converted them to TEX files.
But only for versions smaller than 2.0.
Versions newer than 2.0 (eg. 2.2 or 2.4) fail. 
On Windows it report "out of memory".
On Linux it says:
"Pandoc: internal error: unable to commit 6311456 bytes of memory
(GHC version 8.4.3 for x86_64_alpine_linux)
Please report this as GHC bug: http://www.haskell.org/ghc/reportabug"
and crashes the system.

**Comment by jgm** [comment] 2018-11-14 21:11
Thanks for the report. Are you using the binaries
provided in our GitHub releases page, or
self-compiled, or from a package manager?

How big (MB) are the files you're trying to convert?
What format, markdown?  If any are publicly available,
it would be helpful for us to test.

**Comment by jgm** [comment] 2018-11-15 18:12
Mauro Bieg <notifications@github.com> writes:

> LaTex parsing got a lot more sophisticated in 2.x,
> so that's not so surprising.

I think OP is converting to tex (from, I assume,
markdown?), not from tex.

**Comment by Dibal** [comment] 2018-11-15 18:32
Thanks for comments which seems to have solved the problem.
In fact big pandoc.md files are not  a problem (even a many thousand pages files was rendered properly).
But when a tex-header file and latex commands were included the system crashed.

I have no idea how to limit memory of pandoc's haskell. And even if I limited how should this solve the problem?
But your comments guided me to https://github.com/jgm/pandoc/issues/3169.

I added "--trace" and everything seems to be OK (have to run additional tests).
(Perhaps someone can explain  why tracing every step on stdout may remedy the problem?)

**Comment by jgm** [comment] 2018-11-15 19:17
Dibal <notifications@github.com> writes:

> I added "--trace" and everything seems to be OK (have to run additional tests).
> (Perhaps someone can explain  why tracing every step on stdout may remedy the problem?)

That's quite interesting that this helped.  Haskell
uses lazy evaluation by default, and sometimes this
means that big unevaluated thunks can build up in
memory.  It may be that the tracing forces these
thunks to be evaluated and thereby relieves the memory
pressure.

This is actually a useful hint; maybe there is
something we can do to improve the memory situation by
forcing evaluation as we parse.

**Comment by jgm** [comment] 2018-11-16 16:53
If you're able to share a copy of the file that caused the problem, I can do further testing and maybe improve things. Otherwise, I'll just have to close this, because there's nothing we can do further without being able to reproduce the issue.

**Comment by Dibal** [comment] 2018-11-16 20:32
Please find below a python script which creates the file "test.md". It contains many Latex commands for  nice tables.

1) call: pandoc test.md -o test.tex
2) pandoc 2.4 throw a Haskel memory overflow error message and kills the system

1) call: pandoc test.md -o test.tex --trace
2) Within about 3 minutes pandoc processes about 1000 lines -- and crashes as well (no error message but harddisk busy and no reaction from system).

So the trick "--trace" does not solve the problem in general.
It would be great if there are ideas about what to do (eg nice table definition in Markdown....).

---- 

ts='''
# Title

Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. 
Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.

* point one
* Point two

\vskip 1.2in
\begin{table}[h!]
\footnotesize
\caption*{\textbf{demonstration} \footnotesize{(Zahl1, Zahl2, Zahl3)}}
\begin{tabularx}{\textwidth}{XXXXXXXXXXXXXXXX}
\rowcolorgray
\multicolumn{1}{l}{} &
\multicolumn{3}{c}{2020
 & \multicolumn{3}{c}{2020}
 & \multicolumn{3}{c}{2020}
 & \multicolumn{3}{c}{2020}
\\[0.04in]
\rowcolorgray
\multicolumn{1}{l}{}
& \multicolumn{1}{r}{PKS} & \multicolumn{1}{r}{PKB} & \multicolumn{1}{r}{INF}
& \multicolumn{1}{r}{PKS} & \multicolumn{1}{r}{PKB} & \multicolumn{1}{r}{INF}
& \multicolumn{1}{r}{PKS} & \multicolumn{1}{r}{PKB} & \multicolumn{1}{r}{INF}  \\
\hiderowcolors &&&&&&&&&&&&&&& \\[0.01in]
\multicolumn{1}{l}{\textbf{All}}
 & \multicolumn{1}{r}{10.000} & \multicolumn{1}{r}{10.000} & \multicolumn{1}{r}{0}
 & \multicolumn{1}{r}{10.000} & \multicolumn{1}{r}{10.000} & \multicolumn{1}{r}{0}
 & \multicolumn{1}{r}{10.000} & \multicolumn{1}{r}{10.000} & \multicolumn{1}{r}{0}
\\
\hiderowcolors &&&&&&&&&&&&&&& \\ [-3mm]
\end{tabularx}
\end{table}
\addtocontents{toc}{\protect\setcounter{tocdepth}{2}}
\clearpage
\addcontentsline{toc}{section}{Testing}
\pdfbookmark[1]{Testing}{sec_07e3d83db-a9a0-4796-a391-a9f57642f2d9}
\addtocontents{toc}{\protect\setcounter{tocdepth}{0}}
\mainHeader{Program and testing}
\textbf{Hello}
'''

with open('test.md', 'w') as fn:
    for _ in range(0,1000):
        fn.write(ts)

**Comment by jgm** [comment] 2018-11-16 22:11
Note, if you have problems like this with raw LaTeX in Markdown, the best solution is to put them in explicit raw blocks:

````
# Title

Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. 
Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.

* point one
* Point two

``` {=latex}
\vskip 1.2in
\begin{table}[h!]
\footnotesize
\caption*{	extbf{demonstration} ootnotesize{(Zahl1, Zahl2, Zahl3)}}
\begin{tabularx}{	extwidth}{XXXXXXXXXXXXXXXX}
\rowcolorgray
\multicolumn{1}{l}{} &
\multicolumn{3}{c}{2020
 & \multicolumn{3}{c}{2020}
 & \multicolumn{3}{c}{2020}
 & \multicolumn{3}{c}{2020}
\\[0.04in]
\rowcolorgray
\multicolumn{1}{l}{}
& \multicolumn{1}{r}{PKS} & \multicolumn{1}{r}{PKB} & \multicolumn{1}{r}{INF}
& \multicolumn{1}{r}{PKS} & \multicolumn{1}{r}{PKB} & \multicolumn{1}{r}{INF}
& \multicolumn{1}{r}{PKS} & \multicolumn{1}{r}{PKB} & \multicolumn{1}{r}{INF}  \
\hiderowcolors &&&&&&&&&&&&&&& \[0.01in]
\multicolumn{1}{l}{	extbf{All}}
 & \multicolumn{1}{r}{10.000} & \multicolumn{1}{r}{10.000} & \multicolumn{1}{r}{0}
 & \multicolumn{1}{r}{10.000} & \multicolumn{1}{r}{10.000} & \multicolumn{1}{r}{0}
 & \multicolumn{1}{r}{10.000} & \multicolumn{1}{r}{10.000} & \multicolumn{1}{r}{0}
\\hiderowcolors &&&&&&&&&&&&&&& \ [-3mm]
\end{tabularx}
\end{table}
\addtocontents{toc}{\protect\setcounter{tocdepth}{2}}
\clearpage
\addcontentsline{toc}{section}{Testing}
\pdfbookmark[1]{Testing}{sec_07e3d83db-a9a0-4796-a391-a9f57642f2d9}
\addtocontents{toc}{\protect\setcounter{tocdepth}{0}}
\mainHeader{Program and testing}
\textbf{Hello}
```

````

**Comment by jgm** [comment] 2018-11-16 22:33
I had to double the backslashes in your python script in order to create the right output.

**Comment by DaveJarvis** [comment] 2018-12-17 18:47
Tangentially related that may be of interest:

* https://www.tablesgenerator.com/markdown_tables
* https://rapporter.github.io/pander/pandoc_table.html
* https://pandoc.org/MANUAL.html#tables

FWIW, ConTeXt + pandoc can help keep presentation markup (e.g., TeX macros) out of the document content so that the content's presentation can vary independently of what the content contains. (Incidentally, not having LaTeX macros intertwined with the table data would have likely avoided this issue entirely because pandoc would have generated the correct macro syntax from ASCII tables.)

**Closed** 2018-12-17 19:48 UTC
Labels: closing candidate
