### ISSUE TITLE
feature request: add new Markdown extension cell_attachments that works in ipynb format

### ISSUE THREAD

**Issue by kiwi0fruit** [jgm/pandoc#5299] opened 2019-02-12 09:14 UTC
Feature request: add new Markdown extension `cell_attachments` that works in ipynb format. It is useful for exporting to ipynb that is compatible with older or third party ipynb readers like nteract: https://github.com/nteract/nteract/issues/889 (or GitHub ipynb viewer: https://github.com/kiwi0fruit/misc/blob/master/src/doc.ipynb)

Name was borrowed from here: https://nbformat.readthedocs.io/en/latest/format_description.html#cell-attachments

----

This is also useful for markdown -> ipynb -> markdown conversion so that attachments don't get lost on the last step: https://github.com/jgm/pandoc/issues/5300

**Comment by kiwi0fruit** [comment] 2019-02-12 09:30
This is also useful for markdown -> ipynb -> markdown conversion so that attachments are not losed on the last step.

**Comment by jgm** [comment] 2019-02-12 16:22
#5300 has already been fixed.  Is there still a point to this request?  I'm not sure I understand exactly what is being requested.  Attachments should work with the revised code.

**Comment by jgm** [comment] 2019-02-12 16:23
I plan a new release before long, which will have this fix + a slightly different treatment of output cells.

**Comment by kiwi0fruit** [comment] 2019-02-12 16:28
This is still relevant as attachments are not supported by many ipynb viewers.

**Comment by kiwi0fruit** [comment] 2019-02-12 16:33
Pandoc always generates attachments but I don't want to use them in order to be compatible with other ipynb viewers so I request a way to have ipynb output without attachments (preferably the same Markdown as specified in a flavour `ipynb+xxx-yyy` and affected by standalone and self-contained). Actually turning attachments off/on is a kind of Markdown flavor so I thought that is would be fitting to switch it via Markdown extension.

**Comment by kiwi0fruit** [comment] 2019-02-12 16:35
@jgm So I ask to reopen this issue or have another one opened to track this issue.

**Comment by jgm** [comment] 2019-02-12 17:13
If I understand correctly, you're asking for a way to
turn off attachments, so no cell attachments are generated?

Pandoc reads either ipynb v3 or v4.  But it only
writes v4.  Attachments have been supported since
nbformat v4.1, which was released over three years
ago.  So I didn't think it would be necessary to
support versions that didn't understand attachments.
People shouldn't be using notebook readers that haven't
been updated for three years.

If you really don't want attachments, I believe it
should be possible to eliminate them using a short lua
filter.  (Just clear out the mediabag.)

If you still want to submit an issue, I suggest
a request to support different versions of nbformat
in the writer, instead of just defaulting to the
latest.  The relevant nbformat version could be
taken from metadata.

**Comment by tarleb** [comment] 2019-02-12 17:25
> Just clear out the mediabag.

We don't support that yet, but I can take a look later tonight

**Comment by kiwi0fruit** [comment] 2019-02-12 17:49
Nope, it's better not to use attachments at all as GitHub ipynb viewer
doesn't support them. If it enables them 5 years later then it would be the
right time to use attachments :)

If I recall correctly I can easily NOT have attachments in the latest
Jupyter notebook while I use the latest nbformat. But I don't have such
opportunity in Pandoc.

>

**Comment by jgm** [comment] 2019-02-12 19:10
Peter Zagubisalo <notifications@github.com> writes:

> Nope, it's better not to use attachments at all as GitHub ipynb viewer
> doesn't support them. If it enables them 5 years later then it would be the
> right time to use attachments :)

Here's an example of an ipynb with an attachment in
GitHub:
https://github.com/jgm/pandoc/blob/master/test/ipynb/simple.ipynb

It doesn't crash or anything; it is rendered properly,
only the attached image doesn't show up (you get the
alt text instead).  I don't see how things would be
any better if we simply didn't include the attachment.
You'd see exactly the same thing -- the alt text.

I see that in your original example, the image link
occurs inside raw HTML. GitHub seems to be suppressing
the entire figure element, including the caption, but
that has nothing to do with attachments per se.

**Comment by kiwi0fruit** [comment] 2019-02-13 03:42
If we don't include the attachment then the picture would be visible. I can't get why you don't like an option to fix broken image rendering.

**Comment by kiwi0fruit** [comment] 2019-02-13 03:46
Now pandoc prepends image url with `attachment` so if it stops doing it then everything would work. There can also be embedded base64 image right in the url (just like in Markdown).

I guess the default behavior should be with attachments but why not add option that disables them?

**Comment by kiwi0fruit** [comment] 2019-02-13 03:54
Oh, I see. GItHub not only doesn't support attachments but also doesn't
support image captions. So many things broken... I guess simple Markdown
image case can be fixed by turning off attachments but that's not the only
bad thing. So it's better not to support it at all. Maybe you are right.

**Comment by jgm** [comment] 2019-02-13 05:27
> if it stops doing it then everything would work

I suppose this is true when the image links to an external URL.  When the image links to a local file, it won't work (unless you happen to upload the local file to the same location relative to the ipynb).

One question is whether we should treat images with external links differently, and not create attachments for them.  I'd want to get comments from other Jupyter users on that -- perhaps it's something that could be raised on pandoc-discuss.

**Comment by kiwi0fruit** [comment] 2019-02-13 06:42
By the way nbviewer.jupyter.org also doesn't support attachments properly:

1. [with attachment](https://nbviewer.jupyter.org/github/kiwi0fruit/misc/blob/652d584c5c227d04394f9a6e51701b347800c382/src/doc.ipynb) ([source](https://raw.githubusercontent.com/kiwi0fruit/misc/652d584c5c227d04394f9a6e51701b347800c382/src/doc.ipynb))
2. [with base64 embedding](https://nbviewer.jupyter.org/github/kiwi0fruit/misc/blob/e122491d1dc00e118a919daa53a58f4473ef29a6/src/doc.ipynb) ([source](https://raw.githubusercontent.com/kiwi0fruit/misc/e122491d1dc00e118a919daa53a58f4473ef29a6/src/doc.ipynb))

**Comment by jgm** [comment] 2019-02-13 18:24
Peter Zagubisalo <notifications@github.com> writes:

> By the way nbviewer.jupyter.org also doesn't support attachments properly:

I'm not a Jupyter dev, but I'm not sure it's intended
to work when your image reference is in raw HTML, as
in your case. Try a regular markdown figure

    ![Sample image](attachment:whatever)

**Comment by kiwi0fruit** [comment] 2019-02-14 09:10
Same with `![]()`:

[nbviewer.jupyter.org](https://nbviewer.jupyter.org/github/kiwi0fruit/misc/blob/99a218dddf51916f5791232cbd9f2db7f6e35dbc/src/doc.ipynb) ([source](https://raw.githubusercontent.com/kiwi0fruit/misc/99a218dddf51916f5791232cbd9f2db7f6e35dbc/src/doc.ipynb))

**Comment by kiwi0fruit** [comment] 2019-02-14 09:12
As a temporal fix for this bug there is a panflute filter: [knitty.self_contained_raw_html_img](https://github.com/kiwi0fruit/knitty/blob/master/knitty/self_contained_raw_html_img.py)

**Comment by kiwi0fruit** [comment] 2019-02-14 09:19
UPD: fixing attachment name (as Pandoc corrupts it) doesn't help. Seemingly nbviewer doesn't support attachments regardless.

[nbviewer.jupyter.org](https://nbviewer.jupyter.org/github/kiwi0fruit/misc/blob/a1395bb18f0575e3b21b06f0fe8c2afefb42c551/src/doc.ipynb) ([source](https://raw.githubusercontent.com/kiwi0fruit/misc/a1395bb18f0575e3b21b06f0fe8c2afefb42c551/src/doc.ipynb))

**Comment by jgm** [comment] 2019-02-14 17:31
@choldgraf can you comment on this?  Is it expected behavior that nbviewer doesn't support attachments?

I think it might make sense to make the following change in pandoc's behavior:  instead of creating attachments for all images in markdown cells, do so only for images whose sources aren't external URLs.  That is, leave the external URLs as URLs.  The idea would be to pack in only the local files as attachments.  Does that seem reasonable?

**Comment by jgm** [comment] 2019-02-16 06:58
I think the fix to #5303 addresses the problems that motivated this issue.

**Comment by kiwi0fruit** [comment] 2019-02-16 13:29
Mostly, but not really. This issue is about having control over the output ipynb. Preferably is to being able too turn on/off attachments directly (and also being able to turn on/off self-contained mode). So that to choose one of 3 options: URL as they were given, URL embedded via attachments, URL embedded via base64 encoding (like in `--self-contained` in html).

**Comment by kiwi0fruit** [comment] 2019-02-16 13:33
I guess embedding only locals mode is also important.

>

**Comment by jgm** [comment] 2019-02-16 17:21
I'd like to learn more about why some ipynb viewers do not support attachments when they've been part of the spec for three years.  I'm hoping some Jupyter or GitHub devs can comment here.

@kivikakk do you know what software is used to render ipynb files on GitHub?  I'm wondering why markdown cell attachments don't seem to be supported, and whether this can be fixed.

**Comment by choldgraf** [comment] 2019-02-16 18:01
I can't speak a ton to this, I haven't been deeply involved in notebook format discussions in the past. It could be that some notebook renderers behave differently just for complexity and/or security reasons? I don't know what's the latest version of notebooks that the github renderer was made for :-/

maybe @ivanov has thoughts as well, since he's been working on cellout and may have thought about this kinda thing. or @rgbkrk since it sounds like he may have some experience working with cell attachments w/ nteract?

**Comment by rgbkrk** [comment] 2019-02-17 02:46
> do you know what software is used to render ipynb files on GitHub? I'm wondering why markdown cell attachments don't seem to be supported, and whether this can be fixed.

The version on github hasn't been updated in > 3 years. As far as I know, it's still using `nbconvert` under the hood, using github's rendering pipeline. @jflam is looking into it internally at Github & Microsoft to see about improving the ipynb rendering support. It's out of jupyter developer control.

> I'd like to learn more about why some ipynb viewers do not support attachments when they've been part of the spec for three years. I'm hoping some Jupyter or GitHub devs can comment here.

At least for the nteract frontends, the demand is low enough and the perceived level of work for them high enough that we haven't wanted to touch them.

**Comment by rgbkrk** [comment] 2019-02-17 02:59
I guess an amusing side note to this is that I don't like pushing too far outside of commonmark and common web standards for markdown in the notebook. Since we can't register custom local schemes we have to do some extra parsing on URLs within markdown cells. We already do a bit of this to handle math [within our `@nteract/markdown` package](https://github.com/nteract/nteract/tree/master/packages/markdown).

As for the `attachment:` scheme itself,

```markdown
![inline image](attachment:test.png)
```

When I found out the nbformat spec had this addition it worried me for several reasons. `attachment` is already registered with IANA for an Opera specific protocol with wildly unspecified semantics & syntax. As a result it's already not the same as the notebook. I'd have different feelings if it was namespaced, like as `jupyter-notebook-attachment:`.

It's already in the spec so to me that ship has sailed and eventually we'll have to support it or find another way to support the need for users. It's hard to argue against something that already exists that you don't agree with. I just wouldn't feel like a kind person in doing so.

**Comment by knuesel** [comment] 2022-11-02 09:07
Maybe this can be closed? It seems both the GitHub viewer and nbviewer.org support attachments now. Taking examples from this thread: https://github.com/jgm/pandoc/blob/master/test/ipynb/simple.ipynb and https://nbviewer.org/github/kiwi0fruit/misc/blob/a1395bb18f0575e3b21b06f0fe8c2afefb42c551/src/doc.ipynb both show the image.

**Comment by jgm** [comment] 2022-11-02 15:47
happy to close it!

**Closed by jgm** 2022-11-02 15:47 UTC
Labels: out of scope?
