### ISSUE TITLE
Use <ali:free_to_read> element instead of licence-type= attribute

### ISSUE THREAD

**Issue by castedo** [jgm/pandoc#8042] opened 2022-04-26 14:38 UTC
In pandoc 2.18, the default jats template writes a `licence-type=` attribute in the `<license>` element based on the `license: type:` key of the input metadata. Per the JATS spec linked to from https://pandoc.org/jats.html, the example value is "open-access".

But in the PubMed Central Open Access Subset https://www.ncbi.nlm.nih.gov/pmc/tools/openftlist/ I see the `<ali:free_to_read>` element used and not the `license-type=` attribute.

For instance, if you look at article package ftp://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_package/69/ca/PMC8184209.tar.gz, it has
```
<permissions>
    ...
    <ali:free_to_read xmlns:ali="http://www.niso.org/schemas/ali/1.0/"/>
    <license>
    ...
    </license>
</permissions>
```

Perhaps, rather than license: type: in the metadata, there should just be a boolean value in the metadata (like `free_to_read`) and this injects this `<ali:free_to_read>` element to emulate PubMed Central, or at least emulate eLife articles.

@tarleb

**Comment by tarleb** [comment] 2022-08-07 14:56
This was resolved with #8041. Thanks again!

**Closed by tarleb** 2022-08-07 14:56 UTC
Labels: enhancement, writer, format:JATS

**Comment by castedo** [comment] 2022-10-18 10:00
@tarleb I'm now thinking there should NOT be a free-to-read boolean in the license metadata as I suggested above. After thinking about this some more and reading https://jats.nlm.nih.gov/archiving/tag-library/1.1/element/ali-free_to_read.html, this setting just seems like an antiquated nearly-worthless element. It doesn't seem worth making the documentation more complicated or the extra work.

**Comment by tarleb** [comment] 2022-10-18 13:52
I agree with that. Does that mean that the issue is truly resolved?

**Comment by castedo** [comment] 2022-10-18 14:42
Narrowly defined, this issue, #8042, I think it worth keeping closed and considering resolved.

There's a larger question which is what should pandoc users do if they want their JATS XML to be "open access". The pandoc documentation has that license type field which links to JATS docs that given "open-access" as an example. But it does not appear that PubMed Central is using that field to indicate open access. Rather PMC is using a `<?properties open_access?>` XML processing instruction element under the `article` element to indicate this.

So I'd say technically there is a new issue but we don't know yet what exactly it is. I'm currently trying to figure what I want to output for the JATS XML that I generate. I want to it line up with what PMC does to a very high degree. I'll cycle back and probably create a new issue/PR/suggestion.

In the meantime, a question to ponder:

**What do you think of the idea that pandoc by default generates JATS XML that is marked open access and makes any user that does not want open access JATS XML to override the JATS template?**

I've been thinking that perhaps 'license-type' should be removed (I doubt any reader is going to use it) from the docs and pandoc should just output open access JATS XML by default (probably by doing what PMC does in XML).

**Comment by tarleb** [comment] 2022-10-18 15:47
We use the license type for JOSS, so I wouldn't want to just remove it.

The idea of open-by-default fits my personal ideology, but I have reservations about doing that here. It would have to be very well documented, and even then, it might be better to have people make a conscious decision about the license that they want to use.
