### ISSUE TITLE
Multiple issues with  --citeproc

### ISSUE THREAD

**Issue by sopertob** [jgm/pandoc#7516] opened 2021-08-20 15:53 UTC
**Explain the problem.**
(1) Citations are not rendering title case. (2) Pandoc is not recognizing "omit author" command/hyphen. (3) Pandoc is not applying abbreviations. I am using a makefile document. Also note that I have tried --citation-abbreviations and --abbreviations. The abbreviations file is in JSON. The CSL file was produced by Zotero.

--citeproc --abbreviations=$(ABBREVIATIONS) --csl=$(CSL_FILE) --bibliography=$(BIBLIOGRAPHY)

For reference:
docx: $(MAKEFILE)
	$(PANDOC_COMMAND) $(SOURCE) $(ARGS) $(DOCX_ARGS) -o $(OUTPUT_FILENAME).docx

Everything worked well before I upgraded to the latest version of pandoc. I may be missing something.

**Pandoc version?**
2.14.1 on Mac OSX.

**Comment by sopertob** [comment] 2021-08-20 15:57
The --citeproc line is under the label ARGS.

**Comment by jgm** [comment] 2021-08-20 16:21
If you want help with this, you need to give precise instructions for reproducing the issue (as minimal as possible), including all necessary commands in input files.

Notes:

-  `--citation-abbrevations` is the one you want. See the manual.
- title casing depends both on the style and the locale (are you specifying `lang`?)
- on omit-author, are you using the author-in-text form? see #7219

**Comment by sopertob** [comment] 2021-08-20 16:54
If any precision was lost, it is because I wasn't sure where to start in order to present a linear explanation. I'll try to be more specific.

# Command

* pandoc draft.md --citeproc --citation-abbreviations=abbreviations.json --csl=style.csl --bibliography=bibliography.json -o printout.docx

# Other responses

* RE abbreviations, I used the format in the manual (cut and pasted, actually, and then added with my journals). (See below).
* Yes, to language specified in the bibliography.json file. Although, now that I'm thinking about it, does capitalization matter? I understand that the first two letters are read, so en/eng/english doesn't matter. Some, however are capitalized: En/Eng/English. Could capitalization trip it? 
* Yes, I am using the proper form. It was working well before. But that said, I can't remember if I generated a document for publication before or after the "old behavior" (mentioned in "Citekey outside square brackets not working") was changed after updates (this past April?).  The reason this practice makes sense in the Humanities is footnotes. That is, one can refer in a sentence to the author and then cite the work. Such as, ^[Michel Foucault argued that power was distributed along networks of relations, which could sometimes change from one context to another (in _Discipline and Punish_, p. 101).]

# Abbreviations file (abbreviated sample)

{ "default": {
    "container-title": {
            "Journal of Near Eastern Studies": "JNES",
            "Journal of the American Academy of Religion": "JAAR",
            "Vetus Testamentum": "VT",
            "Zeitschrift fur die Alttestamentliche Wissenschaft": "ZAW"
    }
  }
}

**Comment by jgm** [comment] 2021-08-20 17:18
The command isn't enough; to make the maintainer's life easier, please provide the inputs, so we don't have to guess.

`lang` can be specified in the markdown document's YAML metadata (BCP 47 format must be used), or using `--metadata lang=en`.

You can put your thoughts about the omit-author issue on issue #7219.  Yes, the change was relatively recent.

Manual says `--citation-abbreviations`

>  may be used to specify     
a JSON file containing abbreviations of journals that should be     
used in formatted bibliographies when `form="short"` is                
specified.

So perhaps the issue is that your style doesn't specify `form="short"` for the journal titles.

**Comment by sopertob** [comment] 2021-08-20 17:58
Apologies, I was trying to avoid posting everything in my makefile. I'll
paste its contents here so I don't miss anything. I will also add my
default.yaml and a sample from my bibliography file below.

I run the make command in the folder when I generate a DOCX file, or
other.  I haven't been adding any metadata to the document file itself to
keep things "clean." Some commands in the default.yaml are for PDF only.

The Chicago form *should* specify short for subsequent notes, but not the
initial occurrence nor for the Works Cited. At least, everything was
working before the update. (I am using the same makefile commands, and the
same CSL file.)


ROOT_NAME = article-name
OUTPUT_FILENAME = printout_$(ROOT_NAME)
METADATA = default.yaml
BIBLIOGRAPHY = bibliography_$(ROOT_NAME).json
CSS_FILE =
MAKEFILE = makefile
SOURCE = draft_article-name.md
CSL_FILE = citation_chicago_$(ROOT_NAME).csl
ABBREVIATIONS = abbreviations.json

#####################################################

HTML_ARGS = -s --to=html5
PDF_ARGS = -V documentclass=report --pdf-engine=xelatex --toc --toc-depth=2
DOCX_ARGS = --reference-doc=path/to/reference.docx
METADATA_ARGS = $(METADATA)
CSS_ARGS = --css=$(CSS_FILE)
CITATION_ARGS = --citeproc --citation-abbreviations=$(ABBREVIATIONS)
--csl=$(CSL_FILE) --bibliography=$(BIBLIOGRAPHY)
ARGS = $(CSS_ARGS) $(METADATA_ARGS) $(CITATION_ARGS)
EPUB_ARGS = $(METADATA_ARGS) $(CITATION_ARGS)
PANDOC_COMMAND = pandoc

######################################################

all:    html pdf docx epub
clean:
rm -f printout*html printout*pdf printout*docx printout*epub


html: $(MAKEFILE) $(CSS_FILE)
$(PANDOC_COMMAND) $(SOURCE) $(ARGS) $(HTML_ARGS) -o $(OUTPUT_FILENAME).html

pdf: $(METADATA) $(MAKEFILE)
$(PANDOC_COMMAND) $(SOURCE) $(ARGS) $(PDF_ARGS) $(METADATA_ARGS) -o
$(OUTPUT_FILENAME).pdf

docx: $(MAKEFILE)
$(PANDOC_COMMAND) $(SOURCE) $(ARGS) $(DOCX_ARGS) -o $(OUTPUT_FILENAME).docx

epub: $(METADATA) $(MAKEFILE)
$(PANDOC_COMMAND) $(SOURCE) $(EPUB_ARGS) -o $(OUTPUT_FILENAME).epub


## Default.yaml

---
geometry: margin=1.5in
fontsize: 12pt
reference-section-title: Works Cited
lang: en
header-includes:
- \usepackage{fancyhdr}
- \usepackage{datetime2}
- \pagestyle{fancy}
- \fancyhead{}
- \fancyhead[CO,CE]{Printed \DTMnow\quad\copyright name}
- \usepackage{polyglossia}
- \usepackage{draftwatermark}
- \SetWatermarkColor[gray]{0.93}
- \SetWatermarkText{Draft}
- \SetWatermarkScale{2.5}
- \usepackage{bidi}
- \setmainfont{Times New Roman}
- \usepackage{fontspec}
- \renewcommand{\baselinestretch}{1}
- \setlength{\parindent}{2em}
---

## Sample from bibliography (exported via Better CSL JSON, Zotero plugin)

{"id":"Aster2012","author":[{"family":"Aster","given":"Shawn
Zelig"}],"container-title":"Journal of Near Eastern
Studies","container-title-short":"JNES","DOI":"10.1086/664451","ISSN":"00222968","issue":"1","issued":{"date-parts":[[2012]]},"language":"English","page":"31-46","title":"The
function of the city of Jezreel and the symbolism of Jezreel in Hosea
1-2","type":"article-journal","volume":"71"},

**Comment by sopertob** [comment] 2021-08-20 18:13
Update: forcing "en" in all of my bib entries has fixed the capitalization and short form for subsequent citations.

**Comment by jgm** [comment] 2021-08-20 18:24
> At least, everything was working before the update.

I believe the old pandoc-citeproc didn't respect the limitation to `form="short"` which is called for in the spec, and that may be why you see a difference.

**Comment by jgm** [comment] 2021-08-20 18:25
Now that you've specified the `lang`, do you have any remaining issues, aside from #7219?

**Comment by jgm** [comment] 2021-08-20 18:25
Also, in case you post further issues: the most convenient thing for me is if you just upload a zip file containing everything I need to reproduce the issue (as minimal as possible).

**Comment by sopertob** [comment] 2021-08-20 18:37
In addition to #7219, I'm still not getting abbreviations to work (#3 of
original post). I can add a comment there, as you suggested.

**Comment by sopertob** [comment] 2021-08-20 18:38
Understood, regarding a zip file.

**Comment by jgm** [comment] 2021-08-20 19:17
I can look at the abbreviations issue if you upload a zip file with everything needed and full instructions to reproduce the issue.

**Comment by sopertob** [comment] 2021-08-20 20:25
Can you delete the files from the public forum after you get them? They are
of a manuscript being worked on for publication.

Instructions: once unzipped, navigate to the relevant folder in a terminal
window, run "make docx." The resulting file will be
"printout_trauma-uncivilized.docx."

**Comment by jgm** [comment] 2021-08-20 22:01
Don't upload anything you don't to be public.  Create a minimal example with garbage text.

**Comment by sopertob** [comment] 2021-08-20 22:30
Understood. I don't think the original zip file made it through. (I can't
see it.) I have attached a new zip file to my preceding post.

**Comment by jgm** [comment] 2021-08-20 23:58
Try using `"container-title"` instead of `"title"` in your abbreviations.json.
(Like the example in the User's Guide -- this is documented.)

**Comment by sopertob** [comment] 2021-08-21 01:40
That's what's in the abbreviations file. I copied the format out of the manual. I guess I'm not seeing what you are.

**Comment by jgm** [comment] 2021-08-21 03:04
You're right, sorry!  You do have `collection-title`.

**Comment by jgm** [comment] 2021-08-21 03:08
But look in your csl file.  Where you have `<text variable="container-title"...>` make sure you add a `form="short"` attribute to the element.  That is what the documentation is referring to when it says "may be used to specify a JSON file containing abbreviations of journals that should be used in formatted bibliographies when `form="short"` is specified."

**Comment by jgm** [comment] 2021-08-21 03:43
The reason it worked before is that pandoc-citeproc did not properly implement the spec; it did the abbreviation transformations even without `form="short"`.

**Comment by jgm** [comment] 2021-08-21 04:22
I think that takes care of your issues, aside from #7219 which I'm not sure about.
So, closing.

**Closed by jgm** 2021-08-21 04:22 UTC
Labels: bug

**Comment by sopertob** [comment] 2021-08-21 13:46
That works on my end, too. Thank you.
