### ISSUE TITLE
Expose automatic section numbering to filters.

### ISSUE THREAD

**Issue by RobertZenz** [jgm/pandoc#4258] opened 2018-01-15 08:38 UTC
It would be interesting if the automatic section numbers (`--number-sections`) would be exposed to filters. That would, for example, allow to build a filter which appends the section numbers to automatic section references (or similar).

Currently, we must re-built that index manually in a filter.

**Comment by jkr** [comment] 2018-01-15 16:11
The issue is that `--number-sections` is an option to the writer, and so takes place after the filter. For LaTeX, for example, it doesn't actually do any numbering -- it just sets `secnumdepth` in the the LaTeX preamble, and lets LaTeX do the numbering. So there isn't really anything to expose at the filter level.

@tarleb, is there some function we could expose in lua built on top of hierarchicalize?

**Comment by tarleb** [comment] 2018-01-15 18:25
Nothing great comes to mind right now. We could build a lua function which adds numbering info to the *Header*'s key-value attributes. It wouldn't be terribly efficient (deserialize/reserialize the document completely), but could do the job.

**Comment by jgm** [comment] 2018-01-15 18:27
`hierarchicalize`, which is exposed in the lua interface, does include numbering information.  Are you aware of that?

**Comment by RobertZenz** [comment] 2018-01-16 08:53
Yes, I'm aware of that function (and that you can "re-built" the section numbers in Lua using it).

**Comment by tarleb** [comment] 2021-03-28 12:12
I think we forgot to close this when we introduced [`pandoc.utils.make_sections`](https://pandoc.org/lua-filters.html#pandoc.utils.make_sections), so closing now.

**Closed by tarleb** 2021-03-28 12:12 UTC
Labels: enhancement, lua-filters
