### ISSUE TITLE
how to retain table border In HTML to word conversion

### ISSUE THREAD

**Issue by BlackDeveloper2022** [jgm/pandoc#8388] opened 2022-10-20 12:46 UTC
I am try to retain table border in html to word conversion, but not retain in word.

HTML Structure:
 <table data-frame="box" data-rules="all">
            <colgroup>
                <col data-colname="col1" data-colnum="1" width="77.60pt" style="border-left: 0.5pt solid; border-right: 0.5pt solid;" data-colalign="left" />
                <col data-colname="col2" data-colnum="2" width="77.30pt" style="border-right: 0.5pt solid;" data-colalign="left" />
                <col data-colname="col3" data-colnum="3" width="78.30pt" style="border-right: 0.5pt solid;" data-colalign="left" />
                <col data-colname="col4" data-colnum="4" width="79.05pt" style="border-right: 0.5pt solid;" data-colalign="left" />
            </colgroup>
            <tbody>
                <tr content-type="thead" style="border-bottom: 0.5pt solid; border-top: 0.5pt solid;">
                    <td data-pos="1" style="border-bottom: 0.5pt solid; border-top: 0.5pt solid; background-color: #auto;"><span custom-style="T col hd"><b>
                        City
                    </b></span></td>
                    <td data-pos="2" style="border-bottom: 0.5pt solid; border-top: 0.5pt solid; background-color: #auto;"><span custom-style="T col hd"><b>
                        Green area per cap (m<sup>2</sup>/cap.)
                    </b></span></td>
                    <td data-pos="3" style="border-bottom: 0.5pt solid; border-top: 0.5pt solid; background-color: #auto;"><span custom-style="T col hd"><b>
                        Statista (2018) city greenery (m<sup>2</sup>/cap)
                    </b></span></td>
                    <td data-pos="4" style="border-bottom: 0.5pt solid; border-top: 0.5pt solid; background-color: #auto;"><span custom-style="T col hd"><b>
                        Difference (%)
                    </b></span></td>
                </tr>
            <tr content-type="thead" style="border-bottom: 0.5pt solid;">
                    <td data-pos="1" style="border-bottom: 0.5pt solid; background-color: #auto;"><span custom-style="T body">
                        <p class="Text flush">Madrid</span></td>
                    <td data-pos="2" style="border-bottom: 0.5pt solid; background-color: #auto;"><span custom-style="T body">
                        <p class="Text flush">22.25</span></td>
                    <td data-pos="3" style="border-bottom: 0.5pt solid; background-color: #auto;"><span custom-style="T body">
                        <p class="Text flush">21.09</span></td>
                    <td data-pos="4" style="border-bottom: 0.5pt solid; background-color: #auto;"><span custom-style="T body">
                        <p class="Text flush">&#x2013;5</span></td>
                </tr>
                <tr content-type="thead" style="border-bottom: 0.5pt solid;">
                    <td data-pos="1" style="border-bottom: 0.5pt solid; background-color: #auto;"><span custom-style="T body">
                        <p class="Text flush">Athens</span></td>
                    <td data-pos="2" style="border-bottom: 0.5pt solid; background-color: #auto;"><span custom-style="T body">
                        <p class="Text flush">4.28</span></td>
                    <td data-pos="3" style="border-bottom: 0.5pt solid; background-color: #auto;"><span custom-style="T body">
                        <p class="Text flush">4.81</span></td>
                    <td data-pos="4" style="border-bottom: 0.5pt solid; background-color: #auto;"><span custom-style="T body">
                        <p class="Text flush">12</span></td>
                </tr>
            </tbody>
        </table>

Kindly give solution for table border retain issue.

**Comment by tarleb** [comment] 2022-10-20 14:32
This appears to be a duplicate of #6496 and/or #5460.

**Closed by tarleb** 2022-10-20 14:32 UTC
Labels: bug
