### ISSUE TITLE
epub: exclude headers from being in the toc

### ISSUE THREAD

**Issue by SushiTee** [jgm/pandoc#4824] opened 2018-08-09 11:23 UTC
Currently there is just a class which can be used to not number headers in the toc (.unnumbered).

It would be good to have a class to exclude headers from being in the toc.

Currently I worked around this issue by replacing all headers with paragraphs and some css to make those paragraphs look like headers but this is nasty.

**Comment by jgm** [comment] 2018-08-09 17:13
Duplicate of #1762 - note that there's a filter there that may help you.

**Closed by jgm** 2018-08-09 17:13 UTC

**Comment by mb21** [comment] 2018-08-10 15:53
The idea is probably to solve this for LaTeX and HTML/ePUB output at the same time.

For now, you can simply not use `--toc` and/or write a filter that sets the `toc` variable to what you want.

**Comment by jgm** [comment] 2018-08-10 17:48
#1762 is about making the writers, in general, sensitive to something like `.unlisted`.
I have updated the title to make that clearer.
You are right that the filter there won't help you with ePub.
As @mb21 says, you `--top-depth` could be enough, if you want to exclude all headers below a certain level. Otherwise, your only real alternative is to create the TOC yourself and populate the `toc` variable manually.  This could be done in a filter.
