### ISSUE TITLE
Support plain text as input format

### ISSUE THREAD

**Issue by TangentFoxy** [jgm/pandoc#10408] opened 2024-11-23 22:10 UTC
**Describe your proposed improvement and the problem it solves.**

I want to read in plain text without any modifications and output it in another format (so in effect adding minimal character escaping or whatever is needed to make the plain text come out in the wrapper of that format).

This has been requested before (most recently in #9122) but was resolved by using a custom reader. I do not think that is a good solution because in #6393 the example plain text reader has had to be changed to maintain compatibility. It feels fragile, whereas if plain text input was possible without a custom reader, I would feel secure in using pandoc on plain text even if I haven't touched it in years.

I understand the argument against this is **there is no standard way of formatting plain text, and thus any formatting could be lost or malformed**, correct? (I am referencing brainchild0's comment on #6393.) I think that argument misses the point for those of us who want this. We want to be able to wrap/escape plain text in another format, *not* try to detect and understand whatever formatting conventions were used in the original file.

Additionally, I think the extant solution is fragile because not only has it needed modification over time, but it has also resulted in multiple implementations being created with no easy way for a newbie to understand what will work or not (see #8603 for example).

(I am that newbie.)

**Describe alternatives you've considered.**

Another solution was offered in #2705 to use Markdown and code blocks. I consider this undesirable because while it does prevent misinterpretation of formatting in the input, it guarantees that the output *has* been changed to a code block. Code blocks are usually monospaced and unwrapped by default when any tool displays them, which can be undesirable. (Where it is desired, existing solutions work well.)

In #1721, using a program to handle pre-conversion to Pandoc's native format is suggested, which continues to feel fragile to me.

I may have missed some, but I believe I have looked at all issues and discussions (none there) related to this request.

---

I would additionally like to point out that the core argument of this desire has been said in one form or another in all of these issues: We want to be able to input plain text without interpretation, and have it escaped as necessary to prevent it from automaticlly being re-formatted in an output format. It seems this core desire was missed in the responses to previous issues on this topic.

**Comment by TangentFoxy** [comment] 2024-11-23 22:12
I wrote all of that before reading the current version of the Lua plain text reader at https://pandoc.org/custom-readers#example-plain-text-reader

Now that I have read that, I can see that while it will probably work for my use case, it *also* introduces changes to the plain text by automatically grouping text. The whole point of desiring a plain text input format is to make *no changes at all* to the input text **other than necessary escaping for the output format**.

**Comment by jgm** [comment] 2024-11-24 03:02
> The whole point of desiring a plain text input format is to make no changes at all to the input text other than necessary escaping for the output format.

Well, everyone who wants a "plain text reader" seems to have a different idea of what that means.

You would need to explain with an example what Pandoc AST you'd expect to be the result of parsing some "plain text."  For example, should
```
  ab   cd
ef

gh
```
be 
```hs
[Para [Str "ab", Space, Str "cd", SoftBreak, Str "ef", SoftBreak, SoftBreak, Str "gh"]]
```
or maybe
```hs
Para [Str "  ab   cd\nef\n\ngh"]
```
Endless permutations are possible.  Everyone has different needs.  So directing people to use Lua filters seems appropriate.

There simply *isn't* a well-defined format called "plain text."

**Comment by tarleb** [comment] 2024-11-25 16:29
Closing as duplicate of #6393 and #9122.

**Closed by tarleb** 2024-11-25 16:29 UTC
Labels: enhancement

**Comment by TangentFoxy** [comment] 2024-11-25 19:59
@jgm 

> Well, everyone who wants a "plain text reader" seems to have a different idea of what that means.

<details><summary>Detailed references and quotes from the related issues</summary>
<p>

- In #9122, the problem is clearly stated that parts of input are stripped or modified before the requesting line length wrapping is performed.
- #6393 "All I really want is something that can read plain text without ruining it. As currently things like underscore and bracket usage could give results that don't match the writer's intention." To me, it seems clear that "ruining it" means modifications, as they then clarify that some characters are being treated incorrectly.
  - "I'm parsing emails that can be either HTML or Plain text, and I want to normalize them both into markdown. If I don't do something to at least escape the plain text, then it will sometimes be garbled." The utility is in being able to import plain text without modification so that escaping can be performed as necessary for the intended output.
  - alerque explained it quite well: "Plain text is plain text. [...] any valid UTF-8 should round-trip from the input side to the output side unchanged via `pandoc -f plain -t plain`."
    - They then go on to say "At most it may add paragraph breaks similar to the way the current writter outputs them." but it's clear they're just guessing at concessions that may need to be made if it isn't possible to achieve `pandoc -f plain -t plain` not manipulating a file.
    - They also suggest alternative names if that pass-through can't be achieved to highlight that such an addition isn't *exactly* the same thing: "Another name like `unformatted`, `null`, or `passthrough` instead of `plain` might be in order."
    - I *did* miss their statement "split on `\n{2,}` and have Para elements at the cost of collapsing some whitespace [...] is preferable for my use case" so now I understand what you mean that there isn't perfect agreement.
- #8603 "With `pandoc -f plain`, a user should be able to explicitly declare that Pandoc should treat the input as plain text." and their example is that they want it to not react to `2) ` as indicating an ordered list type.
- #2705 The introductory paragraph clearly explains that they want to be able to use Pandoc to escape formatting in output without having to know what needs escaping - thus the need for an input method that does not modify its source.
  - When asked for clarification of their needs: "I just want my plain text content to appear as faithfully reproduced as possible" and "This means multiple consecutive newlines or spaces should be preserved, any punctuation that would be interpreted as Markdown formatting codes should be escaped so that such formatting does not take place, etc."
  - The suggestion of wrapping in a codeblock is a hack that works for most uses, but is still changing the text.
- #1721 "I am looking for a method to convert a plain Unicode string to Pandoc Markdown."

</p>
</details>

I concede that there are statements requesting subtle differences I did not notice the first time, but the majority seems to agree on the basic premise: We want an input type that **does not manipulate the input**.

You argue that people have different definitions of plain text, but the only differences I see are in how people want their *output*, which is already handled by other options Pandoc has (`--eol`, `--wrap`, `--columns`, the `gutenburg` extension).

We don't *need* endless permutations. An input type that doesn't change anything itself is sufficient.

> There simply isn't a well-defined format called "plain text."

Wikipedia has a very good summary on what is considered plain text or not, and how the term is used to differentiate in various places. The most aggressive differentiation is "Just ASCII text." which I think we can *all* agree is too specific. The least aggressive differentiation is "not containing parts that cannot be correctly interpreted by the character encoding in effect". Pandoc only uses UTF-8 anyhow, so that definition is sufficient for *what* plain text is to Pandoc: **It's text encoded in UTF-8.**

 

I think I better understand now why you are hesitant on this topic. I don't agree, but I think I've made my point.

**Comment by tarleb** [comment] 2024-11-26 20:48
All inputs have to be converted into pandoc's internal document representation, and that representation is semantic. There is no way to read in a document without assigning *some* kind of semantic meaning. E.g., a paragraph followed by a blank line is often considered a paragraph, which is already a semantic interpretation. But it might be an unwanted interpretation. Furthermore, spaces in the internal representation are collapsible, so non-collapsible spaces would need to become "words". Or maybe each line should become a "word"? Or is the whole document like a single word, linebreaks and all? It's just not clear, and there simply cannot be a "one-size-fits-all" solution.

**Comment by TangentFoxy** [comment] 2024-11-27 04:34
> Or is the whole document like a single word, linebreaks and all?

Based on your description of the internal representation, that would be the only way to guarantee that no modification has been made.

**Comment by alerque** [comment] 2024-11-27 06:19
@TangentFoxy If all you want is one giant blob in the AST it would be trivial to write a Lua reader for your purposes. I think you'll find it a lot less useful than you seem to expect when you actually have it leaded up though. Here it is:

```lua
function Reader(input)
  return pandoc.Pandoc({ pandoc.Str(tostring(input)) })
end
```

Save that as `plain.lua` or whatever you like. Now test it on your input file by specifying the Lua file as the input format:

```console
$ pandoc -f plain.lua input.txt -t native
```

You can change the `-t` to whatever output format you plan to us.

Again I think you'll find the net effect less useful than you think, but that *is* the plain text reader your seem to be asking for. Does it actually meant your need? If so great. If not maybe give another pass to what Albert an John and others have been saying about there not being a straight forward way forward that meets expectations here because there is no such thing as a "plain" document. You can have a UTF-8 string blob as evidenced above, but in the content of Pandoc the expectation is that it can be converted *to* some other document format, and that requires inventing structure of some sort.
