### ISSUE TITLE
Validate ICML

### ISSUE THREAD

**Issue by jenstroeger** [jgm/pandoc#2947] opened 2016-05-26 05:30 UTC
Using the RelaxNG schema for IDML from the [Adobe InDesign SDK](http://www.adobe.com/devnet/indesign/sdk.html) for CS5.5 v7.5.3.333, I noticed that the current version of [`tests/writer.icml`](https://github.com/jgm/pandoc/blob/1ead1f39ad71086253ff6cb30d4462be642b4901/tests/writer.icml) does not validate using [xmllint](http://xmlsoft.org/xmllint.html). I am not sure if that's a versioning problem between schema and ICML, or if the ICML file itself might be incorrect. 

```
writer.icml:4: element Document: Relax-NG validity error : Element Document failed to validate attributes
writer.icml:425: element RootTableStyleGroup: Relax-NG validity error : Expecting an element TableStyle, got nothing
writer.icml:425: element RootTableStyleGroup: Relax-NG validity error : Expecting element TextVariable, got RootTableStyleGroup
writer.icml:425: element RootTableStyleGroup: Relax-NG validity error : Element Document has extra content: RootTableStyleGroup
writer.icml fails to validate
```

Any plans to address that?

**Comment by jgm** [comment] 2016-05-26 06:26
@mb21 - any thoughts?

**Comment by mb21** [comment] 2016-05-26 07:26
I validated it against a CS6 schema a while back. But it's quite possible that the writer.icml has changed since then. Can you tell us which exact schema in which exact SDK you used?

P.S. Apparently the `product` field in `<?aid style="50" type="snippet" readerVersion="6.0" featureSet="513" product="8.0(370)" ?>` corresponds as follows to CS versions:

> Adobe InDesign CS4 = (6.x)
> Adobe InDesign CS5 = (7)
> Adobe InDesign CS5.5 = (7.5)
> Adobe InDesign CS6 = (8.x)

**Comment by jenstroeger** [comment] 2016-05-26 13:00
Where did you find that `product` documentation?

[Bookalope](https://github.com/jenstroeger/Bookalope) generates ICML with `<?aid style="50" type="snippet" readerVersion="7.0" featureSet="513" product="7.0(292)" ?>` taken from the CS5.5 SDK (v7.5.3.333). However, the [IDML 7.0 Specification](https://www.adobe.com/content/dam/Adobe/en/devnet/indesign/cs55-docs/IDML/idml-specification.pdf) contains various `product="7.0(nnn)"` values, and two different `featureSet` values, but does not seem to define them.

**Comment by mb21** [comment] 2016-05-26 13:35
The version information is from this [unofficial site](http://producthelp.sdl.com/kb/Articles/3857.html)...

Have you found an ICML schema file that works with `xmllint`? I only found ones that work with `trang` (without doing a converstion first).

**Comment by jenstroeger** [comment] 2016-05-26 14:01
I took the RNC from the InDesign SDK, used [`trang`](https://github.com/relaxng/jing-trang) to convert it to RNG, and then either [`xmllint`](http://xmlsoft.org/xmllint.html) or the Python module  [`lxml`](http://lxml.de/) to validate my/your ICML files against the generated RNG.

Are you saying that validating the ICML using the original RNC yields a `validates` result?

**Comment by mb21** [comment] 2016-05-26 20:47
I could reproduce the validation error you got with:

    # install trang
    $ brew install trang

    # get schema
    $ curl -O http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/indesign/sdk/cs6/idml/idml-schema.zip
    $ unzip idml-schema.zip  -d idml-schema
    $ cd idml-schema/single/

    # convert schema from rnc to rng
    $ trang -O rng IDMarkupLanguage.rnc idml.rng

    # validate the writer.icml file
    $ xmllint --noout --relaxng idml.rng writer.icml

However, creating a new icml file with Adobe InCopy CS6 and validting it the same way also results in errors. Even though I'm fairly certain it's the right schema, since the `IDMarkupLanguage.rnc` has the comment `# Adobe InDesign CS6 8.0.0.370` on the first line. So I guess those schemas are more guidelines than anything that really needs to be implemented for things to work...

**Comment by jenstroeger** [comment] 2016-05-26 22:43
Yes, those were my steps; glad you could reproduce this issue. But what is the point of validating a document against a schema, if the schema is considered inaccurate? That defeats its purpose, IMO.

The thing is, in my workflow every document resulting from a transformation *must* validate in order to ensure correctness. Of course, such a workflow assumes that a schema describes a “correct” document...

**Comment by mb21** [comment] 2016-05-28 12:04
I agree that it's a laudable goal. Unfortunately, the process of writing the ICML writer was more looking at what InCopy produced, taking as much away as possible (unnecessary attributes and elements) but leaving as much in as necessary so that it still opens in InDesign/InCopy and still produces the desired output.

If what InCopy produces would have validated itself, our output would have been much closer to validating as well. Unfortunately, I fear the way things are now there are quite a few things that don't validate, but pull requests welcome :)

**Comment by jgm** [comment] 2016-07-01 22:51
What's the upshot here?  Should this issue be closed?

**Comment by mb21** [comment] 2016-07-02 19:37
The case for leaving it open: it's a laudable goal. The case for closing it: would require a major overhaul of the ICML writer, which personally I'm not going to get around to anytime soon.

**Comment by tarleb** [comment] 2021-05-12 08:37
Given the amount of work that would be involved, the fact that this doesn't seem necessary to use the ICML writer effectively, and the 5 years of inactivity on this issue, I believe that it is safe to close.

**Closed by tarleb** 2021-05-12 08:37 UTC
Labels: complexity:high, enhancement, format:ICML, writer
