### ISSUE TITLE
Data-number is getting defined twice

### ISSUE THREAD

**Issue by ptmkenny** [jgm/pandoc#6006] opened 2019-12-22 18:56 UTC
Bug report: 

Pandoc is failing to create a valid epub from markdown because it defines data-number twice on headings.

Version: pandoc 2.9 on macOS

Input: test.md

```
# Heading 1

## Heading 2

Body text
```

Pandoc command:

`pandoc test.md -o output.epub`

When I open the epub in iBooks, I get the following error:

"error on line 11 at column 79: Attribute data-number redefined"

**Comment by tarleb** [comment] 2019-12-22 19:35
Thanks for the report. This will be fixed in the next release. You can already try a nightly build or the latest release candidate.

Closing as duplicate of #5986 and #6005.

**Closed by tarleb** 2019-12-22 19:35 UTC
