### ISSUE TITLE
Image resource not found issues -- more than one directory

### ISSUE THREAD

**Issue by MakerSeldon** [jgm/pandoc#6261] opened 2020-04-07 17:28 UTC
**Automatic Document Creation with images.** 

> pandoc 2.2.3.2 Compiled with pandoc-types 1.17.5.1, texmath 0.11.0.1, skylighting 0.7.2

I was having a problem creating a book out of README.md files on GitHub. I was documenting a build using the README.md pages at each directory level.  I was trying to take all the specific README.md files and create a single manual/book. 

I have found a workaround, but this seems wrong. The image paths have to be referenced from the directory that pandoc command is run from. This seems counter-intuitive to the instructions to keep relative paths. 

File structure

\Project
  -- README.md 
  -- ImageProject.png
       \-- Description
                  -- README.md
                  -- ImageDescription.png
       \-- Function 1
                  -- README.md
                  -- ImageF1.png 
       \|-- Function 2
                  -- README.md
                  -- Image.F2png

Executed Pandoc in \Project folder. to generate pdf. 
* ImageProject.png correctly included
* ImageDescription.png, ImageF1.png, ImageF2.png all reported unable to locate resources. 

## FAILING Config
README.md examples
##Project README.md
       Text
       ![Image](ImageProject.png)

##Description README.md
      Text
      ![Image](ImageDescription.png)

## Passing Config
README.md examples
##Project README.md
       Text
       ![Image](ImageProject.png)

##Description README.md
      Text
      ![Image](Description/ImageDescription.png)

**Comment by tarleb** [comment] 2020-04-07 17:56
Thanks for the report. This appears to be a duplicate of #3752. Closing in favor of that issue.

**Closed by tarleb** 2020-04-07 17:56 UTC
