### ISSUE TITLE
uniform attribute lists

### ISSUE THREAD

**Issue by blaenk** [jgm/pandoc#1242] opened 2014-04-13 02:48 UTC
So I know this has been [discussed to death](https://github.com/jgm/pandoc/issues/684#issuecomment-14995856) for over 6 years. I know they've been added to headers and inline/block code. Already those few things they've been added to have been extremely useful in my use cases. I've added AST transformers for headers (renaming how they appear in the table of contents) and codeblocks (adding a caption in the resulting HTML). Allowing them to appear in more places could make Pandoc-flavored markdown extremely more powerful and extensible.

That said, I think the advantages have been discussed to death as well. I'm mainly curious what the current state of this is. Is there a fundamental, technical limitation that prevents them from being added to more things? For example, is there a fear of no longer being backwards compatible due to changing the types in the pandoc-types package? Or is it a design decision on your part, that you don't want to add attribute lists to more things? Or is it that you're open to this, but it's not a priority? Like I said, I'm merely curious, not necessarily meaning to pressure you to work on them or anything.

**Comment by mb21** [comment] 2019-02-02 16:51
Duplicate of #684

**Closed by mb21** 2019-02-02 16:51 UTC
Labels: complexity:high, enhancement, status:more-discussion-needed
