### ISSUE TITLE
From latex to odt - Conversion of \dfrac or \frac

### ISSUE THREAD

**Issue by jmulet** [jgm/pandoc#4859] opened 2018-08-27 13:10 UTC
Bug: strange behavior of \dfrac and \frac commands

Pandoc version: pandoc 2.2.3.2
Compiled with pandoc-types 1.17.5.1, texmath 0.11.0.1, skylighting 0.7.2
Platform: mac OS

Source: $\frac{1+2}{3+4}$
Command: pandoc -s -f source.tex -t odt -o source.odt

Bug: produces wrong fraction. The resulting odt formula is 1+2 } over { 3 + 4, so initial and final brackets are missing.

If we modify the source to 
Source: $\\, \frac{1+2}{3+4}$
Command: pandoc -s -f source.tex -t odt -o source.odt
 It produces the expected output

**Comment by jgm** [comment] 2018-08-27 17:06
I can't reproduce this.  The fraction looks fine to
me, with either Word or LibreOffice.  Can you send the
source.odt you are producing?  What are you using to
view it?

**Comment by jmulet** [comment] 2018-08-27 18:33
The source is at [https://piworld.es/pandoc/test.tex](https://piworld.es/pandoc/test.tex)
The cmd used is `pandoc -s -f latex -t odt -o test.odt test.tex`
The produced odt is at [https://piworld.es/pandoc/test.odt](https://piworld.es/pandoc/test.odt)
I am using OpenOffice 4 to open test.odt

![captura de pantalla 2018-08-27 a les 20 26 02](https://user-images.githubusercontent.com/5049732/44678246-4823db00-aa38-11e8-8742-7c6dfb13393f.png)
![captura de pantalla 2018-08-27 a les 20 26 23](https://user-images.githubusercontent.com/5049732/44678252-4b1ecb80-aa38-11e8-848a-be221e829475.png)

**Comment by jgm** [comment] 2018-08-27 19:04
No issues viewing this with LibreOffice:
<img width="831" alt="screen shot 2018-08-27 at 12 02 31 pm" src="https://user-images.githubusercontent.com/3044/44679914-20f5eb00-a9f1-11e8-9d29-38cd081fd5b2.png">
And the xml in the odt looks right.
So I guess this may be an OpenOffice issue?
Closing here.

**Closed by jgm** 2018-08-27 19:04 UTC
Labels: closing candidate
