### ISSUE TITLE
Textile Table with alignment not rendering to html properly

### ISSUE THREAD

**Issue by kopf** [jgm/pandoc#1922] opened 2015-02-03 13:15 UTC
The following table

````
| *Header1* | *Header2* | *Header3*  | *Header4* |
| foo |>.blabla |>. foobar |>. blabla | 
| bar |>.blabloo |>. barfoo |>. blabla | 
| *xyz* |  |>. *abc* |>. *123* | 
````

is rendered in Redmine as such:

![](http://ahye.zzzz.io/s/DeFPcVH3.png)

However, using pandoc to render it to html returns the following:

````
<p>| <strong>Header1</strong> | <strong>Header2</strong> | <strong>Header3</strong> | <strong>Header4</strong> |<br />| foo |&gt;.blabla |&gt;. foobar |&gt;. blabla |<br />| bar |&gt;.blabloo |&gt;. barfoo |&gt;. blabla |<br />| <strong>xyz</strong> | |&gt;. <strong>abc</strong> |&gt;. <strong>123</strong> |</p>
````

which renders in a browser as:

![](http://ahye.zzzz.io/s/d9Wo6HSi.png)

Is this a pandoc bug? Or is there something incorrect about the Textile being used? (i.e. does it use a subset of Textile specific to Redmine? I see nothing about alignment on the [wikipedia page for textile](http://en.wikipedia.org/wiki/Textile_%28markup_language%29), but it renders correctly in [textile-js](http://borgar.github.io/textile-js/))

**Comment by jgm** [comment] 2015-02-03 14:33
Pandoc's textile support is incomplete.  Table cell alignments aren't
implemented.  (Note also that in pandoc alignments apply to a whole
column, so there's a bit of a mismatch here.  But pandoc could, at
least, be taught to ignore the alignment marker, and, better,
treat a column with consistent alignemnts as aligned accordingly.

Many other features documented at http://txstyle.org/doc/15/tables are
also unimplemented, including the syntax for a thead.

**Comment by kopf** [comment] 2015-02-03 15:09
Ah, ok. I wasn't aware of that. Ok! 

Thanks for your help anyway. As I'm really only dealing with textile, I'm just going to go ahead and use the python `textile` package.

**Comment by PowerKiKi** [comment] 2016-07-17 03:27
This seems to be a duplicate of #22 and should probably be closed as such.

**Closed** 2016-07-18 17:42 UTC
Labels: enhancement
