### ISSUE TITLE
Let the Fenced Div class transfer to a custom style in DOCX/ODT etc.

### ISSUE THREAD

**Issue by iandol** [jgm/pandoc#4139] opened 2017-12-11 02:29 UTC
Hi, the new Fenced Div feature in Pandoc 2 is excellent, and I was wondering whether there was a feeling that the class name should be converted to a style by default for writers that support it (DOCX, ODT etc). For DOCX, @jkr made a super wonderful addition (https://github.com/jgm/pandoc/pull/3070) to do this using the custom-style attribute, which I assume we could wire together using a filter, but my question is really whether this being done natively would be beneficial. My view is it would be great to be able to use Fenced Divs to specify styles in DOCX etc.

I'm creating a new issue as there are several overlapping issues which don't specifically deal with the current design intention for what a writer should do with the new fenced div.

Related issues:
https://github.com/jgm/pandoc/issues/2542 (closed)
https://github.com/jgm/pandoc/issues/2106
https://github.com/jgm/pandoc/pull/3070 (merged pull request)

**Comment by mb21** [comment] 2017-12-11 09:41
Agreed, from [this comment](https://github.com/jgm/pandoc/issues/2106#issuecomment-341720408):

> Since the following already works for [docx output](http://pandoc.org/MANUAL.html#custom-styles-in-docx-output):
> 
>     ::: {custom-style=poetry}
>     My example poem,
>     is bad.
>     :::
> 
> the idea is to change the syntax (and probably AST representation) to use a class with the `style-` prefix:
> 
>     ::: style-poetry
>     My example poem,
>     is bad.
>     :::

**Comment by iandol** [comment] 2017-12-11 10:13
I didn't really understand the need for the `+environment` when I first looked at #2106 and assumed it was trying for something different to simple translation of style->style. But that was probably me reading through that thread too quickly. I'm sure there is a good reason why we can't just use a straight conversion of style names (`::: Poetry :::` becomes a Poetry style in word) without needing an extension, i just haven't grokked it yet...

If this is my own ignorance then close this and lets continue on #2106.

**Comment by mb21** [comment] 2017-12-11 12:03
Duplicate of #2106

**Closed by mb21** 2017-12-11 12:03 UTC

**Comment by jgm** [comment] 2017-12-11 15:31
+++ Ian [Dec 11 17 02:13 ]:
>   I didn't really understand the need for the +environment when I first
>   looked at [1]#2106 and assumed it was trying for something different to
>   simple translation of style->style. But that was probably me reading
>   through that thread too quickly. I'm sure there is a good reason why we
>   can't just use a straight conversion of style names (::: Poetry :::
>   becomes a Poetry style in word) without needing an extension, i just
>   haven't grokked it yet...

Perhaps this question should be raised again, but let's raise it
on #2106 so everything is in one place.  I believe the
reasons for custom-style names are presented  there.
