### ISSUE TITLE
Resizing images once their coverted from HTML to docx

### ISSUE THREAD

**Issue by satikusala** [jgm/pandoc#7199] opened 2021-04-03 04:04 UTC
I am using Pandoc to convert from HTML to Docx. It is working great, but for one issue. 

The images in the file can't be resized. No matter what I do I can't get the anchors to resize, them, all I can do it delete them and then copy in the original to be able to resize. Is there a fix for this?

**Comment by mb21** [comment] 2021-04-03 06:33
Thank you for submitting a bug report. However, we cannot improve pandoc or help you unless you give us all of the following information:

* the pandoc version (check using `pandoc -v` and try to reproduce the bug with the latest released version of pandoc.)
* the exact command line used
* the exact input used
* the output received
* the output you expected instead

A small test case (just a few lines) is ideal.  If your input is large, try to whittle it down to a **minimum working example**.

Finally, ask questions on [pandoc-discuss](http://groups.google.com/group/pandoc-discuss) and read the [User's Guide](http://pandoc.org/MANUAL.html).

**Comment by satikusala** [comment] 2021-04-03 14:14
Thank you!!!!

**the pandoc version**
Version: 2.11.3.1

**the exact command line used**
pandoc -s TestFile4.html --reference-doc=aiztemp.docx -o estFile4.docx

**the exact input used**
``<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8">
	<title>Test file</title>
</head>
<body>


<h1>Test file</h1>
<p>  <br><a href=""><img src="file:////Users/michaelbecker/GoogleDrive/DevonThinkTBXDB/Media/LinkedInImg/mBecker.jpg" ></a><br> </p>
<h2>Section 1</h2>
<p>Some text</p>

<h2>Section 2</h2>
<p>Some text</p>


</body>
</html>``

**the output I get 
[TestFile4.docx](https://github.com/jgm/pandoc/files/6252663/TestFile4.docx)
**
Here is the image.
![mBecker](https://user-images.githubusercontent.com/58040263/113481021-1c68fd00-944c-11eb-9f8c-1c5fcdc8b9d7.jpg)

What I want to be able to do is to manually resize the image once it is in Word.  If you open the world file you'll see that it can not be adjusted in anyway.

**Comment by jgm** [comment] 2021-04-03 18:07
I tried inserting an image with Word for comparison.
The resizable image looks like this in the XML:
``` xml
        <w:drawing>
          <wp:inline distT="0" distB="0" distL="0" distR="0"
          wp14:anchorId="36938BE1" wp14:editId="519E1FDC">
            <wp:extent cx="5943600" cy="4830445" />
            <wp:effectExtent l="0" t="0" r="0" b="0" />
            <wp:docPr id="2" name="Picture 2"
            descr="Text, letter  Description automatically generated" />
            <wp:cNvGraphicFramePr>
              <a:graphicFrameLocks xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
              noChangeAspect="1" />
            </wp:cNvGraphicFramePr>
            <a:graphic xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main">

              <a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture">

                <pic:pic xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture">

                  <pic:nvPicPr>
                    <pic:cNvPr id="2"
                    name="Screen Shot 2021-03-18 at 9.31.11 AM.png" />
                    <pic:cNvPicPr />
                  </pic:nvPicPr>
                  <pic:blipFill>
                    <a:blip r:embed="rId7" cstate="print">
                      <a:extLst>
                        <a:ext uri="{28A0092B-C50C-407E-A947-70E740481C1C}">

                          <a14:useLocalDpi xmlns:a14="http://schemas.microsoft.com/office/drawing/2010/main"
                          val="0" />
                        </a:ext>
                      </a:extLst>
                    </a:blip>
                    <a:stretch>
                      <a:fillRect />
                    </a:stretch>
                  </pic:blipFill>
                  <pic:spPr>
                    <a:xfrm>
                      <a:off x="0" y="0" />
                      <a:ext cx="5943600" cy="4830445" />
                    </a:xfrm>
                    <a:prstGeom prst="rect">
                      <a:avLst />
                    </a:prstGeom>
                  </pic:spPr>
                </pic:pic>
              </a:graphicData>
            </a:graphic>
          </wp:inline>
        </w:drawing>
```
The non-resizable one produced by pandoc looks like this:
``` xml
          <w:drawing>
            <wp:inline distT="0" distB="0" distL="0" distR="0"
            wp14:anchorId="5850595D" wp14:editId="1D812DC3">
              <wp:extent cx="2540000" cy="2540000" />
              <wp:effectExtent l="0" t="0" r="0" b="0" />
              <wp:docPr id="1" name="Picture" />
              <wp:cNvGraphicFramePr />
              <a:graphic xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main">

                <a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture">

                  <pic:pic xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture">

                    <pic:nvPicPr>
                      <pic:cNvPr id="0" name="Picture"
                      descr="file:////Users/michaelbecker/GoogleDrive/DevonThinkTBXDB/Media/LinkedInImg/mBecker.jpg" />
                      <pic:cNvPicPr>
                        <a:picLocks noChangeAspect="1"
                        noChangeArrowheads="1" />
                      </pic:cNvPicPr>
                    </pic:nvPicPr>
                    <pic:blipFill>
                      <a:blip r:embed="rId8" />
                      <a:stretch>
                        <a:fillRect />
                      </a:stretch>
                    </pic:blipFill>
                    <pic:spPr bwMode="auto">
                      <a:xfrm>
                        <a:off x="0" y="0" />
                        <a:ext cx="2540000" cy="2540000" />
                      </a:xfrm>
                      <a:prstGeom prst="rect">
                        <a:avLst />
                      </a:prstGeom>
                      <a:noFill />
                      <a:ln w="9525">
                        <a:noFill />
                        <a:headEnd />
                        <a:tailEnd />
                      </a:ln>
                    </pic:spPr>
                  </pic:pic>
                </a:graphicData>
              </a:graphic>
            </wp:inline>
          </w:drawing>
```

**Comment by jgm** [comment] 2021-04-03 18:10
Maybe this is the culprit:
``` xml
                      <pic:cNvPicPr>
                        <a:picLocks noChangeAspect="1"
                        noChangeArrowheads="1" />
```

**Comment by jgm** [comment] 2021-04-03 18:23
Other relevant diffs:

The nonresizable one has
```xml
            <a:noFill />
            <a:ln w="9525">
              <a:noFill />
              <a:headEnd />
              <a:tailEnd />
            </a:ln>
```

**Comment by jgm** [comment] 2021-04-03 18:35
I've tried changing these things, but no help yet.

**Comment by jgm** [comment] 2021-04-03 18:40
Hm, I can't reproduce this myself.  Can you try without the reference-doc to see if the problem persists?  Maybe the issue lies there.

**Comment by satikusala** [comment] 2021-04-03 18:46
Hey there, thanks. I tried without the reference. No Joy. Here is the file that got produced with this command line. 

/usr/local/bin/pandoc -s /Users/michaelbecker/pandocSP/TestFile28.html -o /Users/michaelbecker/pandocSP/TestFile28.docx

[TestFile28.docx](https://github.com/jgm/pandoc/files/6253234/TestFile28.docx)

**Comment by satikusala** [comment] 2021-04-03 18:53
Interesting.  If I open the converted file and save it as a .doc I can then resize the images. If I save it back to a docx I can resize the image. There seems to be something strange with the initial conversion, as you point out.

**Comment by jgm** [comment] 2021-04-03 19:22
If I extract the image from your docx, and then just do this:
```
$ pandoc -o my.docx
![](image2.jpg)
```
I get a docx in which I can resize the image.
Do you get different results?

**Comment by jgm** [comment] 2021-04-03 19:24
Similarly if I create an HTML file that links to the image, and then convert that to docx.
In short, I cannot reproduce this.
Suggestion:

1.  Try upgrading to the latest pandoc and see if you can reproduce.
2. If you still can, create a zip file containing ALL the inputs one needs to reproduce the problem.

**Comment by satikusala** [comment] 2021-04-03 21:34
Thank you sooooo much for your help!!! Mystery solved. If the image is hyperlinked, which it was, you can not edit it. Once I removed the hyperlink, all became right in the world. :)  I am grateful for you. 🙏

**Comment by jgm** [comment] 2021-04-05 16:01
OK, I learned something today. Closing this issue, then.

**Closed by jgm** 2021-04-05 16:01 UTC
