### ISSUE TITLE
leading zeros stripped from variables using template

### ISSUE THREAD

**Issue by chreliot** [jgm/pandoc#5533] opened 2019-05-29 17:53 UTC
Leading zeros in YAML values are stripped in output using templates. They are stripped even if the YAML input is quoted. I *believe* this is new behavior in a recent version. Example input and output follows:

## command run

`pandoc yaml-input.yaml --template=md-template.md -o zeros-output.md`

## zeros-input.yaml
```
---
nozeros: 8
leadingzeros: 008
lzsq: '008'
lzdq: "008"
trailingzeros: 800
... 
```

## md-template.md

```
* No zeros: $nozeros$
* Leading zeros: $leadingzeros$
* Leading zeros single quotes: $lzsq$
* Leading zeros double quotes: $lzdq$
* Trailing zeros: $trailingzeros$
```

## zeros-output.md

```
* No zeros: 8
* Leading zeros: 8
* Leading zeros single quotes: 8
* Leading zeros double quotes: 8
* Trailing zeros: 800
```

**Comment by tarleb** [comment] 2019-05-29 18:17
Thanks you for the report. This seems to be a duplicate of the (resolved) issue #5479. See there for a workaround.

**Closed by tarleb** 2019-05-29 18:17 UTC
