### ISSUE TITLE
Loss of style for titles and/or subtitles in .docx output document

### ISSUE THREAD

**Issue by sschaenz** [jgm/pandoc#10282] opened 2024-10-10 16:22 UTC
I am using a customised ‘reference.docx’, which I created with the command ‘pandoc -o custom-reference.docx --print-default-data-file reference.docx’ and added individual styles for titles and subtitles. This file worked perfectly in Pandoc version 3.1.12 and formatted the title and subtitle as desired (e.g. frame with background colour and custom text colour). 

However, after upgrading to Pandoc 3.5, the problem arises that titles and subtitles lose their formatting and the default formatting is used instead. The content is output correctly, but without the assigned formatting. This suggests that Pandoc may no longer recognise the custom styles or that the assignment of metadata to styles has been changed.

I am using a German version of Microsoft Word, so the style names in my ‘reference.docx’ file may correspond to the localised German names. Since I updated directly from Pandoc 3.1.12 to 3.5, I can't say exactly from which version the problem occurred. However, downgrading to 3.1.12 fixes the problem, so there seems to be a change in the newer Pandoc versions that affects the style assignment for metadata.

Regards
Stefan

**Comment by jgm** [comment] 2024-10-10 17:01
Have you checked the changelog to see what relevant changes were made between 3.1.12 and 3.5?
https://pandoc.org/releases

**Comment by sschaenz** [comment] 2024-10-10 18:36
Yes, I have read the release notes and found some possible clues, but they don’t help me resolve the issue as a user.

I have spent several hours researching and testing, but the documentation did not provide any insights to resolve my issue. 

My understanding was that Pandoc’s reference file could be used to customize the layout of a Word document as long as only the Pandoc-supported styles were modified or utilized. This approach had always worked fine in the past. I also generated a new reference file using Pandoc 3.5 and ran targeted tests with it. However, when I modify the Title and Subtitle layouts (such as color or font), Word now uses the Standard layout style instead. This should not be happening.

I found the following relevant notes in the release history:

### pandoc 3.2.1
“Clean up Abstract Title and Subtitle in default reference docx. Center Subtitle, remove color.”
- This could be related to my problem, but it doesn’t help me find a solution.

### pandoc 3.2
“Use current standard Word theme (#7280). This includes using the sans-serif font Aptos instead of the serif font Cambria, and default colors for headings. Remove duplicate DefaultParagraphFont in styles.xml.”

### pandoc 3.1.12.2
Here’s one relevant note:
“Detect caption by style name not id (#9518). The styleId can change depending on the localization.”

I suspect that my issue with Title and Subtitle formatting might be related to a change in how style names are detected in Pandoc. In earlier versions, Pandoc always processed the `reference.docx` file based on English style names, regardless of the language settings in Microsoft Word.

It would be helpful if Pandoc could provide a way to standardize style name recognition independently of localization. This would prevent issues for users working with different language versions of Word.

**Comment by sschaenz** [comment] 2024-10-10 20:29
lang: de
lang: en

I had also tried it, but there was no improvement.

Hm, my problem should actually be easy to recreate, right?

**Comment by jgm** [comment] 2024-10-10 20:36
Can you post files necessary to reproduce the issue?  Your reference.docx and a sample markdown input, plus the command line you used?

**Comment by jgm** [comment] 2024-10-10 20:56
Note that in the 3.2 revisions, we added a "Title Char" style (standard for Word).
It may be that you need to adjust this style in your reference doc.

**Comment by jgm** [comment] 2024-10-10 20:56
There is also "Subtitle Char".  These are character fonts.

**Comment by sschaenz** [comment] 2024-10-13 14:21
Sorry for the delay, I've been very busy.

Here is an example that reproduces the problem for version 3.5 of Pandoc.


1. display Pandoc version

```bash
$ pandoc --version                                                         
pandoc 3.5
```

2. generate reference file from Pandoc ([reference-3_5.docx](https://github.com/user-attachments/files/17355932/reference-3_5.docx))

```bash
$ pandoc -o reference-3_5.docx --print-default-data-file reference.docx
```

3. open the reference file in Word and adjust the title and subtitle format ([my-reference-3_5.docx](https://github.com/user-attachments/files/17355930/my-reference-3_5.docx))

Title: I have set the font colour to white, the spacing from the top to 80 pt and coloured a background frame in blue.

Subtitle: Font colour also white, spacing adjusted to 4 pt from the top and background colour in a lighter blue

4. create Markdown example file ([my-markdown.md](https://github.com/user-attachments/files/17355929/my-markdown.md)

```markdown
---
title: "Resource Template"
subtitle: "Subtitle Here"
date: "\today"
author: "My Name"
toc: true
toc-depth: 2
lang: en
customer_logo: false
client_name: "Client Name"
security_label: "Confidential"
...

# Introduction

Provide a brief introduction here.

# Section 1: Overview

Include a general overview of the resource.

## Subsection 1.1: Details

Details about the resource, including any relevant information, such as objectives, target audience, or specifications.

# Section 2: Implementation

Instructions or steps for implementing the resource.

## Subsection 2.1: Steps

1. Step one details
2. Step two details
3. Step three details

# Section 3: Additional Information

Include any additional relevant information, like references or contact details.

# Appendix

Include any additional resources or appendices here.
```

5. Result ([my-word-3_5.docx](https://github.com/user-attachments/files/17355931/my-word-3_5.docx)):

The title and subtitle are displayed in the ‘Normal’ style. Likewise ‘author’ and ‘date’. Date is not displayed because \today is a latex option and not for Word. If a date was entered, the date would appear. Format is also wrong here. There is also a page break in the template, which is also missing here.
[my-markdown.md](https://github.com/user-attachments/files/17355929/my-markdown.md)
[my-reference-3_5.docx](https://github.com/user-attachments/files/17355930/my-reference-3_5.docx)
[my-word-3_5.docx](https://github.com/user-attachments/files/17355931/my-word-3_5.docx)
[reference-3_5.docx](https://github.com/user-attachments/files/17355932/reference-3_5.docx)

**Comment by sschaenz** [comment] 2024-10-13 14:26
Thank you for pointing out the updates in the 3.2 revisions regarding the "Title Char" and "Subtitle Char" styles. However, I’m having trouble with these points because I haven’t been able to find any relevant information in the documentation. I’m not sure how to access or adjust these character styles within the reference doc. Could you provide some guidance on how I can use these features?

**Comment by jgm** [comment] 2024-10-13 15:26
OK, this is very strange. Your reference doc has a Title style, but it doesn't get applied.
I will have to look into this.

**Comment by jgm** [comment] 2024-10-13 15:28
But when I try the same thing you did -- same method of creating a reference.docx -- it works fine.

**Comment by jgm** [comment] 2024-10-13 15:33
OK, the issue is this.  Your reference.docx has  w:styleId="para6", and this style has `<w:name w:val="Title">`.  The styleId needs to be Title.

When you create your reference.docx, go to the Styles menu, find the already existing Title style, and modify this.  I'm not sure what you did differently to create the style you had.

**Comment by sschaenz** [comment] 2024-10-13 18:40
I will test it tomorrow. I still have a computer with an older version of Pandoc. I haven't had the problem on this system so far. I will check if the versions of Word are the same, which they should be. My system and Word versions are German. As far as I can remember, the style sheets that were generated from Pandoc were always in English, which did not cause any problems. In Word they were also displayed with the names in English. Now it looks as if Pandoc or Word translates the name of the template (in my case into German).  The fact that I use macOS may also play a role.

There are therefore several factors that can play a role:

- Pandoc version
- Microsoft Word Version
- System and / or Word language
- Operation System

and certainly also the user (in this case me). However, I have tried to rule out errors by creating a new test file including a reference file from scratch.

The style id can probably change depending on the language, which is probably why the names are used. If these are now translated (by whatever means) or adapted to the system language, this would provide an explanation.

**Comment by jgm** [comment] 2024-10-13 19:10
If I recall, we use styleId and not the display name, because that is the thing that is constant across differently localized versions of Word.

**Comment by sschaenz** [comment] 2024-10-13 20:13
pandoc 3.1.12.2

Here’s one relevant note:
“Detect caption by style name not id (https://github.com/jgm/pandoc/issues/9518). The styleId can change depending on the localization.”

see above.

**Comment by jgm** [comment] 2024-10-13 21:05
OK, I got it reversed then.  I knew it was one way or the other!

**Comment by sschaenz** [comment] 2024-10-14 12:40
Here are my tests and the results:

macOS 14.6.1 (Sonoma) Intel Core i7

Microsoft Word for Mac Version 16.89.1 (German)
Licence: Microsoft 365 subscription

pandoc --version
pandoc 3.1.12.2

pandoc -o reference-3_1_12.docx --print-default-data-file reference.docx

The format template Title is displayed in Word as ‘Title’ and Subtitle as ‘Subtitle’.

Open reference-3_1_12.docx with Word
There are no errors and no hints when opening. Everything is OK.
Customise style sheet and save as my-reference-3_1_12.docx

pandoc my-markdown.md -o my-word-3_1_12.docx --reference-doc=my-reference-3_1_12.docx

Result:

Word file is opened.

1st warning: ‘This document contains fields that may refer to other files. Do you want to update the fields in this document?’ (ok)
2nd warning that the table of contents needs to be updated. (ok)

As the fields and the table of contents could not yet be set to a current and valid value by Word, these instructions are understandable. However, you should always call up a Word file first and then save it again before sending it to other people, as they often thank you that the file is damaged!

The formatting is correct, everything is as it should be.

System on which the problem occurs:

macOS 15.0.1 (Sequoia) M3 Pro (ARM)
(Note: I must not have been paying attention, as I would rather not switch to Sequoia for a few months. A new major version of Apple can have all sorts of side effects. You should therefore wait at least 3 months until you upgrade, and the first updates are available).

Microsoft Word for Mac Version 16.89.1 (German)
Licence: Microsoft 365 subscription

Open reference-3_5.docx with Word
There are no errors or messages when opening. Everything is OK.
Customize style sheet and save as my-reference-3_5.docx
I have created a version here with compatibility mode activated to rule out any problems.

pandoc my-markdown.md -o my-word-3_5.docx --reference-doc=my-reference-3_5.docx
pandoc my-markdown.md -o my-word-3_5-cmp.docx --reference-doc=my-reference-3_5-cmp.docx

Result

Word file is opened with the references as before. However, the formatting is not correct. Title and subtitle are displayed correctly, but the formatting is incorrect and set to default for title, subtitle, and date. The author is correct (and the style sheet has the English name). For ‘Table of Contents’ and the chapter and section headings, the identifiers of the template are displayed in German, but the formatting is correct.

I actually suspect the issue is with Pandoc. For once, I would like to exclude Word as the source of the issue. Theoretically, the difference in macOS versions could still be a cause. If this is the case, then there is hardly anything you can do, and you are at the mercy of the folks at Apple. The different architecture of the CPU should not play a role.

I have now installed Pandoc 3.1.12 on the system and repeated the tests. There are no problems. The formatting appears to be correct. So it is probably not due to the different macOS versions.

One last test:

Since I had installed Pandoc 3.5. with brew, I did another installation with the version from the site https://github.com/jgm/pandoc/releases/tag/3.5. I almost expected that this would solve the problem. Unfortunately not. Something has been changed somewhere in Pandoc that is causing the issues. That's the end of my ideas. But I'll save myself the trouble of trying to find out from which version the problem occurs.

**Comment by sschaenz** [comment] 2024-10-15 16:55
I don't think it's related to the OS version either, I just wanted to mention all the possibilities that came to my mind. The problem will be the name of the style sheets. These are translated by Word into German, for example. If I make a change, the style is saved and the translated name is used. Then pandoc can no longer function properly. This is normally why you use IDs and not names. I don't know if Microsoft sees it differently. Anyway, I will try the following in the next few days: I will create a template with the current version and then use a text editor to search and replace the designations with the English designations. This should be a work around. Since templates are not constantly customized, that should be okay with me. I'll let you know when I've tried it. For a quick test, you can also rename Title in one of your reference files with the German translation In Titel. If the formatting is then lost and the template is set to Standard, then that is the problem.

**Comment by jgm** [comment] 2024-10-16 19:40
Note that in my-reference-docx-3_5.docx, styles.xml has
```
<w:style w:type="paragraph" w:styleId="para4">
<w:name w:val="Title"/>
<w:qFormat/>
<w:basedOn w:val="para0"/>
<w:next w:val="para1"/>
<w:pPr>
<w:spacing w:before="1600" w:after="80"/>
<w:contextualSpacing/>
<w:jc w:val="center"/>
<w:pBdr>
<w:top w:val="nil" w:sz="0" w:space="3" w:color="000000" tmln="20, 20, 20, 0, 60"/>
<w:left w:val="nil" w:sz="0" w:space="3" w:color="000000" tmln="20, 20, 20, 0, 60"/>
<w:bottom w:val="nil" w:sz="0" w:space="3" w:color="000000" tmln="20, 20, 20, 0, 60"/>
<w:right w:val="nil" w:sz="0" w:space="3" w:color="000000" tmln="20, 20, 20, 0, 60"/>
<w:between w:val="nil" w:sz="0" w:space="0" w:color="000000" tmln="20, 20, 20, 0, 0"/>
</w:pBdr>
<w:shd w:val="solid" w:color="365F91" tmshd="1677721856, 16777215, 9527094"/>
</w:pPr>
<w:rPr>
<w:rFonts w:ascii="Aptos Display" w:hAnsi="Aptos Display" w:eastAsia="Aptos Display" w:cs="Aptos Display"/>
<w:color w:val="ffffff"/>
<w:spacing w:val="-10" w:percent="96"/>
<w:kern w:val="1"/>
<w:sz w:val="56"/>
<w:szCs w:val="56"/>
<w:lang w:bidi="en-us"/>
</w:rPr>
</w:style>
```
and the name specified here is "Title", not "Titel".  So any localization of that name must be happening somewhere outside the stylesheet.  Since according to the commit comment you mentioned above, we are looking up styles by name and not styleId, we *should* be finding this style.

**Comment by jgm** [comment] 2024-10-16 19:41
PS. I tried manually changing the styleId from `para4` to `Title`, and then it worked.

**Comment by jgm** [comment] 2024-10-16 19:43
It looks like the linked commit may have been focused on just the table caption; maybe we didn't make a general change to looking up styles by name intead of styleId.

**Comment by jgm** [comment] 2024-10-16 19:44
It's quite counterintuitive that Word works this way -- it's the name, not the styleId, that stays constant across localized versions -- but such is MS.

**Comment by sschaenz** [comment] 2024-10-21 08:46
I have narrowed down the problem to a specific Pandoc version. When using Pandoc 3.2, titles and subtitles in the Word file are still displayed correctly according to my customised template. The changes made are properly applied.

However, a deviation occurs as of version 3.2.1: titles and subtitles only appear according to Word's default settings, regardless of the Pandoc or custom templates. My adjustments to the style sheet are ignored, but the content remains correct. Titles and subtitles are displayed with the correct content, but without the intended formatting.

I tested various Pandoc versions to investigate. The problem first appeared in version 3.2.1, while in version 3.2 the templates worked as expected. The tests were carried out with the binary versions of Pandoc, which I downloaded directly from the GitHub page (https://github.com/jgm/pandoc/releases).

I hope this helps to narrow down the error and find a solution.

I will stick with the older version for the time being until the problem is fixed.

**Comment by jgm** [comment] 2024-10-24 15:45
IN the 3.2.1 changelog for docx writer we have two items that might be relevant:

- Allow OpenXML templates to be used with docx ([#8338](https://github.com/jgm/pandoc/issues/8338), [#9069](https://github.com/jgm/pandoc/issues/9069), [#7256](https://github.com/jgm/pandoc/issues/7256), [#2928](https://github.com/jgm/pandoc/issues/2928)).  commit db559e100c02ca1f95953f3eeeca005fdc01b595

- Clean up Abstract Title and Subtitle in default reference docx. Center Subtitle, remove color.  commit c26211b0c9d3b5d4f4040b3fcfbf090ddaf276d6

**Comment by jgm** [comment] 2024-10-24 15:54
I think what is happening is this:  we produce a docx with
```
<w:pStyle w:val="Title" />
```
and the way Word deals with this is to look up the style with `styleId` = `"Title"`.  The default pandoc reference.docx has such a style.  But when you edit it with your localized Word, change the Title style, and save it again, for some reason Word changes the `styleId` to `para4`.  I have confirmed that changing that munally back to `Title` makes it work again.

This is unfortunate and I don't know how to fix it, because I don't know why your Word is changing the `styleId` this way.  Mine does *not* do that.  It's hard to see that this is due to localization; it isn't as if `para4` is the German word for "Title."

**Comment by ctfysh** [comment] 2024-12-13 06:45
I have met with the same problem in MacOS, but in Linux system, this problem was gone. So are there any methods to fix it? @jgm

**Comment by ctfysh** [comment] 2024-12-15 01:47
OK, seeing below.

[output.docx](https://github.com/user-attachments/files/18138558/output.docx)

**Comment by jgm** [comment] 2024-12-15 05:08
That's a file.  What I need are full instructions for reproducing the problem you're having, including exact command line and all input files used.

**Comment by niszet** [comment] 2024-12-16 13:46
I found this issue which I'm facing now. I'm happy if my information helps to solve this issue...

In non-English environment, MS Word changes styleId from Pandoc's original styleId (as discussed in this issue). But Pandoc uses styleId instead of styleName, so Pandoc works correctly in non-English language settings (I'm using in Japanese setting but it's OK). This issue is also happened in my environment and I checked by myself as the end of this comment, too.

But, I checked with `my-reference_3.5.docx` which attached in this issue and using Pandoc 3.2 (or less), it works correctly as we expected (styles are actually work). I think this can be reproduced in English environment (because the file `my-reference_3.5.docx`  has changed styleid).

From Pandoc 3.2.1, docx output can use OpenXML template. So, I checked the file `document.xml` in `my-word-3_5.docx` which attached this issue. It has followings,

```xml
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Title" />
      </w:pPr>
      <w:r><w:t xml:space="preserve">Resource Template</w:t></w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Subtitle" />
      </w:pPr>
      <w:r><w:t xml:space="preserve">Subtitle Here</w:t></w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Author" />
      </w:pPr>
      <w:r><w:t xml:space="preserve">My Name</w:t></w:r>
    </w:p>
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Date" />
      </w:pPr>
      <w:r><w:t xml:space="preserve">oday</w:t></w:r>
    </w:p>
```

It seems only substitution of metadata from template and it is not same as styleid which noted in `style.xml` (it is not Title but para4).

So, I guess, behavior of Pandoc about metadata-related styles (title, subtitle and so on) are changed... around here? (But I'm not sure)

https://github.com/jgm/pandoc/commit/db559e100c02ca1f95953f3eeeca005fdc01b595#diff-000479233aecf4670972e4730bbeccba5636f7bcab34eba9fde82a9dac37d834L182


Followings are facts which I checked.

As same as @sschaenz, by using after Pandoc 3.2.1, this problem are appeared also in my environment.

My environment is Windows 10 Japanese language setting and MS Word (Microsoft 365, version 2411). MS Word language setting is based on OS language setting (It can be changed from Option -> Language in MS Word, but I haven't check by using it...)

In my environment, style names of `Title`, `SubTitle`, `Date` are renamed in Japanese setting. But Author is not changed. These style names are changed to 表題, 副題, and 日付 in MS Word display. (Author is Author on MS Word. Not 著者) In styles.xml, they have name `<w:name w:val="Title"/>` but <w:style w:type="paragraph" w:styleId="a4"> ... and so on, so similar change happened in my case, too.


If I should add any other files, please let me know.

**Comment by niszet** [comment] 2024-12-16 15:01
As you mentioned https://github.com/jgm/pandoc/issues/10282#issuecomment-2435668216, to find the correct styleId from `style.xml`, by using style name in `w:name` in `w:style`, then replace value of `w:val` in `document.xml` to `w:styleId` of `style.xml` , I think.

Because style definition in `style.xml` has same name as original one (even if its attrs are changed in MS Word).

```xml
<w:style w:type="paragraph" w:styleId="para4">
<w:name w:val="Title"/>
<w:qFormat/>
<w:basedOn w:val="para0"/>
...
```

And I guess this is also happened if I use template file to insert docx by using `include-before` (and so on). (before insertion, replace stylename in template by styleId in reference.docx or default.docx ... ?)

**Comment by jgm** [comment] 2024-12-16 18:07
Ah, so if I understand correctly, the issue is this:  the openxml template just literally inserts
```
        <w:pStyle w:val="Title" />
```
(Author, etc.). Here w:val needs to match the `styleId` of the Title style.  But in the localized Word, the `styleId` has changed to something else (like `a4`).  That is why it doesn't work.

The solution, then, is for us to look up the appropriate `styleId` for Title, Author, etc., and pass these to the template as variables.  So template would contain
```
<w:pStyle w:val="Title-style-id">
```
and the docx writer would set `Title-style-id`.  This should not be too hard to implement.

**Comment by jgm** [comment] 2024-12-18 01:33
OK, I believe this issue is fixed now in HEAD.  Testing by people with localized Word versions would be helpful.

**Closed** 2024-12-18 01:33 UTC
Labels: bug

**Comment by helfe-squad** [comment] 2024-12-23 12:25
Hello, i don't understand how to test this fix, can you explain me ? i am a Win 11 user in french location.

**Comment by jgm** [comment] 2024-12-23 18:13
You can test a nightly: https://github.com/jgm/pandoc/actions/runs/12463322978

**Comment by helfe-squad** [comment] 2024-12-27 16:49
It works ! Thank you very munch jgm.
