### ISSUE TITLE
DOI link excludes prefix in some circumstance

### ISSUE THREAD

**Issue by Jmuccigr** [jgm/pandoc#7130] opened 2021-03-08 17:51 UTC
Follow-up to group discussion [here](https://groups.google.com/u/1/g/pandoc-discuss/c/mIDiPPYnzCA).

In certain circumstances, pandoc excludes the prefix part of a doi ( `https://doi.org/`) when creating the link in html output, so instead of 

```html
<a href="https://doi.org/10.3406/ccgg.1997.1433">https://doi.org/10.3406/ccgg.1997.1433</a>
```

it produces

```html
https://doi.org/<a href="https://doi.org/10.3406/ccgg.1997.1433" role="doc-biblioref">10.3406/ccgg.1997.1433</a>.
```

JGM wrote to the group:

> Pandoc does a linkifyVariables step to make the doi variable into a link.
> 
> The problem is that citeproc is neutral as to the underlying format -- it doesn't have any concept of variables that are linked. So it can't extend a link to a prefix. I don't see a really good solution to this, other than a filter which traverses the AST after citeproc is done with it and fixes this up.

**Comment by jgm** [comment] 2021-03-09 00:21
What we need is a precise example allowing us to reproduce the issue, since I thought it was already fixed (#6723).
Note the existing test case in `test/command/6723.md`.

**Comment by jgm** [comment] 2021-03-11 00:29
Can anyone give an example?

**Comment by Jmuccigr** [comment] 2021-03-11 17:48
OK, here's one.

command: `pandoc --citeproc --bibliography=./temple_bib.json --csl=chicago-author-date.csl -t html `
document: `[@Glinister1997]`
bib file contains just the one entry: 
`[{"id":"Glinister1997","accessed":{"date-parts":[[2020,12,19]]},"author":[{"family":"Glinister","given":"Fay"}],"container-title":"Cahiers du Centre Gustave Glotz","DOI":"10.3406/ccgg.1997.1433","issue":"1","issued":{"date-parts":[[1997]]},"language":"eng","page":"61-80","publisher":"Persée - Portail des revues scientifiques en SHS","source":"www.persee.fr","title":"What is a sanctuary?","type":"article-journal","URL":"https://www.persee.fr/doc/ccgg_1016-9008_1997_num_8_1_1433","volume":"8"}]`

For the csl, just change the standard chicago-author-date.csl so that the <citation...> is gone and the <bibliography...> is changed to <citation...>. Or use the attached.
[chicago-author-date.csl.zip](https://github.com/jgm/pandoc/files/6124950/chicago-author-date.csl.zip)

**Comment by jgm** [comment] 2021-03-12 18:16
Confirmed. Native output:
```
[Para [Cite [Citation {citationId = "Glinister1997", citationPrefix = [], citationSuffix = [], citationMode = NormalCitation, citationNoteNum = 1, citationHash = 0}] [Str "Glinister,",Space,Str "Fay.",Space,Str "1997.",Space,Span ("",[],[]) [Str "\8220",Str "What",Space,Str "is",Space,Str "a",Space,Str "sanctuary?",Str "\8221"],Space,Emph [Str "Cahiers",Space,Str "du",Space,Str "Centre",Space,Str "Gustave",Space,Str "Glotz"],Space,Str "8",Space,Str "(1):",Space,Str "61\8211\&80.",Space,Str "https://doi.org/",Link ("",[],[]) [Str "10.3406/ccgg.1997.1433"] ("https://doi.org/10.3406/ccgg.1997.1433",""),Str "."]]]
```
I don't understand why our `fixLinks` isn't working here.

**Comment by jgm** [comment] 2021-03-12 19:20
OK, this is an uncovering something subtle about `walk`.

We were applying `walk fixLinks` to an `Inlines`.  If we instead do `B.fromList . walk fixLinks . B.toList` so that the walking is done on a `[Inline]` list, then it works!

**Comment by rnhmjoj** [comment] 2022-06-23 22:06
I've found another edge [case](http://www.zotero.org/styles/elsevier-with-titles):
```xml
<if variable="DOI">
  <text variable="DOI" prefix=". https://doi.org/"/>
</if>
```

Due to the `. ` at the start of the prefix `fixLinks` doesn't recognize it as a url.
I believe it could be fixed by replacing the condition with
```haskell
| u2 `isSuffixOf` (t <> u1)
```

**Comment by jgm** [comment] 2022-06-24 23:07
@rnhmjoj all of that code is gone now; I think this logic has been moved to jgm/citeproc.
But the code that's there is sensitive to `://` as infix and should work with your sample.  What version of pandoc are you using, compiled against what version of citeproc?

**Closed by jgm** 2022-06-24 23:07 UTC

**Comment by rnhmjoj** [comment] 2022-06-24 23:41
> What version of pandoc are you using, compiled against what version of citeproc?
```
pandoc 2.17.1.1
Compiled with pandoc-types 1.22.2, texmath 0.12.4, skylighting 0.12.3,
citeproc 0.6.0.1, ipynb 0.2
```

> But the code that's there is sensitive to :// as infix and should work with your sample

I suppose so, I have only been checking against the version I have.
