### ISSUE TITLE
Standardize lang metadata

### ISSUE THREAD

**Issue by somenxavier** [jgm/pandoc#2366] opened 2015-08-18 14:52 UTC
Hi,

In the yaml, If you write `lang: catalan`, latex output works. If you write `lang: ca`, html5 works. So there is such incompatibility because latex use full language name and html iso codes. Perhaps you could write a conversion tool in pandoc for automatically pass between `catalan` and `ca` in corresponding document type.

Thanks,

**Comment by jgm** [comment] 2015-08-18 16:05
Yes:  we need a consistent way to specify `lang`, using ISO-639 codes.  Pandoc should work behind the scenes to convert this to what is needed for latex, etc.  See [this pandoc-discuss thread](https://groups.google.com/d/msg/pandoc-discuss/X3DwDJ7sX8c/j1AxwGTNP0wJ) and [this one](https://groups.google.com/forum/#!searchin/pandoc-discuss/otherlang/pandoc-discuss/d-HrqQRh1hE/N_7OjPdXY7gJ).

My current thought is this:  there should be a `lang` metadata field, which takes a string value, which should be an ISO-639 code.  We could get away without `otherlang`, perhaps, if we took @nickbart1980's suggestion and constructed it programatically by scanning the document for Div or Span elements with `lang` attributes.

**Comment by jgm** [comment] 2015-08-19 17:15
See also jgm/pandoc-templates#101

**Comment by jgm** [comment] 2015-08-19 18:58
Duplicate of #1614 - closing in favor of original issue.

**Closed by jgm** 2015-08-19 18:58 UTC
