### ISSUE TITLE
Windows installer doesn't delete old registry entries

### ISSUE THREAD

**Issue by hseg** [jgm/pandoc#4494] opened 2018-03-25 00:05 UTC
Judging by the state of my registry after a couple updates,
it seems the installer doesn't uninstall the old version first.
This leads Windows to think I have multiple versions of Pandoc
installed in the same place, and is a bit confusing to me as a user.
Not a showstopper, but a fix would definitely be appreciated.
NB: The diagnosis of the cause is an educated guess, but hasn't
been tested (yet).

**Comment by jgm** [comment] 2018-03-25 21:32
@nkalvi any ideas?

**Comment by nkalvi** [comment] 2018-03-25 21:36
@hseg I haven't seen it before. Installer usually offers to uninstall if there's an older or current version. Could you please provide some more details (which versions etc.)? Thanks.

**Comment by jgm** [comment] 2018-07-22 06:31
Closing this, since we can't reproduce it and no more information was provided.

**Closed by jgm** 2018-07-22 06:31 UTC
Labels: platform:windows
