### ISSUE TITLE
SVG included with \includegraphics ?

### ISSUE THREAD

**Issue by anfelor** [jgm/pandoc#3722] opened 2017-06-03 19:51 UTC
While trying to convert 
```markdown
```{.plantuml format="svg" caption="Fancy uml diagram" width="70%"}
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml
\\``` -- needed for github, ignore the two backslashes
```
with `pandoc slides.md -t beamer -o slides.pdf --filter pandoc-plantuml-filter`
gives
```
pandoc: Unable to convert `dba2905531256f9ebf116f41123f91f40a6e51e9.svg' for use with pdflatex.
! LaTeX Error: Unknown graphics extension: .svg.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.82 \end{frame}

pandoc: Error producing PDF
```
I first thought this was due to [\includesvg not handling file extensions well](https://tex.stackexchange.com/questions/122871/include-svg-images-with-the-svg-package#129854), but apparently pandoc converts it into this latex:
```latex
\begin{frame}

\begin{figure}[htbp]
\centering
\includegraphics{dba2905531256f9ebf116f41123f91f40a6e51e9.svg}
\caption{ }
\end{figure}

\end{frame}
```
A modified version of `pandoc-plantuml-filter`, which removes the file extension for svg files fails with
```
pandoc: Unable to convert `dba2905531256f9ebf116f41123f91f40a6e51e9' for use with pdflatex.
! LaTeX Error: File `dba2905531256f9ebf116f41123f91f40a6e51e9' not found.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.122 \end{frame}

pandoc: Error producing PDF
```

The Reveal.js version works fine (compiling without errors and embedding the svg image)
and the beamer version works with png, but the images are of low quality, so I would like to get svg to work.

---

I assume the issue is that pandoc is including SVGs with `\includegraphics` instead of `\includesvg`.
```
pandoc 1.16.0.2
Compiled with texmath 0.8.4.1, highlighting-kate 0.6.1.
```

**Comment by ickc** [comment] 2017-06-04 17:52
A few problems with this issue:

1. duplicate of #1793
2. pandoc version used is too old. For any bug reports, you should test against with the latest pandoc version, and even better, latest commit from the master branch (e.g. from [pandoc-extras/pandoc-nightly](https://github.com/pandoc-extras/pandoc-nightly/)). What's the point of bug report if you don't know if it has been already fixed?
3. your example is not minimal enough, and uses a "3rd party" filter. This makes replicating bugs difficult and time consuming.

I suggest you should close this issue and watch for #1793.

**Closed** 2017-06-04 18:07 UTC

**Comment by jgm** [comment] 2017-06-04 19:10
I agree that this is a dup.

As noted in the other issue, the main issue with the
solution proposed here is that it requires an external
package, which itself requires inkscape.

That's still a possibility, but it's not ideal, and
some of the other ideas mentioned in the other thread
should be explored too.
