### ISSUE TITLE
Option to remove table of contents?

### ISSUE THREAD

**Issue by coryschires** [jgm/pandoc#5893] opened 2019-11-10 19:37 UTC
I am converting from DOCX to MD. If the the DOCX file includes as TOC, then the converted MD also includes a TOC.

For my use case, I never want a TOC in the coverted MD. Is there a way to suppress / disable the TOC via Pandoc?

Thanks!

PS: Possibly related issue: https://github.com/jgm/pandoc/issues/5668

**Comment by mb21** [comment] 2019-11-11 10:12
I think there is an issue about this already somewhere... and I think the trouble was that it's not clear from the docx file whether the TOC is part of the document proper, or was generated automatically... @jkr ?

**Comment by jkr** [comment] 2019-11-11 11:29
@coryschires would you mind posting the docx file? If it's easy to filter out, we probably should, since we could regenerate it, from section-layout, in a target-appropriate way.

**Comment by jgm** [comment] 2019-11-11 16:30
Duplicate of #5810 - closing in favor of that.

**Closed by jgm** 2019-11-11 16:30 UTC
