### ISSUE TITLE
\mathrm works in double dollars only, fails in single dollar

### ISSUE THREAD

**Issue by joelkim** [jgm/pandoc#3355] opened 2017-01-15 13:11 UTC
I tried to convert a html file which contains
``$$\mathrm{E}[X]$$``
and
``$\mathrm{E}[X]$``
to docx file using the following command:
```
pandoc -f html+tex_math_dollars+tex_math_single_backslash -o test.docx test.html
```
The first (with double dollars) works but the second (with single dollar) failed. 
What's the problem?

**Comment by jgm** [comment] 2017-01-15 20:58
I couldn't reproduce this.  Can you include the output
of pandoc --version?  And could you be more specific in
what you mean by "failed"?

**Comment by jgm** [comment] 2017-01-18 11:44
I'm going to close this as there is not enough information to do anything, but feel free to comment if you have further relevant information.

**Closed by jgm** 2017-01-18 11:44 UTC
