### ISSUE TITLE
[Withdrawn: can be closed]: Feature request: Data.Extension for custom block delimiter

### ISSUE THREAD

**Issue by technocrat** [jgm/pandoc#2408] opened 2015-09-22 00:35 UTC
For use in writing filters, it would be handy to be able to identify specific blocks for special treatment through some reserved delimiter or a user specified delimiter, such as

zzzzzz 
This block of text needs special treatment, such as escaping % signs -- \% -- for subsequent processing by \LaTeX\ or other non-standard pre-processing.
zzzzzz

This came up in tweaking R tables in RMarkdown on their way to pdf output. R spews raw \LaTeX\ that needs to be intercepted and further massaged, for which **pandoc --filter** provides the opportunity if the changes can be isolated to those specific blocks that need it. For now, I am going to recruit the code block but inevitably there will come the day that I will long for a way to tack on to the AST.

Thanks for considering.

**Comment by mb21** [comment] 2015-09-26 11:18
You can use `div`s with a classes, like:

    <div class="z">
    This block of text needs special treatment, such as escaping % signs -- \% -- for subsequent processing by \LaTeX\ or other non-standard pre-processing.
    </div>

**Comment by technocrat** [comment] 2015-09-26 16:40
Of course! I've got to get over the habit of thinking in terms of a 
sourcefile as "one" language. HTML to the rescue (for a change)

mb21 wrote:

**Comment by ousia** [comment] 2015-11-13 19:46
@technocrat, sorry if I’m missing something, but isn’t this issue a duplicate of #168?

**Comment by technocrat** [comment] 2015-11-13 23:32
Sorry to be obscure. I'll close it since it's been adequately covered elsewhere including #168. This came up for me in trying to write a filter with use with RMarkdown. I had some initial success, summarized here: http://technocrat.github.io/2015/11/11/filters/ but ultimately decided that trying to expose any and all YAML blocks beyond use in templates was both unnecessary and, probably harmful. pandoc so so much so well it seems to incited a greed in us users to turn it eventually into an operating system.

**Comment by jgm** [comment] 2015-11-16 17:50
+++ Richard Careaga [Nov 13 15 15:32 ]:
>   so well it seems to incited a greed in us users to turn it eventually
>   into an operating system.

Well, it already contains a full network stack and a
programming language interpreter!

**Closed** 2015-11-20 04:41 UTC
