### ISSUE TITLE
Citations in footnotes move the author to the front in disregard of the CSL style

### ISSUE THREAD

**Issue by tillgrallert** [jgm/pandoc#8537] opened 2023-01-09 23:02 UTC
There is a difference between inline-citations and citations in footnote for "note" styles when it comes to the position of authors: citations in footnotes always put the author in the front of the reference, no matter what the CSL style mandates. Although it is the first time I noticed this behaviour, it can be reproduced with Pandoc (2.18, 2.19.2) on the lates macOS.

# Example
## input

```md
if I write a reference inline [@Dickson1885TestLetter], everything works as specified in the CSL. However, if I use a footnote[^1], the author name is moved to the front of the citation. Note that the first reference in the second citation is only needed to suppress potential use of "ibid".

[^1]: @Dickson1885TestLettera; @Dickson1885TestLetter.
```

## output

Note that in `[^fn2]` the author names have been moved to the front of the formatted citation. I limit output to the references only:

```md
[^fn1]: PRO, FO 195/1514, Damascus 33, Dickson to White, (Damascus, 6 Oct. 1885).

[^fn2]: Dickson, PRO, FO 195/1514, Damascus 32, to Bonfils, (Damascus, 7 Oct. 1885); Dickson, PRO, FO 195/1514, Damascus 33, to White, (Damascus, 6 Oct. 1885).
```

## expected output

I expect the output to be independent of whether it was generated from an inline citation or a footnote

```md
[^fn1]: PRO, FO 195/1514, Damascus 33, Dickson to White, (Damascus, 6 Oct. 1885).

[^fn2]: PRO, FO 195/1514, Damascus 32, Dickson to Bonfils, (Damascus, 7 Oct. 1885); PRO, FO 195/1514, Damascus 33, Dickson to White, (Damascus, 6 Oct. 1885).
```

**Comment by jgm** [comment] 2023-01-09 23:47
Yes, because the form without brackets `@Dickson1985` is for an author-in-text citation. These are formed by printing the author's name first.  Try with brackets in the footnote, `[@Dickson1985]`.

**Comment by tillgrallert** [comment] 2023-01-10 00:29
Dear John, thank you for the quick response.  Your suggestion creates a new problem. I only write explicit footnotes in markdown when I want to add additional text. In this case, surrounding citations with `[ ]`  will create brackets (`( )`) in my formatted footnotes, where I absolutely would not want them.

- input 1: `[^1]: [@Dickson1885TestLettera; @Dickson1885TestLetter].`
    - correct output: `[^fn1]: PRO, FO 195/1514, Damascus 33, Dickson to White, (Damascus, 6 Oct. 1885); PRO, FO 195/1514, Damascus 32, Dickson to Bonfils, (Damascus, 7 Oct. 1885)`
- input 2: `[^2]: [@Dickson1885TestLettera]. See also [@Dickson1885TestLetter], the later points to the importance of bla bla bla.` 
    - what I would consider incorrect output: `[^fn2]: C.f.  (PRO, FO 195/1514, Damascus 32, Dickson to Bonfils, (Damascus, 7 Oct. 1885)). See also  (PRO, FO 195/1514, Damascus 33, Dickson to White, (Damascus, 6 Oct. 1885)), the later points to the importance of bla bla bla.`

I wonder why the order of elements is touched by Pandoc and not left to CSL as one would expect. Such sorting should be independent of surrounding a reference with brackets.
- input 1: `[^1]: [@Dickson1885TestLettera; @Dickson1885TestLetter].`
    - correct output: `[^fn1]: PRO, FO 195/1514, Damascus 33, Dickson to White, (Damascus, 6 Oct. 1885); PRO, FO 195/1514, Damascus 32, Dickson to Bonfils, (Damascus, 7 Oct. 1885)`
- input 2: `[^2]: [@Dickson1885TestLettera]. See also [@Dickson1885TestLetter], the later points to the importance of bla bla bla.` 
    - what I would consider incorrect output: `[^fn2]: C.f.  (PRO, FO 195/1514, Damascus 32, Dickson to Bonfils, (Damascus, 7 Oct. 1885)). See also  (PRO, FO 195/1514, Damascus 33, Dickson to White, (Damascus, 6 Oct. 1885)), the later points to the importance of bla bla bla.`

I wonder why the order of elements is touched by Pandoc and not left to CSL as one would expect. Such sorting should be independent of surrounding a reference with brackets.

**Comment by jgm** [comment] 2023-01-10 02:33
> I wonder why the order of elements is touched by Pandoc and not left to CSL as one would expect. Such sorting should be independent of surrounding a reference with brackets.

The notion of an author-in-text citation is not part of CSL at all.  CSL gives you the bracketed ones; the unbracketed ones are a pandoc innovation.

What you are looking for is something distinct from either a normal citation or an author-in-text citation. What you want is simply a normal citation that drops the parentheses. Note, however, that the parentheses *are* specified by the CSL style.

**Comment by jgm** [comment] 2023-01-10 03:00
Related: 
https://groups.google.com/g/pandoc-discuss/c/8YoFxeexDWs/m/a85v_OR3AwAJ

**Comment by tillgrallert** [comment] 2023-01-10 09:41
Thank you for pointing me to the Google group. I see that the author-in-text citation is Pandoc-specific "hack" that will eventually find its way into CSL and Zotero (as per their forum). However, the discussion at the Google group clearly states that the parentheses surrounding author-in-text citations are **not specified** by the CSL style (which doesn't know about author-in-text citations). 

This seems to indicate that I will be left with manual editing of the output one way or the other. Either the archival locator is in the "correct" (per our discipline) location, or have unwanted parentheses.

**Comment by jgm** [comment] 2023-01-10 16:36
You are complaining about parentheses in regular citations, not author-in-text citations.  e.g. `[@Dickson1885TestLettera]`.  An author-in-text citation would be `@Dickson1885TestLettera`, and the author's name would not be rendered in parentheses.

**Comment by tarleb** [comment] 2023-05-05 15:57
It seems that this is not a bug, so I'm closing the issue.

**Closed by tarleb** 2023-05-05 15:57 UTC
Labels: bug
