### ISSUE TITLE
Markdown Templates: missing footnote texts in output

### ISSUE THREAD

**Issue by rriemann** [jgm/pandoc#4964] opened 2018-10-11 09:26 UTC
I use the templating system of pandoc (version 2.3.1) to replace a `$variable$` with Markdown text from YAML meta data.

### Issue

When this Markdown text contains a footnote, the footnote anchor name is changed and the footnote text is stripped off. In consequence, the rendered output does not contain the footnote and has a weird anchor in the text.

### Minimal Example

```markdown
---
myinclude: |
  ## Include

  Lorem ipsum dolor sit amet. [^footnote-include]

  [^footnote-include]: This is the included footnote.

  Ut enim ad minim veniam consequat.
---

# Title

$myinclude$

end
```

This file is at the same time a template and the input file. The `$body` tag is not used in the template. So only the meta data is used from the input file.

```shell
pandoc --template=test.md --from=markdown --to=markdown  --atx-headers --standalone --output=test.out.md test.md
```

Output:

```markdown
---
myinclude: |
  ## Include

  Lorem ipsum dolor sit amet. [^footnote-include]

  [^footnote-include]: This is the included footnote.

  Ut enim ad minim veniam consequat.
---

# Title

## Include

Lorem ipsum dolor sit amet. [^1]

Ut enim ad minim veniam consequat.

end
```

### Expected Output

```markdown
---
myinclude: |
  ## Include

  Lorem ipsum dolor sit amet. [^footnote-include]

  [^footnote-include]: This is the included footnote.

  Ut enim ad minim veniam consequat.
---

# Title

## Include

Lorem ipsum dolor sit amet. [^footnote-include]

[^footnote-include]: This is the included footnote.

Ut enim ad minim veniam consequat.

end
```

**Comment by jgm** [comment] 2018-10-12 03:47
There are two issues here:

1. The change of label from `[^footnote-include]` to `[^1]`.
2. The missing footnote definition.

Re 1:  Remember that the contents of the metadata field are parsed as markdown, and then rendered in the target format.  Here that's markdown.`pandoc -f markdown -t markdown` is not the identity transformation.  Footnotes, for example, are given new, numerical labels.  There's no way to ensure that they keep the same labels, since the label is not stored in the AST.  However, if there is some raw markdown that you just want passed verbatim to your template, you can use the raw block syntax in your metadata: https://pandoc.org/MANUAL.html#generic-raw-attribute

Re 2:  Pandoc's markdown writer puts the footnote definitions at the end of the body, by default.  Since you don't have `$body$` in your template, they just disappear.  You could try using `--reference-location=block`.

**Comment by jgm** [comment] 2018-10-12 03:47
Closing, because this is not a bug.

**Closed by jgm** 2018-10-12 03:47 UTC

**Comment by rriemann** [comment] 2018-10-12 08:07
With `--reference-location=block`, the output contains eventually a footnote text! :+1:  :smile: 

Thank you!

```markdown
---
myinclude: |
  ## Include

  Lorem ipsum dolor sit amet. [^footnote-include]

  [^footnote-include]: This is the included footnote.

  Ut enim ad minim veniam consequat.
---

# Title

## Include

Lorem ipsum dolor sit amet. [^1]

[^1]: This is the included footnote.

Ut enim ad minim veniam consequat.

end
```
