### ISSUE TITLE
Latex/PDF: change longtable to be correctly row colored

### ISSUE THREAD

**Issue by salim-b** [jgm/pandoc#4045] opened 2017-11-06 00:10 UTC
If one would like to have zebra striped table rows (or any other kind of row coloring) in the PDF output converted from Pandoc Markdown, the `longtable` environment could be redefined in the YAML header like the following:
```
---
header-includes:
  - \usepackage[table]{xcolor}
  - \definecolor{lightgray}{gray}{0.95}
  - \let\OldLongtable\longtable
  - \let\OldEndLongtable\endlongtable
  - \renewenvironment{longtable}{\rowcolors{1}{white}{lightgray}\OldLongtable}{\OldEndLongtable}
---
```

Now the problem with this is that the resulting row coloring is wider than the actual table. Therefore I've [asked for a solution on the Tex/Latex Stack Exchange site](https://tex.stackexchange.com/questions/393993/row-coloring-too-wide-pandoc-md-pdf) and a user called Zarko recently [provided a workaround](https://tex.stackexchange.com/a/399858/144087) – but on the level of the intermediary Latex code. Right now the longtable for a 4-column table with right-left-left-center alignments produced by Pandoc starts with
```
\begin{longtable}[]{@{}rllc@{}}
```
Zarko changed this into
```
\begin{longtable}[]{@{} >{\columncolor{white}[0pt][\tabcolsep]}rll >{\columncolor{white}[\tabcolsep][0pt]} c@{}}
```
which makes the row coloring the correct width.

**Now I wonder if his adjustmens could be somehow incorporated into Pandoc or it's default Latex template to allow users to define zebra-striped tables.** 🙂 

(Unfortunately I'm not proficient enough to assess – not to speak of implement – this.)

**_Addendum:_**  
As [Zarko pointed out](https://tex.stackexchange.com/questions/393993/row-coloring-too-wide-pandoc-md-pdf#comment995196_399858), just removing the two `@{}` so that the longtable begins only with
```
\begin{longtable}[]{rllc}
```
also fixes the problem. But I guess the `@{}` do serve some purpose, right?

**Comment by mb21** [comment] 2017-11-07 08:50
there's also quite some discussion about table LaTeX output in this issue: https://github.com/jgm/pandoc/issues/1023

**Comment by Wandmalfarbe** [comment] 2017-11-09 18:22
This seems to be a duplicate of #3929.

**Comment by mb21** [comment] 2017-11-09 18:47
Thanks @Wandmalfarbe 

Duplicate of #3929

**Closed** 2017-11-09 18:47 UTC
Labels: format:LaTeX, writer
