### ISSUE TITLE
Set default non-English language for citations and hyphenation

### ISSUE THREAD

**Issue by tubia** [jgm/pandoc#2359] opened 2015-08-13 10:45 UTC
Hi,
I experienced many problems trying to set the default non-English language in a markdown document in which the output is a .pdf (using `latex-engine: xelatex`). In particular regarding bibliography language. I've set `lang: it-IT` and `language: it-IT` with no functioning result. For example, in Italian "translated by" is "tradotto da", still in the output bibliography the sentence in a bibliographical entry was "translated by".
I managed a solution using `locale: it-IT` however this is not listed anywhere.
I still have problems with correct hyphenation, for example this `emerg-ere` is not correct in Italian.

**Comment by ousia** [comment] 2015-08-13 15:08
@tubia, the language setup in Markdown documents is being discussed in issue #1614.

Just out of curiosity, do you use babel or polyglossia?

**Comment by ousia** [comment] 2015-08-19 19:22
@tubia, as a temporary workaround (until #1614 is fixed) you may set `lang: italian` when generating the PDF document with LaTeX.

BTW, isn’t this issue a duplicate of #1614?

**Comment by jgm** [comment] 2015-10-14 04:24
Closing - dup of #1614, now closed.

**Closed by jgm** 2015-10-14 04:24 UTC
