### ISSUE TITLE
Inconsistent parsing of quoted strings depending on whether they contain `[`?

### ISSUE THREAD

**Issue by cscheid** [jgm/pandoc#7368] opened 2021-06-09 21:15 UTC
Using the latest nightly on an Intel MacBook Pro running Big Sur,

```
$ ~/Downloads/pandoc/pandoc-nightly-macos-2021-06-09/pandoc --version
pandoc 2.14.0.1
Compiled with pandoc-types 1.22, texmath 0.12.3, skylighting 0.10.5.1,
citeproc 0.4.0.1, ipynb 0.1.0.1
User data directory: /Users/cscheid/.local/share/pandoc
Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

I seem to be getting inconsistent ASTs for an (admittedly gnarly) markdown paragraph. This is the smallest example pair I could get, but the ASTs are still not tiny - sorry about that. Compare:

```
$ ~/Downloads/pandoc/pandoc-nightly-macos-2021-06-09/pandoc --to json --output - | python -m json.tool
${"[ " + " ]"}
^D
{
    "pandoc-api-version": [
        1,
        22
    ],
    "meta": {},
    "blocks": [
        {
            "t": "Para",
            "c": [
                {
                    "t": "Str",
                    "c": "${"
                },
                {
                    "t": "Quoted",
                    "c": [
                        {
                            "t": "DoubleQuote"
                        },
                        [
                            {
                                "t": "Str",
                                "c": "["
                            },
                            {
                                "t": "Space"
                            },
                            {
                                "t": "Str",
                                "c": "\u201d"
                            },
                            {
                                "t": "Space"
                            },
                            {
                                "t": "Str",
                                "c": "+"
                            },
                            {
                                "t": "Space"
                            },
                            {
                                "t": "Str",
                                "c": "\u201d"
                            },
                            {
                                "t": "Space"
                            },
                            {
                                "t": "Str",
                                "c": "]"
                            }
                        ]
                    ]
                },
                {
                    "t": "Str",
                    "c": "}"
                }
            ]
        }
    ]
}
```

to

```
~/Downloads/pandoc/pandoc-nightly-macos-2021-06-09/pandoc --to json --output - | python -m json.tool
${"( " + " )"}
^D
{
    "pandoc-api-version": [
        1,
        22
    ],
    "meta": {},
    "blocks": [
        {
            "t": "Para",
            "c": [
                {
                    "t": "Str",
                    "c": "${"
                },
                {
                    "t": "Quoted",
                    "c": [
                        {
                            "t": "DoubleQuote"
                        },
                        [
                            {
                                "t": "Str",
                                "c": "("
                            }
                        ]
                    ]
                },
                {
                    "t": "Space"
                },
                {
                    "t": "Str",
                    "c": "+"
                },
                {
                    "t": "Space"
                },
                {
                    "t": "Str",
                    "c": "\u201d"
                },
                {
                    "t": "Space"
                },
                {
                    "t": "Str",
                    "c": ")\u201c}"
                }
            ]
        }
    ]
}
```

The two markdown paragraphs are `${"[ " + " ]"}` and `${"( " + " )"}`. I'm not sure whether this should be considered a pandoc bug or not, but I am surprised by two points here:

- With `${"[ " + " ]"}`, pandoc chooses a "longest parse" for the quote (the `Quoted` node contains `[ " + " ]`). I was expecting this parse to have two `Quoted` nodes.
- With `${"( " + " )"}`, pandoc chooses a "shortest parse", but only interprets the first pair of quotes as a `Quoted` node, then emitting the second pair as literal `\u201d` and `\u201c` smart quotes instead of the `Quoted` node.

I could only get the former behavior to trigger with square brackets, but I'm not sure if this is the root cause.

Am I missing something about how the parser works or should this have been consistent?

**Comment by jgm** [comment] 2021-06-09 22:33
If you use `-t native` instead of `-t json`, you'll get a nicer, more compact representation of the AST.

**Comment by jgm** [comment] 2021-06-09 22:38
In answer to your first question:  our heuristic for recognizing a closing double quote requires that it not come after a space.

But the second case is odd; I'd need to look back at the source to figure out what is going on here.

**Comment by cscheid** [comment] 2021-06-10 16:18
Thank you for the very prompt reply!

Given your answer for the first question, I'm inclined to work around this bit on our end. I'm almost ready to close this as "not a bug" or the equivalent you use here. But just for completeness, let me clarify.

With respect to the first example, the "longest-parse" odd behavior I see appears specific to _square brackets_, and not spaces in the quotes:

```
$ ~/Downloads/pandoc/pandoc-nightly-macos-2021-06-09/pandoc --to native --output -
${"a" + "b"}
[Para [Str "${",Quoted DoubleQuote [Str "a"],Space,Str "+",Space,Quoted DoubleQuote [Str "b"],Str "}"]]
 $ ~/Downloads/pandoc/pandoc-nightly-macos-2021-06-09/pandoc --to native --output -
${"[" + "]"}
[Para [Str "${",Quoted DoubleQuote [Str "[\8221",Space,Str "+",Space,Str "\8221]"],Str "}"]]
```

**Comment by jgm** [comment] 2021-06-10 16:27
I see what is happening now. It's a result of an optimization I made for link parsing, which shortcuts to emitting literal `[..]` with the parsed text if a reference isn't found.  Because of this, the closing " isn't seen.  Note that commonmark does fine here (`pandoc -f commonmark+smart`).  Maybe I should remove this optimization; I'm not sure how much difference it makes.

**Comment by jgm** [comment] 2021-06-10 16:35
Oh, I see now, it's not just an optimization.  The problem is that we don't know if we have a valid reference link til we've parsed the whole document; if one isn't found at that point, we emit the fallback.  Commonmark has a better parsing strategy, but there's not much we can do about the standard markdown parser.  If this is a problem, you can backslash-escape a `[` to avoid it.

**Closed by jgm** 2021-06-10 16:35 UTC
