### ISSUE TITLE
"file not found" for language.dtd when using custom syntax definition

### ISSUE THREAD

**Issue by versionbayjc** [jgm/pandoc#5328] opened 2019-02-25 15:39 UTC
Following the instructions from:
https://pandoc.org/MANUAL.html#syntax-highlighting

I am trying to use a custom syntax definition and theme

I am using pandoc 2.6:
```
$ pandoc -v
pandoc 2.6
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2, skylighting 0.7.5
```
When I use the matlab.xml from: https://github.com/KDE/syntax-highlighting/blob/master/data/syntax/matlab.xml
I receive a file not found error:
```
$ pandoc -s --syntax-definition=matlab.xml exampleFile.md -o exampleFile.pdf

fatal error: file read error: "file not found" when accessing "/Users/jorik/src/pandocExample/language.dtd"
Could not parse syntax definition matlab.xml
```

From this comment in another issue:
https://github.com/jgm/pandoc/issues/4831#issuecomment-412298678
I found a language.dtd, but I think this should either be documented in:
https://pandoc.org/MANUAL.html#syntax-highlighting
 or the language.dtd should not to be needed anymore ;-).

**Comment by jgm** [comment] 2019-02-25 20:24
I think making the file unnecessary would be a nicer change, but this would require changes in jgm/skylighting and I don't see a way to do it.

So for now I'll just document.

**Comment by jgm** [comment] 2019-02-25 20:33
I'm confused now.  The KDE/syntax-highlighting repository no longer contains `language.dtd`, yet most of the xml syntax definitions refer to it.  Where is the canonical version?

**Comment by jgm** [comment] 2019-02-25 20:37
One option would be to turn off validation when parsing; then I think it wouldn't look for the dtd, though it would also mean that one wouldn't get useful error feedback for malformed XML.

The dtd may in fact be vestigial.  There are a couple entities defined there that don't seem to be used in any of the .xml syntax definitions.

**Comment by versionbayjc** [comment] 2019-02-25 20:37
I was also having trouble finding it, I wasn't looking in the right folder:
https://github.com/jgm/highlighting-kate/blob/master/xml/language.dtd

**Comment by jgm** [comment] 2019-02-25 21:28
That's not the from the official KDE repository, though. That's an old version I put in highlighting-kate; it came from an older version of the KDE repository, but the file is no longer in that repository.

**Comment by versionbayjc** [comment] 2019-02-25 21:39
Ah yes, you're of course quite right, I hadn't noticed it (even with jgm in the URL). Fortunately this old file is still good enough to use it with a custom syntax highlighting definition with the current pandoc, though. 😀

**Comment by versionbayjc** [comment] 2019-02-25 21:43
There is a language.xsd in the current KDE repo:
https://github.com/KDE/syntax-highlighting/blob/master/data/schema/language.xsd
even though the extension is different, it does seem to be an updated version of the language.dtd that is in highlighting-kate

**Comment by jgm** [comment] 2019-02-26 00:33
I'm sure you're right.  Hm, maybe the best thing to do is simply remove validation from the parsing in skylighting, so the language.dtd isn't looked for.

**Comment by jgm** [comment] 2019-02-26 01:54
OK, now I remember the difficulty.  Some of the xml definitions look like this (roff.xml):
```
<!DOCTYPE language SYSTEM "language.dtd"
[
  <!ENTITY roffidc "[^]\s]">
  <!ENTITY roffid  "(&roffidc;|\(&roffidc;{2}|\[&roffidc;+\])">
  <!ENTITY roffnum "([0-9]+)">
  <!ENTITY argsep1 "([^\\]|\\[&#37; |\^{}'`\-!?@)/,&amp;:~0E_acdeprtu])">
  <!ENTITY argsep2 "([^\\0-9]|\\[&#37;:{}'`\-_!@/cep])">
]>
```
We can switch off the option  `withSubstDTDEntities  no`, which disables fetching of the DTD.  But when we do this, the entities explicitly defined in between brackets are also ignored, and that breaks things.

**Comment by mb21** [comment] 2019-02-26 08:17
Maybe we could first try to validate it, and if we get an error, log that and continue without validation...

**Comment by jgm** [comment] 2019-02-26 19:01
We already weren't validating. The issue is not validation, but substitution of entities.  Annoyingly, none of the entities defined in the actual language.dtd file are needed, but the bracketed entities don't get substituted unless you turn on an option that requires reading that file...

One solution would be to delete `SYSTEM "language.dtd"` from all the xml files. But this doesn't help a great deal, since the problem will arise again when people try to use syntax definitions from the KDE repo.

**Comment by jgm** [comment] 2019-02-27 06:19
I think I found a fix for this.  New code in skylighting-core master just strips off the `SYSTEM "language.dtd"` before parsing.  Needs a bit more testing before a release.

**Closed** 2019-02-28 07:57 UTC
