### ISSUE TITLE
(TagClose "script") is not a TagOpen

### ISSUE THREAD

**Issue by davidcannatella** [jgm/pandoc#7282] opened 2021-05-14 04:33 UTC
HI everyone,
I'm running Rstudio Version 1.4.1106 with pandoc bundled (2.13) on Big Sur 11.3.1. I'm working with the bookdown package. When I build the book, I get this error at the end of the build (which fails).

```
pandoc: (TagClose "script") is not a TagOpen
CallStack (from HasCallStack):
  error, called at src/Text/HTML/TagSoup/Type.hs:128:19 in tagsoup-0.14.8-L5MEiexJs3vKxwutM9lSL6:Text.HTML.TagSoup.Type
Error: pandoc document conversion failed with error 1
Execution halted

Exited with status 1.
```

I would provide a reprex, but my project has ~30 Rmd files and I have no idea how to localize the problem, given the error message. My other two bookdown projects don't throw this error. I've done a lot of google searching and can't find this error message anywhere, Any ideas where I should look?
Thanks,
Dave

**Comment by mb21** [comment] 2021-05-14 07:05
> I would provide a reprex, but my project has ~30 Rmd files and I have no idea how to localize the problem

try binary-search approach by removing half of the input and seeing if the problem is gone every time..

For future questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!

**Comment by tarleb** [comment] 2021-05-14 09:38
I can reproduce this with a document containing just a closing script tag.

``` html
</script>
```

**Closed** 2021-05-14 10:15 UTC
Labels: format:HTML, reader

**Comment by tarleb** [comment] 2021-05-14 10:17
@davidcannatella please check your code for an unmatched closing `</script>` and re-raise this at the bookdown repo if appropriate. But please try to whittle this down first. At least you know now what to look for.

**Comment by tarleb** [comment] 2021-05-14 10:17
Oh, and thanks for the report.

**Comment by davidcannatella** [comment] 2021-05-14 16:14
Thanks for the advice.

I spent a couple of hours on this, and finally figured out that the problem was not a <script> tad in the .Rmd file, but rather a single "[" along at the beginning of a line.

By itself, the .Rmd file knits without problem, but in the context of the entire bookdown project, it provokes that error.

Should I report this to bookdown, or is this a pandoc issue?

Thanks,
Dave

**Comment by tarleb** [comment] 2021-05-14 16:51
The problem of pandoc crashing should be fixed, not sure about any remaining issues. It's probably good to raise it as a bookdown issue, but feel free to tag me in the issue, or to link it here.
