### ISSUE TITLE
Massive performance drops in Pandoc 2.0.6 (Markdown -> any format)

### ISSUE THREAD

**Issue by simon-kr** [jgm/pandoc#4225] opened 2018-01-05 16:16 UTC
Since the newest version of Pandoc, 2.0.6, the conversion time from Markdown to X has significantly risen. I generate PDF files with lots of snippets of Markdown that need to be converted to LaTeX and have recognized much slower performance. I was using Pandoc 1.16. beforehand, because it was the newest version in my Ubuntu distribution.

My test setup:

Input: MANUAL.txt from current branch
Task: Convert 5 times from Markdown to LaTeX

Ruby source code:
```ruby
start = Time.now
5.times { `#{ARGV[0]}` }
puts "#{((Time.now - start) * 1000).round(3)} ms running time"
```

Ruby call:
```ruby
ruby timer.rb "pandoc -t html MANUAL.txt > test.html"
```

Test results:
> 1.16.0.2 -- 2406.479 ms running time
> 1.19.2.1 -- 2524.801 ms running time
> 2.0 -------- 4014.895 ms running time
> 2.0.5 ------ 4084.534 ms running time
> 2.0.6 ------ 5927.092 ms running time

It seems to be the Markdown reader because the output format does not seem to matter, and the other way round, it's much faster.
Is there any known reason why it's so much slower? There is a significant drop beween 1.x and 2.x and another quite massive one between 2.0.5 and 2.0.6

**Comment by tarleb** [comment] 2018-01-05 16:34
Duplicate of #4216.

**Closed by tarleb** 2018-01-05 16:34 UTC

**Comment by tarleb** [comment] 2018-01-05 16:37
Not sure if the 1.19 -> 2.0 drop has Bern investigated yet, might be worth a separate issue.

**Comment by simon-kr** [comment] 2018-01-05 16:39
Thanks for your fast reaction ... I only looked for open bug reports and not at the closed ones :(
But yes, you may be right, it could be two different issues.
