### ISSUE TITLE
pandoc fails by using up all memory, no output or diagnostic messages

### ISSUE THREAD

**Issue by kagalenko-m-b** [jgm/pandoc#5964] opened 2019-12-06 14:05 UTC
I am using the latest pandoc version and TeXLive2019. I try to convert to docx the output of the Russian PhD dissertation template  https://github.com/AndreyAkinshin/Russian-Phd-LaTeX-Dissertation-Template

Pandoc churns the disk for like an hour, gradually using up all available memory and then all swap, at which point it reports the failure to allocate a block of memory and prints "Killed".

**Comment by mb21** [comment] 2019-12-06 17:24
Thank you for submitting a bug report. However, we cannot improve pandoc or help you unless you give us all of the following information:

* the pandoc version (check using `pandoc -v` and try to reproduce the bug with the latest released version of pandoc, or even better: the development version or [nightly build](https://github.com/pandoc-extras/pandoc-nightly).)
* the exact command line used
* the exact input used

A small test case (just a few lines) is ideal.  If your input is large, try to whittle it down to a **minimum working example**. 

Finally, ask questions on [pandoc-discuss](http://groups.google.com/group/pandoc-discuss) and read the [User's Guide](http://pandoc.org/MANUAL.html).

**Comment by jgm** [comment] 2019-12-06 19:28
As the manual suggests (under Security), it is possible to limit the amount of memory that will be used by pandoc by adding, say, `+RTS -M512M -RTS` (for 512MB).

It would be good to track down the problem here, as this would help us improve the LaTeX parser.  If you can help us narrow it down, that would be great.  You can try, for example, commenting out various bits of the input to see if you can get a more minimal case.

**Comment by kagalenko-m-b** [comment] 2019-12-07 14:57
I used the latest version of pandoc
> pandoc 2.8.0.1
> Compiled with pandoc-types 1.20, texmath 0.12, skylighting 0.8.3

Steps to reproduce the failure are as follows:
```
git clone https://github.com/AndreyAkinshin/Russian-Phd-LaTeX-Dissertation-Template.git
cd Russian-Phd-LaTeX-Dissertation-Template/
pandoc  +RTS -M512M -RTS dissertation.tex -o dissertation.docx
```

That produces the following output:
> pandoc: Heap exhausted;
> pandoc: Current maximum heap size is 536870912 bytes (512 MB).
> pandoc: Use `+RTS -M<size>' to increase it.

Nothing else.

**Comment by jgm** [comment] 2019-12-07 16:55
Oh yes, I had already reproduced it. But it's a massive document with lots of parts. What I was requesting is that you help us narrow down the problem, e.g. by commenting out sections.  That increases the chance it will be fixed.

With heap size, my suggestion was just meant to give you a way of limiting the damage if pandoc runs into a problem like this, preventing it from using all system memory before it gives up.

**Comment by kagalenko-m-b** [comment] 2019-12-07 18:03
Well, it looks like that if one comments out the line 58 
```
\include{Dissertation/contents}        % Оглавление
```
and line 68
```
\include{Dissertation/part3}           % Глава 3
```

Then pandoc prints a lot of warnings about math, such as
> [WARNING] Could not convert TeX math '\begin{aligned}
garbles equations, but does make some output. 

If only line 58 is commented out, then it it gves the following error
> Error at "source" (line 84, column 16):
> unexpected end of input
> \end{document}

**Comment by jgm** [comment] 2021-04-26 05:59
Closing this issue, as it concerns an old version of pandoc. There have been many changes to the LaTeX reader since then, so maybe the issue is fixed. In any case, it's hard to check that without precise instructions for reproducing.  If the issue persists with latest pandoc, feel free to open a new issue.

**Closed by jgm** 2021-04-26 05:59 UTC
Labels: format:LaTeX, reader
