### ISSUE TITLE
pandoc cannot read read-only files on Windows (needs write atrributes permission)

### ISSUE THREAD

**Issue by kiwi0fruit** [jgm/pandoc#5259] opened 2019-01-30 07:41 UTC
```
>>> pandoc "%ProgramFiles%\Git\LICENSE.txt" -t gfm
pandoc: C:\Program Files\Git\LICENSE.txt: openBinaryFile: permission denied (Per
mission denied)
>>> echo 111 | pandoc -H "%ProgramFiles%\Git\LICENSE.txt"
pandoc: C:\Program Files\Git\LICENSE.txt: openBinaryFile: permission denied (Per
mission denied)
>>> echo 111 | pandoc -H "%UserProfile%\.condarc" -t gfm > NUL
NO OUTPUT
```
Pandoc doesn't have write/modify permissions for `%ProgramFiles%\Git\LICENSE.txt` but it has read permissions and that should be enough.

**Comment by mb21** [comment] 2019-01-30 08:37
what pandoc and windows versions?

**Comment by kiwi0fruit** [comment] 2019-01-30 09:00
Windows 7 x64 SP1 RUS
```
pandoc 2.5
Compiled with pandoc-types 1.17.5.4, texmath 0.11.1.2, skylighting 0.7.4
Default user data directory: C:\Users\User\AppData\Roaming\pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by mb21** [comment] 2019-01-30 09:50
Can anybody else reproduce this on windows?

@kiwi0fruit can you print out the file permissions? On unix it would be `ls -l`, and for the record: it works:

    ~ ls -l foo.md 
    ----------  1 maurobieg  staff  0 Jan 30 10:48 foo.md

    ~ pandoc foo.md
    pandoc: foo.md: openBinaryFile: permission denied (Permission denied)

    ~ chmod u+r foo.md 

    ~ ls -l foo.md 
    -r--------  1 maurobieg  staff  0 Jan 30 10:48 foo.md

    ~ pandoc foo.md
    # empty output since file was empty

**Comment by agusmba** [comment] 2019-01-30 10:03
I cannot reproduce it.
Note that I have admin privileges.
I manually removed write permission from a test file (I checked that I no longer could modify it), but pandoc could read it fine.
I'm using a nightly version of pandoc (from a couple of days back), 64bit on windows7.

**Comment by kiwi0fruit** [comment] 2019-01-30 10:13
I can add that `type` command and python entry points executables can read such files without proplems.

**Comment by kiwi0fruit** [comment] 2019-01-30 10:35
It just worked with `pandoc "%SYSTEMROOT%/win.ini"`! Then I checked this from git bash and it didn't works there. And now `pandoc "%SYSTEMROOT%/win.ini"` doesn't work again. Rather strange behaviour. Seems like specific to my installation. But turning off antivirus doesn't change things...

**Comment by kiwi0fruit** [comment] 2019-01-30 10:54
I can no longer reproduce a working situation... Even after reboot and turning antivirus off.

**Comment by kiwi0fruit** [comment] 2019-01-30 11:00
I localized a bit more: if I add permission to "write attributes" it works. Without it - it doesn't work.

Please somebody check about "write attributes" on Windows.

**Comment by kiwi0fruit** [comment] 2019-01-30 11:03
I narrowed it a bit more: it works without "write data" premissions but needs "write atrributes" permission to work.

**Comment by kiwi0fruit** [comment] 2019-01-30 11:18
Narrowed even more: 2.3 works but 2.3.1 doesn't work.

**Comment by agusmba** [comment] 2019-01-30 12:33
I still cannot reproduce it, reducing the permissions on the source file (docx to native):

![image](https://user-images.githubusercontent.com/3104020/51981468-6e402200-2493-11e9-923c-05fb0503b750.png)

pandoc (v~2.6) can read the file and convert it to native.

**Comment by agusmba** [comment] 2019-01-30 12:34
Can you try with this recent build?

https://ci.appveyor.com/project/jgm/pandoc/build/job/a1xjd0spdsv706f9/artifacts

**Comment by kiwi0fruit** [comment] 2019-01-30 12:45
Sure. I'll try with the latest build.

>

**Comment by kiwi0fruit** [comment] 2019-01-30 15:05
The recent build works OK.

**Comment by mb21** [comment] 2019-01-30 15:20
great! closing this then...

**Closed by mb21** 2019-01-30 15:20 UTC
Labels: platform:windows
