### ISSUE TITLE
Certain epubs return a " not found in reftable" error

### ISSUE THREAD

**Issue by mhysther** [jgm/pandoc#8217] opened 2022-08-05 23:11 UTC
Currently using pandoc version 2.18 on Windows 10

Something I initially asked on stackoverflow:
 https://stackoverflow.com/questions/73226420/i-cant-use-pandoc-for-select-epubs

Whatever I try with certain epubs, whether it's merging or converting to something else, I get a " not found in reftable" error. I've tried with the following commands (or any) to no avail:
pandoc (get-item *.epub).FullName -o output.epub
pandoc -f epub -t plain --wrap none -o placeholder.txt placeholder.epub

I've attached a stripped-of-content epub (as zip) that has this error. Only the styles etc. remain.

Please let me know if any clarification is needed!

[placeholder.zip](https://github.com/jgm/pandoc/files/9273939/placeholder.zip)

**Comment by jgm** [comment] 2022-08-06 05:30
Tried with pandoc 2.19 on macOS.
No error was raised, and a blank document resulted (as expected).

**Comment by jgm** [comment] 2022-08-06 05:32
Can you give the complete text of the error message?  It should say ___ not found in reftable.  What is in the ___?

**Comment by mhysther** [comment] 2022-08-08 01:10
Embarrassingly enough, the conversion is working fine for me too now. I have no idea why I was seeing an error the other times, I'm so sorry about that. The merge is still not working though, and nothing precedes the reftable. I've attached a screenshot for clarity!
[pandoc combine](https://user-images.githubusercontent.com/74018815/183319839-83c0aef3-946f-4ff2-90a8-2dbe956a8b4e.PNG)

**Comment by mhysther** [comment] 2022-08-08 01:12
Forgot to clear out some personal data...

Embarrassingly enough, the conversion is working right for me now too. I have no idea why I was previously seeing that issue and I'm so sorry for the confusion. The merge issue is still happening though, and nothing is preceding the not found in reftable error. I have attached a screenshot for clarity!
![pandoc combine](https://user-images.githubusercontent.com/74018815/183319957-e1cdf1b4-1ddc-4f71-927f-c87e78cb93bd.PNG)

**Comment by jgm** [comment] 2022-08-08 02:21
Are you trying to run pandoc on multiple epub input files on the same command line?  That probably won't work, though you could try it with  `--file-scope`.

**Comment by mhysther** [comment] 2022-08-11 04:31
I use this command to merge all epubs within a directory. It's worked for other epubs, but for some reason, just not this particular series of epubs.

**Comment by jgm** [comment] 2022-08-13 19:22
This error message is triggered when pandoc encounters a section with an id that is not in the reftable.
I'm not sure why this would happen, but it's impossible for me to diagnose the problem without the files.
If you can provide redacted files that allow the error to be reproduced, we can try to find the cause; otherwise, we should close this issue.

**Comment by mhysther** [comment] 2022-08-14 05:02
Is there any way I can send the file to a private message/email due to potential copyright concerns? That being said, the only changes I believe I made was to strip text content, it's giving me the same error now with the epub that I attached as a zip.

**Comment by jgm** [comment] 2022-08-14 06:12
The file you attached as a zip is a single epub.  If I understood you correctly, the issue you were having happened when you were trying to merge multiple epubs using pandoc. So I'm confused.
Anyway, you can send something privately to the maintainer as recorded at
https://hackage.haskell.org/package/pandoc
I would need exact instructions for reproducing the problem, including ALL the files needed.

**Comment by steffen-stell** [comment] 2023-01-30 17:52
I encountered this same issue with pandoc 2.14 on Fedora 37. With the latest 3.0.1 binary from github, it worked fine.

**Comment by jgm** [comment] 2023-01-30 18:02
I'm going to close this.

**Closed by jgm** 2023-01-30 18:02 UTC
Labels: bug, status:more-info-needed
