### ISSUE TITLE
Markdown table with non-quadratic structure

### ISSUE THREAD

**Issue by GiantCrocodile** [jgm/pandoc#3622] opened 2017-04-30 15:04 UTC
I wrote this table (note: first line is missing a `|`):

```markdown
| Heading
| --- | --- |
| Name | Description |
| a    | some text |
```

In Atom's markdown plus preview I get a table where first row is one column and row two and three have two columns. When I export it I get a quadratic table structure. I think this is a bug in Atom's preview or is there a way to have a non-quadratic table structure?

**Comment by mb21** [comment] 2017-05-01 10:05
What do you mean with "quadratic table" and more importantly how does this relate to pandoc?

**Comment by GiantCrocodile** [comment] 2017-05-01 10:13
Ok, @mb21: This is a screenshot of how it looks in my Atom's Markdown Preview Plus plugin preview:

![table](https://cloud.githubusercontent.com/assets/6271057/25577527/fa25cc54-2e66-11e7-85f4-c2effa29d591.JPG)

This is how I want the table to look like! When I export it, I get this PDF-output:

![table_pdf](https://cloud.githubusercontent.com/assets/6271057/25577560/3ba63344-2e67-11e7-8dee-181e21c7c4cf.JPG)

I want to have the first row to exist of only one column and not two columns. I'm not sure if my Atom's plugin is rendering it wrong or if pandoc generates the wrong output because of a writer bug.

**Comment by mb21** [comment] 2017-05-01 10:35
Unfortunately, pandoc currently does not support tables with row- or column spans, see https://github.com/jgm/pandoc/issues/1024

However, what you're proposing [isn't even allowed in HTML](http://stackoverflow.com/questions/3484768/can-html-table-have-variable-number-of-cells-on-rows) (AFAIK).

**Comment by GiantCrocodile** [comment] 2017-05-01 10:42
I'm not sure how comes you think it is not allowed in HTML. In the link you've mentioned the first few answers say it is possible and no rule break. You just should define `colspan="<number>"` then. At least it sounds to me that the guy on StackOverflow wanted to do the same thing as I want to do here.

Thanks for your response and linking the other issue!

**Comment by mb21** [comment] 2017-05-01 10:45
Indeed, if you add colspans it's allowed in HTML, but then the cell extends all the way to the right of the table... anyway, closing as a duplicate of #1024 then.

**Closed by mb21** 2017-05-01 10:45 UTC
