### ISSUE TITLE
pandoc-citeproc W10 bibliography path not working

### ISSUE THREAD

**Issue by DOFfactory** [jgm/pandoc#5685] opened 2019-08-12 23:18 UTC
Using latest pandoc version, installed through `scoop`. I write makrdown in VSCode on W10, using the plugin `vscode-pandoc`

My YAML header looks like this:
```
---
bibliography: [C:\Users\user\Dropbox\Bibliography\biblio.bib]
link-citations: true
reference-section-title: References
---
```

I am getting the following error:
```
exec error: Error: Command failed: pandoc "c:\Users\user\Documents\test.md" -o "c:\Users\user\Documents\test.docx" --from markdown+yaml_metadata_block+pandoc_title_block+smart --filter pandoc-citeproc --number-sections --reference-doc=C:\Users\user\custom-reference.docx Could not find bibliography file: C:.bib Error running filter pandoc-citeproc: Filter returned error status 1
```

As soon as I copy the `bib` file into `C:\User\user\Documents` and changed to `bibliography: [biblio.bib]` everything started to work again and the citations are fine. I tried creating a Shortcut (W10), putting the path between quotation marks, apostrophes. Nothing worked. 

I would like to stress that in previous versions this path worked. No idea why it is not working now. 

Obviously something is wrong with the path link, but it would be great to have it fixed once and for all in order to avoid file duplicates, and other related issues.

**Comment by jgm** [comment] 2019-08-13 23:34
The problem is probably that the backslash requires special escaping in YAML.
(Note that metadata fields are first parsed by a YAML parser, and THEN parsed as Markdown.  So even though you wouldn't normally need to escape a `\` before a letter in Markdown, you might need to in a YAML context.)

**Comment by DOFfactory** [comment] 2019-08-14 07:14
Hi @jgm, many thanks for identifying this for me, as far as I can see you are right with this solution. As a person working on Linux, Windows, and macOS intermittently (this is the reason I am using Markdown), I wonder whether it is possible to explain this _explicitly_ somewhere in the pandoc manual so one can find it easily. I use pandoc for few years, and I did not know that YAML understands paths differently to pandoc Markdown (e.g. references to figures, etc.) in the same document.

**Comment by mb21** [comment] 2019-08-14 07:53
It's just how YAML works. But yes, we could put a link in the MANUAL somewhere (where?) that links to the documentation of the YAML version we're using...

**Comment by DOFfactory** [comment] 2019-08-14 08:08
My guess would be, under the `Metadata variables` section in the [MANUAL](https://pandoc.org/MANUAL.html) I would add a hyperlink to the YAML manual pandoc is using, and also there is the following example: 

```
---
title:  'This is the title'
subtitle: "This is the subtitle"
author:
- Author One
- Author Two
description: |
    This is a long
    description.

    It consists of two paragraphs
...
```

I guess a lot of users will check this example, so it might be a good idea to add a line:

```
bibliography:  [C:\\Users\\JohnDoe\\bibliography.bib]
```

**Comment by jgm** [comment] 2019-08-14 18:12
Sorry, got wrong issue number in commit.

**Comment by mb21** [comment] 2019-08-16 07:49
Yes, the `Add thin space` commit isn't related to this. But this was still closed by https://github.com/jgm/pandoc/pull/5687 (adjusting the docs for YAML). Right?

**Closed by mb21** 2019-08-16 07:49 UTC
Labels: docs

**Comment by jgm** [comment] 2019-08-20 07:03
Right.
