### ISSUE TITLE
Excessive memory usage when converting MD to HTML

### ISSUE THREAD

**Issue by DavorJ** [jgm/pandoc#10426] opened 2024-11-28 18:20 UTC
For simplicity, lets say I have a MD file that embeds large blobs. These blobs can be 500MB for example. Attached is a [MD file (blob.md)](https://github.com/user-attachments/files/17951097/blob.md) with an embedded blob of 18MB, for testing, as larger uploads are not possible on GitHub.

When converted to HTML, it should look like this:
<img src="https://github.com/user-attachments/assets/fc8e1dc1-df0f-456a-ad04-e16ba4c711c3" width="300" />

Generating this HTML takes a few seconds and commits 4GB of memory.
<img src="https://github.com/user-attachments/assets/6721592b-2b0b-43b4-99bc-effd9adc761f" width="300" />

Double the size of the MD, and you will at least double the required memory. 40MB MD file commits about 10GB of memory, etc. This seems quite disproportional: the MD already has the blob BASE64 encoded in a string, and all that is required is to copy-paste it into a HTML. **So what is causing the excessive memory use?**

The issues seems to be when using the `--embed-resources` argument:

```bash
pandoc blob.md --to html4 --output blob.html --from markdown # completes instantly with no RAM overhead.
pandoc blob.md --to html4 --output blob.html --from markdown --embed-resources # requires at least 4GB of RAM.
pandoc blob.md --to html4 --output blob.html --from markdown --standalone # instant but should be equivalent?!?
```

Version of pandoc used: `3.5` on Windows 10.

<details><summary>PS You can create the MD file with Rmarkdown like this</summary>

```
---
title: "Test Blob"
output: 
  flexdashboard::flex_dashboard:
---

# Page 1

## Row

### Column 1

´´´{r, echo=FALSE}
set.seed(2024)
blob <- serialize(sample.int(2^31, size = 18*1024^2/8), connection = NULL)
saveRDS(blob, "./blob.dmp", compress = FALSE)
downloadthis::download_file("./blob.dmp")
´´´
```` 
</details>

**Comment by silby** [comment] 2024-11-28 19:38
Discussed here https://github.com/jgm/pandoc/issues/10075

**Comment by jgm** [comment] 2024-11-29 14:46
Closing as a duplicate of #10075. The problem is with an inefficient URI parser in network-uri.  The patches I submitted to network-uri should help somewhat, but they haven't made it into a released version yet (the last release is from 2022).

**Closed by jgm** 2024-11-29 14:46 UTC
Labels: bug

**Comment by DavorJ** [comment] 2025-03-17 19:04
@jgm, I just tested [v3.6.4](https://github.com/jgm/pandoc/releases/tag/3.6.4) and I have exactly the same memory usage as with [v3.5](https://github.com/jgm/pandoc/releases/tag/3.5). As far as I see, your commits are included in v3.6.4, and I was expecting at least some minor improvement in memory use?

**Comment by silby** [comment] 2025-03-17 19:22
Oh this is partly my bad for not looking at your test file in the first place. I don't think the thing you're doing would be affected by the work I investigated and jgm finished to close #10075.

Note that `--standalone` doesn't actually imply `--embed-resources`. `--self-contained` (deprecated) does. So your first and third command lines are instant b/c all that is happening to your raw block when you run pandoc on the example document is it's getting copied to the output without modification.

What `--embed-resources` ultimately does is call `makeSelfContained` on the about-to-be-output HTML, which parses, modifies, and rerenders the output using TagSoup. [As I noticed](https://github.com/jgm/pandoc/issues/10075#issuecomment-2510290619), TagSoup is also guilty of bad behavior when presented with long URIs, and none of the work under #10075 would mitigate that in this scenario.

**Comment by jgm** [comment] 2025-03-17 23:43
It would be great to figure out why tagsoup is using so much memory and fix this!
Alternatively, we could try to soup up a verison of `html-parse` that has source positions.
Either of these would be a great project for someone -- but I'm unlikely to take it on any time soon myself.
