### ISSUE TITLE
Way to convert markdown ==highlighting== as highlighting in .docx or .odt files

### ISSUE THREAD

**Issue by ReaderGuy42** [jgm/pandoc#7743] opened 2021-12-09 16:57 UTC
**Describe your proposed improvement and the problem it solves.**
As discussed [here](https://groups.google.com/g/pandoc-discuss/c/C-OP94sfxAI) I'm looking for a way to have markdown ==highlighting== done with double '=' convert to font highlighting in Word or Libreoffice Writer files. This does not appear to be standard practice yet, but this mode of highlighting is used at least in Obsidian.md and I would guess some other markdown editor.

So from what I understand you'd need to implement a way for pandoc to interpret (?) the '==' as a marker for highlighting and then have it convert this to a way that .docx or .odt files can understand it?

**Describe alternatives you've considered.**
Markdown bold and italics with asterisks ('*' or '**') work well when converting a .md file to a .docx but I use a lot of highlighting in my markdown so it would be handy to be able to convert that to .docx files as well, without having to manually go through the file and replace all the ==highlighting== to something in Word.

Thanks :)

**Comment by jgm** [comment] 2021-12-09 17:15
Can you link to documentation of this syntax?  If it is widely enough used, we could consider adding an extension for it.

**Comment by ReaderGuy42** [comment] 2021-12-09 19:51
Sure, in the Google discussion linked above, someone mentioned this [site discussing highlighting](https://www.markdownguide.org/extended-syntax/#highlight) and [this discussion here](https://talk.commonmark.org/t/highlighting-text-with-the-mark-element/840).
Thanks :)

**Comment by ReaderGuy42** [comment] 2021-12-15 10:09
I'll look into that thanks. But is that easier than adding something like that in pandoc? I have no idea how to do either of those, just curious :)

**Comment by iandol** [comment] 2021-12-15 11:12
I’m not a pandoc developer, just another end user. I suppose if this syntax was very common or added to one of the existing markdown variants that pandoc already supports it would make sense to add it to pandoc, but there are so many conflicting variants adding extensions for everything would be very unwieldly and increase the maintenance costs. Pandoc has filters and now even custom readers to enable flexible input parsing. I suppose it is up to the developers whether a == to <mark> / highlight extension would be worth it given how prevalent it is amongst markdown producers…

**Comment by alxnbl** [comment] 2022-01-02 14:06
Hi, I use pandoc as part of a tool that exports MS OneNote pages into mardown by converting DocX files into markdown. I would be very interested by a solution to support ==HighLight== syntax during DocX to Md conversion.

**Comment by ReaderGuy42** [comment] 2022-01-17 12:48
Have there been any updates on this?

**Comment by tarleb** [comment] 2022-07-16 09:10
Filter that emulates the `==highlight==` syntax, as suggested by @iandol: https://gist.github.com/tarleb/a0646da1834318d4f71a780edaf9f870
You'll just need to adjust the `markup_inlines` function to return `pandoc.Span(inlines, {['custom-style']='highlight'}`.

**Comment by ReaderGuy42** [comment] 2022-07-16 14:34
Thanks! What exactly would I do with the code? I don't understand much of anything about programming, so I'm not sure how to use the script.

**Comment by tarleb** [comment] 2022-07-16 15:45
Save the code to a file `highlight.lua` next to the Markdown file, then pass that file to pandoc by adding to your command line `--lua-filter=highlight.lua`.

**Comment by ReaderGuy42** [comment] 2022-07-16 16:12
OK, I have that set up now, but I don't think it's working. Could that have to do with the markup_inlines function you mention? I'm not sure how to change what you say there either. Thanks!

**Comment by alxnbl** [comment] 2022-07-18 08:10
@tarleb : I don't know much about behavior  of pandoc filters so sorry if the question is  dumb. Is there a way to use your filter to convert from docx into markdown ? Thus converting highlighted text in docx into "==text==" format in markdown ? Thanks

**Comment by jgm** [comment] 2022-07-29 00:21
Proposal:

- [ ] add a new (non-default) Markdown extension `highlighting` (or should it be `mark` or `highlight`?)
- [ ] in markdown reader, if this extension is enabled, parse material between `==` as a Span with class `mark` (which is already rendered as `<mark>` in the HTML writer)
- [ ] in markdown writer, if this extension is enabled, render a Span with class `mark` as `==` .. `==`
- [ ] docx writer: handle Span with class `mark` using a special style?
- [ ] latex writer: handle Span with class `mark` using a special macro?
- [ ] org reader/writer: is there an equivalent?

**Comment by saf-dmitry** [comment] 2022-08-10 13:53
@tarleb Would you mind to add your filter to the [Lua filter repository](https://github.com/pandoc/lua-filters), as soon as it will again be possible?

**Comment by saf-dmitry** [comment] 2022-08-10 14:06
@jgm In reStructuredText: handle Span with class `mark` using a special [role](https://docutils.sourceforge.io/docs/ref/rst/roles.html), e.g. `` :mark:`text` ``

**Comment by tarleb** [comment] 2022-08-11 08:11
@saf-dmitry I'm not sure yet if I will maintain the filter in the future, so I'm going to keep it as a gist for now. Please feel free to create a repo for it if you want, it's MIT licensed.

**Comment by Johnson0907** [comment] 2022-11-19 16:14
@jgm Could you add a new Markdown extension to parse `==` .. `==`? It is very necessary for Typora users and Obsidian users. Thanks.

**Comment by owlonewolf** [comment] 2023-02-07 15:57
I had this running with the markdown extension, but when I applied a lua filter (include-files) it seems to override the markdown extension. Sorry if this is a rookie question, but it this intended behaviour? Is there a way to get both the markdown ext and a lua-filter working? The order of flags does not seem to matter. 

cmd code: 
`pandoc -f markdown+mark --lua-filter=include-files.lua "folder\main.md"  --bibliography "zotlibrary.bib" --citeproc --csl "....\Zotero\styles\apa.csl" -s -o pandoc_output.docx`

**Comment by tarleb** [comment] 2023-02-07 16:16
In the filter, make sure that the `pandoc.read` function uses `markdown+mark` as format. Please raise this at https://github.com/pandoc/lua-filters if you have more questions.

**Comment by aminevsaziz** [comment] 2023-03-02 03:50
@tarleb unfortunately this only work for markdown. It would great tool if org format is supported.

**Comment by tarleb** [comment] 2023-03-02 10:48
@aminevsaziz We do (currently) not support custom markup in org. Highlighting in org is therefore out of scope, as org mode has no built-in syntax for highlighting.

**Closed** 2023-03-02 10:48 UTC
Labels: enhancement, format:Markdown

**Comment by aminevsaziz** [comment] 2023-03-02 10:57
> @aminevsaziz We do (currently) not support custom markup in org. Highlighting in org is therefore out of scope, as org mode has no built-in syntax for highlighting.

How about supporting ==..== so that when you export to docx you get text highlighted. Highlighting is emacs is possible with [org-extra-emphasis](https://github.com/QiangF/org-extra-emphasis) but the exporter is the real issue. 
A Standardsyntax of ==..== is good idea.

**Comment by alerque** [comment] 2023-03-02 12:36
@aminevsaziz Unless I'm misunderstanding something Pandoc would be the wrong place to make that change. If you want a standard syntax added to org mode an issue should be opened on whatever project manages the defacto version of that language. I'm sure once support is standardized upstream Pandoc would be able to accommodate the addition. With the exception of Pandoc Flavored Markdown and internal representations like the AST, this repo and tooling are not responsible for setting standard syntax in other languages, only for implementing the ones that exist externally.

**Comment by aminevsaziz** [comment] 2023-03-02 12:44
> @aminevsaziz Unless I'm misunderstanding something Pandoc would be the wrong place to make that change. If you want a standard syntax added to org mode an issue should be opened on whatever project manages the defacto version of that language. I'm sure once support is standardized upstream Pandoc would be able to accommodate the addition. With the exception of Pandoc Flavored Markdown and internal representations like the AST, this repo and tooling are not responsible for setting standard syntax in other languages, only for implementing the ones that exist externally.

Okay 👍🏻
