### ISSUE TITLE
Problems when converting numbered equations in latex to word with pandoc

### ISSUE THREAD

**Issue by Hazel0412** [jgm/pandoc#7070] opened 2021-02-02 10:53 UTC
Latex contents are as follows:

**\documentclass{article}
\usepackage{amsmath}      % for \tag and \eqref macros
\setlength\textwidth{7cm} % just for this example
\begin{document}
\[
1+1=2 \tag{5.23} \label{eq:special}
\]
A cross-reference to equation \eqref{eq:special}.
\end{document}**

Expected result:
<img width="291" alt="Screen Shot 2021-02-02 at 6 46 43 PM" src="https://user-images.githubusercontent.com/34848527/106589464-02638900-6587-11eb-87a3-1618d232437d.png">

The command for converting to word:
**pandoc -s tag_ref.tex -o tag_ref.docx**

The bug reported:

[WARNING] Could not convert TeX math '1+1=2 \tag{5.23} \label{eq:special}', rendering as TeX:
  1+1=2 \tag{5.23} \label{eq:special}
            ^
  unexpected "{"
  expecting "%", "\\label", "\\nonumber" or whitespace

The bug won't show if I delete "\tag{5.23}" which is required in the paper editing, since the equation numbering has been self-defined.

How can I convert successfully while using "\tag{}" as a way of numbering equations?
Thanks!

**Comment by jgm** [comment] 2021-02-02 17:25
As a workaround you might just add this macro definition to your tex file:
```
\renewcommand{\tag}[1]{\quad\text{(#1)}}
```
This won't be perfect but it should at least allow pandoc to compile your document without error.
We don't yet support equation cross-refs very well.

**Comment by tarleb** [comment] 2021-03-13 18:55
I think this is a duplicate of #2851. Closing in favor of that issue.

**Closed by tarleb** 2021-03-13 18:55 UTC
