### ISSUE TITLE
Bug: using mathjax with defaults adds wrong script url [2.10.1]

### ISSUE THREAD

**Issue by gabyx** [jgm/pandoc#6593] opened 2020-08-05 22:47 UTC
Reproduce:

*test.yaml*:
```yaml
html-math-method:
    method: mathjax
```

```shell
echo '$asdasd$' | pandoc -f markdown+tex_math_dollars --standalone --defaults=test.yaml -t html5
```

adds a wrong url
```html
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/" type="text/javascript"></script>
```

**However**:
```shell
echo '$asdasd$' | pandoc -f markdown+tex_math_dollars --standalone --mathjax -t html5
```
adds the correct url `https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js`

**Comment by mb21** [comment] 2020-08-06 08:08
I believe this is fixed in pandoc 2.10

**Comment by gabyx** [comment] 2020-08-06 09:02
Thx.
I will test it.

**Comment by jgm** [comment] 2020-08-06 18:57
I think the issue is still here, if it is an issue.
(Note: triggering mathjax via yaml metadata isn't an officially supported feature; you're relying on some fragile assumptions about how the writers work.)

**Comment by jgm** [comment] 2020-08-06 18:58
Oh, never mind, I see you're using a defaults file. That *should* work, so this is a bug.

**Comment by gabyx** [comment] 2020-08-06 19:10
Still an issue in 2.10.1, yes, tested it.

**Comment by gabyx** [comment] 2020-08-06 19:15
Probably relates to this [line](https://github.com/jgm/pandoc/blob/a5fa55969f1b4afc0ca3e38be50b69c65d43a460/src/Text/Pandoc/Options.hs#L111)?

**Comment by jgm** [comment] 2020-08-06 21:43
Closed by d8ad766d17603784b86fc5c2e1b22864125d04d1

**Closed by jgm** 2020-08-06 21:43 UTC
