### ISSUE TITLE
[Markdown -> PDF] - Header level 4+ is misplaced when followed by a table

### ISSUE THREAD

**Issue by TiBeN** [jgm/pandoc#1658] opened 2014-09-30 11:22 UTC
Using pandoc from official ubuntu repos, v1.12.2.1,

When a header level 4 or higher is followed by a table, it is placed after the table. 
Unless i misunderstund a feature, i suspect a bug.

Here's an example and it's pdf output:

```markdown

# Title 1

  Right     Left     Center     Default 
-------     ------ ----------   -------
     12     12        12            12
                                                                    
## title 2

  Right     Left     Center     Default 
-------     ------ ----------   ------- 
     12     12        12            12 

### Title 3

  Right     Left     Center     Default
-------     ------ ----------   ------- 
     12     12        12       12

#### Title 4

  Right     Left     Center     Default
-------     ------ ----------   -------
     12     12        12            12

#### Title 5
       
  Right     Left     Center     Default 
-------     ------ ----------   -------
     12     12        12            12 

```

![pandoc-bug](https://cloud.githubusercontent.com/assets/910115/4457062/3bd3c024-4892-11e4-9f9b-75303c8f7c53.jpg)

Forgot to mention the command line used: 
```bash
pandoc test.md -o test.pdf
```

**Comment by lierdakil** [comment] 2015-04-17 18:48
I'm thinking on how this should be addressed, and apparently there are three options:

1. Insert empty paragraph before all tables
2. Insert empty paragraphs after all lv. 4-5 headings
3. Find where lv. 4-5 headings are followed by a table and insert `RawBlock (Format "latex") "\\mbox{}"` there.

Thoughts?

**Comment by jgm** [comment] 2015-04-17 19:12
@lierdakil
Could this be fixed by redefining `\paragraph` in the default
template, so it works more like `\subsection`?

There's reason to do that anyway: people are always complaining
about how the level-4 and level-5 headings don't have line breaks
after them in PDF output, and this behavior isn't really consistent
with how other writers work.

**Comment by lierdakil** [comment] 2015-04-17 19:27
@jgm, that would be a variation of (2). Something like this could work:

```latex
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}\\}
```

**Comment by lierdakil** [comment] 2015-04-17 19:28
Note that for lv.5 headings, we need to give `\subparagraph` the same treatment.

**Comment by lierdakil** [comment] 2015-04-17 19:30
I'm a little concerned about labels however, since they would point to paragraph *after* line break.

**Comment by lierdakil** [comment] 2015-04-17 19:37
Sorry about this stream of consciousness, but I tested, and yes, labels pose a problem. Consider

```latex
\paragraph{Title}\mbox{}\\
\label{title}

Text
```

Here, `\label{title}` points to an empty paragraph, so `\ref{title}` will be suppressed by latex (since it doesn't contain any text)

So we'll *have* to implement this in writer -- I really see no other option.

**Comment by lierdakil** [comment] 2015-04-17 19:40
Another way we could handle this is to define `\sectionlevel4` and `\sectionlevel5` with *two* arguments each, accepting text *and* label. This would allow for broader template customization. But that would require changes to writer anyway.

**Comment by jgm** [comment] 2015-04-17 19:46
What about #3 without the `\\`, then?  I don't think that's such a big issue.  Does
```
\paragraph{Title}\mbox{}\label{title}

Text
```
work?

**Comment by jgm** [comment] 2015-04-17 19:49
Oh, never mind.  If we can modify the writer (and why not?) then let's have

```
\paragraph{Title}\label{title}\\

(the table)
```
Would this work? If needed, we could put an mbox before or after the `\\`.

**Comment by lierdakil** [comment] 2015-04-17 19:54
Seems like I was mistaken actually, skimming through stackexchane on TeX. Let me try a couple more ideas -- maybe it *is* possible to limit this to template.

**Comment by lierdakil** [comment] 2015-04-17 20:16
Okay. After a little more reading and testing,

```latex
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
```

(i.e. without `\\`) will work absolutely fine. This works because while `\paragraph` does not interpret next newline as a paragraph break, `\mbox{}` does. So this essentially makes it that `\paragraph` ends up in a paragraph of its own, and `\label` ends up in same paragraph (since there's no newline after `\mbox{}`). Makes sense?

**Comment by lierdakil** [comment] 2015-04-17 20:29
https://github.com/jgm/pandoc-templates/pull/92 should most likely do the trick.

**Closed** 2015-04-18 01:51 UTC
Labels: Minor

**Comment by hugoroy** [comment] 2015-05-03 16:31
FYI it looks like this triggers an error:

! LaTeX Error: \paragraph undefined.

**Comment by lierdakil** [comment] 2015-05-03 16:42
@hugoroy, could you show exactly how did you encounter this error? I.e. input files, pandoc options, etc. It works fine for me.

**Comment by hugoroy** [comment] 2015-05-03 16:49
This specific file was with another class than 'article'. I can't show that specific file because it's confidential.

**Comment by lierdakil** [comment] 2015-05-03 17:14
If a given file is confidential, you could hack together a simple example. But I get what the problem is.
This opens a whole another can of worms then, since heading levels 4-5 are represented as `\paragraph` and `\subparagraph` respectively, and if your documentclass does not have those defined, you are very likely to run into problems. Point taken though, I guess we can add a conditional to this particular snippet.

**Comment by jgm** [comment] 2015-05-03 18:09
+++ Nikolay Yakimov [May 03 15 10:14 ]:
>If a given file is confidential, you could hack together a simple example. But I get what the problem is.
>This opens a whole another can of worms then, since heading levels 4-5 are represented as `\paragraph` and `\subparagraph` respectively, and if your documentclass does not have those defined, you are very likely to run into problems. Point taken though, I guess we can add a conditional to this particular snippet.

Just add definitions of `\paragraph` and `\subparagraph` to your
template or documentclass, and you're good to go.

**Comment by lierdakil** [comment] 2015-05-03 18:10
@jgm that's suboptimal IMO. But I'll create a PR to fix this soon.
