### ISSUE TITLE
Muse reader is very slow

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#4285] opened 2018-01-21 18:15 UTC
I noticed the last time I ran benchmarks that the muse reader is an order of magnitude slower than the other readers.  (Try, for example, converting MANUAL.txt to muse with pandoc, then running the muse reader on the result.)  Running with `--trace` should give some insight into what is happening here.

**Comment by labdsf** [comment] 2018-02-03 17:06
Paragraphs in Muse can be terminated by any block element. When document contains a long list and list items end in paragraphs, the rest of the list is parsed and discarded just to check that paragraph terminates here.

Simple solution would be to check for custom terminators, so pandoc parses a list marker instead of the whole list. I don't really want to do it, because it is error-prone and adding new kinds of lists, tables etc. will require writing more custom terminator parsers, parsing just a list marker or table row.

Partially this problem can be solved by making paragraph parser accept *additional* custom terminators, so, for example, list parser can pass a list item parser down and paragraph terminates by parsing a list item, not the rest of the list. I will need it anyway to parse additional descriptions in definition list items (which can't start a list, so can't terminate paragraphs now):
```
 First item :: first definition
            :: second definition
```
But it does not solve the whole problem. For example, if an ordered list is immediately followed by bullet list, the whole bullet list will be parsed to check that lat ordered list item terminates.

Better solution would be to somehow pass the result of parsing back to the corresponding level (there can be infinitely many in case of nested lists), but I don't see how I can restructure parser to make it possible. Any suggestions of parsers solving this problem I can look at?

**Comment by jgm** [comment] 2018-02-03 19:22
In the Markdown reader I use a guard in the 'endline' parser
to ensure that we stop parsing paragraph lines if the next
line, e.g. starts a list.

**Comment by labdsf** [comment] 2018-02-03 20:04
@jgm I looked at the code, that is simply what I suggested in the second paragraph.

What I really need is some sort of `manyTill parser end` which lets `parser` check for `end` (e.g., let paragraph parser check for end on each newline) and returns the result of parsing `end` to the caller (so it does not have to parse it again).

**Comment by labdsf** [comment] 2018-02-03 21:00
I found someone implemented the `manyTill` variant I talk about, called `manyTillTake`: https://www.reddit.com/r/haskell/comments/590ylp/trouble_using_parsec_using_trylookahead/

Now the problem is to pass its result to the correct level.

What I want to implement is a `listContinuationTill end` which tries to parse indented blocks until the `end`. Indented block itself can be a paragraph, which is parsed by `paraTill (end <|> parseBlock)`. Paragraph can either end because it hits `parseBlock`, in which case the result should be consumed by `listContinuationTill` or it hits `end`, in which case the result should be passed to the upper level by `listContinuationTill`.

So instead of `end <|> parseBlock` I need something like `Text.Megaparsec.eitherP` to combine `end` and `parseBlock` results into Either. Left would be passed upwards, and Right would be consumed.

I wonder if someone already implemented something like this as a library.

**Comment by labdsf** [comment] 2018-02-05 22:52
Started to fix it in https://github.com/jgm/pandoc/commit/fe5fd12812e657c720cc2c2ddff314ad7c1547fd

The goal is to remove `parseBlock` and `para` completely.

**Comment by labdsf** [comment] 2018-02-12 14:35
Fixed in https://github.com/jgm/pandoc/commit/8aed3652c2cb1811aa5685bbeb7c97b097b2eed4

**Closed by labdsf** 2018-02-12 14:35 UTC
Labels: format:Muse, performance, reader
