### ISSUE TITLE
Table of contents not generated for DOCX

### ISSUE THREAD

**Issue by AllThatIsTheCase** [jgm/pandoc#458] opened 2012-03-25 16:42 UTC
What steps will reproduce the problem?
1. Create a Markdown file with headings
2. Use pandoc --toc to create DOCX file

*What is the expected output? What do you see instead?*
I expect a table of contents at the top; I see none. When I render to PDF, the TOC is present.

*What version of the product are you using? On what operating system?*
1.9.1.2

**Comment by lierdakil** [comment] 2015-03-29 06:35
Okay, since #2014 and #1968 are merged, it's now possible to implement `--toc` with relatively little effort. #2037 does exactly that.

**Comment by tolot27** [comment] 2015-03-29 10:00
Great, thanks!

It should be noted/documented that this implementation supports `--toc-depth` as well.

I would also suggest moving it after abstract rather than before. That is the typical order for thesis, dissertation and scientific/technical articles. See also http://en.wikipedia.org/wiki/Table_of_contents.
There are only few other cases where the TOC is before the abstract. In most cases it is after the abstract.

Issue #1612 suggests for the TOC placement.

**Comment by ousia** [comment] 2015-03-29 10:30
> Issue #1612 suggests for the TOC placement.

@tolot27, I suggest to comment in #1612, since that issue was marked as _More discussion needed_.

**Comment by lierdakil** [comment] 2015-03-29 10:43
Right. I'll move it to after abstract then. I'm reluctant to implement suggestions from #1612 here, since
a) it behaves quite differently from other writers 
b) there is an ongoing discussion on syntax

**Comment by tolot27** [comment] 2015-03-29 11:01
My comment https://github.com/jgm/pandoc/issues/458#issuecomment-87384315 was related to this issue here, IMHO, because it was about the hardcoded placment (the defaults).
I've just referenced #1612 again and will continue to discuss configurable placement of TOC there.
@lierdakil: You are right not to implement #1612 here because it #1612 just depends on this issue.

**Comment by jgm** [comment] 2015-03-29 22:11
Closed by #2037.

**Closed by jgm** 2015-03-29 22:11 UTC
Labels: enhancement, Major

**Comment by brainchild0** [comment] 2019-02-01 22:46
Although activity ended some time ago on this issue, I am unable to find documentation on the current expected behavior.  Presently, I use a reference document featuring a table of contents.  When I open the generated document, the table of contents is visible but has no content.  It must be updated manually. 

Is the expected behavior that the table of contents updates automatically when the document is opened?

Am I experiencing a limitation of my application, LibreWriter, compared to Microsoft Word, which would behave differently?

Is documentation available on this subject?

**Comment by jgm** [comment] 2019-02-01 23:43
brainchild0 <notifications@github.com> writes:

> Although activity ended some time ago on this issue, I am unable to find documentation on the current expected behavior.  Presently, I use a reference document featuring a table of contents.  When I open the generated document, the table of contents is visible but has no content.  It must be updated manually. 

Yes, that's as described in the thread above.  Note
this linked comment:
https://github.com/jgm/pandoc/issues/458#issuecomment-58720613

I'm sorry, that's the best we can do; there seems to
be no way to make it update the fields without manual
intervention, as far as I can see.

**Comment by brainchild0** [comment] 2019-02-02 01:37
In the earlier comments, it was implied that as long as the document was opened once, the application would detect the _dirty_ flag and regenerate the index.  Reading down the chain of comments, I am not finding when, if ever, it was determined otherwise.  Indeed, it is sensible that the application would behave as such, since if a document were generated interactively, as most are, then the index would need to be regenerated whenever it became obsolete.  I am confused about why I the manual step is required.

 Would I be seeing different behavior if were using Microsoft Office, not Libre Office?

**Comment by brainchild0** [comment] 2019-02-03 02:37
I confirmed that it is a known issue that LibreOffice never updates indices unless the update feature is explicitly invoked.  I found the report for the issue in the tracker for LibreOffice, apparently unresolved after being reported 15 years ago.

**Comment by nicola-lunghi** [comment] 2022-08-15 09:11
Hi,
I was wondering if it would be complicated to add support for lot, lof in docx / odt
the toc works nice in the current version

**Comment by nicola-lunghi** [comment] 2022-08-15 10:57
Ok something similar to this should work

```
makeLOF :: (PandocMonad m) => WriterOptions -> WS m [Element]
makeLOF opts = do
  let lofCmd = "TOC \\h \\z \\c \"Figure\""
  return
    [
      mknode "w:p" [] [
        mknode "w:pPr" [] [
          mknode "w:pStyle" [("w:val","TableofFigures")] (),
        ], -- w:pPr
        mknode "w:r" [] [
          mknode "w:fldChar" [("w:fldCharType","begin"),("w:dirty","true")] (),
          mknode "w:instrText" [("xml:space","preserve")] lofCmd,
          mknode "w:fldChar" [("w:fldCharType","separate")] (),
          mknode "w:fldChar" [("w:fldCharType","end")] ()
          ] -- w:r
      ] -- w:p
    ]
```

Now I need someone that knows haskell to verify it and add the missing bits @tolot27 ??

taken the xml from the examples here and adapted the TOC code

http://www.ericwhite.com/blog/exploring-tables-of-contents-in-open-xml-wordprocessingml-documents-part-2/

```
        public static void AddTof(WordprocessingDocument doc, XElement addBefore, string switches, int? rightTabPos)
...
            string xmlString =
@"<w:p xmlns:w='http://schemas.openxmlformats.org/wordprocessingml/2006/main'>
  <w:pPr>
    <w:pStyle w:val='TableofFigures'/>
    <w:tabs>
      <w:tab w:val='right' w:leader='dot' w:pos='{0}'/>
    </w:tabs>
    <w:rPr>
      <w:noProof/>
    </w:rPr>
  </w:pPr>
  <w:r>
    <w:fldChar w:fldCharType='begin' dirty='true'/>
    <w:instrText xml:space='preserve'> {1} </w:instrText>
    <w:fldChar w:fldCharType='separate'/>
    <w:fldChar w:fldCharType='end'/>
  </w:r>
</w:p>";
```
Note that to get a List of Tables word seems to do the same but with 
```
  let lotCmd = "TOC \\h \\z \\c \"Table\""
```
instead of 
```
  let lofCmd = "TOC \\h \\z \\c \"Figure\""
```
I think it simply replaces Figures and Table -> probably could be added as an input to the function

**Comment by agusmba** [comment] 2022-08-24 07:35
@nicola-lunghi  you'd get more visibility opening a new feature request instead of commenting on an old closed issue. (just my 2c)

**Comment by nicola-lunghi** [comment] 2022-08-24 09:34
I've opened https://github.com/jgm/pandoc/issues/8245
