### ISSUE TITLE
Not reading <title> from docbook

### ISSUE THREAD

**Issue by martinfowler** [jgm/pandoc#4800] opened 2018-07-28 20:30 UTC
Pandoc seems to be ignoring <title> elements when reading docbook.

Given this input

     <book xmlns = 'http://docbook.org/ns/docbook'>
       <title>The Title</title>
       <para>Lorem Ipsum</para>
     </book>

If I run pandoc with `pandoc -s -f docbook -t html`

I get the following warning

    [WARNING] This document format requires a nonempty <title> element.
      Please specify either 'title' or 'pagetitle' in the metadata.
      Falling back to 'Untitled'

And the output doesn't include any title

    <!DOCTYPE html>
    <html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
    <head>
      <meta charset="utf-8" />
      <meta name="generator" content="pandoc" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
      <title>Untitled</title>
      <style type="text/css">
          code{white-space: pre-wrap;}
          span.smallcaps{font-variant: small-caps;}
          span.underline{text-decoration: underline;}
          div.column{display: inline-block; vertical-align: top; width: 50%;}
      </style>
      
    </head>
    <body>
    <p>Lorem Ipsum</p>
    </body>
     #</html>

I would expect "The Title" to appear in the head's <title> tag and for the title to appear as a heading in the body. 

The same problem occurs if I use <article> rather than book. However if I use <section> I get the same warning, "Untitled" in the <head> but I do get "The Title" inside `<h1>` in the body.

I'm running pandoc version 2.2.2.1 on MacOs 10.13.6 installed from Homebrew

**Comment by mb21** [comment] 2018-07-29 10:16
I think the problem is that the `checkInMeta` function only adds the metadata if the `dbAcceptsMeta` field in the state is `True`. And we only set it to true if we are in an element like `<info>`, but not `<book>`, or `<article>`, etc.

Weirdly, the [title](https://tdg.docbook.org/tdg/5.0/title.html) can have parent `<book>` etc, while e.g. the [author](https://tdg.docbook.org/tdg/5.0/author.html) element cannot.

**Comment by jgm** [comment] 2018-07-30 18:02
It will work if inside a bookinfo or info element.

I didn't realize that a title element could go
directly inside book, but it seems that book can
contain title and subtitle directly.  (And so can
article.)  So the reader should be modified to
allow this.

**Comment by jgm** [comment] 2018-07-30 21:40
Closed by 78dca68a0a484f3230535e91a98a30cb8090aee8

**Closed by jgm** 2018-07-30 21:40 UTC
Labels: format:DocBook, reader
