### ISSUE TITLE
html to docx/rtf conversion issue.

### ISSUE THREAD

**Issue by Nilay-git** [jgm/pandoc#2080] opened 2015-04-14 10:17 UTC
Hello,

I tried to convert an html file to .docx and .rtf file.
The command is used is: 

pandoc -s input.html -o output.docx

This command generates correctly formatted docx while I used '<strong></strong>' of '<em></em>'. But If I use any inline css like 'color', 'font-size', then the doc file is generated without those styles. Same happens in case of .rtf as well. Do I have to use any other command to include css? Can Anyone help me on this?

**Comment by jgm** [comment] 2015-04-14 16:35
Pandoc will correctly convert the structure of the document, but it pays no attention to CSS.  So, this is out of scope, not a bug.

**Closed by jgm** 2015-04-14 16:35 UTC
