### ISSUE TITLE
Add Pod docs files and Raku lang, please.

### ISSUE THREAD

**Issue by RustemB** [jgm/pandoc#6488] opened 2020-06-29 07:56 UTC
Can you add syntax for https://raku.org/ ?

And converting for
https://docs.raku.org/language/pod (or https://perldoc.perl.org/perlpod.html)

**Comment by tarleb** [comment] 2020-06-29 11:33
Syntax definitions are imported from the KDE project (via `[skylighting](https://github.com/jgm/skylighting)). Best to direct the request to them: https://invent.kde.org/frameworks/syntax-highlighting#how-to-contribute

There is issue #176 for Pod support already; closing in favor of that issue.

**Closed by tarleb** 2020-06-29 11:33 UTC

**Comment by jubilatious1** [comment] 2023-07-24 16:16
Please Reopen!

Raku (a.k.a. Perl6) has a different documentation format called POD6 (alias name "Rakudoc").

See: https://design.raku.org/S26.html

And: https://github.com/Raku/problem-solving/issues/375#issue-1784755272

So this request isn't a duplicate of #176 which is asking for Perl(5) POD support.

Thank you!

**Comment by jgm** [comment] 2023-07-25 14:49
Sure - please open a new issue on jgm/skylighting, as noted above.
