### ISSUE TITLE
The same docx convert to gfm got different result

### ISSUE THREAD

**Issue by rickywu** [jgm/pandoc#5400] opened 2019-03-28 11:22 UTC
I have one multiline table in docx and use gfm format output, the original file got table like this:

```
<table>
<tbody>
<tr class="odd">
<td><strong>要素</strong></td>
<td><strong>生成方式</strong></td>
<td><strong>说明</strong></td>
</tr>
<tr class="even">
<td>需求编号</td>
<td>自动生成</td>
<td>与xxx生成需求编号保持一致或产生对应关系，建议与xxx编号规则一致。</td>
</tr>
<tr class="odd">
<td>需求类别</td>
<td>下拉选择</td>
<td>选项：项目需求、系统维护需求</td>
</tr>
<tr class="even">
<td>需求模板</td>
<td>下拉选择</td>
<td><p>需求类别选择项目需求时，选项：业务原始需求、</p>
<p>建设需求书、业务需求书、需求规格说明书（项目）</p>
<p>需求类别选择任务需求时，选项：业务原始需求、需求规格说明书（系统维护）</p></td>
</tr>
<tr class="odd">
<td>需求名称</td>
<td>手输</td>
<td></td>
</tr>
<tr class="even">
<td>需求提出部门</td>
<td>选择</td>
<td>业务部门</td>
</tr>
<tr class="odd">
<td>需求负责人</td>
<td>手输</td>
<td>姓名、联系方式</td>
</tr>
<tr class="even">
<td>受理人</td>
<td>手输</td>
<td>业务条线、姓名、联系方式</td>
</tr>
</tbody>
</table>
```

BUT if I modify the docx and keep the multiline table the same, the table becomes:
```
<table>
<thead>
<tr class="header">
<th><strong>要素</strong></th>
<th><strong>生成方式</strong></th>
<th><strong>说明</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>需求编号</td>
<td>自动生成</td>
<td>与xxx生成需求编号保持一致或产生对应关系，建议与xxx编号规则一致。</td>
</tr>
<tr class="even">
<td>需求类别</td>
<td>下拉选择</td>
<td>选项：项目需求、系统维护需求</td>
</tr>
<tr class="odd">
<td>需求模板</td>
<td>下拉选择</td>
<td><p>需求类别选择项目需求时，选项：业务原始需求、</p>
<p>建设需求书、业务需求书、需求规格说明书（项目）</p>
<p>需求类别选择任务需求时，选项：业务原始需求、需求规格说明书（系统维护）</p></td>
</tr>
<tr class="even">
<td>需求名称</td>
<td>手输</td>
<td></td>
</tr>
<tr class="odd">
<td>需求提出部门</td>
<td>选择</td>
<td>各业务部门</td>
</tr>
<tr class="even">
<td>需求负责人</td>
<td>手输</td>
<td>姓名、联系方式</td>
</tr>
<tr class="odd">
<td>受理人</td>
<td>手输</td>
<td>业务条线、姓名、联系方式</td>
</tr>
</tbody>
</table>
```

**Comment by mb21** [comment] 2019-03-28 11:52
Thank you for submitting a bug report. However, we cannot improve pandoc or help you unless you give us all of the following information:

* the pandoc version (check using `pandoc -v` and try to reproduce the bug with the latest released version of pandoc, or even better: the development version or [nightly build](https://github.com/pandoc-extras/pandoc-nightly).)
* the exact command line used
* the exact input used
* the output received
* the output you expected instead

A small test case (just a few lines) is ideal.  If your input is large, try to whittle it down to a **minimum working example**. For binary input formats like docx, you should attach the minimum sample file.

Finally, ask questions on [pandoc-discuss](http://groups.google.com/group/pandoc-discuss) and read the [User's Guide](http://pandoc.org/MANUAL.html).

**Comment by rickywu** [comment] 2019-03-29 02:37
pandoc -v
```
pandoc 2.7.1
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
```

command:
    pandoc testRowsTable.docx -f docx -t gfm+pipe_tables+gfm_auto_identifiers+shortcut_reference_links --atx-headers --wrap=none --extract-media="" -o out.md

Input: 
[testRowsTable.docx](https://github.com/jgm/pandoc/files/3020850/testRowsTable.docx)

WPS saved docx output from pandoc:
```
1.转换为Markdown表头位置未正确显示;

|          |          |               |           |
| -------- | -------- | ------------- | --------- |
| **一级目录** | **二级目录** | **三级目录**      | **备注**    |
| 业务需求     | 项目需求     | 业务原始需求        |           |
|          |          | 建设需求书         |           |
|          |          | 业务需求书         |           |
|          |          | 需求规格说明书（项目）   |           |
|          | 系统维护需求   | 业务原始需求        |           |
|          |          | 需求规格说明书（系统维护） |           |
| 技术需求     |          |               | 暂无条目化管理需求 |
| 缺陷       |          |               | 暂无条目化管理需求 |

2.表格格式丢失,未能正常显示表格;

<table>
<tbody>
<tr class="odd">
<td><strong>要素</strong></td>
<td><strong>生成方式</strong></td>
<td><strong>说明</strong></td>
</tr>
<tr class="even">
<td>需求编号</td>
<td>自动生成</td>
<td>与生成需求编号保持一致或产生对应关系建议编号规则一致。</td>
</tr>
<tr class="odd">
<td>需求模板</td>
<td>下拉选择</td>
<td><p>需求类别选择项目需求时，选项：业务原始需求、</p>
<p>建设需求书、业务需求书、需求规格说明书（项目）</p>
<p>需求类别选择任务需求时，选项：业务原始需求、需求规格说明书（系统维护）</p></td>
</tr>
<tr class="even">
<td>需求名称</td>
<td>手输</td>
<td></td>
</tr>
<tr class="odd">
<td>需求提出部门</td>
<td>选择</td>
<td>各业务部门</td>
</tr>
<tr class="even">
<td>需求负责人</td>
<td>手输</td>
<td>姓名、联系方式</td>
</tr>
<tr class="odd">
<td>受理人</td>
<td>手输</td>
<td>业务条线、姓名、联系方式</td>
</tr>
</tbody>
</table>
```

Office Word 2016 saved docx output from pandoc which is correct:
```
1.转换为Markdown表头位置未正确显示;

| **一级目录** | **二级目录** | **三级目录**      | **备注**    |
| -------- | -------- | ------------- | --------- |
| 业务需求     | 项目需求     | 业务原始需求        |           |
|          |          | 建设需求书         |           |
|          |          | 业务需求书         |           |
|          |          | 需求规格说明书（项目）   |           |
|          | 系统维护需求   | 业务原始需求        |           |
|          |          | 需求规格说明书（系统维护） |           |
| 技术需求     |          |               | 暂无条目化管理需求 |
| 缺陷       |          |               | 暂无条目化管理需求 |

2.表格格式丢失,未能正常显示表格;

<table>
<thead>
<tr class="header">
<th><strong>要素</strong></th>
<th><strong>生成方式</strong></th>
<th><strong>说明</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>需求编号</td>
<td>自动生成</td>
<td>与生成需求编号保持一致或产生对应关系建议编号规则一致。</td>
</tr>
<tr class="even">
<td>需求模板</td>
<td>下拉选择</td>
<td><p>需求类别选择项目需求时，选项：业务原始需求、</p>
<p>建设需求书、业务需求书、需求规格说明书（项目）</p>
<p>需求类别选择任务需求时，选项：业务原始需求、需求规格说明书（系统维护）</p></td>
</tr>
<tr class="odd">
<td>需求名称</td>
<td>手输</td>
<td></td>
</tr>
<tr class="even">
<td>需求提出部门</td>
<td>选择</td>
<td>各业务部门</td>
</tr>
<tr class="odd">
<td>需求负责人</td>
<td>手输</td>
<td>姓名、联系方式</td>
</tr>
<tr class="even">
<td>受理人</td>
<td>手输</td>
<td>业务条线、姓名、联系方式</td>
</tr>
</tbody>
</table>
```

Seems it's an office 2013 version compatibility problem?

**Comment by mb21** [comment] 2019-03-29 08:08
So the issue is that when converting `testRowsTable.docx` to markdown, the first row of the table is not a header row, or...?

**Comment by rickywu** [comment] 2019-03-29 14:25
@mb21
Two issues:
1. table one's header splitter location is not correct
3. table two not include thread tag and header class

**Comment by mb21** [comment] 2019-03-29 14:39
1. but that's simply because it's not a header in the docx input, right?
2. pandoc doesn't support fancy things like classes on tables, see #1024

**Comment by rickywu** [comment] 2019-03-29 15:11
1. No, it exactly is a header in the docx
2. Why Word saved docx's output include thread tag but Libre Office not

**Comment by jkr** [comment] 2019-03-30 23:08
So the issue is that docx produced from LibreOffice doesn't work as expected, but docx produced by MS Word does work as expected? 

We only aim to cover Word's docx, which we treat as the reference implementation of the standard.

**Comment by rickywu** [comment] 2019-03-31 11:41
Yes, so you don't have any plan to support LibreOffice?
If so, we can close.

**Comment by jkr** [comment] 2019-03-31 15:13
We support `.odt` files written by LibreOffice, and `.docx` files produced by Word.  So, yes, closing.

**Closed by jkr** 2019-03-31 15:13 UTC

**Comment by rickywu** [comment] 2019-04-01 00:57
@jkr, But I tried use LibreOffice save as odt file and still has this problem?

**Comment by jkr** [comment] 2019-04-02 13:41
@rickywu: If the issue is about ODT files created with LibreOffice, then it might be a limitation of the ODT reader. You should file a different bug for that (it really doesn't have anything to do with Word or docx). When you do, make sure to attach a minimal ODT file that demonstrates the issue. 

It might be easier for some bug-fixers to help as well if your example used a latin script (English would probably be the safest, since it's the dev language of pandoc). Pandoc itself tries to be language-agnostic, but it might be hard for some devs to address your problem if their keyboards aren't set up for the writing system.
