### ISSUE TITLE
Request for markdown writer to support output of shortcut reference links

### ISSUE THREAD

**Issue by binaryphile** [jgm/pandoc#1977] opened 2015-02-27 21:58 UTC
There is an existing option for outputting reference links, --reference-links.  However, it only generates [collapsed reference links](http://spec.commonmark.org/0.17/#collapsed-reference-link).

I would like to be able to generate shortcut reference links which do not include the empty trailing square brackets [].  To my eyes the empty brackets are visual clutter and unnecessary.

Could there be a separate command-line switch which adds support for [shortcut reference links](http://spec.commonmark.org/0.17/#shortcut-reference-link)?  Such an option might be --shortcut-reference-links.

Thanks for any consideration.

**Comment by jgm** [comment] 2015-02-28 23:34
Instead of adding another option, I like the idea of adding
a "shortcut_reference_links" Markdown extension, and
enabling it in both the reader and the writer.  IF the
extension is enabled (which would be the default), the
writer could use a shortcut reference link unless doing so
would cause problems (e.g. because it was followed
immediately by another link).

Just about every Markdown processor since Markdown.pl 1.0.1
supports the shortcut format.

+++ Ted Lilley [Feb 27 15 13:58 ]:

**Comment by wcaleb** [comment] 2015-03-01 02:32
Would such a default mean that words in brackets (non-links) would always have to be backslash-escaped? Or would they only have to be escaped if a link reference for the bracketed words existed somewhere in the file?

**Comment by binaryphile** [comment] 2015-03-01 05:02
Words in brackets only qualify as shortcut reference links if there is a matching link definition at the bottom of the page.  If not, the words in brackets aren't intended to be a link and are then rendered normally.

**Comment by wcaleb** [comment] 2015-03-01 14:55
Thanks for the clarification.

**Comment by zudov** [comment] 2015-03-01 22:13
Just wanted to mention that markdown reader already supports shortcut references. 

Of course, as @jgm said the option also should be added to the reader. When the option is disabled reader shouldn't parse the example below as a reference, am I right? 

```bash
zudov@x200 ~/ $ cat | pandoc -t html
[foo]

[foo]: /foo "bar"

<p><a href="/foo" title="bar">foo</a></p>
zudov@x200 ~/ $ 
```

**Comment by zudov** [comment] 2015-03-01 22:15
By the way, is anyone working on this?

**Comment by mpickering** [comment] 2015-03-01 22:20
Yes and no.

**Comment by wcaleb** [comment] 2015-03-02 01:26
@mpickering If it's more "no" than "yes," I'd like to try my hand at this ...

**Comment by zudov** [comment] 2015-03-02 02:35
@wcaleb I am sorry to say that I kind of started working on this. If you would like to join, or code-review, or tell that I am doing it wrong :), or compete with alternative implementation you are mostly welcome.

I've pushed what I have so far https://github.com/zudov/pandoc/commit/bc0f0dac86d107ada441272872f36731488771b5 . And at the moment I am thinking on how to figure out if shortcutting a reference would cause problems.

**Comment by wcaleb** [comment] 2015-03-02 02:45
@zudov No worries. This is about as far as I had gotten, too (though you have done more with the tests).

But I'm not sure I understand why you've added a `WriterOption`. Why not just check to see if the `Ext_shortcut_reference_links` is enabled with `if isEnabled Ext_shortcut_ref_links opts`? I took @jgm to be saying that he'd prefer this just to be an extension (set by default as a pandoc extension) instead of an option.

Like you, I'm also stuck on how and where to have the writer check if a `Link` is followed immediately by another `Link`, as that does create a problem.

Incidentally, this probably needs a separate issue, but in playing around with this, I noticed that the reader does not quite handle [Example 458](http://spec.commonmark.org/0.17/#example-458) and 459 according to the CommonMark standard. Unless I'm missing something.

**Comment by zudov** [comment] 2015-03-02 03:01
> why you've added a WriterOption

You are right, it's not needed. I've just added it before I realized that it's not needed. Was going to remove it.

> I'm also stuck on how and where to have the writer check if a Link is followed immediately by another Link

One hackish solution I am going to try is to traversing over the list of inlines and recording identifiers of those references that aren't shortcutable, not sure how would it work out.

> the reader does not quite handle Example 458 and 459

It doesn't. I am not sure if there is a priority to support CommonMark with current markdown reader (last time I checked around 200 test cases were failing with default pandoc settings), but it seems reasonable to support that  kind of cases.

**Comment by zudov** [comment] 2015-03-02 05:07
@wcaleb I've made a prototype of one way to handle our problem https://github.com/jgm/pandoc/commit/b0b38229962a7ea39474ab46754d535462ca87ec

Basically I've made it so that `inlineToMarkdown` explicitly traverses over list of inlines instead of being a mapping function. These are lots of changes, but they are quite simple. Can be expanded with more rules for detecting unshortcutable links.
It's quite drafty now, needs to be finalized.

That solution isn't very ugly, but adds quite a lot of verbosity which isn't so nice. I should try some other ways.

**Comment by mpickering** [comment] 2015-03-02 14:53
I think the best way would be to do the following.

1. Introduce a new datatype `InternalState` which has a single field which is true if the current item is followed by a link.
2. Replace the `State WriterOptions Doc` with `StateT WriterOptions (Reader InternalState) Doc` and give this a type synonym (maybe `MWriter`)
3. Replace `inlinesToMarkdown` with something like 

```
inlinesToMarkdown xs = zipWithM combine xs (tail xs ++ [Str ""])

combine :: Inline -> Inline -> MWriter Doc
combine l@(Link _ _) (Link _ _) = local setFollowedByLink (inlineToMarkdown l)
combine el _ = inlineToMarkdown el
```

That seems like it would be a lot cleaner?

**Comment by wcaleb** [comment] 2015-03-02 15:11
@mpickering @zudov 

Here's what I did: https://github.com/wcaleb/pandoc/commit/e0dad88440b79561ce96418b2f812b200213cf8a. My implementation is modeled on the avoidBadWraps function in `inlineListToMarkdown` and basically adds a space between adjacent links in the AST. This passes basic tests, but do you see any problems with it?

**Comment by wcaleb** [comment] 2015-03-02 15:16
(NB: one problem I still need to fix is that in addition to adjacent links, I'm also checking for link followed by opening bracket, when  I guess what I really should be checking for an open bracket, some string, and then a closed bracket.)

**Comment by wcaleb** [comment] 2015-03-02 16:06
I'm also now seeing, though, that my implementation might not be exactly the feature desired, since by adding a `Space` it's more interventionist. If the goal is to have adjacent links keep the trailing empty brackets, even when the shortcut extension is enabled, then I'd have to adjust so that those are added instead of a space.

**Comment by jgm** [comment] 2015-03-02 17:26
Also, adding a space won't suffice.  Reference links can have a space
between the two bracketed parts.
http://johnmacfarlane.net/babelmark2/?normalize=1&text=%5Bhi%5D+%5Bfoo%5D%0A%0A%5Bfoo%5D%3A+%2Furl%0A

**Comment by zudov** [comment] 2015-03-02 17:27
@mpickering Yes, that seems much cleaner and expandable with additional rules. I would add it this evening.

**Comment by zudov** [comment] 2015-03-02 22:14
@mpckering After playing with this idea, I am not exactly sure about it. The problem is that if I change the type of [`inlineToMarkdown`](https://github.com/jgm/pandoc/blob/2678edad0660677f3fad5cd86ae7839aba0f8a68/src/Text/Pandoc/Writers/Markdown.hs#L766) to `MWriter Doc` I am forced to make changes to the code of `inlineToMarkdown` or changing the type of [`inlineListToMarkdown`](https://github.com/jgm/pandoc/blob/2678edad0660677f3fad5cd86ae7839aba0f8a68/src/Text/Pandoc/Writers/Markdown.hs#L691) due to the fact that `inlineToMarkdown` uses `inlineListToMarkdown`. However if I change the type of `inlineListToMarkdown` this forces me to change the type/code of all functions that use `inlineListToMarkdown` and I end up in a situation where basically all the code uses `MWriter` which is actually needed only for inline elements. 

So, it seems that this idea can't be used without multiple changes. It's much better than my current solution as it doesn't require a special case function `inlineLinkToMarkdown`. On the other hand `MWriter` way allows to only view the next inline element, whereas my current solution just operates on the whole list and therefore can be more flexible.

I would try to play with it a bit more, probably I just didn't pick the idea right, please advise me.

Besides, I noticed that read-only(?) `WriterOptions` are passed to virtually every function which returns `State WriterState a`. From the first look it seems like a right place for transformer with `Reader WriterOptions`. I thought that if I refactor the writer in such a way that `WriterOptions` are passed through `Reader` the `MWriter` idea would suit much better, in fact `WriterOptions` can be one of the fields of `InternalState`. What do you think?

**Comment by zudov** [comment] 2015-03-02 22:19
Speaking of `Reader WriterOptions` I've noticed that most readers are passing the options as arguments. I am a little confused, is there something that I don't see or it is just for historical reasons.

**Comment by jgm** [comment] 2015-03-02 22:21
+++ Konstantin Zudov [Mar 02 15 14:14 ]:
>   @mpckering After playing with this idea, I am not exactly sure about
>   it. The problem is that if I change the type of [1]inlineToMarkdown to
>   MWriter Doc I am forced to make changes to the code of inlineToMarkdown
>   or changing the type of [2]inlineListToMarkdown due to the fact that
>   inlineToMarkdown uses inlineListToMarkdown. However if I change the
>   type of inlineListToMarkdown this forces me to change the type/code of
>   all functions that use inlineListToMarkdown and I end up in a situation
>   where basically all the code uses MWriter which is actually needed only
>   for inline elements.
>
>   So, it seems that this idea can't be used without multiple changes.
>   It's much better than my current solution as it doesn't require a
>   special case function inlineLinkToMarkdown. On the other hand MWriter
>   way allows to only view the next inline element, whereas my current
>   solution just operates on the whole list and therefore can be more
>   flexible.

You're going to need to view more than the next inline
element anyway, since otherwise the pattern

    Link, Space, Link

might produce

    [foo] [bar]

which could be interpreted as a single reference link.

>   Besides, I noticed that read-only(?) WriterOptions are passed to
>   virtually every function which returns State WriterState a. From the
>   first look it seems like a right place for transformer with Reader
>   WriterOptions. I thought that if I refactor the writer in such a way
>   that WriterOptions are passed through Reader the MWriter idea would
>   suit much better, in fact WriterOptions can be one of the fields of
>   InternalState. What do you think?

This could be done (and in some writers, options are a field
of state).  It's this way partly for historical reasons,
because originally the writer didn't use state.

**Comment by zudov** [comment] 2015-03-02 22:30
> You're going to need to view more than the next inline element anyway

I see, thanks. In that case [`zipWithM` approach](https://github.com/jgm/pandoc/issues/1977#issuecomment-76724759) wouldn't really work (unless `zipWith3M` and so on, but it doesn't look good).

> This could be done (and in some writers, options are a field of state).

Good to know. It doesn't look like it's absolutely needed in terms of current issue, but probably some other day. I've counted ~150 occurrences of `opts` around the module, would be nice to pass it around in a less explicit way.

**Comment by wcaleb** [comment] 2015-03-02 22:32
@jgm @zudov Since I'm learning a lot from this exchange, can I ask whether, in principle, the idea of adding some kind of pattern-matching function in the `inlineListToMarkdown` function (which would I guess require moving some of the getting of references up from the `inlineToMarkdown` function) would work? And if not, why not?

**Comment by jgm** [comment] 2015-03-02 22:37
+++ W. Caleb McDaniel [Mar 02 15 14:32 ]:
>   [1]@jgm [2]@zudov Since I'm learning a lot from this exchange, can I
>   ask whether, in principle, the idea of adding some kind of
>   pattern-matching function in the inlineListToMarkdown function (which
>   would I guess require moving some of the getting of references up from
>   the inlineToMarkdown function) would work? And if not, why not?

I think it could work, yes!  In fact, that's got to be the
least invasive fix.

Here's an idea.  Pattern match for `Link : Space : Link` or
`Link : Link`.  If either of these is found, and if the
shortcut reference links option is enabled, you could just
insert a `RawInline (Format "markdown") "[]"` after the
first Link.

**Comment by wcaleb** [comment] 2015-03-02 22:44
OK, I'll try that on my branch later tonight. You can see I was moving on that path in link from earlier comment.

**Comment by zudov** [comment] 2015-03-02 22:44
@jgm @wcaleb Either I don't get it, or it is really close to what I have [here](https://github.com/jgm/pandoc/blob/2678edad0660677f3fad5cd86ae7839aba0f8a68/src/Text/Pandoc/Writers/Markdown.hs#L717).

`inlineListToMarkdown` calls `inlinesToMarkdown` which iterates over list of inlines and pattern matches on consecutive links. The difference from the approach in the last @jgm message is that I have a special case rendering function `inlineLinkToMarkdown` which is used for rendering links and inserts "[]" according to parameter `followedByLink`. @jgm's approach is much better as it wouldn't require a horrible special case rendering function.

**Comment by wcaleb** [comment] 2015-03-02 22:48
@jgm PS the problem I was running  into was cases where a reference link is used multiple times, in which case that label gets put in later. That would then render the raw brackets added via pattern matching superfluous and wrong.

**Comment by zudov** [comment] 2015-03-02 23:00
@wcaleb I guenn, that might be the reason not to append brackets as a raw markdown from pattern-matching function but instead do it from `inlineToMarkdown`.

**Comment by jgm** [comment] 2015-03-02 23:05
+++ W. Caleb McDaniel [Mar 02 15 14:48 ]:
>   @jgm PS the problem I was running into was cases where a reference link
>   is used multiple times, in which case that label gets put in later.
>   That would then render the raw brackets added via pattern matching
>   superfluous and wrong.

Ah yes, I see what you're getting at.  For example, if you convert `[foo](url) [foo](url2) [foo](url3)`, with the current writer you'll get `[foo][] [foo][1] [foo][2]`; changing this to `[foo][] [1][] [2]` would be wrong; `[foo][] [foo][1] [foo][2]` would be needed.  Well, maybe a custom rendering function is a better way to go then; the insertion of raw markdown is a bit hackish.

**Comment by zudov** [comment] 2015-03-03 02:00
I have more or less finished commit https://github.com/jgm/pandoc/commit/f15f4df5ad65a5ddfaa716fef06c6682e1498fad

The corner cases which we discussed here are described with tests. It does the job, but there is a room for improvement (e.g. I am thinking about joining `inlineListToMarkdown` with `inlinesToMarkdown`).

@wcaleb I am looking forward to your implementation, so that we can merge the best parts of our commits into one PR.

*PS:* It's really scary how github shows commits to forks as if they were in the upstream repository (see the link above)

**Comment by zudov** [comment] 2015-03-03 04:10
Wow. Just found such a simple way to get rid of a special case function. I've just added a `Bool` field to `WriterState` that shows that current element can't be shortcutted.

The commit is referenced above, but it makes more sense to look at the diff to the master rather than on commit itself

https://github.com/jgm/pandoc/compare/master...zudov:shortcut_ref_link

**Comment by wcaleb** [comment] 2015-03-03 05:57
@zudov I haven't tested thoroughly, but would this slight modification of your method also work?

https://github.com/wcaleb/pandoc/commit/f6ab33183aeebd95ce16941a3cd32b97503641a3

Instead of creating a field to `WriterState`, couldn't we just disable the `Ext_shortcut_ref_links` in `writerOptions` when processing unshortcutable links?

**Comment by zudov** [comment] 2015-03-03 06:31
@wcaleb Great idea. I am pretty sure it will work correctly, as:
```haskell
  let useShortcutRefLinks = shortcutable && isEnabled Ext_shortcut_reference_links opts
```
if we get rid of `shortcutable` and just disable extension it would be the same thing.
The set of extensions is small, so there is almost no overhead when we remove the element.

**Comment by zudov** [comment] 2015-03-03 07:27
@wcaleb This is amazing

**Comment by timtylin** [comment] 2015-03-03 08:13
@zudov Looks great! May I humbly suggest refactoring `inlineListToMarkdown` before it gets too crazy. Perhaps something like:

```haskell
-- | Convert list of Pandoc inline elements to markdown.
inlineListToMarkdown :: WriterOptions -> [Inline] -> State WriterState Doc
inlineListToMarkdown opts lst = do
  inlist <- gets stInList
  render (if inlist then avoidBadWraps lst else lst)
  where render [] = return empty
        render (i:is) = liftM2 (<>) (inlineToMarkdown opts' i) (render is)
        opts' = if shortcut
                 -- disable shortcut links if followed by another link
                 then opts{ writerExtensions = Set.delete
                              Ext_shortcut_reference_links $
                              writerExtensions opts }
                 else opts
        shortcut = case i of
                     (Link _ _) -> case is of
                         (Link _ _):_       -> False
                         Space:(Link _ _):_ -> False
                         _                  -> True
                     _ -> True

avoidBadWrapsInList :: [Inline] -> [Inline]
avoidBadWrapsInList [] = []
avoidBadWrapsInList (Space:Str ('>':cs):xs) =
  Str (' ':'>':cs) : avoidBadWraps xs
avoidBadWrapsInList (Space:Str [c]:[])
  | c `elem` "-*+" = Str [' ', c] : []
avoidBadWrapsInList (Space:Str [c]:Space:xs)
  | c `elem` "-*+" = Str [' ', c] : Space : avoidBadWraps xs
avoidBadWrapsInList (Space:Str cs:Space:xs)
  | isOrderedListMarker cs = Str (' ':cs) : Space : avoidBadWraps xs
avoidBadWrapsInList (Space:Str cs:[])
  | isOrderedListMarker cs = Str (' ':cs) : []
avoidBadWrapsInList (x:xs) = x : avoidBadWraps xs

isOrderedListMarker :: String -> Bool
isOrderedListMarker xs = endsWithListPunct xs &&
              isRight (runParserT (anyOrderedListMarker >> eof)
                       defaultParserState "" xs)
  where endsWithListPunct xs = case reverse xs of
                                 '.':_ -> True
                                 ')':_ -> True
                                 _     -> False
```

(I haven't checked whether this would compile. Take it with a giant grain of salt.)

**Comment by zudov** [comment] 2015-03-03 08:38
@timtylin Seems reasonable, I'll cut it down a little.

**Comment by zudov** [comment] 2015-03-03 09:25
@timtylin Still not perfect, but a bit better https://github.com/zudov/pandoc/commit/cf8b7a43207d0001071b41daa960eb99a3b1a9fb

How does it look?

**Comment by timtylin** [comment] 2015-03-03 09:30
@zudov To be honest I was more concerned about getting rid of the `shortcut`/`noshortcut` function redirect, just because it may be harder to maintain. I was trying to write it in a way that will allow future manipulations on `opts` to be trivially incorporated with minimal line changes.

**Comment by mpickering** [comment] 2015-03-03 10:15
I think 8d6ae26f797dd17d47a16bcd615cbfae8ba4813f is hacky and confusing. The right place for that flag is in `WriterOptions` as you originally had it.

**Comment by wcaleb** [comment] 2015-03-03 13:21
@mpickering We moved to an extension instead of a command line option because that seemed to be what @jgm preferred: https://github.com/jgm/pandoc/issues/1977#issuecomment-76557044.

**Comment by wcaleb** [comment] 2015-03-03 14:39
@timtylin In your originally suggested refactoring, `i` is out of scope for `shortcut`. @zudov here's a slightly shorter refactoring; I don't know if, by eliminating `recur`, this might be clearer to future readers: https://github.com/wcaleb/pandoc/commit/eb72f35726a26d369626558b3f10d11859ebf017.

**Comment by timtylin** [comment] 2015-03-03 23:18
@wcaleb geez, that'll teach me to program from the hip. Anyways, that looks great!

**Comment by zudov** [comment] 2015-03-04 00:49
@wcaleb I think @mpickering didn't mean `WriterOptions` but `WriterState` (that's what the linked commit is about). 

I would agree with @mpickering as extensions are not supposed to be switched on and off at runtime, extensions are enabled by user and define the behaviour of writer as a whole. Whereas `WriterState` seems to be a right place for flag that indicates that currently rendered link shouldn't be shortcuted (as it is about writer's state).

Solution that switches the extension is a bit shorter, but it can be really confusing for a person who looks at the source of `inlineToMarkdown opts (Link _ _)` as that person would expect that the extension is enabled.

**Comment by wcaleb** [comment] 2015-03-04 01:07
@zudov Aha. Makes sense. Thanks for the clarification!

**Comment by zudov** [comment] 2015-03-04 03:39
@wcaleb @mpickering @timtylin See the refered commit. I decided that as suggested by @mpickering it's reasonable to avoid manipulation with options and extensions at writer runtime.

Speaking of refactoring. At the moment we deal with this piece of code:

```haskell
  where go [] = return empty
        go (i:is) = case i of
            (Link _ _) -> case is of
                -- ^ If a link is followed by another link we don't shortcut it
                (Link _ _):_       -> unshortcutable
                Space:(Link _ _):_ -> unshortcutable
                _                  -> shortcutable
            _ -> shortcutable
          where shortcutable = liftM2 (<>) (inlineToMarkdown opts i) (go is)
                unshortcutable = do
                    iMark <- withState (\s -> s { stRefShortcutable = False })
                                       (inlineToMarkdown opts i)
                    modify (\s -> s {stRefShortcutable = True })
                    fmap (iMark <>) (go is)
```
I quite like that flow where `go` pattern matches on the list and choses one of the locally defined branches. I think it clearly says: "Unless link is followed by another link we proceed normally, otherwise we disable shortcutting while rendering current inline, render it and go further".

However my vision is a bit biased here, as I was playing with this code quite a lot, and what I find to be clear might be confusing for others. What do you think?

**Comment by timtylin** [comment] 2015-03-04 04:15
> However my vision is a bit biased here, as I was playing with this code quite a lot, and what I find to be clear might be confusing for others. What do you think?

It's obviously clear enough as it is. I'm just going through the thought exercise of "what happens when you need to introduce matching on some other pattern in the future"? Branching where you did is fine if that's all we're ever doing to the inline list (that modifies state/options), but we're changing a really generic processing function here, and I just feel that this kind of redirect style really isn't that composable with other possible effect that we may want to put on the inline writer in the future. I feel that typically in idiomatic Haskell you'd want to pre-compose multiple possible effects, and have only one place in the code where it is applied.

**Comment by zudov** [comment] 2015-03-04 04:32
> "what happens when you need to introduce matching on some other pattern in the future"?
This actually should be pretty easy, just one more match and another branch. 

> you'd want to pre-compose multiple possible effects, and have only one place in the code where it is applied.

I see, @mpickering 's idea was pretty close to that https://github.com/jgm/pandoc/issues/1977#issuecomment-76724759 .

We clearly need to observe the adjacent elements to the one that is currently rendered, and usually it's achieved with pattern-matching while iterating over the list. State and effects is what makes it unidiomatic, but I couldn't come up with a better way that would remain extensible.

**Comment by timtylin** [comment] 2015-03-04 04:50
> We clearly need to observe the adjacent elements to the one that is currently rendered, and usually it's achieved with pattern-matching while iterating over the list.

I probably wasn't clear enough. The pattern matching part is perfectly fine. It's mostly a matter of stylistic choice over what the cases bind to. They way they are now where they redirect to another function is a bit more imperative. The one drawback is that you then have multiple duplicated calls then to `liftM2 (<>) (inlineToMarkdown opts i) (go is)`, one at each leaf of the case tree. Alternatively, you can have them return filters that transform writer state or options. This way you only have to call `liftM2 (<>) (inlineToMarkdown opts i) (go is)` once in the entire code, after combining all the state/option filters and applying them all together. This approach can be seen as more declarative/reactive.

**Comment by zudov** [comment] 2015-03-04 08:19
I get the idea. We had something similar to that with `recur`.

By the way, the changed state/options should be applied just to `(inlineToMarkdown opts i)` not to the whole `liftM2 (<>) (inlineToMarkdown opts i) (go is)`. Another obstacle, is that we don't just need to change the state before running `inlineToMarkdown opts i`, but we need also need to change the state after running it.

Something like this seems closer to what you described:
```haskell
where shortcutable = recur id
      unshortcutable = recur $ \act -> setShortcutable False *> act <* setShortcutable True
      recur f = liftM2 (<>) (f (inlineToMarkdown opts i)) (go is)
      setShortcutable v = modify (\s -> s { stRefShortcutable = v })
```
This would be easier to extend with additional rules, but I am not sure is it required at the moment.

**Comment by mpickering** [comment] 2015-03-04 09:07
> By the way, the changed state/options should be applied just to (inlineToMarkdown opts i) not to the whole liftM2 (<>) (inlineToMarkdown opts i) (go is). Another obstacle, is that we don't just need to change the state before running inlineToMarkdown opts i, but we need also need to change the state after running it.

This is why I originally suggested to change from just using the State
monad to using a monad transformer stack!

**Comment by timtylin** [comment] 2015-03-04 09:09
> but we also need need to change the state after running it.

Actually, I think in this case we can cheat by always setting `stRefShortcutable` after rendering a `Link` :D

**Comment by zudov** [comment] 2015-03-04 11:12
As there is a working code I would prepare a PR and then we can discuss final details there.

**Comment by jgm** [comment] 2015-03-29 04:40
Closing this issue, fixed by @zudov's merged-in patch.

**Closed by jgm** 2015-03-29 04:40 UTC
Labels: enhancement

**Comment by binaryphile** [comment] 2015-03-29 18:09
Wow that's awesome, thanks guys.  I had no idea it would be so involved.
