### ISSUE TITLE
Generate inline links from automatic links

### ISSUE THREAD

**Issue by alexconst** [jgm/pandoc#2755] opened 2016-03-04 10:22 UTC
I checked the manual but didn't find anything for it.
Is there a way to convert
~~~
<http://google.com>
~~~
To
~~~
[http://google.com](http://google.com)
~~~

*Why would any sane person need that?* 
Basically to work around a bug with the newest version of GitHubPages and Jekyll.
(I can always cook up some `sed` post-processing, but with pandoc it would be cleaner)

I did found the `--reference-links` and actually tried it, but as expected it doesn't do what I wish for and actually breaks liquid tags.

Thanks

**Comment by wilx** [comment] 2016-03-09 06:26
:+1: for this request. I am using Pandoc Markdown and conversion to PHP Markdown Extra to produce a format mostly compatible with WordPress. One thing that does not work for me is the autolinks. WordPress simply eats the whole `<http://example.com/>` and does not show anything.

**Comment by ousia** [comment] 2016-03-09 08:42
> _Why would any sane person need that?_
> Basically to work around a bug with the newest version of GitHubPages and Jekyll.

And wouldn’t it be better to fix the actual bug?

**Comment by alexconst** [comment] 2016-03-09 11:03
> And wouldn’t it be better to fix the actual bug?

True.

This isn't a Pandoc bug. It would just be a nice to have feature. As a way to make markdown links more robust.
My point being that Pandoc is the swiss army knife for documentation capable of bridging different formats together, while walking through the minefield unscathed.

BTW, I actually don't need this anymore has I've made a vim plugin that takes care of this (and several other "blogging" issues). 
But as predicted this is something that affects more people. So maybe worth considering.

**Comment by ousia** [comment] 2016-03-09 12:21
> > And wouldn’t it be better to fix the actual bug?
> 
> True.
> 
> This isn't a Pandoc bug. It would just be a nice to have feature. As a way to make markdown links more robust.

Well, a filter would be the best way of doing it. Sorry for not offering the filter myself, but asking at the mailing list is the best way of doing it. (I cannot code [either Haskell or anything] :worried:.)

And if you allow me an open question: how about reporting the issue at GitHub and Jekyll? (This isn’t incompatible with having a filter until the issue is fixed.)

**Comment by jgm** [comment] 2016-03-09 15:13
You can accomplish this with a filter that adds a title
(even a single space) to every link.  Pandoc will not create
an autolink if there's a title.

+++ Václav Haisman [Mar 08 16 22:26 ]:

**Comment by jgm** [comment] 2016-03-09 15:16
Closing: I agree that the sensible course of action is to submit a bug report on GitHub pages.
Workaround is a filter that adds a title to links not containing one.

**Closed by jgm** 2016-03-09 15:16 UTC

**Comment by alexconst** [comment] 2016-03-09 15:25
For anyone looking for the bug report in GHP
https://github.com/github/pages-gem/issues/231

**Comment by wilx** [comment] 2016-03-09 17:47
@jgm 

> You can accomplish this with a filter that adds a title (even a single space) to every link. Pandoc will not create an autolink if there's a title.

This does not appear to be true.

```{.text}
$ echo '[Para [Link ("",[],[]) [Str "http://example.com"] ("http://example.com","Link http://example.com")]]' | pandoc -f native -t markdown 
<http://example.com>
$ pandoc -v | head -n 1
pandoc 1.16.0.2
```

As long as the `Str "http://example.com"` is the same as link URL itself, it produces the `<http://example.com>` link.

**Comment by jgm** [comment] 2016-03-09 17:53
+++ Václav Haisman [Mar 09 16 09:47 ]:
>   [1]@jgm
>
>     You can accomplish this with a filter that adds a title (even a
>     single space) to every link. Pandoc will not create an autolink if
>     there's a title.
>
>   This does not appear to be true.

Ah. I stand corrected.  Perhaps it should be true, but
maybe there was a reason I did it this way?

**Comment by wilx** [comment] 2016-03-09 18:21
> Ah. I stand corrected. Perhaps it should be true, but maybe there was a reason I did it this way?

I cannot think of a reason why the title does not work of conversion to Markdown. However, an autourl is converted to other formats differently than an ordinary link. E.g., for HTML the link has additional `class="uri"` attribute on `<a>`. It seems to make sense to have some distinct representation of bare URLs even in Markdown.

It seems to me that allowing autourls to be converted into bare URLs makes some sense.
