### ISSUE TITLE
++text++ -> <ins>text</ins>, for symmetry 

### ISSUE THREAD

**Issue by keiyakins** [jgm/pandoc#3035] opened 2016-07-21 17:11 UTC
Currently, you can mark text as deleted in pandoc markdown with `~~text~~`. There's no similar way to mark it as inserted. This'd be a nice enhancement, useful for any time you're communicating changes back and forth.

**Comment by mb21** [comment] 2017-01-23 09:39
see also https://github.com/jgm/pandoc/issues/1560

**Comment by mb21** [comment] 2018-11-05 08:33
Duplicate of #1560

**Closed by mb21** 2018-11-05 08:33 UTC
Labels: AST change, enhancement, format:Markdown
