### ISSUE TITLE
Support attributes for more elements in AST

### ISSUE THREAD

**Issue by johnd0e** [jgm/pandoc#4097] opened 2017-11-26 10:28 UTC
Now pandoc support attributes for a very limited set of elements.
Even if currently it's impossible to define attributes in markdown syntax, it would be very useful for other formats (or for further processing with filters).

E.g. now html reader just skips attributes of all unsupported elements, instead of storing them in AST.
So a lot of metadata gets lost.

Perhaps not every AST element deserves own attributes, but may be it will not be too hard to support more?
Personally I want attributes for all kinds of lists.
But it also seems very natural for such elements as Para, Table, BlockQuote,...

**Comment by tarleb** [comment] 2017-11-26 10:46
See also #684.

**Comment by mb21** [comment] 2017-11-26 11:05
Duplicate of #684

**Closed by mb21** 2017-11-26 11:05 UTC
