### ISSUE TITLE
Defaults file variables:/header-includes: works differently than Metadata header-includes:

### ISSUE THREAD

**Issue by allefeld** [jgm/pandoc#5970] opened 2019-12-08 18:03 UTC
Following the example under "Metadata blocks" in the manual, combined with the documentation for "Default files", I put the following in a file `options.yaml`:

````
variables:
  header-includes:
    - |
      ```{=latex}
      \input{\string~/.pandoc/templates/definitions.tex}
      ```
````

However, the generated LaTeX file contains all the lines, including ```` ```{=latex}```` and ```` ``` ````.

Putting the `header-includes:` block directly into the input file's metadata block however works as expected.

Apparently, different rules apply to entries within a file's metadata block and to `variables` in a defaults file.

I think this inconsistency is unfortunate. If for some reason this cannot be changed, it should be mentioned in the documentation.

(Note that I cannot instead use `include-in-header: ~/.pandoc/templates/definitions.tex` directly in the options file because Pandoc does not interpret `~`.)

Pandoc 2.8.1 installed from the official Debian package.

**Comment by jgm** [comment] 2019-12-08 20:19
Not a bug.  Variables are plain text to be inserted verbatim into the document.  Hence, the markdown isn't parsed.  Metadata is markdown text.

**Comment by jgm** [comment] 2019-12-08 20:27
Maybe the best solution would be to make pandoc interpret `~` in these contexts.
It's a bit awkward since this is *nix specific, though.

**Comment by jgm** [comment] 2019-12-08 20:28
Note also that if you just want this stuff to be passed through verbatim, you don't need the surrounding ` ```{=latex} ` part at all. Just leave it off and all will be well.

**Comment by allefeld** [comment] 2019-12-08 21:27
I understand. I still think it would be helpful to emphasize this difference in the manual.

`~`, I agree, it is *nix specific and therefore doesn't really belong into a cross-platform language. An alternative would be to support environment variables in general, maybe using the syntax that is used for variables in templates: `${HOME}`

Or even better, have a variable `${data-dir}`, so I could write
```
include-in-header: ${data-dir}/definitions.tex
```
This file is a lengthy list of macros I like to use for writing LaTeX math, and I'd prefer not to put them into the template itself, among others reasons so I can have them identically in a beamer template.

**Comment by jgm** [comment] 2019-12-09 07:33
Well, the manual already says:

> Like  `--variable`, `--metadata` causes template variables to be set.
> But unlike `--variable`, `--metadata` affects the metadata of the
> underlying document (which is accessible from filters and may be
> printed in some output formats) and metadata values will be escaped
> when inserted into the template.

and for metadata in YAML metadata blocks in markdown:

> Metadata will be taken from the fields of the YAML object and added to any
existing document metadata.  Metadata can contain lists and objects (nested
arbitrarily), but **all string scalars will be interpreted as Markdown.**

If there are specific changes you'd make, you could suggest them.

The request for a way to specify a path probably belongs in a separate issue.

**Comment by allefeld** [comment] 2019-12-09 20:09
Missed that, sorry! I have to say I'm frequently getting lost in the manual recently. Along with Pandoc's functionality, it has grown so large. Maybe at some point I'll make a suggestion how to make it better accessible, but for now I'm closing this.

I'll make a separate issue regarding the path.

**Closed** 2019-12-09 20:18 UTC

**Comment by allefeld** [comment] 2019-12-09 20:20
see #5977

**Comment by mb21** [comment] 2019-12-10 10:22
> I'm frequently getting lost in the manual recently. 

@allefeld you might be interested in the discussion under https://github.com/jgm/pandoc-website/issues/34
