### ISSUE TITLE
Docx reader: smartTags omitted

### ISSUE THREAD

**Issue by uoou** [jgm/pandoc#3412] opened 2017-02-03 04:51 UTC
Deep apologies if this is known - I did search but it's tricky to search for.

I was converting a .docx to markdown (tried other formats after finding the bug and they all seem affected) and on conversion, certain words, all proper nouns, were being omitted.

I don't know for sure, I don't have access to MS Word, but I suspect what's happening is that Word is auto-capitalising these proper nouns and then perhaps marking them in some way with some hidden character and pandoc is reading them as garbage.

If I use google docs as a filter - i.e. upload the .docx to google docs then download it again (still as .docx) the problem is resolved.

I will attach the afflicted .docx file. It's under a CC-ND-SA license.

An example passage where the bug occurs is: 

"but it’s worth remembering that King James, to whom Bacon dedicated the book—and who was at the time one of the finest scholars in Europe—was completely baffled"

On conversion, the word "Europe" is omitted.

[sh.docx](https://github.com/jgm/pandoc/files/749594/sh.docx)

Thanks!

**Comment by mb21** [comment] 2017-02-03 08:41
The problem is probably the `smartTag`, from the posted docx:

    <w:smartTag w:uri="urn:schemas-microsoft-com:office:smarttags" w:element="place"><w:r><w:t>Europe</w:t></w:r></w:smartTag>

**Comment by mb21** [comment] 2017-02-03 09:13
ah, this is a duplicate of https://github.com/jgm/pandoc/issues/2242 then...

**Closed by mb21** 2017-02-03 09:13 UTC
Labels: format:Docx, reader

**Comment by abartov** [comment] 2020-09-29 13:01
Thank you very much for fixing this!  Random letters in my docx (beyond my control) are in "SmartTag" tags (for no discernible reason), and their disappearance was driving my crazy.
