### ISSUE TITLE
Features missing from Pandoc's markdown

### ISSUE THREAD

**Issue by pharpend** [jgm/pandoc#2124] opened 2015-04-30 22:48 UTC
Hello, @jgm 

This came up in #2108 . I have a [textbook][1], which is written in
LaTeX. I was wanting to convert it into EPub and HTML with Pandoc, but
Pandoc's limited LaTeX support was, well, limiting.

You pointed out that, if I want flawless support, I should use
Pandoc's markdown. There are a few critical features needed to write a
textbook, which Pandoc's markdown doesn't have:

1.  Macros. You have limited support for math `\newcommand`s, but you
    don't support `\newenvironment`, or `\let`.

2.  Nothing like `\input`, except passing multiple files at once. 

    I would have to do some shell-scripting fu to get this to
    work. This is especially so if, for instance, I wanted to have
    "one page per node" for the HTML output, but concatenated output
    for EPub.

3.  Nothing like `cleverref`. This is a hugely important feature,
    because it allows linked indexing.

4.  You don't have anything like the `exercise` package.

5.  This isn't a markdown feature, but Pandoc is pretty difficult to
    install, so using it as my project's compiler would mean fewer
    contributors.

    I don't blame you for this, I blame the Haskell people. That said,
    maybe we should try to find a solution to this. [Halcyon]
    (https://halcyon.sh/) looks promising.

[1]: http://learnyou.org/

**Comment by jgm** [comment] 2015-04-30 23:39
+++ Peter Harpending [Apr 30 15 15:48 ]:
>4.  This isn't a markdown feature, but Pandoc is pretty difficult to
>    install, so using it as my project's compiler would mean fewer
>    contributors.

I find this curious.  I've provided binary packages for OSX, Windows, and Linux.  That should be about as easy as it gets, no?  In addition, just about every linux distribution also has pandoc in its package manager (though usually an older version), and you can also use homebrew to install on OSX.

**Comment by lierdakil** [comment] 2015-05-01 02:25
(2) bugs me a bit as well. @jgm, what do you think? It's not very hard to add support for this, I think, and it would somewhat simplify building big scary Markdown documents with Pandoc (atm it requires some bash- or makefile-fu to implement)

As for (3), I have been working on [pandoc-crossref](https://github.com/lierdakil/pandoc-crossref) filter, which somewhat emulates cleveref (and can export to it). You might want to take a look, if nothing else. Feel free to file issues for any missing functionality.

(5) seems somewhat weird. I don't think that pandoc is harder to install than LaTeX. I think on Windows it's even easier, and on Gentoo and Arch is at the very least not considerably harder, since it's in gentoo-haskell and haskell-core overlays respectively.

**Comment by pharpend** [comment] 2015-05-01 03:26
I use Arch, and I haven't tried the AUR variant. Generally, on Arch, it's a good idea to not let `pacman` install any Haskell stuff beyond `ghc` and `cabal`. So one is therefore required to deal with cabal hell.

**Comment by lierdakil** [comment] 2015-05-01 03:31
AUR Haskell packages are usually broken, that much is true. But I didn't
mean AUR, I meant this: https://wiki.archlinux.org/index.php/ArchHaskell.
It's still community repository, though, but I don't really see much
difference with Arch anyway.

2015-05-01 6:26 GMT+03:00 Peter Harpending <notifications@github.com>:

**Comment by jgm** [comment] 2015-05-01 03:37
+++ Peter Harpending [Apr 30 15 20:26 ]:
>I use Arch, and I haven't tried the AUR variant. Generally, on Arch, it's a good idea to not let `pacman` install any Haskell stuff beyond `ghc` and `cabal`. So one is therefore required to deal with cabal hell.

You could just use the binary package for linux (assuming you're 64 bit).
It won't interfere with anything eles on your system.

**Comment by pharpend** [comment] 2015-05-01 03:52
@jgm Where is this binary package? I see a `.deb` file on Pandoc's downloads page. I'm not familiar with Debian's packaging system, so I don't know if that's a binary.

**Comment by jgm** [comment] 2015-05-01 04:03
+++ Peter Harpending [Apr 30 15 20:52 ]:
>@jgm Where is this binary package? I see a `.deb` file on Pandoc's downloads page. I'm not familiar with Debian's packaging system, so I don't know if that's a binary.

That's it.
http://unix.stackexchange.com/questions/83540/installing-a-deb-package-on-arch-is-it-possible

You can also unpack manually:

    ar -vx pandoc-1.13.2-1-amd64.deb
    tar xvzf data.tar.gz

This will put everything you need in the usr subdirectory of
your working directory.  Your binaries will be in usr/bin.

**Comment by r-gaia-cs** [comment] 2015-05-01 23:05
> 1.  Macros. You have limited support for math `\newcommands`, but you
>     don't support `\newenvironment`, or `\let`.

Pandoc supports filters.
You can use it as macros.

> 2.  Nothing like `\input`, except passing multiple files at once. 
> 
>     I would have to do some shell-scripting fu to get this to
>     work. This is especially so if, for instance, I wanted to have
>     "one page per node" for the HTML output, but concatenated output
>     for EPub.

The best option here is create a program that uses Pandoc.

> 3.  Nothing like `cleverref`. This is a hugely important feature,
>     because it allows linked indexing.

Pandoc doesn't support cross reference yet. =(

> 4.  You don't have anything like the exercise package.

Again,
you can implement this using filters.

**Comment by lierdakil** [comment] 2015-05-03 14:16
@r-gaia-cs
filters are not a direct substitution for macros, sadly, since (a) marcos are much easier than filters, and (b) macros are *embedded* in document and can be very document-specific, while fitlers can't.
It's possible to implement cross-referencing with filters though.

**Comment by DOFfactory** [comment] 2015-07-31 14:09
>  `<3>` Nothing like `cleverref`. This is a hugely important feature,
because it allows linked indexing.

I can second this. And I do understand that this might be problematic to implement. There are others who are exploring the options (see #2336). But until then what do you think about about introducing a list of "unsupported" commands, which in the converted document (e.g. tex > odt) will highlight that 
> :heavy_exclamation_mark: this command could not be converted, check it and change manually :heavy_exclamation_mark:

It will help the conversion process and the consecutive review IMHO for many of us easier.

**Comment by pharpend** [comment] 2015-07-31 18:30
On Fri, Jul 31, 2015 at 07:09:42AM -0700, DOFfactory wrote:
> But until then what do you think about about introducing a
> list of "unsupported" commands, which in the converted document
> (e.g. tex > odt) will highlight that > :heavy_exclamation_mark: this
> command could not be converted, check it and change manually
> :heavy_exclamation_mark:

FWIW, I've been working in my spare time on a Haskell-oriented solution:
<https://github.com/pharpend/comarkdown>. It's not finished yet, but the
general direction I think is correct.

Essentially, it's a preprocessor for markdown, does macros and
environments and such, then sends the processed text to Pandoc for
conversion into whatever.

**Comment by DOFfactory** [comment] 2015-07-31 18:52
Thanks @pharpend. So most of us, LaTeX users, use pandoc for converting tex > pandoc markdown > odt/docx. I wonder whether adding another step as a pre-processor for pandoc would do any good for us.

**Comment by KurtPfeifle** [comment] 2015-07-31 19:44
If you are a LaTeX user, you can do the *smart* thing and become even more
productive and efficient by starting to switch your main authoring language
to Markdown. Less typing, less headaches with TeX syntax, more
concentration on content writing.

The use Pandoc to convert to LaTeX. Your LaTeX skillz are not in vain — you
can use them to polish the LaTeX created by Pandoc, and you can also put
them to good use when hacking your own personal customized Pandoc template
for LaTeX.

And if you need to output ODT/DOCX/HTML/EPUB, jus use the same Markdown
source…
​

**Comment by DOFfactory** [comment] 2015-07-31 21:07
Thanks @KurtPfeifle but no time for changing the working environment at 85% completion of the task I am working on ... Maybe doable on the next project. 

Still I am unhappy with the option that a code is simply "stripped" from the converted text without any sign that `pandoc` actually deleted something (reference, todo comment, or anything `pandoc` cannot interpret). Do you think this should be the correct behaviour?

**Comment by pharpend** [comment] 2015-07-31 22:43
@DOFfactory I was suggesting (for future projects) comarkdown as a *replacement* for LaTeX. You can consider comarkdown as a superset of normal markdown. Essentially, comarkdown is a Pandoc reader that has support for macros and environments, the key features in LaTeX. It also supports Markdown's superior syntax, Unicode, and programmability with Haskell. I haven't written much of a standard library yet, so it's not usable.

**Comment by Hi-Angel** [comment] 2015-08-01 06:09
@pharpend I don't think that Markdown have a way to configure things like pages, margins. Though that could be done with CSS, e.g. [page selector](http://www.w3.org/TR/css3-page/#syntax-page-selector) *(in fact I did it before, but I am not sure that pandoc know the selector)*.

The problem with CSS page selector is that it relatively new, and even browsers don't yet support it *(at least haven't a few months ago)*. So I wanted to switch to Markdown+LaTeX. Still, the problem is the convertation to office formats.

**Comment by pharpend** [comment] 2015-08-01 19:11
@Hi-Angel comarkdown + something like Hakyll would support that.

**Comment by jgm** [comment] 2015-08-08 18:30
This is not focused enough to be a useful issue.
Feel free to submit more focused issues if you like, but I'm going to close this sprawling discussion.

**Closed by jgm** 2015-08-08 18:30 UTC
