### ISSUE TITLE
pdf-engine weasyprint; md -> pdf = blank pdf 

### ISSUE THREAD

**Issue by sufjanrouse** [jgm/pandoc#4524] opened 2018-04-04 08:17 UTC
Thanks for supporting Weasyprint! However when I try to use weasyprint as pdf-engine I end up with an blank pdf. If I generate a html and then use Weasyprint on that html to produce a pdf it works fine.
It also works fine if I instead use wkhtmltopdf as pdf-engine.

**cmd**
`pandoc -o output.pdf --pdf-engine=weasyprint test.md`

**test.md**
`# Test`

**Result**
pdf generated but blank

**Environment**
pandoc version 2.1.3 (hash-2388be648)
weasyprint 0.42.3
python 2.7.14
Windows 10 / MSYS2

**Comment by jgm** [comment] 2018-04-09 00:00
I can't reproduce this.  Works fine for me.  Same versions, except with python 3 and MacOS.
Can you try with `--verbose` to see if you get any useful information?

**Comment by sufjanrouse** [comment] 2018-04-09 07:13
Thanks for looking into it. --verbose did not give any useful information for my eyes but maybe it tells you more?

`pandoc -o output.pdf --pdf-engine=weasyprint --verbose test.md`

``` 
[INFO] No value for 'lang' was specified in the metadata.
  It is recommended that lang be specified for this format.
[WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata.
  Falling back to 'test'
[makePDF] Command line:
weasyprint "-" ".\\html2pdf30404-0.pdf"

[makePDF] Environment:
<environment variables, let me know if those are of interest of you aswell>

[makePDF] Contents of intermediate HTML:
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang xml:lang>
<head>
  <meta charset="utf-8"></meta>
  <meta name="generator" content="pandoc"></meta>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes"></meta>
  <title>test</title>
  <style type="text/css">
      code{white-space: pre-wrap;}
      span.smallcaps{font-variant: small-caps;}
      span.underline{text-decoration: underline;}
      div.column{display: inline-block; vertical-align: top; width: 50%;}
  </style>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
<base href="C:\msys64\home\H776592\workspace\eliot\">
</head>
<body>
<h1 id="test">Test</h1>
</body>
</html>

c:\python27\lib\site-packages\weasyprint\fonts.py:41: UserWarning: @font-face is currently not supported on Windows
  warnings.warn('@font-face is currently not supported on Windows') 
```

Intermediate html contains `<h1 id="test">Test</h1>` and looks alright. Applying Weasyprint on that intermediate html works.

@font-face warning is prompted also when generating directly with Weasyprint html -> pdf so it should (?) not be the problem.

Puzzling!

**Comment by mb21** [comment] 2018-04-09 08:12
Maybe this has something to do with the way we pipe the input to the `weasyprint` process as well? Works on unix, doesn't on Windows? Can you try the following (or equivalent syntax for windows):

    echo test | weasyprint - out.pdf

**Comment by sufjanrouse** [comment] 2018-04-09 09:01
`echo test | weasyprint - out.pdf` in windows10 + msys2 works fine.

**Comment by jgm** [comment] 2018-04-09 16:27
Yes, I suspect this may be Windows-related.  I don't have a Windows
setup to test on -- can anyone else confirm this behavior on Windows?

It would be helpful to know if it works for you to produce a PDF
via wkhtmltopdf.  We use the same internal piping method for that
as we do for weasyprint.

Another question that might be relevant: do you have write access to the
working directory?

**Comment by sufjanrouse** [comment] 2018-04-09 16:39
Yes it works with wkhtmltopdf as pdf-engine.

**Comment by jgm** [comment] 2018-04-09 16:40
Interesting.  Are you able to compile pandoc from source on your machine?
I have a change I'd like to try out.

**Comment by sufjanrouse** [comment] 2018-04-09 16:46
Should be no problem to compile and try out your change. Will have to wait until tomorrow though when I'm back at work.

**Comment by jgm** [comment] 2018-04-09 16:53
OK, I've made a change that I think might do the trick.  I suspect this has to do with lazy IO; I've noticed some differences before between linux and windows.

It should be possible to grab a binary from the latest appveyor build (once it finishes):
https://ci.appveyor.com/project/jgm/pandoc/build/artifacts

**Comment by sufjanrouse** [comment] 2018-04-10 06:38
Just tried out the fix but still the same behavior: blank pdf for weasyprint but works for wkhtmltopdf.

**Comment by jgm** [comment] 2018-04-12 15:46
I'm out of ideas.  The same code is used, practically, for
producing the PDF with weasyprint and with wkhtmltopdf.
The only difference is the command name and the arguments
used.

Can anyone else reproduce this on Windows?  I was not able
to reproduce the issue on macOS.

**Comment by mb21** [comment] 2018-04-12 17:36
Maybe it has more todo with weasyprint on windows... it's written in Python and as such might be started differently to compiled programs...

**Comment by mb21** [comment] 2018-05-05 09:40
Most probably, this will be fixed by https://github.com/jgm/pandoc/pull/4628 as well.

**Comment by mb21** [comment] 2018-05-06 09:04
I'm assuming this is fixed by https://github.com/jgm/pandoc/pull/4628 on current master (should be in [nightly build](https://github.com/pandoc-extras/pandoc-nightly) shortly). Please post back if the problem persists...

**Closed by mb21** 2018-05-06 09:04 UTC
Labels: platform:windows

**Comment by sufjanrouse** [comment] 2018-05-07 08:13
@mb21 I've just tested and can confirm that #4628 fixes this issue. Thanks!
