### ISSUE TITLE
All docx lines annotated with {dir=“ltr”}

### ISSUE THREAD

**Issue by fmatheus** [jgm/pandoc#5723] opened 2019-09-02 14:20 UTC
Even the empty lines of a google docs download docx are annotated when converting from docx to markdown as default behavior. I think it should not be the default, or at least should be easy to disable, since it brakes previous behavior. This was not a bidi file, all lines are ltr:

    [test line]{dir=“ltr”}
    
    []{dir="ltr"}

pandoc 2.7.3
Compiled with pandoc-types 1.17.6, texmath 0.11.2.2, skylighting 0.8.2

Seems related to #5545.

**Comment by jgm** [comment] 2019-09-02 15:00
Just tried with a docx generated by Google Docs. Sure enough, it is riddled with `<w:rtl w:val="0"/>` elements.  I'm not sure why Google does this, but I suppose we'll have to work around it.

**Comment by jgm** [comment] 2019-09-02 16:49
@jkr any ideas about how to handle this?

Basically we should only insert the "dir=ltr" span when the pPr or enclosing sectPr includes `<w:bidi/>`.  The default is ltr.

**Comment by jkr** [comment] 2019-09-02 19:27
Hmm... I couldn't reproduce with a google docs download. But, yeah, only doing it with bidi seems right. The issue is that we can't do just ignore it if it's zero or "ltr" because it might be an ltr section in a rtl doc. 

@jgm, would it be possible to post the google doc you downloaded?

**Comment by jgm** [comment] 2019-09-02 23:54
I just opened a doc, typed a few lines, and downloaded as docx.
Here's an example.
[Untitled.docx](https://github.com/jgm/pandoc/files/3567253/Untitled.docx)

**Comment by jgm** [comment] 2019-09-02 23:54
Converting this to markdown yields
```
[Hi]{dir="ltr"}

[]{dir="ltr"}

[This is a brand new document.]{dir="ltr"}

[]{dir="ltr"}
```

**Comment by jkr** [comment] 2019-09-03 15:55
Sorry -- I had forgotten that I had written the part in the *writer*, but not this part in the reader. Which explains why racking my brain trying to remember my thinking was coming up empty. 

I imagine it's safe to just ignore the RTLs unless they're inside of a bidi prop. Even then, for the sake of correctness, we should only know whether they reverse direction (this clearly doesn't, since it's a zero). I'll take a look at the spec and see if there's anything illuminating in there, but for now, it seems like the safe thing is to have a `envBidi` toggle (or perhaps triple: `Just LTR`, `Just RTL`, `Nothing`) and only pay attention to these if the toggle is on.

**Comment by jgm** [comment] 2019-09-03 17:05
I agree, I think that's the thing to do.

`<w:bidi>` can appear either in `sectPr` or in `pPr`.  Currently it doesn't look like we have anything that reads `sectPr`?

**Comment by jkr** [comment] 2019-09-03 17:38
No, we don't read `sectPr`. Weirdly, `sectPr` comes as a child of the *last* paragraph in the section (except for the last section, in which case it's a child of `body`). Unfortunately, we don't have a native concept of section that we can translate this into -- first/last complications aside.

I think we could add one at the docx level (add a `SectBreak` type to the `BodyPart` algebraic type) but we'd have to move it to the beginning of the section area when we got to it. 

This also means that we'd have to do a second pass to figure out what to do with all the `rtl` stuff.
But we have to do that  anyway to convert the `Docx` type to `Pandoc`, so we could take care of it there.

Okay, I'll give it a try, and see how it works.

**Comment by jgm** [comment] 2019-09-03 19:26
> Unfortunately, we don't have a native concept of section that we can translate this into -- first/last complications aside.

Div?

**Comment by jkr** [comment] 2019-09-03 19:29
I meant in the docx type ("native" was a misstatement). Going docx type -> pandoc type is fairly easy, since we can just set an environment when we hit the section break. Divs would add noisiness for not much gain.

Sorry -- I was mainly trying to think it out from the docx-parsing side.

**Comment by jgm** [comment] 2019-09-11 04:06
Any progress on this?

**Comment by jkr** [comment] 2019-09-11 09:46
Yeah -- but the correct implementations of sections are the sticking point. It requires either a considerable change in parsing or in conversion. I've tried a couple of things. But if the release is waiting on it, I'll go with a good-enough approach and make it more elegant later.

**Comment by jgm** [comment] 2019-09-11 15:51
Ah, I see.  Well, I don't have a specific timeline for a release, so there's still time to work on it.

**Comment by agusmba** [comment] 2019-09-13 09:18
> Sections are actually fairly useful in the docx Writer ...

Are you referring in the end to section jumps in the final docx also? If so, that'd give me pause.
Word document styling gets noticeably complicated once you start using sections. Unfortunately 95% of Word users don't know how to properly deal with them (I completely made that up).
It's not that it's really complicated just a big hassle that can wreak havoc in your document if you're not careful.

**Comment by jkr** [comment] 2019-09-13 12:28
Yeah, I am talking about the writer there. it might be better left for filters. I don't know. The two main use cases I come across, and need to use the filter to inject the ooxml for, are both for typesetting full book manuscripts in docx (which humanities publishers are still pretty insistent on -- I imagine some dissertation committees are pretty insistent on docx as well):

1. Lower-case roman page-numbering for front-matter, and
2. Restarting footnote numbering with each chapter 

Both are essential, and both require sections. 

But I can also see the point that sections will create unforeseen consequences if people aren't careful with their `reference.docx`. But that goes for a lot of things.

Anyway, this is off-topic for this change, which I'll do without sections. I'll probably put up something for discussion later. In the meantime, I'll try to publish my filter.

**Comment by jkr** [comment] 2019-09-22 17:56
BTW, I've just been waiting for the style changes to stabilize on this.

**Comment by jgm** [comment] 2019-09-26 18:27
Style changes have been merged now.

**Comment by jgm** [comment] 2019-10-09 05:55
@jkr is something still blocking this?
I'd be fine with a fix that just ignores the section stuff, for now.

**Comment by jgm** [comment] 2019-11-03 19:49
@jkr I'm getting close to clearing the issues on the 2.8 milestone.  It would really be nice to get this one in there: what is the state of things?

**Comment by jkr** [comment] 2019-11-04 01:08
Compiling as we speak -- trying to get it done tonight. Should have an update in an hour or so. Sorry again for the state of my attention...

**Closed** 2019-11-04 02:33 UTC
Labels: format:Docx, reader

**Comment by jgm** [comment] 2019-11-04 06:30
Excellent, thanks!

**Comment by conor909** [comment] 2019-11-28 14:18
I'm using a reference.docx file but the RTL formatting doesn't work at all, will the updates fix this ?

**Comment by jkr** [comment] 2019-11-28 14:51
If you're using a reference.docx, you're probably taking about the docx writer. This was a bug in the docx reader. 

If you do file a bug in the proper place, you will need to be more clear about what "doesn't work at all" means. What do you expect to happen? What actually happens? What version are you using? Including a sample input file and the reference.docx file you're using will also help.

**Comment by conor909** [comment] 2019-11-28 15:05
well after saving RTL formatting on text in my reference file, it isn't applying RTL formatting to to the text in my outputted file - but sorry for pissing in your cornflakes @jkr I'll ask somewhere else
