### ISSUE TITLE
pandoc docx styles doesnt support TOC

### ISSUE THREAD

**Issue by ghodsizadeh** [jgm/pandoc#6886] opened 2020-11-24 14:04 UTC
I think there is a bug in Docx style that it's not understandable by `pandoc` itself  when converting it to  EPUB:
To reproduce the problem create a Word document and add some heading1 and some heading2 and save the file.
when you convert that word to epub you'll find an epub with clean TOC, but when you convert main Docx to another Docx using pandoc and again convert it to epub you will find that headings are heading (in style) but they are not in TOC.
I ask a question in [StackOverflow](https://stackoverflow.com/questions/64988085/create-table-of-contents-in-epub-when-converting-from-docx-pandoc) but I think its a bug (or missing feature) in converting to Docx files.

**Comment by jgm** [comment] 2020-11-24 18:17
If you want us to investigate this, we need more than this (as stated in the boilerplate text on the issue).  Pandoc version and a complete example that suffices to reproduce the problem, including the exact commands used.

**Comment by tarleb** [comment] 2021-05-06 08:52
Closing for lack of info, and because I believe this to be a duplicate of #5810 and #5893.

**Closed by tarleb** 2021-05-06 08:52 UTC
Labels: format:Docx, reader, status:more-info-needed
