### ISSUE TITLE
Pandoc ignores \underline{} in Latex input

### ISSUE THREAD

**Issue by dangrec** [jgm/pandoc#3868] opened 2017-08-23 07:03 UTC
pandoc 1.19.2.1

A latex file as follows

\documentclass{article}
\begin{document}
I want \underline{some text} underlined.
\end{document}

put through pandoc as follows:
pandoc -f latex test.tex -t native -o test.atx

produces file test.atx as follows:

[Para [Str "I",Space,Str "want",Space,Str "underlined."]]

Can pandoc underline this text?

Thanks!

**Comment by mb21** [comment] 2017-08-23 08:42
Currently not...

Duplicate of #2264

**Closed** 2017-08-23 08:42 UTC
