### ISSUE TITLE
Markdown header attributes with definition lists

### ISSUE THREAD

**Issue by rsmith-fhiso** [jgm/pandoc#1959] opened 2015-02-19 19:52 UTC
It seems to me it would be both useful and logical if when both the `header_attributes` and `definition_lists` extensions were enabled, header attributes were permitted on definition term lines.  For example, 

```
Term {#term}
    A paragraph giving its definition.
```

... should generate the following HTML:

```
<dl>
<dt id="term">Term</dt>
<dd>A paragraph giving its definition.</dd>
</dl>
```

**Comment by ousia** [comment] 2015-02-20 06:22
@rsmith-fhiso :+1:

But why limit this only to definition lists? Or even to lists?

**Comment by mpickering** [comment] 2015-02-20 09:21
The implementation overhead is quite high as most formats don't support arbitrary attributes on elements.

**Comment by rsmith-fhiso** [comment] 2015-02-20 10:35
I was limiting it to <dl>s because there seems to be strong case for that.  A common (and the originally intended) use for a <dl> is a list of definitions, for example in a glossary.  When used like that it's common and reasonable to want to link a use of the term in text to its definition.  That seems a stronger case than the case for `header_attrbitutes` on arbitrary elements, though I'm certainly not against a broader implementation.

**Comment by ousia** [comment] 2015-02-20 18:23
> The implementation overhead is quite high as most formats don't support arbitrary attributes on elements.

@mpickering, I would limit these attributes to three special ones: `:class`, `#id` and `:lang`.

I think this is a reasonable implementation.

Right now, not even the YAML `lang` field works for LaTeX. And the issue is that TeX has hyphenation enabled by default.

So, if one happens to write documents other than US English, there is a need for a workaround in LaTeX because of this.

**Comment by bpj** [comment] 2017-03-17 17:12
This works quite well and isn't very obtrusive with bracketed spans:

    [Term]{#term}

    :   A paragraph giving its definition.

Even `Term []{#Term}` works if the brackets around the actual term bother you, although the HTML or LaTeX output looks a bit funny.

**Comment by jgm** [comment] 2017-03-18 13:46
I agree with @bpj; the existing syntax for ids on spans is enough, and we don't need other changes.
Closing.

**Closed by jgm** 2017-03-18 13:46 UTC
Labels: AST change, complexity:high, enhancement

**Comment by Mpic** [comment] 2020-03-03 08:23
> 
> 
> This works quite well and isn't very obtrusive with bracketed spans:
> 
> ```
> [Term]{#term}
> 
> :   A paragraph giving its definition.
> ```
> 
> Even `Term []{#Term}` works if the brackets around the actual term bother you, although the HTML or LaTeX output looks a bit funny.

Does this require some filter or extension enabled ? It does not work for me, pandoc says that reference `term` is not found when I try to cite it with `@term`.  
How are we supposed to use it ?

**Comment by jgm** [comment] 2020-03-03 17:22
Citing with `@term` will only work for example lists.  It isn't a general syntax for references.

**Comment by Mpic** [comment] 2020-03-04 11:18
What do you mean with "example lists" ? Is it not "definition lists", like the example shown ? 

```
[Term]{#term}

:   A paragraph giving its definition.
```

**Comment by bpj** [comment] 2020-03-04 11:36
They are distinct:

https://pandoc.org/MANUAL.html#numbered-example-lists

https://pandoc.org/MANUAL.html#definition-lists

Numbered examples and references to them are quite common in academic works
in some fields, e.g. linguistics, but seldom seen elsewhere for obvious
reasons.


Den ons 4 mars 2020 12:19Mpic <notifications@github.com> skrev:

**Comment by Mpic** [comment] 2020-03-04 13:29
Thanks !

Ok then, how am I supposed to reference the term identified by `#term`, as you suggested earlier ?

**Comment by jgm** [comment] 2020-03-04 16:34
You can use a regular internal link `[like this](#term)`.

**Comment by Mpic** [comment] 2020-03-05 10:02
Oh, I see. Thank you for the clarification !
