### ISSUE TITLE
Incorrect text modifier output for haddock markdown links

### ISSUE THREAD

**Issue by expipiplus1** [jgm/pandoc#2507] opened 2015-11-09 17:41 UTC
When writing a link in italics into Haddock markdown pandoc outputs `<link /label/>` when the correct output should be `/<link label>/`

Haddock interprets the `label` text literally without any modifiers.

**Comment by jgm** [comment] 2015-11-09 18:38
The problem is that the type of the link label (in Pandoc)
is [Inline].  So the link label can contain arbitrary
formatting.  In the special case where it is
[Emph [Str "blah"]], you could put the italics around
the link.  But in general, this kind of transformation
won't be possible.

I think that the cleanest solution, if formatting is not
allowed in the link label, is just to remove all formatting
from the label ("stringify").

+++ Joe Hermaszewski [Nov 09 15 09:41 ]:

**Comment by expipiplus1** [comment] 2015-11-09 18:44
Removing all formatting would certainly be better than what's done at the moment.

How tricky would be be to lift `Emph` and friends around the link in simple cases like this?

**Comment by jgm** [comment] 2015-11-09 18:54
+++ Joe Hermaszewski [Nov 09 15 10:44 ]:
>   Removing all formatting would certainly be better than what's done at
>   the moment.
>
>   How tricky would be be to lift Emph and friends around the link in
>   simple cases like this?

This could be done -- just pattern match on [Emph xs] and add
a special clause for that -- but it seems like an ad hoc special case.

**Comment by jgm** [comment] 2015-11-20 04:17
Closed by 995f28ff0756ad2d3edb63ee073137b42ff6f17e

**Closed by jgm** 2015-11-20 04:17 UTC
