### ISSUE TITLE
Some questions about using tex files and the docx writer 

### ISSUE THREAD

**Issue by petobens** [jgm/pandoc#2571] opened 2015-12-03 17:35 UTC
Consider the following `foo.tex` file:

```tex
\documentclass[leqno]{article}

\usepackage{amsmath}
\renewcommand{\L}{\ensuremath{\operatorname{\mathcal{L}}}}

\begin{document}

% Sections are not numbered in docx:
\section{Numbered section}

% Using renewcommand fails
\begin{equation*}
  \frac{\partial \L}{\partial q(\omega)} = 0
\end{equation*}

% Using \nonumber issue:
\begin{align}
  \sigma & = 2\\
  \delta  & = 3\nonumber
\end{align}
\end{document}
```
which gives:

![balhh1](https://cloud.githubusercontent.com/assets/2583971/11568273/fe97bbb8-99c9-11e5-8666-dcf067bc9813.png)

If I now run `pandoc -s foo.tex -o foo.docx` I get (Word 2016):
![blahh](https://cloud.githubusercontent.com/assets/2583971/11568294/14d05228-99ca-11e5-8f64-4673344c8b67.png)

So my questions are:
i) is it possible to number sections (and equations, figures, tables, etc)? According  to #742 it seems it is still not possible
ii) Why  does the usage of `\renewcommand` fail in the first equation?
iii) Why does using `\nonumber` fail in the second equation?

Thanks in advance! (great tool BTW)

**Comment by jgm** [comment] 2015-12-03 18:00
i) Yes, you can number sections.  Just add `--number-sections` to the command line.  You can number equations if you put them in pandoc "example lists"; however, they won't be numbered by default.

ii) The equations ought to be turned into native Word equations; the fact that they aren't indicates that texmath (the library used for this) is having trouble parsing them.  In the case of the first equation, the problem is

```
% texmath
\frac{\partial {\ensuremath{\operatorname{\mathcal{L}}}}}{\partial q(\omega)} = 0
orname{\mathcal{L}}}}}{\partial q(\omega
                   ^
unexpected "}"
expecting "%", "\\label" or whitespace
```
I need to look into this; I can't see why texmath is tripping on this.  But do you see a problem with the macro expansion itself?  `\L` was replaced by its definition (with surrounding braces), wasn't it?

iii) texmath doesn't understand `\nonumber`.  You can work around this by adding `\renewcommand{\nonumber}{}`.

**Comment by jgm** [comment] 2015-12-03 18:07
OK, I see the issue with `\operatorname`.  Currently texmath assumes that a math operator will be a simple string (so there's no room for styling like `\mathcal`).  That's apparently too restrictive for LaTeX (I'm not sure off the top of my head about the other formats texmath supports).

Can you open an issue on jgm/texmath with the simple example

    \operatorname{\mathcal{L}}

asking for better support of this case?
Also a separate issue to support (i.e. ignore) `\nonumber`.

Both these issues need to be addressed in texmath.

**Comment by jgm** [comment] 2015-12-03 18:07
Closing here since these are texmath issues.

**Closed by jgm** 2015-12-03 18:07 UTC

**Comment by petobens** [comment] 2015-12-03 18:47
Hi @jgm, thanks for the quick reply. I opened the corresponding issues on texmath as requested. 

Regarding the section numbering, I tried running both `pandoc -s --number-sections foo.tex -o foo.docx` and `pandoc -s -N foo.tex -o foo.docx` on the following `foo.tex` file:

```tex
\documentclass{article}
\begin{document}
\section{First section}
\subsection{First subsection}
\subsubsection{First subsubsection}
\end{document}
```

but I get:
![asdkalsdakls](https://cloud.githubusercontent.com/assets/2583971/11570265/0e20bf66-99d5-11e5-897b-d59c69d2fb77.png)


Am doing something wrong? (maybe it is an issue with Word 2016?) 
Once again thanks for your help.

**Comment by jgm** [comment] 2015-12-03 19:08
Oh, I should have read the man page;

       -N, --number-sections
              Number section headings in LaTeX, ConTeXt, HTML, or EPUB output.
              By default, sections are  not  numbered.   Sections  with  class
              unnumbered  will never be numbered, even if --number-sections is
              specified.

It's not implemented in docx yet.

**Comment by jgm** [comment] 2015-12-03 19:08
You might use a filter to add section numbers, for now.

**Comment by petobens** [comment] 2015-12-03 19:46
> You might use a filter to add section numbers, for now.

Thanks for the tip. Which filter is recommended (i.e works with docx files)  to add section, equation, figures and table numbering?  I tried [this one](https://github.com/lierdakil/pandoc-crossref/issues/41) without much success.

On a side note, one last question regarding equations: with the following `foo.tex` fie:

```tex
\documentclass{article}
\usepackage{amsmath}
\begin{document}
\begin{equation*}
\int_{\omega \in \Omega}\!p(\omega)q(\omega)\,d \omega
\end{equation*}
\begin{equation*}
\int_{\omega \in \Omega}p(\omega)q(\omega)\,d \omega
\end{equation*}
\end{document}
```

I get (on Word): 

![asdas](https://cloud.githubusercontent.com/assets/2583971/11571827/11d35c9c-99dd-11e5-989a-aa85d4fe816f.png)
 
instead of:
![fad](https://cloud.githubusercontent.com/assets/2583971/11571865/3ae4a3c0-99dd-11e5-89e0-a192467f806c.png)


Should I open another issue on texmath?

**Comment by jgm** [comment] 2015-12-11 20:42
Yes, please open another issue on texmath for this second thing (which I can confirm).
Here is the OMML output produced by texmath for the first equation:
```
<math display="block" xmlns="http://www.w3.org/1998/Math/MathML">
  <mrow>
    <msub>
      <mo>∫</mo>
      <mrow>
        <mi>ω</mi>
        <mo>∈</mo>
        <mi>Ω</mi>
      </mrow>
    </msub>
    <mspace width="-0.167em" />
    <mi>p</mi>
    <mo stretchy="false" form="prefix">(</mo>
    <mi>ω</mi>
    <mo stretchy="false" form="postfix">)</mo>
    <mi>q</mi>
    <mo stretchy="false" form="prefix">(</mo>
    <mi>ω</mi>
    <mo stretchy="false" form="postfix">)</mo>
    <mspace width="0.167em" />
    <mi>d</mi>
    <mi>ω</mi>
  </mrow>
</math>
```
and for the second:
```
<math display="block" xmlns="http://www.w3.org/1998/Math/MathML">
  <mrow>
    <msub>
      <mo>∫</mo>
      <mrow>
        <mi>ω</mi>
        <mo>∈</mo>
        <mi>Ω</mi>
      </mrow>
    </msub>
    <mi>p</mi>
    <mo stretchy="false" form="prefix">(</mo>
    <mi>ω</mi>
    <mo stretchy="false" form="postfix">)</mo>
    <mi>q</mi>
    <mo stretchy="false" form="prefix">(</mo>
    <mi>ω</mi>
    <mo stretchy="false" form="postfix">)</mo>
    <mspace width="0.167em" />
    <mi>d</mi>
    <mi>ω</mi>
  </mrow>
</math>
```

**Comment by jgm** [comment] 2015-12-11 20:50
Apologies, that was MathML output.  Here's the OMML output for the first equation:
```
<m:oMathPara>
  <m:oMathParaPr>
    <m:jc m:val="center" />
  </m:oMathParaPr>
  <m:oMath>
    <m:nary>
      <m:naryPr>
        <m:chr m:val="∫" />
        <m:limLoc m:val="subSup" />
        <m:supHide m:val="off" />
        <m:supHide m:val="off" />
      </m:naryPr>
      <m:e />
      <m:sub>
        <m:r>
          <m:rPr />
          <m:t>ω</m:t>
        </m:r>
        <m:r>
          <m:rPr />
          <m:t>∈</m:t>
        </m:r>
        <m:r>
          <m:rPr />
          <m:t>Ω</m:t>
        </m:r>
      </m:sub>
      <m:sup />
    </m:nary>
    <m:r>
      <m:rPr />
      <m:t>p</m:t>
    </m:r>
    <m:r>
      <m:rPr />
      <m:t>(</m:t>
    </m:r>
    <m:r>
      <m:rPr />
      <m:t>ω</m:t>
    </m:r>
    <m:r>
      <m:rPr />
      <m:t>)</m:t>
    </m:r>
    <m:r>
      <m:rPr />
      <m:t>q</m:t>
    </m:r>
    <m:r>
      <m:rPr />
      <m:t>(</m:t>
    </m:r>
    <m:r>
      <m:rPr />
      <m:t>ω</m:t>
    </m:r>
    <m:r>
      <m:rPr />
      <m:t>)</m:t>
    </m:r>
    <m:r>
      <m:rPr />
      <m:t> </m:t>
    </m:r>
    <m:r>
      <m:rPr />
      <m:t>d</m:t>
    </m:r>
    <m:r>
      <m:rPr />
      <m:t>ω</m:t>
    </m:r>
  </m:oMath>
</m:oMathPara>
```
interestingly, Word has an option to "hide the superscript."  When I did that, it produced:

    <m:oMath>
          <m:nary>
            <m:naryPr>
              <m:chr m:val="∫" />
              <m:limLoc m:val="subSup" />
              <m:supHide m:val="off" />
              <m:supHide m:val="off" />
            </m:naryPr>
            <m:e />
            <m:sub>
              <m:r>
                <m:rPr />
                <m:t>ω</m:t>
              </m:r>
              <m:r>
                <m:rPr />
                <m:t>∈</m:t>
              </m:r>
              <m:r>
                <m:rPr />
                <m:t>Ω</m:t>
              </m:r>
            </m:sub>
          </m:nary>
          <m:r>
            <m:rPr />
            <m:t>p</m:t>
          </m:r>
          <m:r>
            <m:rPr />
            <m:t>(</m:t>
          </m:r>
          <m:r>
            <m:rPr />
            <m:t>ω</m:t>
          </m:r>
          <m:r>
            <m:rPr />
            <m:t>)</m:t>
          </m:r>
          <m:r>
            <m:rPr />
            <m:t>q</m:t>
          </m:r>
          <m:r>
            <m:rPr />
            <m:t>(</m:t>
          </m:r>
          <m:r>
            <m:rPr />
            <m:t>ω</m:t>
         </m:r>
          <m:r>
            <m:rPr />
            <m:t>)</m:t>
          </m:r>
          <m:r>
            <m:rPr />
            <m:t> </m:t>
          </m:r>
          <m:r>
            <m:rPr />
            <m:t>d</m:t>
          </m:r>
          <m:r>
            <m:rPr />
            <m:t>ω</m:t>
          </m:r>
        </m:oMath>

**Comment by jgm** [comment] 2015-12-11 21:08
Okay, there was a dumb typo in texmath -- I've just fixed it, and the fix should solve the problem about the little boxes where the superscripts would go

**Comment by jgm** [comment] 2015-12-11 21:21
On the other issue, with the `\!`:  you can fix this by putting brackets around the expression:

    \int_{\omega \in \Omega}{\!p(\omega)q(\omega)\,d \omega}

That tells the parser that the whole thing is the "base argument (`m:e`)" for the integral.  Otherwise the parser just takes `\!` to be the argument, and since OMML doesn't allow negative spaces, the argument becomes empty.

**Comment by jgm** [comment] 2015-12-11 21:22
No need to open a texmath issue for the second issue now.

**Comment by petobens** [comment] 2015-12-11 21:37
Thank you!!
