### ISSUE TITLE
closing of span wrapping tex failure

### ISSUE THREAD

**Issue by Thell** [jgm/pandoc#2243] opened 2015-06-22 20:18 UTC
`pandoc 1.14.0.4`

__Input:__
```
<p>
<span class="foo">
\begin{equation*}
1
\end{equation*}
</span>
</p>


<div class="foo">
\begin{equation*}
2
\end{equation*}
</div>


<span class="foo">
\begin{equation*}
2
\end{equation*}
</span>

Notice the incorrect p tags.

```

`~/.cabal/bin/pandoc SpanError.md --from markdown --to html --mathjax`

__Output:__

```
<p>
<span class="foo">
\begin{equation*}
1
\end{equation*}
</span>
</p>
<div class="foo">
\begin{equation*}
2
\end{equation*}
</div>
<span class="foo">
\begin{equation*}
2
\end{equation*}
<p></span></p>
<p>Notice the incorrect p tags.</p>
```

**Comment by jgm** [comment] 2015-06-26 20:58
Do you need to use a span here?  Why not use a div?

The problem is that pandoc parses `\begin{equation*}...\end{equation*}` as a raw LaTeX block (all LaTeX environments are treated as block-level).  Span, by contrast, is inline-level, and you can't have block-level elements inside span tags.  So the opening and closing span tags get broken up into separate blocks.  The first one goes into a Plain block, because there is no whitespace after it, and the second one goes into a Para block.  I hope this explains what you're seeing.

**Comment by Thell** [comment] 2015-06-26 21:18
Yep, perfect explanation; and, span wasn't required, a div worked fine for what I was doing. Still getting used to having raw LaTeX blocks being used on --to html; which I am truly liking a lot!

I had been using spans to wrap math blocks when wrapped in mathjax delims, so using a div instead should be a minor thing in most cases.

Thanks.

**Closed** 2015-06-28 01:15 UTC
