### ISSUE TITLE
enhancement: comma as decimal separator in other languagues

### ISSUE THREAD

**Issue by Konfekt** [jgm/pandoc#4124] opened 2017-12-05 15:55 UTC
If the `lang` attribute is for example `de, fr, es` (see https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html for other examples), then compile the comma `,` in math mode as a decimal separator if not followed  by a space. For example `$0,5$ km` means half a kilometer, and not `0` and `5` kilometers.

**Comment by Konfekt** [comment] 2017-12-05 16:01
This is what the `icomma` package in `TeX` achieves. For `HTML` for example, there may be other means.

**Comment by mb21** [comment] 2017-12-05 16:01
You're converting from markdown to what? And what should the exact output be?

**Comment by Konfekt** [comment] 2017-12-05 16:10
For example, to `HTML`. At the moment, from the `HTML` output, it seems that `0,5` is interpreted as a list of numbers, even if `lang` is for example `de`, say, where it is a decimal separator.

**Comment by mb21** [comment] 2017-12-05 16:12
So what's the proposed output of `echo '$0,5$' | pandoc`, or `echo '$0,5$' | pandoc --mathjax` ?

**Comment by Konfekt** [comment] 2017-12-05 16:24
We have
```sh
--- ~ » echo '$0,5$' | pandoc
<p><span class="math inline">0, 5</span></p>
```
If `lang = fr`, for example, most languages other than `en`, then proposed is
```sh
<p><span class="math inline">0,5</span></p>
```
(no space between 0 and 5) and only if there is a space (and if `lang = fr`), then 
```sh
--- ~ » echo '$0,5$' | pandoc
<p><span class="math inline">0, 5</span></p>
```

**Comment by mb21** [comment] 2017-12-05 16:30
Pandoc has already some such things with the [smart extension](http://pandoc.org/MANUAL.html#extension-smart)

But the dollars are actually a `math` environment, so I'm not sure most people would appreciate spaces being inserted in some cases.

You can always insert the spaces by hand, or write a [filter](https://pandoc.org/scripting.html) that implements a heuristic...

**Comment by Konfekt** [comment] 2017-12-05 16:34
The problem is that I would like to *remove* the spaces inserted by pandoc. This seems more complicated. In `TeX`, this can be achieved by `0{,}5` or `0,\!5`.

Well, for `HTML` a workaround seems to leave `0,5` as text, that is `$\eta =$ 0,5` instead of `\eta=0,5`. Then the spacing is correct.

**Comment by mb21** [comment] 2017-12-05 16:40
> In `TeX`, this can be achieved by `0{,}5` or `0,\!5`.

I guess this could be implemented in https://github.com/jgm/texmath, which is what pandoc uses under the hood.

**Comment by jgm** [comment] 2017-12-05 17:23
The problem is this.  For "fake it with unicode mode",
pandoc passes the math to texmath and uses its Pandoc
renderer.  But information about what the language is
is not available to texmath.

I'd suggest using one of the workarounds suggested by @mb21.

>     In TeX, this can be achieved by 0{,}5 or 0,\!5.

**Comment by Konfekt** [comment] 2017-12-05 21:36
Ok, it does not surprise that texmath cannot detect the language because it was probably inconceivable from the outset why the tongue would matter to texmath (math notation is international).

The suggested workaround is writing a filter as explained in https://pandoc.org/scripting.html . 

As a user, an easier workaround would be an explicit negative space after the comma. Would it also be possible to compile a negative space such as `\!` command by texmath?

**Comment by jgm** [comment] 2017-12-05 22:03
texmath should be able to handle \!, have you tried it?

+++ Konfekt [Dec 05 17 21:36 ]:

**Comment by Konfekt** [comment] 2017-12-06 15:42
Yes, 
````html
--- ~ » echo '$0,\!5$' | pandoc 
<p><span class="math inline">0, ​5</span></p>
```
Despite the negative space, `pandoc` adds a space after the comma. 

It would be nice if `texmath` recognized `{,}` as a command to avoid that extra space. That is,
````html
--- ~ » echo '$0{,}5$' | pandoc 
<p><span class="math inline">0,5</span></p>
```
(There's no space after `,`).

**Comment by jgm** [comment] 2017-12-06 17:12
This may be a texmath issue.
```
% % texmath -t pandoc
0,\!5
^D
[Str "0",Str ",",Str "\8198",Str "\8203",Str "5"]
% texmath -t pandoc
0{,}5
^D
[Str "0",Str ",",Str "\8198",Str "5"]
```
The 8203 is a zero-width space, so that's good.  One might ask:  why do we also get the 8198, six-per-em space?  This is space added around certain symbols, in accord with Appendix G of the TeXBook.  See `addSpaces` in `src/Text/TeXMath/Writers/Pandoc.hs` in texmath.  Clearly we're not doing what latex does, since it doesn't insert the space in these cases (though it does for `0,5`).  So this needs adjustment.  Can you close this issue and open a new issue on jgm/texmath, copying this information?

**Comment by jgm** [comment] 2017-12-06 17:13
Further relevant information about how texmath parses this:
```
% texmath -t native
0{,}5
[ENumber "0",ESymbol Pun ",",ENumber "5"]
% texmath -t native
0,5
[ENumber "0",ESymbol Pun ",",ENumber "5"]
% texmath -t native
0,\!5
[ENumber "0",ESymbol Pun ",",ESpace ((-1) % 6),ENumber "5"]
```

**Comment by jgm** [comment] 2017-12-06 17:16
Never mind about opening teh issue, I'll do it.

**Comment by jgm** [comment] 2017-12-06 17:17
Opened jgm/texmath#107, closing this.

**Closed by jgm** 2017-12-06 17:17 UTC
