### ISSUE TITLE
newcommand not working for latex-beamer

### ISSUE THREAD

**Issue by strobelm** [jgm/pandoc#3295] opened 2016-12-09 15:33 UTC
Hi,

i'm writing a presentation in markdown and wanted to convert it to latex-beamer slides. It seems that newcommand is not supported by beamer:

talk.md
```
---
title:
- Test
date:
- today
header-includes:
  - \usepackage{amsmath}
---
\renewcommand{\C}{\mathbb{C}}
\newcommand{\R}{\mathbb{R}}

# Test
- $\C$
- $\R$
```

`pandoc talk.md  -o talk-beamer.pdf` works fine, result is correct
`pandoc talk.md -t beamer -o talk-slides.pdf` yields 

>  ! LaTeX Error: \C undefined.
> 
> See the LaTeX manual or LaTeX Companion for explanation.
> Type  H <return>  for immediate help.
>  ...                                              
>                                                   
> l.75 \end{frame}
> 
> pandoc: Error producing PDF

> pandoc --version
> pandoc 1.19
> Compiled with pandoc-types 1.17.0.4, texmath 0.9, highlighting-kate 0.6.3
> Default user data directory: /home/michael/.pandoc

Any idea if this is my fault or a bug?

**Comment by jgm** [comment] 2016-12-09 20:53
You're using `\renewcommand` for `\C` -- this only works if
the command `\C` has previously been defined.  Apparently
it is in defined by something in the default latex template,
but not by something in the default beamer template.

Try switching it to `\newcommand` and it should work.

**Comment by strobelm** [comment] 2016-12-10 09:14
Thanks for the hint! Unfortunately the problem is still there, even with newcommand:

```
\newcommand{\CCCC}{\mathbb{C}}
\newcommand{\RRRR}{\mathbb{R}}

# Test
- $\CCCC$
- $\RRRR$
```

> ! Undefined control sequence.
> \beamer@doifinframe ...} \tightlist \item \(\CCCC 
>                                                   \) \item \(\RRRR \) \end {...
> l.86 \end{frame}
> 
> pandoc: Error producing PDF
>

**Comment by strobelm** [comment] 2016-12-10 09:17
Probably here is the issue: 
output of pandoc -t beamer talk.md -o talk.tex
```
\begin{frame}

\newcommand{\CCCC}{\mathbb{C}}
\newcommand{\RRRR}{\mathbb{R}}

\end{frame}

\begin{frame}{Test}

\begin{itemize}
\tightlist
\item
  \(\CCCC\)
\item
  \(\RRRR\)
\end{itemize}

\end{frame}
```
I think newcommands should not be placed in a frame.

**Comment by jgm** [comment] 2016-12-10 09:26
In this case pandoc produces the following latex:
``` tex
\begin{frame}

\newcommand{\CCCC}{\mathbb{C}}
\newcommand{\RRRR}{\mathbb{R}}

\end{frame}

\begin{frame}{Test}

\begin{itemize}
\tightlist
\item
  \(\CCCC\)
\item
  \(\RRRR\)
\end{itemize}

\end{frame}
```
As @strobelm notes, the problem is that the newcommand is in a different frame; its effects are confined to the frame where it is defined.  Note that it will work fine if you move the newcommand statements into the slide where they're used.

Assuming you want the newcommands to affect the whole document, there are a couple things you could do:

1.  Put them in the preamble using header-includes in metadata.
2.  Put your slides under level-2 headers instead of level-1 headers; this way the content at the beginning will not be put in a slide (which you don't want anyway).

I think this resolves the issue, so I'll close it.

**Closed by jgm** 2016-12-10 09:26 UTC

**Comment by strobelm** [comment] 2016-12-10 09:35
Thanks a lot!
