### ISSUE TITLE
the number and text overlap

### ISSUE THREAD

**Issue by XiaTeng1993** [jgm/pandoc#4263] opened 2018-01-16 04:04 UTC
<img width="774" alt="machi 2018-01-16 12-02-20" src="https://user-images.githubusercontent.com/17228692/34971507-ef4cd342-fab5-11e7-90f2-5b5759453223.png">
I didn't find any documents to solve.

**Comment by jgm** [comment] 2018-01-16 04:48
Please see the contributing guidelines.
You should always provide the  pandoc version and exact instructions for reproducing the problem. In this case, we don't even know what the output format is.

**Comment by XiaTeng1993** [comment] 2018-01-16 05:10
I had that wrong. this's the info of problem.
version: 1.19.2.1
instructions:

```
pandoc -N -s --toc --toc-depth=3 \
--smart --template=template/template.latex --latex-engine=xelatex \
-V CJKmainfont='PingFang SC' -V mainfont='Monaco' -V geometry:margin=1in\
output/api.md \
-o output/api.pdf --wrap=preserve --columns=1 \
--from="markdown_github+grid_tables+header_attributes+yaml_metadata_block+raw_tex" \
-V tables=true -V lang=zh-cn \


```

**Comment by jgm** [comment] 2018-01-16 06:41
This still isn't enough, without the input file and custom template, we can't reproduce this.

**Comment by XiaTeng1993** [comment] 2018-01-16 07:15
Sorry...  this's a simple example.
Thank you for your attention.
[example.zip](https://github.com/jgm/pandoc/files/1633951/example.zip)

**Comment by mb21** [comment] 2018-01-16 10:28
This is most probably a LaTeX or XeTeX issue, from the pandoc MANUAL:

> To debug the PDF creation, it can be useful to look at the intermediate
> representation: instead of `-o test.pdf`, use for example `-s -o test.tex`
> to output the generated LaTeX.

You can then test it with `xelatex test.tex`.

**Comment by mb21** [comment] 2018-01-16 11:14
Also, your example doesn't appear to contain the mentioned input `api.md`... a minimal example input that reproduces the problem would be best.

**Comment by XiaTeng1993** [comment] 2018-01-16 11:33
I would like to thanks for your patience that  trying to solve my problem.  
   : ）

**Comment by mb21** [comment] 2018-01-16 11:37
You could modify your tempate.latex using this approach: https://tex.stackexchange.com/questions/296545/overlapping-numbers-and-titles-in-toc

**Comment by jgm** [comment] 2018-01-17 17:19
Closing, since this is a latex template customization issue.

**Closed by jgm** 2018-01-17 17:19 UTC
Labels: status:more-info-needed
