### ISSUE TITLE
org-reader: Parse image and table label

### ISSUE THREAD

**Issue by michelk** [jgm/pandoc#2999] opened 2016-06-26 09:12 UTC
- The org-reader does not read the image and table label.
- Cross-references are not rendered correctly.

cc @tarleb   

# Minimal example
## Org-file: 

```org
As illustrated in figure [[fig:myfig]], ... and listed in table [[tab:mytab]]

#+CAPTION: My figure.
#+LABEL: fig:myfig
[[blub.png]]


#+CAPTION: My table.
#+LABEL: tab:mytab
 | Name | Value |
 |------+-------|
 | Uno  |     1 |
 | Due  |     2 |

```

## Expected Latex
```latex
As illustrated in figure \ref{fig:myfig}, \ldots{} and listed in table
\ref{tab:mytab}

\begin{figure}[htbp]
\centering
\includegraphics{blub.png}
\caption{My figure}
\label{fig:myfig}
\end{figure}

\begin{longtable}[]{@{}ll@{}}
\caption{My table}\label{tab:mytab}\tabularnewline
\toprule
Name & Value\tabularnewline
\midrule
\endfirsthead
\toprule
Name & Value\tabularnewline
\midrule
\endhead
Uno & 1\tabularnewline
Due & 2\tabularnewline
\bottomrule
\end{longtable}
```

## Actual latex
```latex
As illustrated in figure \url{fig:myfig}, \ldots{} and listed in table
\url{tab:mytab}

\begin{figure}[htbp]
\centering
\includegraphics{blub.png}
\caption{My figure}
\end{figure}

\begin{longtable}[]{@{}ll@{}}
\caption{My table}\tabularnewline
\toprule
Name & Value\tabularnewline
\midrule
\endfirsthead
\toprule
Name & Value\tabularnewline
\midrule
\endhead
Uno & 1\tabularnewline
Due & 2\tabularnewline
\bottomrule
\end{longtable}
```

**Comment by tarleb** [comment] 2016-06-26 18:56
Thanks for the report.  This is a duplicate of #2496, though info in that threat aren't fully correct any longer.

PR #3001 adds labels for figures.  Labeling tables is not possible at the moment. (@jgm, please correct me if I'm wrong.)

**Comment by jgm** [comment] 2016-06-27 00:50
Closing in favor of #2496

**Closed by jgm** 2016-06-27 00:50 UTC

**Comment by michelk** [comment] 2016-10-05 05:13
Org-mode

```org
As seen in fig. [[fig:1]]
```

Translates to latex:
```latex
As seen in fig. \url{fig:1}
```

I would expect
```latex
As seen in fig. \ref{fig:1}
```
Is it possible to fix this in the org-reader?

**Comment by tarleb** [comment] 2016-10-05 18:12
Unfortunately this is not a simple change. It requires, among other things, changes to pandoc's internal document model, which is always a lot of work.  See also #1299.

**Comment by jgm** [comment] 2016-10-06 08:52
I suppose the org reader could keep an internal count of
figure numbers, and insert the figure number as the
link text here.  That wouldn't require any changes to
pandoc-types at all.

+++ Albert Krewinkel [Oct 05 16 11:12 ]:

**Comment by tarleb** [comment] 2016-10-06 20:54
I'm probably being dense here again, but I don't see how this would work. From a quick grep it seems to me that the LaTeX writer won't output `\ref` no matter what. Am I misunderstanding something?

**Comment by michelk** [comment] 2016-10-07 06:19
I guess John means, that the org-reader could parse `[[fig:1]]` as a literal `1`.

But this approach fails for example when outputting a LaTeX report, where this could be `1.1`

**Comment by michelk** [comment] 2016-10-07 11:46
Meanwhile I would be happy with this workaround.

**Comment by jgm** [comment] 2016-10-09 20:21
+++ Michel Kuhlmann [Oct 06 16 23:19 ]:
>   I guess John means, that the org-reader could parse [[fig:1]] as a
>   literal 1.
>
>   But this approach fails for example when outputting a LaTeX report,
>   where this could be 1.1

Correct, but this is the best we could achieve with just
changes in the org reader.  A better solution would require
a complete (and probably complex) label/reference system in
pandoc.

**Comment by michelk** [comment] 2017-08-03 12:08
Any update with the numbering workaround?

**Comment by michelk** [comment] 2017-08-03 12:17
Or would you recommend a lua-filter?

**Comment by tarleb** [comment] 2017-08-05 20:45
Apologies, I'm currently short on time and cannot work on this right now.

I believe a filter-based solution should be possible.  Allowing lua filters to use a hierarchicalized version of the AST would probably help here (and would make the solution for tarleb/pandoc-org-presentations#1 *much* simpler).

**Comment by michelk** [comment] 2022-08-06 09:08
Is there any update with table-labels in the org-mode reader?

```org-mode
 #+CAPTION:  My caption.
 #+LABEL: tab:mytable
|      Year | Topic                                    |
|-----------+--------------------------------------|
```

`\label{tab:mytable}` still doesn't show up in latex.

**Comment by tarleb** [comment] 2022-08-06 09:38
Looks like a shortcoming of the LaTeX writer. Please open a new issue for this.

**Comment by michelk** [comment] 2022-08-06 11:36
I'm unsure, what to describe in the new issue. Should I just reference to this issue?

**Comment by michelk** [comment] 2022-08-07 06:42
Another question (maybe off-topic here): 

How could I pass image-width to LaTeX? `ATTR_HTML` or `ATTR_LATEX` doesn't seem to work.

```org-mode
#+CAPTION: My figure.
#+LABEL: fig:myfig
#+ATTR_HTML: :width \textwidth
[[blub.png]]
```

**Comment by tarleb** [comment] 2022-08-07 14:53
The pandoc-discuss mailing list would probably be a better place for these questions.

Re image width: use `#+ATTR_HTML: :width 100%`

Re labels on LaTeX tables: I've opened #8219 to keep track of the issue.
