### ISSUE TITLE
org-reader: regression with ATTR_HTML?

### ISSUE THREAD

**Issue by hrehfeld** [jgm/pandoc#7583] opened 2021-09-20 10:29 UTC
See #3222 

Hmm, is this a regression or intended behavior? ATTR_HTML were correctly parsed and associated to the images before, but now result in this weird AST with a RAW_BLOCK:

``` org
#+ATTR_HTML: :jpeg-quality 95
[[./DSC06738.jpg]]
[[./DSC06724.jpg]]

```
`pandoc --resource-path=src/photography/2017:~/tmp/foo.org --wrap=none --shift-heading-level-by=1 -f org -t json ~/tmp/foo.org | python -mjson.tool`

``` json
{
    "pandoc-api-version": [
        1,
        22
    ],
    "meta": {},
    "blocks": [
        {
            "t": "RawBlock",
            "c": [
                "org",
                "#+ATTR_HTML: :jpeg-quality 95"
            ]
        },
        {
            "t": "Para",
            "c": [
                {
                    "t": "Image",
                    "c": [
                        [
                            "",
                            [],
                            []
                        ],
                        [],
                        [
                            "./DSC06738.jpg",
                            ""
                        ]
                    ]
                },
                {
                    "t": "SoftBreak"
                },
                {
                    "t": "Image",
                    "c": [
                        [
                            "",
                            [],
                            []
                        ],
                        [],
                        [
                            "./DSC06724.jpg",
                            ""
                        ]
                    ]
                }
            ]
        }
    ]
}
```

This works:

``` org
#+ATTR_HTML: :jpeg-quality 95
[[./DSC06738.jpg]]

[[./DSC06724.jpg]]
```

``` json
{
    "pandoc-api-version": [
        1,
        22
    ],
    "meta": {},
    "blocks": [
        {
            "t": "Para",
            "c": [
                {
                    "t": "Image",
                    "c": [
                        [
                            "",
                            [],
                            [
                                [
                                    "jpeg-quality",
                                    "95"
                                ]
                            ]
                        ],
                        [],
                        [
                            "./DSC06738.jpg",
                            ""
                        ]
                    ]
                }
            ]
        },
        {
            "t": "Para",
            "c": [
                {
                    "t": "Image",
                    "c": [
                        [
                            "",
                            [],
                            []
                        ],
                        [],
                        [
                            "./DSC06724.jpg",
                            ""
                        ]
                    ]
                }
            ]
        }
    ]
}
```

```
pandoc 2.14.0.2
Compiled with pandoc-types 1.22, texmath 0.12.3, skylighting 0.10.5.1,
citeproc 0.4.0.1, ipynb 0.1.0.1
```

**Comment by jgm** [comment] 2021-09-20 15:50
It's easier to see what's happening using a simple `-t native`:
```
j% pandoc -f org -t native
#+ATTR_HTML: :jpeg-quality 95
[[./DSC06738.jpg]]
[[./DSC06724.jpg]]
^D
[ RawBlock
  ( Format "org" ) "#+ATTR_HTML: :jpeg-quality 95"
, Para
  [ Image
    ( "", [], [] ) []
    ( "./DSC06738.jpg", "" )
  , SoftBreak
  , Image
    ( "", [], [] ) []
    ( "./DSC06724.jpg", "" ) ] ]
```
But
```
% pandoc -f org -t native
#+ATTR_HTML: :jpeg-quality 95
[[./DSC06738.jpg]]
[ Para
  [ Image
    ( "", [], [ ( "jpeg-quality", "95" ) ] ) []
    ( "./DSC06738.jpg", "" ) ] ]
```

So if there's just one image in the paragraph (an "implicit figure"), the attributes are added.  Otherwise not.

**Comment by jgm** [comment] 2021-09-20 15:51
How does this work in Emacs org export?  Does the attribute get added to the single element following, or to all the elements in the paragraph, or what?

**Comment by jgm** [comment] 2021-09-20 15:53
To answer my own question, org gives the following html:
```html
<p jpeg-quality="95">
<img src="./DSC06738.jpg" alt="DSC06738.jpg" jpeg-quality="95" />
<img src="./DSC06724.jpg" alt="DSC06724.jpg" />
</p>
```
Oddly, the attribute is added BOTH to the paragraph and to the first inline element in it.  Is that really how it's supposed to work?

**Comment by hrehfeld** [comment] 2021-09-20 15:55
Ah, good idea to check what org does. Although it's not very sensible imho:

```
#+ATTR_HTML: :jpeg-quality 95
[[./DSC06738.jpg]]
[[./DSC06724.jpg]]
```
``` html
<p jpeg-quality="95">
<img src="./DSC06738.jpg" alt="DSC06738.jpg" jpeg-quality="95" />
<img src="./DSC06724.jpg" alt="DSC06724.jpg" /></p>
```

and
 
```
#+ATTR_HTML: :jpeg-quality 95
[[./DSC06738.jpg]]

[[./DSC06724.jpg]]
```

``` html
<div id="orgd2a9006" class="figure">
<p><img src="./DSC06738.jpg" alt="DSC06738.jpg" jpeg-quality="95" />
</p>
</div>


<div id="orgf5fff9e" class="figure">
<p><img src="./DSC06724.jpg" alt="DSC06724.jpg" /></p>
</div>
```

**Comment by hrehfeld** [comment] 2021-09-20 15:58
Not very helpful: https://orgmode.org/worg/dev/org-syntax.html#Affiliated_keywords

> With the exception of comment, clocks, headlines, inlinetasks, items, node properties, planning, property drawers, sections, and table rows, every other element type can be assigned attributes.
> 
> This is done by adding specific keywords, named “affiliated keywords”, just above the element considered, no blank line allowed.
> 
> Affiliated keywords are built upon one of the following patterns:
> 
> #+KEY: VALUE
> #+KEY[OPTIONAL]: VALUE
> #+ATTR_BACKEND: VALUE
> KEY is either “CAPTION”, “HEADER”, “NAME”, “PLOT” or “RESULTS” string.
> 
> BACKEND is a string constituted of alpha-numeric characters, hyphens or underscores.
> 
> OPTIONAL and VALUE can contain any character but a new line. Only “CAPTION” and “RESULTS” keywords can have an optional value.
> 
> An affiliated keyword can appear more than once if KEY is either “CAPTION” or “HEADER” or if its pattern is “#+ATTR_BACKEND: VALUE”.
> 
> “CAPTION”, “AUTHOR”, “DATE” and “TITLE” keywords can contain objects in their value and their optional value, if applicable.

**Comment by phmarek** [comment] 2021-12-22 12:22
Not sure whether it's the same problem, but it might be related (reproducible up to pandoc 2.16.2):

```org
#+ATTR_HTML: :width 100% :height 360px
[[file:....svg]]

#+ATTR_HTML: :width 100% :height 360px 
[[file:....svg]]
```

Please note the extra space at the end of the second `ATTR_HTML` line; with `pandoc % -o %.html` the result is this:

```html
<p><img src="....svg" style="width:100.0%" height="360" /></p>
<p><img src="....svg" style="width:100.0%" /></p>
```

Ie. an additional whitespace makes the last argument vanish trom the output!

**Comment by jgm** [comment] 2021-12-22 17:00
@tarleb may have more insight on this issue.

**Comment by tarleb** [comment] 2022-01-01 12:46
It seems to me that pandoc, while not doing the exact same thing org does, is close enough to org mode. Please re-open if you disagree and believe that we should improve pandoc's behavior.

@phmarek that looks like a separate issue which I fixed now in eae9be3a484b7046a9d8ca4eeca990b6a3719b0c.

**Closed by tarleb** 2022-01-01 12:46 UTC
Labels: bug, format:Org-mode, reader

**Comment by michelk** [comment] 2023-04-04 08:54
Is there still a regression with pandoc 3.1.2? 
```
pandoc -f org -t latex
#+ATTR_HTML: :width 40%
[[./IMAGE.png]]
\includegraphics[width=0.4\textwidth,height=\textheight]{./IMAGE.png}


pandoc -f org -t latex
#+LABEL: fig:image
#+ATTR_HTML: :width 40%
[[./IMAGE.png]]
\includegraphics[width=0.4\textwidth,height=\textheight]{./IMAGE.png}



pandoc -f org -t latex
#+CAPTION: My Caption.
#+LABEL: fig:image
#+ATTR_HTML: :width 40%
[[./IMAGE.png]]

\begin{figure}
\hypertarget{fig:image}{%
\centering
\includegraphics{./IMAGE.png}
\caption{My Caption.}\label{fig:image}
}
\end{figure}

```

**Comment by tarleb** [comment] 2023-04-04 09:59
@michelk Please describe the problem with the posted snippets.

**Comment by tarleb** [comment] 2023-04-04 10:16
Ah, you probably mean the missing label in the second case? Looks like a LaTeX writer issue. Would you raise a new issue so it won't get lost?

**Comment by michelk** [comment] 2023-04-04 10:17
Sorry for being unclear. I had the issue, that image-width is not considered in the third case.

**Comment by tarleb** [comment] 2023-04-04 11:11
Ah, I had missed that. Pandoc includes the width property on the *Figure* element, but the LaTeX writer doesn't use that information. This should probably be fixed in both the Org reader *and* the LaTeX writer.

**Comment by michelk** [comment] 2023-04-04 14:35
I opened a new issue: #8748
