### ISSUE TITLE
note block remove following line break

### ISSUE THREAD

**Issue by docsAsCode** [jgm/pandoc#6379] opened 2020-05-19 06:46 UTC
When i convert a RST file into asciidoc file, note blocks are well converted but they remove following line break : 

```rst
.. note::

  blabla

.. note::

  blabla

example
-----------
```

becomes

```asciidoc
[NOTE]
.Note
====
blabla
====[NOTE]
.Note
====
blabla
======== example
```

I use pandoc 2.9.2 with this command : 
```
pandoc -s -f rst -t asciidoc myfile.rst -o myfile.adoc
```

Thx

**Comment by jgm** [comment] 2020-05-19 15:58
Duplicate of #6308 which is already fixed in master.
(You can use a nightly if you like: see Actions.)

**Closed by jgm** 2020-05-19 15:58 UTC
