### ISSUE TITLE
Quotes after emphasis

### ISSUE THREAD

**Issue by twsh** [jgm/pandoc#2228] opened 2015-06-12 20:19 UTC
Pandoc doesn't correctly interpret the interaction of quotes and emphasis.

For example, a file 'foo.md' with content

```
*foo*'s 'foo'
```

produces the following output with `$ pandoc --to latex foo.md`:

```
\emph{foo}`s 'foo'
```

and with `pandoc --smart foo.md`:

```
<p><em>foo</em>‘s ’foo’</p>
```

**Comment by spetey** [comment] 2015-09-22 02:41
I've had the same issue. Wish I knew enough to help fix it.

**Comment by ltrgoddard** [comment] 2016-08-19 11:11
There is a related issue with abbreviations. For instance, the phrase `1950s, '60s and '70s`
renders with opening rather than closing smart quotes: `1950s, ‘60s and ‘70s`.

**Comment by jgm** [comment] 2016-08-20 12:13
Cannot reproduce this!

    % pandoc -S
    1950s, '60s and '70s
    ^D
    <p>1950s, ’60s and ’70s</p>

Those are closing quotes.

+++ Louis Goddard [Aug 19 16 04:11 ]:

**Comment by ltrgoddard** [comment] 2016-08-20 16:02
Apologies, I should have looked a bit closer before posting. I'venarrowed it down to abbreviations which precede single-quoted quotations. The following should reproduce the problem, but it also happens over much longer spans of text (e.g. a whole paragraph in my thesis):

`This is a sentence including an abbreviation such as '60s. This is a sentence including 'some quoted text'.` (Output should have an opening quote before the abbreviation and a closing quote before the quotation.)

I suppose this is only a major problem for British users like me who use single quotes for quotations.

**Comment by jgm** [comment] 2016-08-20 16:43
I think it's almost impossible to get these right in every
case.  After all, in something like

    '60s, ah, 'twas a great decade'

you'd WANT an open quote in from of 60s.  So, short of
building AI into pandoc, I think we need to close this.

You can always use literal unicode quote characters when
things get complicated like this.

+++ Louis Goddard [Aug 20 16 09:02 ]:

**Comment by ltrgoddard** [comment] 2016-08-20 16:46
Fair enough! I use a regex in my Makefile as a workaround anyway.

**Comment by jgm** [comment] 2017-03-13 20:25
jgm/cmark has a better algorithm for parsing emphasis and smart quotes, and it gets these cases right.  So it is possible---maybe that's a reason to leave this open.

**Closed** 2017-05-24 21:23 UTC
Labels: bug, format:Markdown, reader
