### ISSUE TITLE
Build error in pandoc 1.15.0.6

### ISSUE THREAD

**Issue by nek0** [jgm/pandoc#2443] opened 2015-10-08 07:32 UTC
When trying to build pandoc version 1.15.0.6 as a dependency of my own project, cabal aborts the build process with the following error:

```
src/Text/Pandoc/Shared.hs:756:49:
    Not in scope: type constructor or class ‘Archive’

src/Text/Pandoc/Shared.hs:777:38: Not in scope: ‘toEntry’

src/Text/Pandoc/Shared.hs:786:19:
    Not in scope: ‘toArchive’
    Perhaps you meant ‘mbArchive’ (line 778)

src/Text/Pandoc/Shared.hs:787:25: Not in scope: ‘addEntryToArchive’

src/Text/Pandoc/Shared.hs:787:43: Not in scope: ‘emptyArchive’

src/Text/Pandoc/Shared.hs:790:48:
    Not in scope: type constructor or class ‘Archive’

src/Text/Pandoc/Shared.hs:804:38: Not in scope: ‘toEntry’

src/Text/Pandoc/Shared.hs:813:19:
    Not in scope: ‘toArchive’
    Perhaps you meant ‘mbArchive’ (line 805)

src/Text/Pandoc/Shared.hs:814:25: Not in scope: ‘addEntryToArchive’

src/Text/Pandoc/Shared.hs:814:43: Not in scope: ‘emptyArchive’

src/Text/Pandoc/Shared.hs:820:27: Not in scope: ‘fromArchive’

src/Text/Pandoc/Shared.hs:822:27: Not in scope: ‘fromArchive’
```

The command to build pandoc was a simple `cabal install --only-dependencies`.

**Comment by jgm** [comment] 2015-10-08 16:24
That's bizarre.  I've never encountered this, and I can't
explain why you'd be seeing this.  These symbols are all
exported by Codec.Archive.Zip, which is imported unqualified
at the top of Text.Pandoc.Shared.

What ghc and cabal versions?  Can you see what version of
zip-archive is being installed?

+++ rys ostrovid [Oct 08 15 00:32 ]:

**Comment by nek0** [comment] 2015-10-08 19:06
ghc is version 7.10.2.
I have cabal-install 1.22.6.0 with the cabal library 1.22.4.0.
The installed zip-archive package in the sandbox is 0.2.3.7

Thanks for looking into that matter.

**Comment by jgm** [comment] 2015-10-08 19:32
I'm afraid I'm completely baffled, then.
I can't think of any reason you'd be getting the messages
you're getting.  Are you using any unusual ghc options or
global language features?

+++ rys ostrovid [Oct 08 15 12:06 ]:

**Comment by nek0** [comment] 2015-10-09 13:14
here is nothing unusual in the ghc options and I am using these Language extensions:
```
    extensions: TemplateHaskell
                QuasiQuotes
                OverloadedStrings
                NoImplicitPrelude
                CPP 
                MultiParamTypeClasses
                TypeFamilies
                GADTs
                GeneralizedNewtypeDeriving
                FlexibleContexts
                EmptyDataDecls
                NoMonomorphismRestriction
                DeriveDataTypeable
                ViewPatterns
                TupleSections
                RecordWildCards
```

By the way: I tried to build standalone pandoc, not as dependency and it worked. I'm also pretty baffled.

**Comment by jgm** [comment] 2015-10-09 17:36
NoImplicitPrelude could cause problems for pandoc and
its dependent libraries, if it were enabled globally
as a compile option (rather than per-file as a pragma).
Otherwise I don't see anything that helps here...

Try creating a simple project that uses pandoc as a
dependency and just does a simple conversion.  If that
works, then we know that the problem lies with some
difference btw that simple project and yours.

+++ rys ostrovid [Oct 09 15 06:14 ]:

**Comment by Zigazou** [comment] 2015-10-09 20:13
I have the same problem when I want to compile a personal project using pandoc (indirectly that is, because it is used by yesod-markdown).

Here are my program versions:

- ghc 7.10.2
- cabal-install 1.22.6.0
- cabal library 1.22.4.0
- stack 0.1.5.0
- zip-archive 0.2.3.7

On the contrary I have been able to individually compile Pandoc 1.15.1 on the same machine. The problem seems to exist in versions 1.14.* and 1.15.0.*

**Comment by jgm** [comment] 2015-10-09 20:28
Very weird.  I have never come across this.  It would be helpful if one of you could put together a very minimal project that suffices to reproduce this (something I could clone and try myself).

**Comment by Zigazou** [comment] 2015-10-09 20:49
In fact, on the source code obtained via `git clone https://github.com/jgm/pandoc.git`, doing a `cabal build` will correctly compile Pandoc 1.15.1. If I do a `cabal clean`, `git checkout tags/1.15.0.6` and `cabal build` again, I have the error.

Looking more closely, it seems to me it is due to the `import Codec.Archive.Zip` being incorrectly placed in the `#ifdef HTTP_CLIENT` in the 1.15.0.6 version of the `src/Text/Pandoc/Shared.hs` (line 153). In the 1.15.1, it is placed outside of any `#if` (line 140).

**Comment by jgm** [comment] 2015-10-09 21:10
Aha!  Yes, this was fixed in commit
ab7c5f22213d2963ea6dbbf2267a4a6ec7d5774d

So I think this issue can be closed, but it does point
to the need for a new release of pandoc soon.

Note that it should work, even on 1.15.0.6, if
HTTP_CLIENT is set.  This is set if the https
flag is set.  Perhaps your project had something
incompatible with the dependencies needed for
the https flag, and cabal tried a build plan
without this flag set.  You can set it manually
when you build your project, and that might help.

+++ Frédéric BISSON [Oct 09 15 13:49 ]:

**Closed** 2015-10-10 20:08 UTC
