### ISSUE TITLE
Suggestion: syntax for tables' column positions and/or sizes

### ISSUE THREAD

**Issue by adamryczkowski** [jgm/pandoc#3782] opened 2017-07-05 10:13 UTC
I am planning to implement an algorithm that will optimize the table layout, when there are cells with arbitrary spans. The algorithm will output the optimal position of each column dividing line. It would be nice, if you leave a spot in the specification for manual column sizes and/or positions. It would be ignored by all the writers except for those that deal with actual pixel rendering, like MSWord, PDF or HTML. 

It may be another use case for the (hopefully) forthcoming attributes https://github.com/jgm/pandoc/issues/684 .

**Comment by Wolf-at-SO** [comment] 2017-07-05 10:23
@adamryczkowski Am I right that column widths in Markdown cannot be specified? On a layout task for describing the meaning of icons (in a users manual): 1st col Icon, 2nd col description, I'm observing an oversized icon column when the image file (and path) names are long. 

I'm able to reduce its size using the `![ident]` + `[ident]: url` syntax. <sub>Am I overlooking something important?</sub>

**Comment by adamryczkowski** [comment] 2017-07-05 10:29
>Am I right that column widths in Markdown cannot be specified?
Correct me, if I am wrong. I couldn't see that. And note, that I ask for column width measured in actual physical medium length unit (such as mm), not in number of characters.

**Comment by adamryczkowski** [comment] 2017-07-05 11:04
@Wolf-at-SO 

>On a layout task for describing the meaning of icons (1st col: Icon, 2nd col: description), I'm observing an oversized icon column when the image file (and path) names are long.

I am afraid I don't know what you are referring to. I write about tables with text, not graphics/icons.

**Comment by Wolf-at-SO** [comment] 2017-07-05 11:20
@adamryczkowski ... now I'm unsure myself. It seems to be restricted to tables with multi-line cells, I'm just figuring out the cause of my problem ...

**Comment by Wolf-at-SO** [comment] 2017-07-05 14:35
@adamryczkowski I got it: it's the automatic table layout for [multiline tables](http://pandoc.org/MANUAL.html#extension-multiline_tables) which is unsatisfying. I tried to report this in #3783

**Comment by jgm** [comment] 2017-07-05 23:44
The current Table type already includes fields for
column widths (relative to textwidth).

**Comment by mb21** [comment] 2017-07-06 08:17
closing in favour of #1024

**Closed by mb21** 2017-07-06 08:17 UTC
