### ISSUE TITLE
raw tex not filtered if it includes \begin or \end

### ISSUE THREAD

**Issue by zeeMonkeez** [jgm/pandoc#3754] opened 2017-06-21 19:54 UTC
```
---
title: test
header-includes:
- \newcommand{\benv}{\begin{env}}
- \newcommand{\eenv}{\end{env}}
- \newcommand{\tenv}{test}
---

\benv
env1
\eenv

\begin{env}
env2
\end{env}

\tenv
```

Calling `pandoc rt.md -o rt.html` produces:

```
<p>\benv env1 \eenv</p>
```

Expected output:

```
<p>env1</p>
```

I would not expect the command definition of `\benv` and `\eenv`to be parsed, as that would be nontrivial, to produce output consistent with the `\begin{env}…\end{env}`. Instead, I would expect output consistent with behaviour from `\tenv`.

pandoc compiled from ea1724e.

**Comment by jgm** [comment] 2017-06-22 06:52
What version of pandoc?  With the dev version I get

     <p>env1 </p>

With 1.19.1 I get

     <p>env1 </p>
     <p></p>



+++ Jonas Zimmermann [Jun 21 17 12:54 ]:

**Comment by jgm** [comment] 2017-06-22 06:53
Sorry, I hadn't included your YAML header. Now I get what
you get, and I see that you're using the dev version.

**Comment by jgm** [comment] 2017-06-22 07:02
So the issue is that, when a macro for `\benv` is defined in
the document, it gets parsed as a plain string.  When no
macro is defined, things work as expected.  I'll have to
look into this.  I suspect the problem is that `\benv`
expands into something that can't be parsed either as an
inline or as a block element (since it's just part of a
block).  The real issue is that pandoc tries to resolve
the macros piecemeal, instead of resolving them and changing
the input stream.

See #982.  In fact, I think this can probably be closed
as a dup of #982.

**Closed** 2017-06-22 09:06 UTC
