### ISSUE TITLE
Crashing on listin formats on Windows 7

### ISSUE THREAD

**Issue by frank-freihube-rmcan-com** [jgm/pandoc#4379] opened 2018-02-19 11:59 UTC
When trying to list formats (both `--list-input-formats` and `--list-output-formats`) the output seems to be right but after the output the program crashes showing the Windows `pandoc.exe has stopped working` dialog.

Steps to reproduce:
+ open cmd.exe
+ navigate to pandoc installation path
+ call `pandoc --list-input-formats` or `pandoc --list-output-formats`

System:
Windows 7 SP1 64bit

**Comment by agusmba** [comment] 2018-02-19 14:56
This is already reported in https://github.com/jgm/pandoc/issues/4283 (in the comments you can see the problem is present with different parameters)

**Comment by jgm** [comment] 2018-02-19 22:30
Closing as a dup.

**Closed by jgm** 2018-02-19 22:30 UTC
