### ISSUE TITLE
Footnote numbering is wrong in inserted Titleblock content.

### ISSUE THREAD

**Issue by krfkeith** [jgm/pandoc#3200] opened 2016-11-01 01:08 UTC
I'm using titleblock variables to insert specific content into HTML output. In my template, I just of course reference the relevant variable. This normally works fine: markdown is correctly converted into HTML. However, this is one problem, if I try to use footnotes, the numbering is all wrong. As an example, let's suppose I have the following markdown.

    ---
    title: My Test Document
    author: John Doe
    date: 1 January 2016
    abstract: |
        This is my abstract.^[Here is a foonote in the abstract]

        Here's another paragraph
    ---

    Lorem ipsum dolor sit amet, equidem adolescens eu sea. Ius cu
    congue splendide reprimique. Has voluptua delectus ea.^[Here's a
    body footnote] Mel veniam debitis no, ius et choro tantas, ex illud
    latine iracundia sit.^[And here's another]

This yields an output something like the following:

***

# My Test Document
### Abstract
This is my abstract.<sup>[4](#)</sup>

Here's another paragraph

### Body
Lorem ipsum dolor sit amet, equidem adolescens eu sea. Ius cu
congue splendide reprimique. Has voluptua delectus ea.<sup>[1](#)</sup>
Mel veniam debitis no, ius et choro tantas, ex illud latine iracundia
sit.<sup>[2](#)</sup>

### Footnotes
1. Here's a body footnote
2. And here's another
3. Here is a foonote in the abstract

***

There are several things to notice here:

* The numbers are out of order: the footnote number in the abstract is [4] instead of [1]. (To be honest, this doesn't surprise me as much, since presumably titleblock data is processed after the body proper.)
* The numbers skip from [2] to [4]
* However, [3] is present in the footnote list.

Any idea on how I might et this to work how I want? Or am I just sunk?

**Comment by jkr** [comment] 2016-11-01 05:47
(Note that your code doesn't work, since the yaml with the equals sign isn't valid.)

Can't reproduce with the latest pandoc. Adding a simple abstract to the template, I get the correct output.

What version of pandoc are you using? How are you adding an abstract in your template.

@jgm -- one problem this did demonstrate: in output formats with separate footnotes and no abstract field in the template (org, rst, html) there will be the footnote from the abstract, but no abstract itself (using standalone and the default template). So, for example, with the default org template, we'd get:

~~~{.org}
#+TITLE: My Test Document

#+AUTHOR: John Doe
#+DATE: 1 January 2016

Lorem ipsum dolor sit amet, equidem adolescens eu sea. Ius cu congue
splendide reprimique. Has voluptua delectus ea.[2] Mel veniam debitis
no, ius et choro tantas, ex illud latine iracundia sit.[3]

[1] Here is a foonote in the abstract

[2] Here's a body footnote

[3] And here's another
~~~

**Comment by jgm** [comment] 2016-11-01 09:00
+++ Jesse Rosenthal [Oct 31 16 22:47 ]:
>   [1]@jgm -- one problem this did demonstrate: in output formats with
>   separate footnotes and no abstract field in the template (org, rst,
>   html) there will be the footnote from the abstract, but no abstract
>   itself (using standalone and the default template). So, for example,
>   with the default org template, we'd get:

True, but I don't see any reasonable solution.

**Comment by jkr** [comment] 2016-11-01 12:23
The only way I can see it working (pseudocode):

~~~
if standalone:
   my_template <- get template
   newmeta <- filter (in my_template) meta
   renderTemplate newmeta
fi
~~~

Not sure I can see from `doctemplates` how to achieve the filter step, tho.

**Comment by krfkeith** [comment] 2016-11-01 22:05
> (Note that your code doesn't work, since the yaml with the equals sign isn't valid.)

Oh thanks, that was a screw up on my part.

I've managed to reproduce the problem: apparently when using a custom writer, the erroneous footnote numbering arises. For reference, I'm using the provided ``sample.lua`` writer include with pandoc. Here is the command I'm using to compile the document with:

    pandoc --template=html.tmpl -t sample.lua test.md -o test.html

The file ``html.tmpl`` is just a modified version of the default HTML templated outputed with ``pandoc -D html`` which outputs the abstract.

**Comment by jgm** [comment] 2016-11-01 22:13
+++ krfkeith [Nov 01 16 15:05 ]:
>     (Note that your code doesn't work, since the yaml with the equals
>     sign isn't valid.)
>
>   Oh thanks, that was a screw up on my part.
>
>   I've managed to reproduce the problem: apparently when using a custom
>   writer, the erroneous footnote numbering arises. For reference, I'm
>   using the provided sample.lua writer include with pandoc. Here is the
>   command I'm using to compile the document with:
>pandoc --template=html.tmpl -t sample.lua test.md -o test.html

Yes, I guess that's because in the lua writer we have

    function Doc(body, metadata, variables)

and (the way the writers work) the parameters get evaluated
in order, so metadata last.  Not sure how to work around
this; we could change the argument order in Doc, but this
would break every existing filter!

**Comment by jgm** [comment] 2016-12-07 11:31
I'll mark this as a WontFix, I just don't see a good way to deal with this without breaking other stuff.

**Closed by jgm** 2016-12-07 11:31 UTC
