### ISSUE TITLE
latex-template release 2.14 / problem with german umlauts in yaml title option

### ISSUE THREAD

**Issue by cp-tanuki** [jgm/pandoc#7362] opened 2021-06-07 16:47 UTC
I encountered a problem with the use/encoding of german umlauts in the title option of yaml headers. When converted to pdf (via pdflatex) they are not properly displayed.

Minimal example (umlaut.md):

~~~
---
title: ÄÖÜäöü
---

ÄÖÜäöü
~~~

converted with

~~~
> pandoc umlaut.md -o umlaut.pdf
~~~

expected output

>**ÄÖÜäöü**
>
>ÄÖÜäöü

actual output

>**[some illegible symbols]**
>
>ÄÖÜäöü

After some investigation I traced back the problem to the revision of the latex template in release 2.14:

>Move title, author, date up to top of preamble (#7295). This allows header-includes to use them, and puts them in a position where you can see them immediately.

The source of the problem seems to be the "timing" in the preamble: In the current template the title-options (lines 33 ff.) are given *before* "\usepackage[utf8]{inputenc}" (line 133, enclosed in "\ifPDFTeX"). As a consequence the umlauts in the title are not displayed correctly while the umlauts in the document body are fine.

I tested putting the title-options after "\ifPDFTeX" and then everything worked as expected.

**Comment by jgm** [comment] 2021-06-08 01:12
One workaround is to use `--pdf-engine=xelatex`

**Comment by JohnLukeBentley** [comment] 2021-06-08 05:10
On pandoc v2.14.0.1, using the minimal example and command my output comes out fine:

![image](https://user-images.githubusercontent.com/18357541/121126333-56e77f80-c86b-11eb-909e-4941aa937ee1.png)

@jgm can you reproduce the error (the illegible symbols)?

**Comment by cp-tanuki** [comment] 2021-06-08 11:04
> One workaround is to use `--pdf-engine=xelatex`

@jgm Yes, I figured that out. But thank you anyway :-)

**Comment by cp-tanuki** [comment] 2021-06-08 11:43
> On pandoc v2.14.0.1, using the minimal example and command my output comes out fine:

@JohnLukeBentley Thanks for your reply! I tried reproducing the error on my linux (mint) machine (with pandoc 2.14.0.1) and -- as you said -- it doesn't show up.

I'm not sure though if this is due to the operating system (the error occurs on my windows 10 system with pandoc 2.14.0.1 and 2.14) or if it depends on the tex-distribution (on my windows machine I'm using MikTex 2.9 on my linux machine TexLive 2019).

Unfortunately this is about the limit of my tech knowledge so that I'm not able to do some further testing at this point.

(For the moment the best option for me is to downgrade to pandoc 2.13 on my windows machine.)

**Comment by jgm** [comment] 2021-06-08 11:44
I can't reproduce this either.

**Comment by jgm** [comment] 2021-06-08 11:44
> (For the moment the best option for me is to downgrade to pandoc 2.13 on my windows machine.)

I'd say using xelatex is a better option.

**Comment by mb21** [comment] 2021-06-08 11:50
@cp-tanuki have you tried updating your pdflatex version?

**Comment by JohnLukeBentley** [comment] 2021-06-08 12:37
@cp-tanuki a new version of MikTex (21.6) has just dropped ("6/8/2021"): https://miktex.org/download.

I recommend an upgrade from MikTex 2.9. Then try compiling (not using pandoc) a known good minimal tex document to force a download of basic packages.

I'm on Windows 10 and (have just upgraded to ...)

```
> pdflatex --version
MiKTeX-pdfTeX 4.6.1 (MiKTeX 21.6)
© 1982 D. E. Knuth, © 1996-2021 Hàn Thế Thành
...
```
At the time of my original post I was on `MiKTeX-pdfTeX 4.6 (MiKTeX 21.3)`. After my upgrade to `MiKTeX-pdfTeX 4.6.1 (MiKTeX 21.6)` I've reconfirmed that I still *can't* reproduce the problem. Which is good news for us all.

**Comment by cp-tanuki** [comment] 2021-06-08 17:14
> I recommend an upgrade from MikTex 2.9. Then try compiling (not using pandoc) a known good minimal tex document to force a download of basic packages.

@JohnLukeBentley @mb21 Thorough uninstall and upgrade to MikTex 2.9 did the trick!

Thank you all for your help!

**Comment by jgm** [comment] 2021-06-08 23:43
OK, then I'll close this without making any changes.

**Closed by jgm** 2021-06-08 23:43 UTC

**Comment by JohnLukeBentley** [comment] 2021-06-09 03:13
@cp-tanuki can I take it you meant you've upgraded *from*  MikTex 2.9? What does `pdflatex --version`, from the command line, return?

**Comment by cp-tanuki** [comment] 2021-06-09 07:14
>
> can I take it you meant you've upgraded _from_ MikTex 2.9? What does `pdflatex --version`, from the command line, return?

@JohnLukeBentley  Sorry, I meant 'upgrade to MikTeX 21.6'. I corrected my comment.

`pdflatex --version` returns:

~~~
MiKTeX-pdfTeX 4.6.1 (MiKTeX 21.6)
© 1982 D. E. Knuth, © 1996-2021 Hàn Th? Thành
TeX is a trademark of the American Mathematical Society.
using bzip2 version 1.0.8, 13-Jul-2019
compiled with curl version 7.72.0; using libcurl/7.72.0 Schannel
compiled with expat version 2.2.10; using expat_2.2.10
compiled with jpeg version 9.4
compiled with liblzma version 50020052; using 50020052
compiled with libpng version 1.6.37; using 1.6.37
compiled with libressl version LibreSSL 3.1.4; using LibreSSL 3.1.4
compiled with MiKTeX Application Framework version 4.1.1; using 4.1.1
compiled with MiKTeX Core version 4.6; using 4.6
compiled with MiKTeX Archive Extractor version 4.0; using 4.0
compiled with MiKTeX Package Manager version 4.3; using 4.3
compiled with uriparser version 0.9.4
compiled with xpdf version 4.02
compiled with zlib version 1.2.11; using 1.2.11
~~~

**Comment by JohnLukeBentley** [comment] 2021-06-09 11:47
@cp-tanuki great, you are all sorted then!

As an additional tip, for almost any internet forum if you edit a comment it is traditional and helpful to leave substantive errors intact and otherwise correct the error.

E.g.
> and so the moon is made of cheese.
>
> Edit: I see now the moon is made of rock, metal and dust.

or
> and so the moon is made of ~~cheese~~ rock, metal and dust.
>
> Edit: Corrected claim about what the moon was made of.

This so, in principle, future readers can make sense of what is going on in a thread. In particular with regard to the subsequent responses of others. Not that it is particularly important in this case.
