### ISSUE TITLE
slidy: internal links don't work

### ISSUE THREAD

**Issue by somenxavier** [jgm/pandoc#3017] opened 2016-07-13 07:33 UTC
When I have 

```
# Afirmacions #

>  * $$3+5+2 = 3+5 = 8+2 = 10$$^[$=$ no significa implica]
>  * $$\frac{3}{5} + \frac{1}{2} = \frac{4}{7}$$
>  * $$3+5 \cdot 2 = 8 \cdot 2 = 16$$
>  * $$\frac{2}{3} + \frac{4}{5} = \frac{20}{30} + \frac{24}{30} = \frac{44}{30}$$
>  * $$\frac{2}{3} + \frac{4}{5} = 0,66 + 0,8 = 1,46$$
```

and I generate a slidy, then the footnote link has wrong href.

**Comment by AlbaMalaga** [comment] 2016-10-21 04:20
As of today, the link generated by your, @somenxavier, example is kind of correct -  in the html file the footnote is kept with id `fn1`, and href links to `#fn1`. What I mean is that it is correct from the strictly html-ish point of view, but it behaves counter-intuitively to me in the context of slidy presentation. 

When I open a pandoc-generated slidy presentation with plenty of footnotes with javascript disabled on Firefox 45.4.0 , everything works fine. I mean, when I click on the small number linking to the footnote I am actually directed to the place where the footnote's text is.

However, there is something counter-intuitive when I open it with javascript enabled, i.e. as an actual slidy presentation. When I click (or Ctrl+click/Cmd+click) on the small number indicating a footnote, I am directed to the next slide, even though all the footnotes are regrouped on the last slide. However if I right-click and ask for "Open Link in New Tab" the page that opens is almost the expected one - it opens my document precisely at the footnote's text but not viewed as a slide, it has instead the same look and feeling as if JavaScript was disabled.

I have similar counter-intuitive behavior with backlinks when JavaScript is enabled. If right-click on the backlink next to footnotes text and ask for "Open Link in New Tab" , I am sent to the place where the small floating number indicating the footnote is, but instead of a slidy look it has instead the same look and feeling as if JavaScript was disabled. If I simply click, nothing happens.

Here goes a MWE markdown-pandoc source for slides with many footnotes : 

	% Simple slidy presentation with footnotes
	% Alba MÁLAGA ^[`new` slidy ♥ fan]
	% 21 october 2016
	
	# Make simple things… #  
	## …complicated [^2]##  
	Let us put many footnotes in this slidy presentation :  
	
	- in a bullet list [^3]  
	- in title page  
	- in section titles  
	- in block quotes  
	
	# Just to make it a multi-slide …^[…oops!]#  
	## … let us add a slide ##  
	A quote with footnote using `inline_notes`  
	
	> The only perfect thing is the empty set ^[∅]  
	
	A quote with footnote using `footnotes`  
	
	> I am tired… [^6]  
	
	[^2]: complicated ≠ complex  
	[^3]: bullet lists are so *ppt*-ish  
	[^6]: …let's get some sleep  

The line I used for compiling it into the html file of a slidy presentation is: 

	pandoc -t slidy test.md -s -o test.html

The version of pandoc I used is [1.13.2.1](https://github.com/jgm/pandoc/releases/tag/1.13.2) (I used it via [SageMathCloud](https://cloud.sagemath.com)).

**Comment by somenxavier** [comment] 2016-10-21 09:58
@AlbaMalaga thanks for this intensive testing.

**Comment by mb21** [comment] 2017-01-17 16:52
It seems that slide uses the fragment identifier (the part after the hash in the URL) to keep track of which slide you're on, so all internal links in the document won't work. This has been discovered on [SO as well..](http://stackoverflow.com/questions/29454614/internal-links-in-html-slides-made-from-markdown-with-pandoc)

Maybe there's an option in slidy to disable the usage of the fragment identifier. Alternatively we could change the pandoc to link to the correct slide...

**Comment by mb21** [comment] 2017-01-17 16:55
this is actually a duplicate of https://github.com/jgm/pandoc/issues/2094, I'm thus closing this.

**Closed by mb21** 2017-01-17 16:55 UTC
Labels: format:HTML, writer
