### ISSUE TITLE
MathJax cannot render the converted piecewise function result well 

### ISSUE THREAD

**Issue by redstoneleo** [jgm/pandoc#8071] opened 2022-05-14 10:34 UTC
tested with pandoc version 2.18 on win11
`pandoc.exe "fx.docx" --self-contained --mathjax -o example35.html`

[fx.docx](https://github.com/jgm/pandoc/files/8692742/fx.docx)

**Comment by jgm** [comment] 2022-05-14 22:27
Yes, the output has `&` characters in it -- I assume that's what you mean.
Here is the XML from the Word file:
```xml
<m:oMath>
  <m:r>
    <w:rPr>
      <w:rFonts w:ascii="Cambria Math"
      w:hAnsi="Cambria Math" />
      <w:sz w:val="24" />
      <w:szCs w:val="24" />
    </w:rPr>
    <m:t>f</m:t>
  </m:r>
  <m:d>
    <m:dPr>
      <m:ctrlPr>
        <w:rPr>
          <w:rFonts w:ascii="Cambria Math"
          w:hAnsi="Cambria Math" />
          <w:i />
          <w:sz w:val="24" />
          <w:szCs w:val="24" />
        </w:rPr>
      </m:ctrlPr>
    </m:dPr>
    <m:e>
      <m:r>
        <w:rPr>
          <w:rFonts w:ascii="Cambria Math"
          w:hAnsi="Cambria Math" />
          <w:sz w:val="24" />
          <w:szCs w:val="24" />
        </w:rPr>
        <m:t>x</m:t>
      </m:r>
    </m:e>
  </m:d>
  <m:r>
    <w:rPr>
      <w:rFonts w:ascii="Cambria Math"
      w:hAnsi="Cambria Math" />
      <w:sz w:val="24" />
      <w:szCs w:val="24" />
    </w:rPr>
    <m:t>=</m:t>
  </m:r>
  <m:d>
    <m:dPr>
      <m:begChr m:val="{" />
      <m:endChr m:val="" />
      <m:ctrlPr>
        <w:rPr>
          <w:rFonts w:ascii="Cambria Math"
          w:hAnsi="Cambria Math" />
          <w:i />
          <w:sz w:val="24" />
          <w:szCs w:val="24" />
        </w:rPr>
      </m:ctrlPr>
    </m:dPr>
    <m:e>
      <m:eqArr>
        <m:eqArrPr>
          <m:ctrlPr>
            <w:rPr>
              <w:rFonts w:ascii="Cambria Math"
              w:hAnsi="Cambria Math" />
              <w:i />
              <w:sz w:val="24" />
              <w:szCs w:val="24" />
            </w:rPr>
          </m:ctrlPr>
        </m:eqArrPr>
        <m:e>
          <m:sSup>
            <m:sSupPr>
              <m:ctrlPr>
                <w:rPr>
                  <w:rFonts w:ascii="Cambria Math"
                  w:hAnsi="Cambria Math" />
                  <w:i />
                  <w:sz w:val="24" />
                  <w:szCs w:val="24" />
                </w:rPr>
              </m:ctrlPr>
            </m:sSupPr>
            <m:e>
              <m:r>
                <w:rPr>
                  <w:rFonts w:ascii="Cambria Math"
                  w:hAnsi="Cambria Math" />
                  <w:sz w:val="24" />
                  <w:szCs w:val="24" />
                </w:rPr>
                <m:t>x</m:t>
              </m:r>
            </m:e>
            <m:sup>
              <m:r>
                <w:rPr>
                  <w:rFonts w:ascii="Cambria Math"
                  w:hAnsi="Cambria Math" />
                  <w:sz w:val="24" />
                  <w:szCs w:val="24" />
                </w:rPr>
                <m:t>2</m:t>
              </m:r>
            </m:sup>
          </m:sSup>
          <m:r>
            <m:rPr>
              <m:sty m:val="p" />
            </m:rPr>
            <w:rPr>
              <w:rFonts w:ascii="Cambria Math"
              w:hAnsi="Cambria Math" />
              <w:sz w:val="24" />
              <w:szCs w:val="24" />
            </w:rPr>
            <m:t>sin</m:t>
          </m:r>
          <m:r>
            <w:rPr>
              <w:rFonts w:ascii="Cambria Math"
              w:hAnsi="Cambria Math" />
              <w:sz w:val="24" />
              <w:szCs w:val="24" />
            </w:rPr>
            <m:t>⁡</m:t>
          </m:r>
          <m:f>
            <m:fPr>
              <m:ctrlPr>
                <w:rPr>
                  <w:rFonts w:ascii="Cambria Math"
                  w:hAnsi="Cambria Math" />
                  <w:sz w:val="24" />
                  <w:szCs w:val="24" />
                </w:rPr>
              </m:ctrlPr>
            </m:fPr>
            <m:num>
              <m:r>
                <w:rPr>
                  <w:rFonts w:ascii="Cambria Math"
                  w:hAnsi="Cambria Math" />
                  <w:sz w:val="24" />
                  <w:szCs w:val="24" />
                </w:rPr>
                <m:t>1</m:t>
              </m:r>
            </m:num>
            <m:den>
              <m:r>
                <w:rPr>
                  <w:rFonts w:ascii="Cambria Math"
                  w:hAnsi="Cambria Math" />
                  <w:sz w:val="24" />
                  <w:szCs w:val="24" />
                </w:rPr>
                <m:t>x</m:t>
              </m:r>
            </m:den>
          </m:f>
          <m:r>
            <w:rPr>
              <w:rFonts w:ascii="Cambria Math"
              w:hAnsi="Cambria Math" />
              <w:sz w:val="24" />
              <w:szCs w:val="24" />
            </w:rPr>
            <m:t>, &amp;</m:t>
          </m:r>
          <m:r>
            <m:rPr>
              <m:nor />
            </m:rPr>
            <w:rPr>
              <w:rFonts w:ascii="Georgia"
              w:hAnsi="Georgia" />
              <w:sz w:val="24" />
              <w:szCs w:val="24" />
            </w:rPr>
            <m:t xml:space="preserve">


          </m:r>
          <m:r>
            <w:rPr>
              <w:rFonts w:ascii="Cambria Math"
              w:hAnsi="Cambria Math" />
              <w:sz w:val="24" />
              <w:szCs w:val="24" />
            </w:rPr>
            <m:t>x&lt;0</m:t>
          </m:r>
        </m:e>
        <m:e>
          <m:sSup>
            <m:sSupPr>
              <m:ctrlPr>
                <w:rPr>
                  <w:rFonts w:ascii="Cambria Math"
                  w:hAnsi="Cambria Math" />
                  <w:i />
                  <w:sz w:val="24" />
                  <w:szCs w:val="24" />
                </w:rPr>
              </m:ctrlPr>
            </m:sSupPr>
            <m:e>
              <m:r>
                <w:rPr>
                  <w:rFonts w:ascii="Cambria Math"
                  w:hAnsi="Cambria Math" />
                  <w:sz w:val="24" />
                  <w:szCs w:val="24" />
                </w:rPr>
                <m:t>x</m:t>
              </m:r>
            </m:e>
            <m:sup>
              <m:r>
                <w:rPr>
                  <w:rFonts w:ascii="Cambria Math"
                  w:hAnsi="Cambria Math" />
                  <w:sz w:val="24" />
                  <w:szCs w:val="24" />
                </w:rPr>
                <m:t>2</m:t>
              </m:r>
            </m:sup>
          </m:sSup>
          <m:r>
            <w:rPr>
              <w:rFonts w:ascii="Cambria Math"
              w:hAnsi="Cambria Math" />
              <w:sz w:val="24" />
              <w:szCs w:val="24" />
            </w:rPr>
            <m:t>, &amp;</m:t>
          </m:r>
          <m:r>
            <m:rPr>
              <m:nor />
            </m:rPr>
            <w:rPr>
              <w:rFonts w:ascii="Georgia"
              w:hAnsi="Georgia" />
              <w:sz w:val="24" />
              <w:szCs w:val="24" />
            </w:rPr>
            <m:t xml:space="preserve">


          </m:r>
          <m:r>
            <w:rPr>
              <w:rFonts w:ascii="Cambria Math"
              w:hAnsi="Cambria Math" />
              <w:sz w:val="24" />
              <w:szCs w:val="24" />
            </w:rPr>
            <m:t>x≥0</m:t>
          </m:r>
        </m:e>
      </m:eqArr>
    </m:e>
  </m:d>
</m:oMath>
```
Note that the `&amp;` characters are there!  So I think pandoc is doing a fine job converting the OOML to LaTeX; the problem is that your Word file has some extra characters there.  Why they don't show up in Word, I don't know.

**Comment by tarleb** [comment] 2022-08-04 09:26
Closing for now, as it this does not appear to be a pandoc issue. Please reopen with more info if you think pandoc could handle this better.

**Closed by tarleb** 2022-08-04 09:26 UTC
Labels: bug, status:resolved?
