### ISSUE TITLE
Partial word quote with smart extension

### ISSUE THREAD

**Issue by esnahn** [jgm/pandoc#6057] opened 2020-01-10 14:29 UTC
With pandoc.exe 2.8.0.1

```
$ pandoc --to=latex
'test' 'test'ish
^Z
`test' 'test'ish
```
I want the output to be `` `test' `test'ish``

In some languages including Korean, often quotes don't cover the entire 'word'.
It can be something like this: '작은 따옴표'는 "큰 따옴표"와 다르다.

I hope pandoc smart extension could understand these quotes correctly.

**Comment by mb21** [comment] 2020-01-10 15:09
Seems to be fixed in pandoc 2.9.1

**Comment by jgm** [comment] 2020-01-10 15:45
I can reproduce this in pandoc 2.9.1.1.

**Comment by jgm** [comment] 2020-01-10 15:46
```
% pandoc -t native
'test' 'test'ish
^D
[Para [Quoted SingleQuote [Str "test"],Space,Str "\8217test\8217ish"]]
```

**Comment by jgm** [comment] 2020-01-10 15:51
Pandoc uses some heuristics to determine what is a quoted section.  Part of the heuristic is that the final quote shouldn't be in the middle of a word. If we relax that, it may have undesirable consequences elsewhere.

I would suggest just using literal curly quote characters in your input text.  That will avoid all confusion.

I'm not saying this isn't a solvable problem. In fact, my (C) cmark library, which is used in pandoc's `gfm` and `commonmark` parsers, handles this case correctly.  You could try `pandoc -f commonmark+smart` or `pandoc -f gfm+smart`.

**Comment by jgm** [comment] 2020-01-10 15:55
To elaborate a bit further:  pandoc does something that cmark doesn't, which is create Quoted elements in the AST.  This is needed for translation into formats like DocBook, which uses a `quote` element.  That means that in a case like
```
'test test's'
```
pandoc would have to decide whether the Quoted section ends at the second or third '.

**Comment by esnahn** [comment] 2020-01-10 16:17
I'm ok with detecting it only when a non-alphabet character follows. In the meantime, I will take your suggestion. Thanks for the quick response.

**Comment by kysko** [comment] 2020-01-12 15:42
other possible temporary solutions:

- use zero-witdh space, which will remain in the converted text
  - directly `'test' 'test'​ish`, inserting the unicode character before "ish"
  - using html code `'test' 'test'&#8203;ish`

  both resulting in AST
  ````
  [Para [Quoted SingleQuote [Str "test"],Space,Quoted SingleQuote [Str "test"],Str "\8203ish"]]
  ````
  and in latex:
  ````
  `test' `test'\hspace{0pt}ish
  ````

- use special span class to process in lua filter: `'test' [test]{.squote}ish` for single quote

**Comment by esnahn** [comment] 2020-01-12 16:24
> * use zero-witdh space, which will remain in the converted text

I don't want it to break the line at there, so it wouldn't be optimal.

> * use special span class to process in lua filter: `'test' [test]{.squote}ish` for single quote

It's interesting that lua filter can help this, I will look into this solution. Thanks!

**Comment by kysko** [comment] 2020-01-12 22:06
yes, zws will break, not good in your case.

there's a "word joiner", somewhat like a "non breaking zero width space", `'test'&#8288;ish`, which will give AST
```
[Para [Quoted SingleQuote [Str "test"],Str "\8288ish"]]
```
and latex with corresponding unicode character, but compiler complains about that.

There's also the "narrow no break space" `'test'&#8239;ish` which gives latex
```
`test'\,ish
```
but even that small space might annoy you. Using `\,\!` might compensate, but don't know what markdown would map to `\!`

And then there's inserting code span
```
`\nobreak`{=latex}
```
but it becomes very ugly, and might as well use span with class above.

**Closed** 2024-12-23 05:00 UTC
Labels: format:Markdown, reader
