### ISSUE TITLE
template.docx fails to render table when Document Title style is changed

### ISSUE THREAD

**Issue by arnaldorusso** [jgm/pandoc#2152] opened 2015-05-14 14:43 UTC
Dear devs.

I have found a problem, while using pandoc to convert HTML files to .docx
After modifying my `template.docx` Which render all fonts as `Calibri` and with a blue color.
When I modify specially this style, it fails to render my tables, and disply each cell in a new line of the document.
Does any of you know about this issue?

Cheers.

**Comment by jgm** [comment] 2016-11-19 21:55
Without a specific example that allows us to reproduce the issue, there's not much we can do with this report.  Since it's old, I'll close it, but feel free to reopen it with more information if you like.

**Closed by jgm** 2016-11-19 21:55 UTC
