### ISSUE TITLE
Having image filename containing 'x' crashes Markdown > PDF production  

### ISSUE THREAD

**Issue by izimbra** [jgm/pandoc#2158] opened 2015-05-18 21:16 UTC
For example, having the following reference in the Markdown file:

    [fig3]: img/cropProcesses840×385.png "Figure 3" 

leads to the following output:

    ! Argument of \MT@res@a has an extra }.
    <inserted text> 
                \par
    l.267 ...degraphics{img/cropProcesses840×385.png}
    
    pandoc: Error producing PDF from TeX source

Changing the reference to:

     [fig3]: img/cropProcesses385.png "Figure 3" 

solves the problem.

System: OS X 10.10.2, TeX-Live 2013 (via MacTeX), pandoc: 1.13.2 (via cabal)

**Comment by nkalvi** [comment] 2015-05-18 22:16
@izimbra 
Suspecting whether the filename is being interpreted as hex char (due to 0x), I tried to reproduced it, but it worked fine. I tried it under OS X 10.10.3, Tex-Live Version 1.21 and Pandoc 1.13.2.

This is the TexLive I have:
![screen shot 2015-05-18 at 6 13 18 pm](https://cloud.githubusercontent.com/assets/2199312/7691581/a4c4f632-fd89-11e4-8679-3c3e082bf5e4.png)

Do you get errors when you export to other formats too?
If possible, could you update to the version of TexLive above and then try it?

**Comment by jgm** [comment] 2015-05-18 23:23
That's not a regular 'x', it's a Unicode times sign '×'.

You'll find you have the same problem with any non-ascii
characters in the filename:  e.g. testé.jpg.

See
https://groups.google.com/forum/#!topic/comp.text.tex/B9rtJyuIbFY

Solution is easy:  add `--latex-engine=xelatex` to your
pandoc command line.

**Comment by nkalvi** [comment] 2015-05-18 23:31
@jgm Though I wrongfully thought it was an `x`, I copied the name specified in the report when naming the file - here's the file's name on my system: `2158/img/cropProcesses840×385.png`. So it did work fine with the given name.

**Comment by jgm** [comment] 2015-05-19 05:16
+++ nkalvi [May 18 15 16:31 ]:
>@jgm Though I wrongfully thought it was an `x`, I copied the name specified in the report when naming the file - here's the file's name on my system: `2158/img/cropProcesses840×385.png`. So it did work fine with the given name.

I was able to reproduce the original report.  It may have to do with pdflatex versions.

**Comment by nkalvi** [comment] 2015-05-19 11:05
Looks like it - this is the version I tested with:

```
pdflatex --version
pdfTeX 3.14159265-2.6-1.40.15 (TeX Live 2014)
kpathsea version 6.2.0
Copyright 2014 Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
Compiled with libpng 1.6.10; using libpng 1.6.10
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with xpdf version 3.03
```

**Comment by jgm** [comment] 2015-05-20 03:04
I'm going to close this.  The answer is `--latex-engine=xelatex`.

**Closed by jgm** 2015-05-20 03:04 UTC
