### ISSUE TITLE
Converting Epub with noteref to any format drops <a ... epub:type="noteref"> in result

### ISSUE THREAD

**Issue by Aspvik** [jgm/pandoc#7884] opened 2022-02-02 15:24 UTC
**Explain the problem.**
When I convert any epub3 file with footnotes ```<a ... epub:type="noteref">``` to html, pdf or docx the entire \<a> element is removed from the body in the resulting file. The actual note itself at the end of the document is present. If I remove the ```epub:type="noteref"```attribute before converting it comes through.

```pandoc -o org.html -s -f epub org.epub```

FYI: The document starts out as a docx, then we store them as epub internally, and offer pdf exports. So the source epub file is also generated by Pandoc.

**Pandoc version?**
pandoc 2.17.1.1
Compiled with pandoc-types 1.22.1, texmath 0.12.4, skylighting 0.12.2,
citeproc 0.6.0.1, ipynb 0.2

**Comment by jgm** [comment] 2022-02-02 18:33
See #5531.
Can you upload a minimal example we can test with?

**Comment by Aspvik** [comment] 2022-02-03 06:56
Original: example.docx

```pandoc -o example.epub example.docx```
example.epub: EPUB/text/ch00N.xhtml footnotes/note are present.

```pandoc -o example.html -s -f epub example.epub```
index.html: \<a> tag's are missing

I had to zip the example files because of unsupported file formats.
[Examples.zip](https://github.com/jgm/pandoc/files/7992391/Examples.zip)

**Comment by jgm** [comment] 2022-02-07 17:22
OK, I see the problem now and have a path to fixing it.

**Comment by Aspvik** [comment] 2022-02-08 07:54
Excellent. I built from source now and the issue is resolved. When do you expect this fix to be released?

**Comment by jgm** [comment] 2022-02-08 07:57
Really?  It's not resolved in my tests.
The change I pushed only adds some warnings.

**Comment by Aspvik** [comment] 2022-02-08 08:07
I could see the warnings while converting. Still the \<a> tag is present in the final html output.

There is however a new block at the end which does not seem complete ```footnotes-end-of-document```
[example2.html.txt](https://github.com/jgm/pandoc/files/8021866/example2.html.txt)

**Comment by jgm** [comment] 2022-02-08 17:01
The problem is that we aren't finding the id in the note table.
Previously we just passed over this without notice. With the change above, we emit a warning and an *empty* note. So, you'll see the `<a>` tag but it will link to a blank note.  This is because I still haven't fixed the root problem.

**Closed** 2022-02-09 19:47 UTC
Labels: bug

**Comment by jgm** [comment] 2022-02-09 20:29
I can't tell you when the next release will be.  For now you can use a nightly.
