### ISSUE TITLE
pptx as input

### ISSUE THREAD

**Issue by masters3d** [jgm/pandoc#7621] opened 2021-10-12 18:40 UTC
**Describe your proposed improvement and the problem it solves.**
Unknown input format pptx

`pandoc --list-input-formats` pptx no included

**Describe alternatives you've considered.**

Manual converting to another supported format

**Comment by iogrt** [comment] 2022-06-23 16:51
this is a duplicate of: https://github.com/jgm/pandoc/issues/4252

**Closed** 2022-06-23 17:00 UTC
Labels: enhancement, new:reader, format:Pptx
