### ISSUE TITLE
Invalid XML when converting from docx to EPUB

### ISSUE THREAD

**Issue by bgoldowsky** [jgm/pandoc#8033] opened 2022-04-21 18:51 UTC
When converting a docx file with an ampersand in the title, the EPUB generated by pandoc has this in nav.xhtml:
   `<title>Anxiety & Depression in Teens1</title>`
The & is invalid in XML and should instead be rendered as `&amp;` or else the EPUB will be usable by many downstream applications.

Checked in pandoc 2.14.2 and 2.18 on MacOS, same result on linux.

**Comment by jgm** [comment] 2022-04-21 19:43
Can you help narrow this down?  Is it a problem with the docx reader or the epub writer?
I attempted to reproduce it in the writer with
```
 % pandoc -o my.epub -s
---
title: This & That
...

# one
^D
```
but nav.xhtml has
```
  <title>This &amp; That</title>
```

**Comment by jgm** [comment] 2022-04-21 19:44
I can't see how there could be a problem with the reader; the writer shouldn't ever emit invalid HTML.  But then it should be possible to reproduce it with other input formats.  Please give simple instructions for reproducing the issue.

**Comment by tarleb** [comment] 2022-08-03 21:57
Closing, since the problem cannot be reproduced.

**Closed by tarleb** 2022-08-03 21:57 UTC
Labels: bug, status:more-info-needed
