### ISSUE TITLE
Convert Docx to markdown

### ISSUE THREAD

**Issue by xBumblebee** [jgm/pandoc#8639] opened 2023-02-20 10:38 UTC
I am trying to convert from document file to markdown format using pandoc, I use "**pandoc "test.docx" -f docx -t markdown_phpextra+pipe_tables -o test2.md --extract-media=. -w gfm --wrap=none** ".

The "Contents" section already exists in the document file and there are direct links. But when I convert it to markdown format, for example;

**Contents**
- [A. DOCUMENT LOCATION [- 2 -](#document-location)](#document-location)

There are two identification sections in this section. **(#document-location)]**(#document-location) Also, direct links do not work because there are non-English characters.

**Comment by jgm** [comment] 2023-02-22 00:26
You'll need to provide a minimal test file for us to reproduce the error, or we don't have enough to go on.

Also, your command line is strange:  `-t markdown_phpextra` and `-w gfm` are both specifying an output format; choose one.

**Comment by tarleb** [comment] 2023-05-05 15:07
Closing this due to the missing reproducible example.

**Closed by tarleb** 2023-05-05 15:07 UTC
Labels: status:more-info-needed
