### ISSUE TITLE
eurosym in Pandoc seems to be incompatible with hyperref

### ISSUE THREAD

**Issue by harriott** [jgm/pandoc#3801] opened 2017-07-14 16:43 UTC
- `Windows 10 version 1703`, `MiKTeX 2.9.6300 64-bit`, `pandoc v1.19.2.1`.
- `Arch linux 4.11.9-1`, `texlive-bin 2016.41290-12`, `pandoc 1.19.2.1-90`.

`eurosym.md` contains just:

    # 2€
    2€

`pandoc eurosym.md -o eurosym.pdf --latex-engine=xelatex` returns variants of:

    ! Improper alphabetic constant.
    <to be read again>
                       \euro
    l.70 \section{2\euro{}}

    pandoc.exe: Error producing PDF

Further details: [pandoc convert to pdf fails when € is in a header](http://stackoverflow.com/questions/44032498/pandoc-convert-to-pdf-fails-when-%e2%82%ac-is-in-a-header).

**Comment by mb21** [comment] 2017-07-14 18:25
could not reproduce on macOS with `XeTeX 3.14159265-2.6-0.99996 (TeX Live 2016)` maybe a windows thing...?

**Comment by harriott** [comment] 2017-07-14 19:25
mb21, no (as elaborated on StackOverflow), I've used the latest jgm `default.latex`.

**Comment by jgm** [comment] 2017-07-14 20:52
The second answer here is illuminating on what the error
message means:

https://tex.stackexchange.com/questions/64900/improper-alphabetic-constant

Not sure yet how to fix this in pandoc.

**Comment by jgm** [comment] 2017-07-14 20:55
Note that this works fine with --latex-engine=pdflatex.

The difference is that, when pdflatex is used, we have

    \usepackage{eurosym}

while with xelatex, we have

    \newcommand{\euro}{€}

in the default template.

**Comment by jgm** [comment] 2017-07-14 21:09
Minimal case that fails for me using `xelatex`:
```latex
\documentclass[]{article}
\usepackage{unicode-math}
\newcommand{\euro}{€}

\usepackage[unicode=true]{hyperref}

\begin{document}

\hypertarget{section}{
\section{2\euro{}}\label{section}
}

\end{document}
```
Note that if you comment out the unicodemath part, OR if you remove hyperref and the hyperref specific commands, it compiles successfully.  So it's the combination of the custom `\euro` macro with BOTH unicodemath and hyperref that seems to cause the problem.

**Comment by adunning** [comment] 2017-09-07 10:12
This can be fixed by dropping the `\euro` command and the two associated lines from the template, and writing € directly. It's already handled through the `textcomp` package (part of the core LaTeX distribution), which is automatically loaded when using the Pandoc template under pdfLaTeX via the `upquote` package. (To prevent errors, either the conditional loading of the `upquote` package in the template should be removed, or `textcomp` should be called directly with pdfLaTeX.)

The following produces an identical PDF under any of the three LaTeX engines:

```latex
\documentclass{article}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \usepackage{unicode-math}
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
\usepackage{upquote}
\usepackage{hyperref}

\begin{document}

\hypertarget{section}{
\section{2€}\label{section}
}

\end{document}
```

**Closed** 2017-09-08 23:28 UTC
Labels: format:LaTeX, writer
