### ISSUE TITLE
convert html tables to markdown/...

### ISSUE THREAD

**Issue by JanSchulz** [jgm/pandoc#2015] opened 2015-03-20 19:46 UTC
currently, it seems that pandoc cannot convert html tables in markdown documents to docx/PDF (that's at least the result I get when I use markdown with inline html in RMarkdown). 

```
$$ echo "<table><tr><td>hello world</td><td>text</td></tr></tr><td>text2</td><td>text2</td></tr></table>" | pandoc --from html --to latex
"

hello world

text

text2

text2

"
$$ echo "<table><tr><td>hello world</td><td>text</td></tr></tr><td>text2</td><td>text2</td></tr></table>" | pandoc --from html --to markdown
"
hello world
text
text2
text2
"
```

I found this bugreport, which had a perl script which "fixes" this: https://code.google.com/p/pandoc/issues/detail?id=132. Unfortunately the bugreport was marked "wontfix" with this explanation:

> I hesitate to try to write an HTML table -> pandoc table converter, because (i) HTML tables are still sometimes used for layout in web pages, and (ii) pandoc tables include information about the relative widths of columns, which would be hard to derive from HTML tables.

That pandoc can't handle html table conversation to pdf/docx currently bites me, as most of the stuff in IPython is outputted as html, especially the table output from pandas, a data wrangling library in python, and this html can't be converted properly into pdf/docx.

Could this problem be revisited?

**Comment by jgm** [comment] 2015-03-22 00:53
>I found this bugreport, which had a perl script which "fixes" this: https://code.google.com/p/pandoc/issues/detail?id=132. Unfortunately the bugreport wa marked "wontfix" with this explanation:

That issue, and the google code tracker, is ancient.  We haven't
used Google Code for many years.  So ignore that.

All raw HTML in Markdown documents is parsed as raw HTML, and will only
appear in HTML output, or in Markdown or other formats that allow raw
HTML.

So if you want a table in Markdown that will work in all output
formats, use one of the many sorts of Markdown table formats that
pandoc supports.

For your purposes, you might be able to write a script (or pandoc
filter) that uses pandoc itself to convert HTML tables to pandoc
Markdown tables.

Pandoc can convert HTML tables when you do `pandoc --from html`
(assuming you have a recent enough version of pandoc, and the tables
don't have colspans or rowspans, which pandoc can't currently handle).

>      $$ echo "<table><tr><td>hello world</td><td>text</td></tr></tr><td>text2</td><td>text2</td></tr></table>" | pandoc --from html --to latex

In this case, it didn't work because you have a typo:  `</tr>` where you
need `<tr>`.

**Comment by JanSchulz** [comment] 2015-03-22 03:15
Oups, sorry for the wrong example, here is one I think is valid but doesn't produce the intended output:

```
C:\Windows\System32>python -c "import pandas; print(pandas.DataFrame({'a':[1,2,3
,4],'b':['aaaaaaaa','b','ccccccccccccccccccccccccccc','d']}).to_html())"
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>a</th>
      <th>b</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td> 1</td>
      <td>                    aaaaaaaa</td>
    </tr>
    <tr>
      <th>1</th>
      <td> 2</td>
      <td>                           b</td>
    </tr>
    <tr>
      <th>2</th>
      <td> 3</td>
      <td> ccccccccccccccccccccccccccc</td>
    </tr>
    <tr>
      <th>3</th>
      <td> 4</td>
      <td>                           d</td>
    </tr>
  </tbody>
</table>

C:\Windows\System32>python -c "import pandas; print(pandas.DataFrame({'a':[1,2,3
,4],'b':['aaaaaaaa','b','ccccccccccccccccccccccccccc','d']}).to_html())" |pandoc
 --from html --to latex
a

b

0

1

aaaaaaaa

1

2

b

2

3

ccccccccccccccccccccccccccc
```

**Comment by lierdakil** [comment] 2015-03-22 03:54
@JanSchulz this is fixed in `master`. See #1859 for explaination and #1885 for fixes. Basically, wait for 1.13.3, or build from git.

I think it's safe to say that this is a duplicate of #1859.

**Comment by JanSchulz** [comment] 2015-03-22 04:07
Yep, looks like a duplicate. Sorry that I didn't find that.

How far off is a 1.13.3 release?

**Comment by lierdakil** [comment] 2015-03-22 04:48
@JanSchulz if I had to guess, based on sheer number of commits since last release, possibly somewhere in April-May. I think @jgm might give a more definite answer.

**Closed** 2015-03-22 18:56 UTC
