### ISSUE TITLE
man->gfm option lists no longer produces lists

### ISSUE THREAD

**Issue by vapier** [jgm/pandoc#8394] opened 2022-10-22 15:27 UTC
**Explain the problem.**

a common style in man pages is to document options using `.TP` followed by the option followed by the description.  this produces a "list-like" set of paragraphs which makes it clear where option documentation starts & ends.

in versions before 2.10, this largely worked as expected -- a list would be produced.  but since 2.10/2.11, paragraphs are produced.  i don't see anything in the changelog, so i have to assume this was not intentional.  if it was intentional, the output makes it harder to read when an option has a long description, possibly with multiple paragraphs.

example `getent.1` file (taken from [getent(1) man page](https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/tree/man1/getent.1)):
```man
.SH NAME
getent \- get entries from Name Service Switch libraries
.SH OPTIONS
.TP
.BR \-s\ \fIservice\fP ", " \-\-service\ \fIservice\fP
Override all databases with the specified service.
(Since glibc 2.2.5.)
.TP
.BR \-i ", " \-\-no\-idn
Disables IDN encoding in lookups for
.BR ahosts / getaddrinfo (3)
(Since glibc-2.13.)
.TP
.BR \-? ", " \-\-help
Print a usage summary and exit.
.TP                                                                
.B "\-\-usage"
Print a short usage summary and exit.
.TP
.BR \-V ", " \-\-version
Print the version number, license, and disclaimer of warranty for
.BR getent .
```

when running pandoc-2.9 and older, we get:
```sh
pandoc-2.9 -r man -w gfm getent.1 > getent.md
```
```md
# NAME

getent - get entries from Name Service Switch libraries

# OPTIONS

  - **-s *service***, **--service *service***  
    Override all databases with the specified service. (Since glibc
    2.2.5.)

  - **-i**, **--no-idn**  
    Disables IDN encoding in lookups for **ahosts**/**getaddrinfo**(3)
    (Since glibc-2.13.)

  - **-?**, **--help**  
    Print a usage summary and exit.

  - **--usage**  
    Print a short usage summary and exit.

  - **-V**, **--version**  
    Print the version number, license, and disclaimer of warranty for
    **getent**.
```

but with newer versions, we get paragraphs:
```sh
pandoc -r man -w gfm getent.1 > getent.md
```
```md
# NAME

getent - get entries from Name Service Switch libraries

# OPTIONS

**-s *service***, **--service *service***  
Override all databases with the specified service. (Since glibc 2.2.5.)

**-i**, **--no-idn**  
Disables IDN encoding in lookups for **ahosts**/**getaddrinfo**(3)
(Since glibc-2.13.)

**-?**, **--help**  
Print a usage summary and exit.

**--usage**  
Print a short usage summary and exit.

**-V**, **--version**  
Print the version number, license, and disclaimer of warranty for
**getent**.
```

**Pandoc version?**
```
$ uname -a
Linux vapier 5.15.0 #1 SMP PREEMPT Wed Nov 3 00:00:42 EDT 2021 x86_64 AMD FX(tm)-4350 Quad-Core Processor AuthenticAMD GNU/Linux

$ pandoc --version
pandoc 2.19.2
Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.2, skylighting 0.13,
citeproc 0.8.0.1, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4
User data directory: /home/vapier/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by jgm** [comment] 2022-10-24 04:37
Pandoc will parse these as DefinitionLists, which will render very well in formats that support them, including LaTeX, HTML, and pandoc's own markdown dialect.  gfm does not have any dedicated syntax for definition lists, however, so we have to make a choice about how to render them in that format.

Rendering them without bullets gives output that is closer to what you see in formats that actually support definition lists (which do not include bullets).  I do agree, though, that the bullets make the list structure clearer.  It's a hard call.

See #1039.  (I think this issue is essentially a duplicate of that one.)

**Comment by jgm** [comment] 2022-10-24 04:38
Note that you could use a Lua filter to convert each DefinitionList to a BulletList, to get the output you desire.

**Comment by jgm** [comment] 2022-10-24 04:45
Here's one that would do the job:
```lua
function DefinitionList(el)
  local items = {}
  for _, item in ipairs(el.content) do
    local term, def = item[1], item[2][1] -- assumes only one defn
    table.insert(def, 1, pandoc.Para(term))
    items[#items + 1] = def
  end
  return pandoc.BulletList(items)
end
```

**Comment by vapier** [comment] 2022-10-26 09:15
thanks for the tip.  i'm using Python for my filters and was able to extend it to convert DefinitionList to BulletList like pandoc itself used to.  it seems my custom filter keeps growing to workaound issues :/.

```
        bl = []
        for (term, details) in value:
            details[0][0]['c'][:] = term + [LineBreak()] + details[0][0]['c']
            bl += details
        return BulletList(bl)
```

i'll leave it to you whether you want to dupe it over, but that issue has been open for almost a decade :/

**Comment by jgm** [comment] 2022-10-26 15:43
Well, the reason it's open is not that it's hard to make the change, but rather that I'm not persuaded the change is a good one (see above, and comments in linked issue).

**Closed by jgm** 2022-10-26 15:43 UTC
Labels: bug
