### ISSUE TITLE
Problem with data-number attribute written twice in epub3 and epub2 export with Pandoc 2.9

### ISSUE THREAD

**Issue by Kotik73** [jgm/pandoc#6005] opened 2019-12-22 15:47 UTC
I have a problem when creating epub3 (and also epub2) output with
- pandoc 2.9 (installed via homebrew)
- System: macOS Catalina 10.15.2
- ebook Readers used to check: iBooks, Murasaki

When I open created epub3 ebooks with an ebook reader, the title and toc still displays, but all the subsequent pages only show an error like:

```
This page contains the following errors:
error on line 11 at column 83: Attribute data-number redefined
Below is a rendering of the page up to the first error.
```

I checked the created epub file, and found that ``data-number`` is written twice as attribute in the section tag (here in ch001.xhtml):

 ```
<?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE html>
 <html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" xml:lang="en-US">
 <head>
 <meta charset="utf-8" />
 <meta name="generator" content="pandoc" />
 <title>ch001.xhtml</title>
<link rel="stylesheet" type="text/css" href="../styles/stylesheet1.css" />
</head>
<body epub:type="bodymatter">
<section id="setup-and-configuration" class="level1 section" data-number="1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Setup and Configuration</h1>
```

Example Markdown to check:

```
---
title: 'Bug Example'
...

# Setup and Configuration

Some text

## Level 2

### Level 3

## Level 2 again

# Level 1 again

```

Command used to create epub:

- ``pandoc input.md -t epub3 --toc -o output.epub``

Also tested with --number-sections, -f markdown+smart, --toc-depth=2 and also -t epub2 in various combinations, same result.

**Comment by tarleb** [comment] 2019-12-22 16:14
Closing as duplicate of #5986.

**Closed by tarleb** 2019-12-22 16:14 UTC

**Comment by jgm** [comment] 2019-12-22 17:29
I hope to put out a new release addressing this soon.
