### ISSUE TITLE
reference.docx throws up errors in Word

### ISSUE THREAD

**Issue by RobertGoulding** [jgm/pandoc#3741] opened 2017-06-16 15:12 UTC
pandoc 1.19.2.1

I created a Word reference file with the command `pandoc --print-default-data-file reference.docx > custom-reference.docx`. I then opened this file in Word (MS Office 365 ProPlus Version 1704), and made some changes: under the "Design" tab, I selected "Black & White (Word)", and then modified the spacing and justification in the "Normal" style. The resulting file I moved into my user data directory as reference.docx (and I attach it here).

[reference.docx](https://github.com/jgm/pandoc/files/1081160/reference.docx)

But now, when I use pandoc to produce a Word file, I get a message in Word that the resulting file cannot be opened, and must be recovered.  The file is then recovered successfully, but with this message:

![screenshot 2017-06-16 10 56 03](https://user-images.githubusercontent.com/22690062/27232557-79c9d6da-5284-11e7-8de9-707d9e4633e4.png)

I recall that I have had similar errors in the past with reference files generated by pandoc, and then modified.

**Comment by jgm** [comment] 2017-06-17 21:34
To figure out where the problem lies, it would be helpful to know whether you get the same problems if you:

1)  generate the default reference.docx as before, open in Word, change on letter in the "Hello world" text, save in Word, then use the resulting file as a reference.docx to create a new file.

2) same as 1) but also change the Normal style (but don't mess with the Design tab).

**Comment by RobertGoulding** [comment] 2017-06-19 23:30
With a minimal markdown document, neither 1 nor 2 produced any errors.  And then I tried the Design tab on the reference document, and *that* didn't cause any errors either!

So then I tried it with the complex document that generated the errors in the first place. 1: no errors. 2: no errors. So then I tried using the Design tab, and still no errors!

As a last resort, I moved the custom-built reference.docx into the Roaming/pandoc directory, which is what I had done before; and then invoked pandoc without explicitly requiring a reference-docx.  *Now* those errors reappeared.

So, I started over.  Now compiling a minimal document, with the reference docx in the default data directory:

If I place the generated reference.docx in there unmodified, I get no errors.
**If I change even a single character of the reference.docx**, I get errors in Word.

So it clearly has something to do with how pandoc is reading the reference.docx from the default data directory. I can make any sort of change at all to an explicitly requested reference.docx, and I get no errors (and the chosen formatting is passed through to the generated Word file).  But any change at all to the reference.docx in the default data directory causes errors in the generated Word file.

**Comment by iandol** [comment] 2017-06-20 04:09
I tried to use your reference.docx called explicitly from my downloads dir with `--reference-docx=` on macOS and there are no problems or errors loading the resulting docx file either. But if I move it into the default data dir and either call it explicitly (`--reference-docx=`)or not I also see errors loading the resulting file in Word.

![screen shot 2017-06-20 at 12 05 38](https://user-images.githubusercontent.com/153905/27316267-39314b78-55b1-11e7-852e-65737b6f60b5.png)

Latest Word for macOS (15.35), with Pandoc 1.19.2.1.

**Comment by jgm** [comment] 2017-06-20 08:09
Can you try this with the dev version?  Binary nightlies can be found here:
https://github.com/pandoc-extras/pandoc-nightly/releases
I could not reproduce the issue with the dev version, but could with 1.19.2.1, so I suspect this has already been fixed.

**Comment by iandol** [comment] 2017-06-20 08:59
Can confirm this is fixed with pandoc-osx-710bb18 nightly!

**Closed** 2017-06-20 09:07 UTC
Labels: format:Docx, writer

**Comment by RobertGoulding** [comment] 2017-06-20 15:51
Thanks, this is fixed in Windows too.  I didn't know about the nightly builds -- will check them first before reporting any other bugs.
