### ISSUE TITLE
Possibility to retain some classes in translation

### ISSUE THREAD

**Issue by robinsdg** [jgm/pandoc#4942] opened 2018-10-01 14:38 UTC
In the process of converting HTML or Markdown to ICML, I’d love the possibility to allow/force a class through the translation process. As it is, HTML → ICML removes all classes and a lot of element distinction, and this makes it impossible to have, for example, an article lede – it’s an element that never made it into HTML, and now I usually either include the `.lede` class, or put it inside `<article><header>`. But both of these methods are lossy, and I lose the distinction that I’d like.

So is there a reasonable feature request in, say, retaining classes between formats that allow them? In Kramdown there is, for example, the `:refdef:` _attribute list definition_, in HTML you can create classes at will, and in InDesign a paragraph style could reflect the base element with a modifier (for example, `Paragraph / Lede`). This means it could translate back and forth with relative predictability.

Of course, it would break HTML as an input format if all transformations would retain every class, so perhaps it could be implemented as an opt-in flag, perhaps even with a whitelist to ensure that you know what you’re asking for. Maybe this is not as simple as I’m making it sound, but it would certainly extend the usefulness of the ICML writer, and could have value for others.

**Comment by jgm** [comment] 2018-10-01 16:31
You don't see what elements the classes are attached to.  Pandoc's underlying representation of a document can represent classes on Div, Span, Link, Image, and Header elements.  It may be that the ICML writer is not passing these through for these elements, in which case the fix would be an easy one in the ICML writer.  But if e.g. you expect a class on a `<p>` tag to be passed through, that couldn't happen unless we modified the pandoc AST to allow attributes on all elements (there's an open issue about this).

**Comment by mb21** [comment] 2018-10-01 17:38
I think passing through all classes is probably not what you'd want in ICML output. It should more closely mirror the [custom styles we already have for docx](http://pandoc.org/MANUAL.html#custom-styles-in-docx).

So I guess this is a duplicate of https://github.com/jgm/pandoc/issues/2106, then?

**Comment by robinsdg** [comment] 2018-10-02 08:36
@jgm That makes sense. Same with @mb21 – that sounds like a more robust, more opt-in level of solution. I like your proposal from the thread in #2106 – what would you advise I look into here? I don’t write Lua, and the ICML format is quite verbose and picky (like all XML).

**Comment by mb21** [comment] 2018-10-29 15:53
Closing this in favour of #2106.

I might eventually get around to implementing this in the ICML writer...

**Closed by mb21** 2018-10-29 15:53 UTC

**Comment by mb21** [comment] 2018-12-23 18:47
This should work in [current nitghlies](https://github.com/pandoc-extras/pandoc-nightly) analogous to Custom Styles in Docx (see the MANUAL).

**Comment by robinsdg** [comment] 2019-01-03 12:58
Testing the latest nightlies, I’m finding it hard to get a consistent result. If the HTML attribute `custom-style` is set, that should carry into the ICML file, correct? I’m not getting that to work. What am I missing? I’ve set the `+styles` extra on both input and output, and any variation of that, but I’m not sure I fully understand it.

**Comment by mb21** [comment] 2019-01-03 13:45
@robinsdg yes, but the attribute only works on spans and divs. Can you post example input? E.g. the following works, right?:

    echo 'foo [my span]{custom-style="my style"} bar' | pandoc -s -t icml

**Comment by robinsdg** [comment] 2019-01-03 16:25
Yes, that works. I didn’t realise it had to be spans and divs explicitly, but now it all works fine. Thanks a lot!
