### ISSUE TITLE
Jira Reader: Lines for lists can start with "space"

### ISSUE THREAD

**Issue by Estigy** [jgm/pandoc#6204] opened 2020-03-23 10:09 UTC
Pandoc 2.9.2, Jira 8.2.3

What I get from the Jira API:
This is a *bold* comment:\r\n # It\r\n # uses\r\n # numbered\r\n\r\nand\r\n * unnumbered\r\n * lists.

Please note the spaces before all "#" and "*".
If those spaces were not there, the lists would be constructed correctly.

**Comment by tarleb** [comment] 2020-03-23 10:56
Duplicate of #6183. This has been fixed in the current development version. Please try one of the nightly builds.

**Closed by tarleb** 2020-03-23 10:56 UTC
