### ISSUE TITLE
Translating divs into LaTeX environements

### ISSUE THREAD

**Issue by grea09** [jgm/pandoc#4471] opened 2018-03-19 10:48 UTC
Hello,
I am asking if it wouldn't be more fitting to the philosophy of Pandoc to translate the newly introduced block/div syntax into environements when for the LaTeX writer.

I did a kinda general purpose filter for that [here](https://github.com/grea09/pancake/blob/master/filter/pandoc-science.py) but I was wondering why blocks in markdown couldn't get transformed automatically into `\begin{$class}$content\end{$class}` and to add a small bit of code in the latex template of the like : `\provideenvironement{$class}` (using something like [that](https://tex.stackexchange.com/questions/20687/does-newenvironment-have-a-provideenvironment-cousin-as-newcommand-has-prov)). I know that there are a wide variety of environements and packages that can apply to so excuse my ignorange on that.

I am asking mainly because some other issues are instances of what that feature could fix :
https://github.com/jgm/pandoc/issues/4150
https://github.com/jgm/pandoc/issues/3145

Is there any fundamental problems or incompatibilities in doing so ? Does that break anything within the philosophy of Pandoc ?

**Comment by mb21** [comment] 2018-03-19 10:55
I like the idea, yet the devil is in the details. However, you can already achieve this with a simple lua-filter.

**Comment by mb21** [comment] 2018-03-19 10:55
Duplicate of #2106

**Closed by mb21** 2018-03-19 10:55 UTC

**Comment by jgm** [comment] 2018-03-19 16:18
Antoine GRÉA <notifications@github.com> writes:

> I did a kinda general purpose filter for that [here](https://github.com/grea09/pancake/blob/master/filter/pandoc-science.py) but I was wondering why blocks in markdown couldn't get transformed automatically into `\begin{$class}$content\end{$class}` and to add a small bit of code in the latex template of the like : `\provideenvironement{$class}` (using something like [that](https://tex.stackexchange.com/questions/20687/does-newenvironment-have-a-provideenvironment-cousin-as-newcommand-has-prov)). I know that there are a wide variety of environements and packages that can apply to so excuse my ignorange on that.

Is the idea that the template would have have something like
this?

$for(class)$
\provideenvironment{\$class$}{}{}
$endfor$

to define a dummy environment for each class, so that the document
compiles even if the user hasn't defined these environments?

You should comment further in the linked issue, not here.
