### ISSUE TITLE
Add support for LaTeX tabbing environment

### ISSUE THREAD

**Issue by casperdcl** [jgm/pandoc#4430] opened 2018-03-05 16:04 UTC
pandoc `2.1.2-1` x64 debian

foo.md:
```md
% Markdown with raw LaTeX

# Title

## Subsection

Without the nested `\tabbing`, this does fine:

\begin{minipage}{\columnwidth}
\begin{align}
y=mx+c,
\end{align}

\begin{tabbing}
where \= $y$ \= is the function, \\
\> $m$ \> is the gradient, \\
\> $x$ \> is the input, and \\
\> $c$ \> is the offset.\\
\end{tabbing}
\end{minipage}
```

command:
```bash
pandoc -o foo.latex foo.md
```

result (`pandoc 2.1.2-1`):
```latex
...
Without the nested \texttt{\textbackslash{}tabbing}, this does fine:

\textbackslash{}begin\{minipage\}\{\columnwidth\} \begin{align}
y=mx+c,
\end{align}

\textbackslash{}begin\{tabbing\} where = \(y\) = is the function,
\textbackslash{} \textgreater{} \(m\) \textgreater{} is the gradient,
\textbackslash{} \textgreater{} \(x\) \textgreater{} is the input, and
\textbackslash{} \textgreater{} \(c\) \textgreater{} is the
offset.\textbackslash{} \textbackslash{}end\{tabbing\}
\textbackslash{}end\{minipage\}
...
```

expected (`pandoc 1.19.2.1-1`):
```latex
...
Without the nested \texttt{\textbackslash{}tabbing}, this does fine:

\begin{minipage}{\columnwidth}
\begin{align}
y=mx+c,
\end{align}

\begin{tabbing}
where \= $y$ \= is the function, \\
\> $m$ \> is the gradient, \\
\> $x$ \> is the input, and \\
\> $c$ \> is the offset.\\
\end{tabbing}
\end{minipage}
...
```

**Comment by jgm** [comment] 2018-03-05 17:25
A better minimal case:
```
\begin{tabbing}
where \= $y$ \= is the function, \\
\end{tabbing}
```
`pandoc -f latex` yields
```
Error at "source" (line 2, column 10):
unexpected $
where \= $y$ \= is the function, \\
```

**Comment by casperdcl** [comment] 2018-03-05 17:58
`tabbing` iteself was the issue? Interesting. Surely

```regex
\\begin\{(\w+)\}.*\\end\{\1\}
```

should always be supported?

**Comment by jgm** [comment] 2018-03-05 18:14
+++ Casper da Costa-Luis [Mar 05 18 17:58 ]:
>   tabbing iteself was the issue? Interesting. Surely
>
>\\begin\{(\w+)\}.*\\end\{\1\}
>
>   should always be supported?

The question is what to do with what's inside the
environment.  This requires parsing it according to
the rules set up by the environment.

We could perhaps add a fallback rule that just
slurps up the whole environment as raw tex.

**Comment by jgm** [comment] 2021-01-01 21:06
Closing as a duplicate of #2349

**Closed by jgm** 2021-01-01 21:06 UTC
Labels: format:LaTeX, reader
