### ISSUE TITLE
Images in stylesheets not embedded in epub

### ISSUE THREAD

**Issue by yihui** [jgm/pandoc#2733] opened 2016-02-22 03:20 UTC
The full minimal reproducible example can be downloaded here: https://www.dropbox.com/sh/v53cqqr854tdf5b/AAAGpUYy0MljfHaT9FhOyGENa?dl=0

test.md

``` md

---
title: Test
author: John Smith
stylesheet: test.css

---

Test

<div class="caution">Test block.</div>
```

test.css

``` css
.caution {
  padding: 1em 1em 1em 4em;
  margin-bottom: 10px;
  background: #f5f5f5 url("images/caution.png") left center/3em no-repeat;
}
```

images/caution.png

![caution](https://cloud.githubusercontent.com/assets/163582/13208599/2ce94b12-d8e0-11e5-9b9a-76d975e3c952.png)

To reproduce the problem:

``` bash
pandoc -o test.epub test.md
```

The caution icon is missing in the block when we view test.epub:

![screen shot 2016-02-21 at 9 16 19 pm](https://cloud.githubusercontent.com/assets/163582/13208633/6d424c72-d8e0-11e5-81ed-ce2309aaaa39.png)

If we use the developer tools in calibre, we can see the image images/caution.png is not found. I think Pandoc should be able to recognize the external resources in the stylesheet, and copy them when rendering epub.

**Comment by jgm** [comment] 2016-02-22 05:36
What pandoc version are you using?

+++ Yihui Xie [Feb 21 16 19:20 ]:

**Comment by yihui** [comment] 2016-02-22 05:42
I tested both Pandoc 1.15.2 and 1.16.0.2.

**Comment by ickc** [comment] 2017-01-22 22:33
Can you reproduce the problems with the latest version of pandoc?

**Comment by mb21** [comment] 2017-01-23 09:52
Closing this in favour of https://github.com/jgm/pandoc/issues/2733 since there's more discussion over there. Please comment if this is a different issue...

**Closed by mb21** 2017-01-23 09:52 UTC
Labels: format:EPUB, writer

**Comment by yihui** [comment] 2017-01-24 03:31
@ickc Yes, I still can repro (with 1.19.1).

@mb21 This is #2733. I think you meant another issue, but I don't know which.

**Comment by mb21** [comment] 2017-01-24 08:37
@yihui thanks, I meant https://github.com/jgm/pandoc/issues/2766 (edited comment above)

**Comment by ickc** [comment] 2017-01-24 09:00
Could it be a different issue? This one is about an image used in an external CSS for ePub output.

**Comment by mb21** [comment] 2017-01-24 09:08
@yihui @ickc thanks, finally the right one: https://github.com/jgm/pandoc/issues/1941
