### ISSUE TITLE
LaTeX to EPub: German quotation marks not translated correctly

### ISSUE THREAD

**Issue by aschatt** [jgm/pandoc#4789] opened 2018-07-23 13:00 UTC
German quotation marks in LaTex like "`this"' are not translated to the correct German typography but to English quotation marks in the EPub document.

**Comment by mb21** [comment] 2018-07-23 14:36
Duplicate of #661

**Closed by mb21** 2018-07-23 14:36 UTC

**Comment by mb21** [comment] 2018-07-23 14:37
Meanwhile:

> You could try using the `--html-q-tags` option. Then use CSS to style the q tags appropriately.

**Comment by jgm** [comment] 2018-07-23 18:01
Closer to #84 and #2620
