### ISSUE TITLE
Support RestructuredText substitution references

### ISSUE THREAD

**Issue by jonashaag** [jgm/pandoc#5995] opened 2019-12-17 15:08 UTC
Markdown source:

```markdown
[`foo`](https://google.com)
```

(Illegal) RestructuredText output as of v2.8.1:

```rst
```foo`` <https://google.com>`__
```

Expected RestructuredText output:

```rst
|some_random_string|_

.. |some_random_string| replace:: ``foo``
.. some_random_string: https://google.com
```

See also [this SO post](https://stackoverflow.com/questions/4743845/format-text-in-a-link-in-restructuredtext) and [RestructuredText docs on Substitution References](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#substitution-references)

**Comment by jgm** [comment] 2019-12-17 18:03
Duplicate of #3973

**Closed by jgm** 2019-12-17 18:03 UTC
