### ISSUE TITLE
an infinite loop in latex

### ISSUE THREAD

**Issue by tkawabata25** [jgm/pandoc#6395] opened 2020-05-23 06:06 UTC
If you do a  specify the file, pandoc will get caught in an infinite loop.

<pre>pandoc --version
pandoc.exe 2.9.2
Compiled with pandoc-types 1.20, texmath 0.12.0.1, skylighting 0.8.3.2
</pre>

<pre>pandoc .\loop.tex --verbose
[INFO] Skipped '\smash' at line 30 column 31
[INFO] Skipped '\vphantom' at line 30 column 31
[INFO] Skipped '\egroup' at line 30 column 31
[INFO] Skipped '\smash' at line 30 column 31
[INFO] Skipped '\vphantom' at line 30 column 31
[INFO] Skipped '\egroup' at line 30 column 31
:
</pre>

loop.tex
<pre>%\documentclass[english]{ipsj}
%\documentclass[english,preprint]{ipsj}
\documentclass[english,preprint,JIP]{ipsj}

\usepackage{graphicx}
\usepackage{latexsym}

\def\Underline{\setbox0\hbox\bgroup\let\\\endUnderline}
\def\endUnderline{\vphantom{y}\egroup\smash{\underline{\box0}}\\}
\def\|{\verb|}

\setcounter{volume}{26}% vol25=2017
\setcounter{number}{1}%
\setcounter{page}{1}

\received{2016}{3}{4}
%\rereceived{2011}{10}{1}   % optional
%\rerereceived{2011}{10}{31} % optional
\accepted{2016}{8}{1}

\usepackage[varg]{txfonts}%%!!
\makeatletter%
\input{ot1txtt.fd}
\makeatother%
\begin{document}
\Underline{\|\end{biography}|}\\
\|\end{document}|
\end{biography}
\end{document}
</pre>

Is it badly written?
[loop.txt](https://github.com/jgm/pandoc/files/4671231/loop.txt)

**Comment by jgm** [comment] 2020-05-23 16:08
Pandoc should not go into an infinite loop. However, I have no idea what you are trying to do in this document.  Can you explain?

**Comment by jgm** [comment] 2020-05-23 16:09
By the way, the following snippet is sufficient to cause the problem:
```tex
\def\Underline{\setbox0\hbox\bgroup\let\\\endUnderline}
\def\endUnderline{\vphantom{y}\egroup\smash{\underline{\box0}}\\}
\def\|{\verb|}
\Underline{\|\end{biography}|}\\
```

**Comment by jgm** [comment] 2020-05-23 16:10
I think the issue is the `\let\\\endUnderline`.
I don't think pandoc's handling of tex primitives is smart enough to allow redefining `\\`.

**Comment by jgm** [comment] 2020-05-23 16:11
It would be worth tracking down why pandoc loops here and providing some way to detect such cases and bail.

**Comment by jgm** [comment] 2020-05-23 16:17
Inspecting the token grabbed by `satisfyTok`, we see a loop here:
```
Tok "source" (line 1, column 1) (CtrlSeq "def") "\\def"
Tok "source" (line 1, column 5) (CtrlSeq "Underline") "\\Underline"
Tok "source" (line 1, column 15) Symbol "{"
Tok "source" (line 1, column 16) (CtrlSeq "setbox") "\\setbox"
Tok "source" (line 1, column 23) Word "0"
Tok "source" (line 1, column 24) (CtrlSeq "hbox") "\\hbox"
Tok "source" (line 1, column 29) (CtrlSeq "bgroup") "\\bgroup"
Tok "source" (line 1, column 36) (CtrlSeq "let") "\\let"
Tok "source" (line 1, column 40) (CtrlSeq "\\") "\\\\"
Tok "source" (line 1, column 42) (CtrlSeq "endUnderline") "\\endUnderline"
Tok "source" (line 1, column 55) Symbol "}"
Tok "source" (line 1, column 56) Newline "\n"
Tok "source" (line 1, column 56) Newline "\n"
Tok "source" (line 2, column 1) (CtrlSeq "def") "\\def"
Tok "source" (line 2, column 5) (CtrlSeq "endUnderline") "\\endUnderline"
Tok "source" (line 2, column 18) Symbol "{"
Tok "source" (line 2, column 19) (CtrlSeq "vphantom") "\\vphantom"
Tok "source" (line 2, column 28) Symbol "{"
Tok "source" (line 2, column 29) Word "y"
Tok "source" (line 2, column 30) Symbol "}"
Tok "source" (line 2, column 31) (CtrlSeq "egroup") "\\egroup"
Tok "source" (line 2, column 38) (CtrlSeq "smash") "\\smash"
Tok "source" (line 2, column 44) Symbol "{"
Tok "source" (line 2, column 45) (CtrlSeq "underline") "\\underline"
Tok "source" (line 2, column 55) Symbol "{"
Tok "source" (line 2, column 56) (CtrlSeq "box") "\\box"
Tok "source" (line 2, column 60) Word "0"
Tok "source" (line 2, column 61) Symbol "}"
Tok "source" (line 2, column 62) Symbol "}"
Tok "source" (line 2, column 63) (CtrlSeq "\\") "\\\\"
Tok "source" (line 2, column 65) Symbol "}"
Tok "source" (line 2, column 66) Newline "\n"
Tok "source" (line 2, column 66) Newline "\n"
Tok "source" (line 3, column 1) (CtrlSeq "def") "\\def"
Tok "source" (line 3, column 5) (CtrlSeq "|") "\\|"
Tok "source" (line 3, column 7) Symbol "{"
Tok "source" (line 3, column 8) (CtrlSeq "verb") "\\verb"
Tok "source" (line 3, column 13) Symbol "|"
Tok "source" (line 3, column 14) Symbol "}"
Tok "source" (line 3, column 15) Newline "\n"
Tok "source" (line 3, column 15) Newline "\n"
Tok "source" (line 4, column 1) (CtrlSeq "setbox") "\\setbox "
Tok "source" (line 4, column 1) Word "0"
Tok "source" (line 4, column 1) (CtrlSeq "hbox") "\\hbox"
Tok "source" (line 4, column 1) (CtrlSeq "hbox") "\\hbox"
Tok "source" (line 4, column 1) (CtrlSeq "hbox") "\\hbox"
Tok "source" (line 4, column 1) (CtrlSeq "hbox") "\\hbox"
Tok "source" (line 4, column 1) (CtrlSeq "setbox") "\\setbox "
Tok "source" (line 4, column 1) Word "0"
Tok "source" (line 4, column 1) (CtrlSeq "hbox") "\\hbox"
Tok "source" (line 4, column 1) (CtrlSeq "hbox") "\\hbox"
Tok "source" (line 4, column 1) (CtrlSeq "bgroup") "\\bgroup"
Tok "source" (line 4, column 1) (CtrlSeq "let") "\\let"
Tok "source" (line 4, column 1) (CtrlSeq "\\") "\\\\"
Tok "source" (line 4, column 1) (CtrlSeq "endUnderline") "\\endUnderline"
Tok "source" (line 4, column 11) Symbol "{"
Tok "source" (line 4, column 11) Symbol "{"
Tok "source" (line 4, column 12) (CtrlSeq "verb") "\\verb"
Tok "source" (line 4, column 12) Symbol "|"
Tok "source" (line 4, column 14) (CtrlSeq "end") "\\end"
Tok "source" (line 4, column 18) Symbol "{"
Tok "source" (line 4, column 19) Word "biography"
Tok "source" (line 4, column 28) Symbol "}"
Tok "source" (line 4, column 29) Symbol "|"
Tok "source" (line 4, column 30) Symbol "}"
Tok "source" (line 4, column 31) (CtrlSeq "vphantom") "\\vphantom"
Tok "source" (line 4, column 31) Symbol "{"
Tok "source" (line 4, column 31) Word "y"
Tok "source" (line 4, column 31) Symbol "}"
Tok "source" (line 4, column 31) (CtrlSeq "egroup") "\\egroup"
Tok "source" (line 4, column 31) (CtrlSeq "egroup") "\\egroup"
Tok "source" (line 4, column 31) (CtrlSeq "smash") "\\smash"
Tok "source" (line 4, column 31) Symbol "{"
Tok "source" (line 4, column 31) (CtrlSeq "underline") "\\underline"
Tok "source" (line 4, column 31) Symbol "{"
Tok "source" (line 4, column 31) (CtrlSeq "box") "\\box "
Tok "source" (line 4, column 31) Word "0"
Tok "source" (line 4, column 31) Symbol "}"
Tok "source" (line 4, column 31) Symbol "}"
Tok "source" (line 4, column 31) (CtrlSeq "vphantom") "\\vphantom"
Tok "source" (line 4, column 31) (CtrlSeq "vphantom") "\\vphantom"
Tok "source" (line 4, column 31) Symbol "{"
Tok "source" (line 4, column 31) Word "y"
Tok "source" (line 4, column 31) Symbol "}"
Tok "source" (line 4, column 31) (CtrlSeq "egroup") "\\egroup"
Tok "source" (line 4, column 31) (CtrlSeq "egroup") "\\egroup"
Tok "source" (line 4, column 31) (CtrlSeq "smash") "\\smash"
Tok "source" (line 4, column 31) (CtrlSeq "smash") "\\smash"
Tok "source" (line 4, column 31) Symbol "{"
Tok "source" (line 4, column 31) (CtrlSeq "underline") "\\underline"
Tok "source" (line 4, column 31) Symbol "{"
Tok "source" (line 4, column 31) (CtrlSeq "box") "\\box "
Tok "source" (line 4, column 31) Word "0"
Tok "source" (line 4, column 31) Symbol "}"
Tok "source" (line 4, column 31) Symbol "}"
Tok "source" (line 4, column 31) (CtrlSeq "vphantom") "\\vphantom"
Tok "source" (line 4, column 31) (CtrlSeq "vphantom") "\\vphantom"
Tok "source" (line 4, column 31) Symbol "{"
Tok "source" (line 4, column 31) Word "y"
Tok "source" (line 4, column 31) Symbol "}"
Tok "source" (line 4, column 31) (CtrlSeq "egroup") "\\egroup"
Tok "source" (line 4, column 31) (CtrlSeq "egroup") "\\egroup"
Tok "source" (line 4, column 31) (CtrlSeq "smash") "\\smash"
Tok "source" (line 4, column 31) (CtrlSeq "smash") "\\smash"
```

**Comment by kanata25** [comment] 2020-05-25 14:42
> Pandoc should not go into an infinite loop. However, I have no idea what you are trying to do in this document. Can you explain?

I'm thinking of converting Japanese papers to JATS using Pandoc. I got a template LaTeX manuscript from the internet, tried it a few times, and Pandoc hung up. It is supposed to be used by embedding it in the system, and I am exploring whether there is a method because it may be a workaround.

> It would be worth tracking down why pandoc loops here and providing some way to detect such cases and bail.

My poor linux server will die after a few hours, so I'll try to avoid it with the following command.

<pre><code>timeout 20 pandoc --from=latex --to=jats_publishing --template default.jats --metadata-file="xxx.yml" "loop.tex"</code></pre>

I would appreciate it if you could improve it so that it wouldn't hang if possible, or let me specify a timeout option.

**Comment by jgm** [comment] 2020-05-25 16:14
Since you can impose a timeout using an external command, separation of concerns speaks against building that into pandoc.  But I'd like to fix the loop!  reproducing tex's macro processing is not an easy task.

**Comment by kanata25** [comment] 2020-05-26 03:11
Thank you for your comment.
Since the timeout command is called, do not hurry. 
It may be a difficult task, but I would appreciate it if you can fix it so that it does not loop.

**Comment by positron96** [comment] 2022-02-22 11:38
So, my `pandoc` has been running for 2 hours reading a tex file, I assume I've hit the same problem. Has there been any progress regarding the issue?

**Comment by jgm** [comment] 2022-02-22 16:50
There have been some changes which might affect this issue. (What version are you using?)
I note that with the most recent version of pandoc, we don't get a loop with loop.tex above:
```
% pandoc loop.tex
[WARNING] Could not load include file ot1txtt.fd.tex at loop.tex line 27 column 19
Error at "loop.tex" (line 32, column 16):
expecting \end{document}
\end{biography}
               ^
```

**Comment by jgm** [comment] 2022-02-22 17:02
Closing this issue because the above cases don't produce loops.  If you have a new case that loops, please open a new issue.

**Closed** 2022-02-22 17:02 UTC
Labels: format:LaTeX, reader

**Comment by positron96** [comment] 2022-02-24 04:11
Ok, I believe I've hit another bug then, since my pandoc (with `--verbose` flag) is looping on parsing tex files included in big root tex file. Unfortunately I'm not in position to share the files, so unless I can make a reproducible minimal example, I'm stuck with this bug.

**Comment by jgm** [comment] 2024-02-09 19:12
@dokterbob if you comment out the line
```
% \usepackage{iclr2024_conference,times}
```
then pandoc can handle it.  I haven't chased this down yet, but it looks like a problem interpreting one of the macros defined in iclr2024_conference.sty.
