### ISSUE TITLE
Remove parentheses around author-suppressed citations in footnotes

### ISSUE THREAD

**Issue by bdhamilton** [jgm/pandoc#6828] opened 2020-11-11 18:24 UTC
In pandoc 2.11.1.1 and citeproc 0.1.1.1, the following Markdown:

`[^note]: Finn first laid out his proposal in -@finn2016...`

produces the following output in PDF:

<img width="382" alt="Screen Shot 2020-11-10 at 1 20 10 PM" src="https://user-images.githubusercontent.com/2359963/98849008-8858b380-2420-11eb-8288-8210bf9605f6.png">

Note that all author-suppressed citations are wrapped in parentheses. Those parentheses should be removed to bring the behavior into alignment with current behavior for citations that include the author.

**Comment by tillgrallert** [comment] 2020-12-30 16:38
In pandoc 2.11.3.2 I get parentheses around citations in notes no matter what I do. Consider this md example:

```md
Lorem ipsum dolor[@Said+2001] sit amet consectetur[^1]

[^1]: [@Said+2001]
```

The reference is (CSL JSON):

```json
[{"id":"Said+2001","author":[{"family":"Said","given":"Edward W."}],"container-title":"The Nation","issued":{"date-parts":[[2001,10,22]]},"language":"en","title":"The Clash of Ignorance","type":"article-newspaper","URL":"http://www.thenation.com/article/clash-ignorance"}]
```

The output (HTML for illustrative purposes) with a common note based CSL, such as Chicago Manual of Style 17th edition is the following:

<p>Lorem ipsum dolor<span class="citation" data-cites="Said+2001"><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></span> sit amet consectetur<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<section class="footnotes" role="doc-endnotes">
<hr />
<ol>
<li id="fn1" role="doc-endnote"><p><em>The Nation</em>, October 22, 2001, <a href="http://www.thenation.com/article/clash-ignorance" role="doc-biblioref">http://www.thenation.com/article/clash-ignorance</a>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2" role="doc-endnote"><p><span class="citation" data-cites="Said+2001"> (<em>The Nation</em>, October 22, 2001)</span><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>


 Is this intended behaviour? Because I could not find any documentation for it.

**Comment by jgm** [comment] 2020-12-30 18:29
@tillgrallert - If you're using a note style, then regular citations in notes will be put in parentheses.  But if you use an in-text citation like `@Said+2001` (no brackets), it will be rendered without parentheses. This ought to be documented better.

**Comment by tillgrallert** [comment] 2020-12-30 21:58
@jgm thank you very much for the quick reply and the manual draft. This might not be the right place to ask this question but what is the rationale behind wrapping "normal" citations in footnotes in parentheses? Coming from history and related disciplines that never use author-date referencing, I have not once encountered references in footnotes that were wrapped in parentheses.

**Comment by jgm** [comment] 2020-12-30 23:23
> what is the rationale behind wrapping "normal" citations in footnotes in parentheses?

There's a long discussion of this issue at <https://groups.google.com/g/pandoc-discuss/c/8YoFxeexDWs/m/a85v_OR3AwAJ>. (Some of the changes proposed there have already been made, so don't get confused.) You may want to contribute to that thread.

**Comment by tillgrallert** [comment] 2020-12-30 23:36
Thank you very much for this response.

**Comment by tarleb** [comment] 2021-05-05 11:16
I believe this has been resolved, hence closing.

**Closed by tarleb** 2021-05-05 11:16 UTC
