### ISSUE TITLE
docx annotations

### ISSUE THREAD

**Issue by pyarmak** [jgm/pandoc#2884] opened 2016-04-28 18:36 UTC
So I see it is possible to get tracked changes out of a docx using `--track-changes` but is it possible to get annotations out as well? 
[unoconov](https://github.com/dagwieers/unoconv) gets out the annotations but doesn't get the tracked changes so I'm looking for an amalgamation of sorts I guess—a best of both worlds of sorts.

**Comment by jgm** [comment] 2016-04-28 20:49
@jkr

**Comment by jkr** [comment] 2016-04-29 19:22
I can take a look, now that classes are over and I have a bit of time. @pyarmak: are these the same as track-changes comments or a different word feature? Could you post a sample docx with annotations so I can take a look?

The same question as always applies: where would we put them after we take them out? Comments? More likely, some form of `<span class="annotation"...` . But then would we need a command-line toggle?

@jgm: there's another issue that comes along with this: annotations can probably have blocks inside of them. `Note` is the only inline that can take blocks, right?

**Comment by pyarmak** [comment] 2016-04-29 19:34
@jkr yeah when I said annotations I mean those track-changes comments (all under review tab if memory serves correctly). 
And yeah I was thinking sort of the same way that tracked changes are handled with spans and a command line flag. 
The only thing that I think might cause issues are the nested comments (i.e. when a person comments on a comment).

**Comment by jgm** [comment] 2016-04-29 20:03
+++ Jesse Rosenthal [Apr 29 16 12:22 ]:
>   [2]@jgm: there's another issue that comes along with this: annotations
>   can probably have blocks inside of them. Note is the only inline that
>   can take blocks, right?

Correct.

**Comment by jgm** [comment] 2016-04-29 20:04
+++ Jesse Rosenthal [Apr 29 16 12:22 ]:
>   [2]@jgm: there's another issue that comes along with this: annotations
>   can probably have blocks inside of them. Note is the only inline that
>   can take blocks, right?

But you could always squish the blocks into inlines;
presumably there's very rarely block structure in an
annotation.

**Comment by jkr** [comment] 2016-05-03 16:20
Yeah -- we'd have to squash them somehow. The way it works internally is that comments are in their own file (like footnotes and endnotes) so there isn't any xml issue of having a block inside of an inline. Obviously we can't do that. Two questions we need to answer on this before we move forward:

1. How to squash. Two options I see here:

    a. replace par breaks by `[LineBreak, LineBreak]`
    b. insert a pilcrow (¶) or some other graphical marker.  
  I'd actually prefer option (b), since in those rare occasions where it arises, I'd like to know what's actually going on. But I imagine that most would prefer option (a). I'd go along with the general sentiment (or precedent, if there is any).

2. Where to place the comment. The problem is that it's usually a comment on a selected region. Because it uses text in another file, the selection can span paragraphs. Here, again, I see three options:

    a. Simply place the comment at the opening: `<span comment="..."></span>`

    b. Place an element at the beginning and the end: 
    
    ```          
    <span id="comment-1-begin" comment="..."></span>
    ...
    <span id="comment-1-end"></span>
    ```

    c. Surround text in a span. If it goes across blocks, close and then continue:

    ```          
    <p>...<span id="comment-1" comment="...">text text text</span></p>
    
    <p><span id="comment-1a">text text text</span>...</p>
    ```
   My sense here is that (b) or (c) is better, since there isn't much point in preserving a comment without at least attempting to preserve its context. Of the two, I think I prefer (c) since in the usual case, it reduces to a single span around the selected text.

@jgm: thoughts?

**Comment by jgm** [comment] 2016-05-03 17:04
1(b) sounds okay to me.  [LinBreak, LineBreak] doesn't work
too well in all output formats (e.g. LaTeX).

2(c) sounds fine too.  I don't have strong feelings.

**Comment by nokome** [comment] 2016-06-21 15:51
Just noting that #1561 is related (actually is probably a duplicate).

Also offering to help out with this issue where I can. I have zero experience with Haskell but could write an implementation in C++ (or Python) if that is of use as a starting point for someone else to translate into Haskell.

**Comment by jkr** [comment] 2016-06-21 17:03
The holdup isn't the comments themselves, which are fairly trivial. It's the related issue of having a satisfactory `[Block] -> [Inline]` function, which I haven't had time to massage the edge-cases on (tables, in particular). I'll try to get to that this week, and the rest should follow easily on that.

**Comment by nokome** [comment] 2016-06-21 17:21
Thanks @jkr. For my use case (embedding code in comments) I need to maintain line breaks and other whitespace formatting when squashing. I assume it should be fine to include "\n" (or pilcrow) and "\t" characters in the `comment` attribute.

Also, are you planning to address `html`->`docx` conversion of comments i.e. going back the other way?

**Comment by jkr** [comment] 2016-06-22 14:42
@nokome: comments in the docx writer is doable, and should come after this. (We still have to decide exactly what a comment span looks like.) Note, though, that we wouldn't be able to perform a roundtrip. `[Block] -> [Inline]` is necessarily lossy, so we couldn't run `[Inline] -> [Block]` to get back what we had before. (Basically, you can put whatever you want inside, except for a footnote, inside a docx comment, but in the pandoc AST, it can only be a set of inlines, because it has to fit inside a span.)

**Comment by jkr** [comment] 2016-06-23 15:00
Okay -- I just pushed some basic comment functionality to the docx reader with 8bb739f7ff353722981fe442ae0c137910604850. Note that it has to be run with `--track-changes=all`. Also, you will get warnings if the comments includes anything other than paras or plains, though we will do the best to convert them in a sensible way. 

I'm going to close this and open up a new issue for adding comments to the docx writer.

**Closed by jkr** 2016-06-23 15:00 UTC

**Comment by dbaynard** [comment] 2016-08-16 17:26
It might be worth modifying the html templates to display comments differently by default; as it stands comments are inserted bang in the middle of the text.

**Comment by alyjak** [comment] 2016-08-16 18:00
Why aren't comments added as footnotes? It looks like you could re-use that code verbatim for this feature. Maybe just make the footnote reference id have the word comment in it or something similar to identify that it's a different type of footnote.

**Comment by dbaynard** [comment] 2016-08-16 18:10
For someone familiar with filters, it would be fairly straightforward to convert the comments to footnotes. My point was that as a default, the comments shouldn’t be inserted into the text without identification.

**Comment by jkr** [comment] 2016-08-16 20:28
Comments only show up with `--track-changes=all`, right? So if there were any insertions or deletions, those would just be sitting next to each other in there as well.

I guess the obvious css would be: insertions = green and deletions=green and strikethrough. But what would you suggest for comments? Boxed somehow?

I take it this would be for stand-alone output?

**Comment by dbaynard** [comment] 2016-08-16 22:51
I’ve put some suggested css for comments at jgm/pandoc-templates#213.

```css
span.comment-start:before {
    content: "(" attr(date) ")";
    display: block;
    text-align: right;
}
span.comment-start {
    position: relative;
    float: right;
    border: black solid thin;
    background-color: bisque;
    padding: 6px;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    -o-user-select: none;
    user-select: none;
}
span.comment-start:after {
    content: "--" attr(author);
    display: block;
    text-align: right;
}
```

I think insertions are more blue and underlined in Word, green in coloured diff output, green and underlined (for all) in google docs and blue in libreoffice. The underline helps with monochrome printing, which might be relevant for css. So I guess green and underline for insertions?

We could do something different for screen and print, actually.

The footnotes idea isn’t too bad, but I think the goal should be to have a sensible default that makes it clear track changes has been left on!

The other question concerns other output formats; I assume they would all silently ignore the spans.

Excellent work, by the way. This is a really, really useful feature. Type a thesis in markdown, send to supervisor as docx, and extract comments afterwards for a to-do list. Great job!

**Comment by dbaynard** [comment] 2016-08-31 02:18
@jkr This relates (tangentially) to #2374. Would you be up for adding an ‘enhancement’ issue for all of this? Happy to contribute.
