### ISSUE TITLE
\let\Oldsection\section in YAML header-includes gets parsed wrong

### ISSUE THREAD

**Issue by didibus** [jgm/pandoc#3522] opened 2017-03-22 06:29 UTC
Hi,

I'm adding`\let\Oldsection\textbackslash{}section` to my pandoc markdown YAML header-include.

```
---
header-includes:
- \usepackage[section]{placeins}
- \let\Oldsection\section
- \renewcommand{\section}{\FloatBarrier\Oldsection}
- \let\Oldsubsection\subsection
- \renewcommand{\subsection}{\FloatBarrier\Oldsubsection}
- \let\Oldsubsubsection\subsubsection
- \renewcommand{\subsubsection}{\FloatBarrier\Oldsubsubsection}
---
```

So that my figures in subsections show up where I declared them. Found this solution here: http://tex.stackexchange.com/questions/279/how-do-i-ensure-that-figures-appear-in-the-section-theyre-associated-with/235312#235312

The problem is the latex it generates is as follows:

```
\usepackage[section]{placeins}
\let\Oldsection\textbackslash{}section
\renewcommand{\section}{\FloatBarrier\Oldsection}
\let\Oldsubsection\textbackslash{}subsection
\renewcommand{\subsection}{\FloatBarrier\Oldsubsection}
\let\Oldsubsubsection\textbackslash{}subsubsection
\renewcommand{\subsubsection}{\FloatBarrier\Oldsubsubsection}
```

As you can see, the let does not work, because it added the `textbackslash{}` to some of my headers. I'm not sure if this parsing is intentional, if so, how can I escape it so that my latex shows up as is?

Using pandoc 1.19.2.1 on Windows 7 with texlive 2010.

**Comment by wilx** [comment] 2017-03-22 10:57
I think this is a duplicate of #2139.

**Comment by wilx** [comment] 2017-03-22 11:00
Use separate `header.tex` file for those definitions that you will include using `--include-in-header=` switch on command line to work around this.

**Comment by mb21** [comment] 2017-03-22 12:42
jep, closing in favour of https://github.com/jgm/pandoc/issues/2139

**Closed by mb21** 2017-03-22 12:42 UTC
