### ISSUE TITLE
Table in table doesn't work from html to latex

### ISSUE THREAD

**Issue by kasperpeulen** [jgm/pandoc#4419] opened 2018-02-28 13:27 UTC
Some of the html we put in pandoc, contains tables inside of tables. It seems impossible to compile this in latex. Here is an example:

https://pandoc.org/try/?text=%3Ctable%3E%0A%3Ctr%3E%0A%3Ctd%3E%0A%3Cp%3EFirst+paragraph%3C%2Fp%3E%0A%3Ctable%3E%0A%3Ctr%3E%0A%3Ctd%3E%0A%3Cp%3EHello+world%3C%2Fp%3E%0A%3C%2Ftd%3E%0A%3C%2Ftr%3E%0A%3C%2Ftable%3E%0A%3C%2Ftd%3E%0A%3C%2Ftr%3E%0A%3C%2Ftable%3E&from=html&to=latex

If I parse the resulting latex, I get a compile error:
```
Argument of \LT@nofcols has an extra }.
<inserted text> 
                \par 
l.14 \begin{longtable}[]{@{}l@{}}
```

**Comment by mb21** [comment] 2018-02-28 14:06
Duplicate of https://github.com/jgm/pandoc/issues/3586

**Closed by mb21** 2018-02-28 14:06 UTC

**Comment by mb21** [comment] 2018-02-28 14:07
Your best bet is to use a different `--pdf-engine`
