### ISSUE TITLE
Multiple Definition Lists directly next to eachother, get translate to AST as a single definition. 

### ISSUE THREAD

**Issue by ekiim** [jgm/pandoc#4818] opened 2018-08-07 03:33 UTC
Pandoc 2.2.1
`pandoc  -t json file.md`

I found this problem, that when I put two definition lists next to each other, get render to the AST, as one definition, for exampe, Word one, Is a Def List, then It's followed by a Paragraph, and then, according to the AST, get render to a single definition, when I'm intending it to be two seperate definitions.
```
Word one
: This is the body of the definition
: This is an alternative definition of multiple lines and well we all alot of
    text that falls under the same scope of this definition, but still is
    technically spread over three lines
: This is the body of the definition


This is some dummy tesxt innter paragraph


Theorem {#id .class-one .class-two data-set="theorems"}
: This is the body of the definition



Corolary {#identifier .class-three .class-four data-grid="tester"}
: This is the body of the definition



```
A little bit of context, I'm working on a Filter, that allows to have Attributes in Definition lists, (still experimenting on it). So I can have Theorem, Definition, Corloary, or Word Definition Like Structure. 
And well, In this context having two definitions in a row, makes perfect sence....

Any Ideas, What I can do?
Currently I'm solving it by putting a Horizontal Rule to seperate, and then remove If It's in between to deflists, in the AST, but I think this should be simpler...

**Comment by jgm** [comment] 2018-08-07 05:12
If I understand you correctly, you would like the `Theorem` and `Corolary` parts to be two separate definite lists, instead of one definition list containing two definitions.  Is that correct?

This is a special case of a general issue with lists in Markdown. For example, two adjacent ordered lists will be parsed as a single ordered list.  The standard solution is to put a blank HTML comment between them.

**Comment by ekiim** [comment] 2018-08-07 06:03
Exactly that. 
I tried that, I don't love the solution but it works. 
Is there ever going to be Id, Attributes, Classes for all elements in the AST? 
Because so far with the filter (json) I'm doing, I can put them, but pandoc ignores them.

**Comment by jgm** [comment] 2018-08-07 16:02
No concrete plans. It would be nice, eventually.

You could put your definition list inside a div with the attributes. These will be parsed and included in the AST.

```
::: {.theorem #mytheorem}
My Theorem
:   Blah blah blah.
:::
```

**Comment by jgm** [comment] 2018-08-07 16:02
Closing this because it's not a bug.

**Closed by jgm** 2018-08-07 16:02 UTC
