### ISSUE TITLE
conversion fail: html --> tex

### ISSUE THREAD

**Issue by pauloney** [jgm/pandoc#2287] opened 2015-07-09 22:00 UTC
Converting (v. 1.15.0.4) an HTML file with base64 included images to LaTeX generates a file that is not usable by LaTeX.

Example: pandoc sample.html -s -o sample.tex

```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
        <head>
                <meta charset="utf-8" />
                <title>Key</title>
        </head>
        <body id="Otgovori" lang="en-US">
                <div>
                        <p class="Normal">Example 1</p>
                        <p class="Normal"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADQAAAA4CAYAAACyutuQAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAjUlEQVRoQ+3RQQqAMAxEUc/iWbz/laLiRrqJTBAm4RcedJFSPtkiYpskHejmPjFMOtDNc8lW6Y4gdwS5I8gdQe4IckeQO4Lc/Rp0nf31werI3isIqlgCCfqCoAqCBARVECQgqIIgAUEVBAkIqiBIQFAFQQKC3BHkjiB3BLkjyN38oEHSgV6yVXaTDnRzAnzm9tRRL/2RAAAAAElFTkSuQmCC" alt="" />&#9;a) 2625371;  b) 2867029; c) 52040339;  d) 2034;</p>
                </div>
        </body>
</html>
```

The file produced is not usable by any of the latex engines.

As remarked by Kurt Pfeifer, the convertion html --> pdf works flawlessly.

Paulo Ney

**Comment by jgm** [comment] 2015-07-09 22:56
I'm not sure there's a good way to fix this, unless LaTeX
have some way to emed binary image data in a source file.
So, maybe not a bug.

+++ Paulo Ney de Souza [Jul 09 15 15:00 ]:

**Comment by KurtPfeifle** [comment] 2015-07-10 00:28
> [....] good way to fix this, unless LaTeX have some way to embed binary image data in a source file.

How does the direct HTML => PDF conversion work ? -- Surely by extracting the embedded `data:` images into separate, temporary files.

It should be similar for HTML => LaTeX then, maybe by providing an extra command line switch,\
`--extract-data-uris`, or by extending the `--extract-media=<dir>` from EPUB/DOCX/ODT(soon) also to HTML?

**Comment by KurtPfeifle** [comment] 2015-07-10 00:29
(Sorry for having opened the separate issue #2289 -- I hadn't noticed this one when I did)

**Comment by KurtPfeifle** [comment] 2015-07-10 00:35
@pauloney: I do not think your $subject for this issue is a fair description of the problem. The conversion to LaTeX isn't a complete failure. It's just that (current) LaTeX=>PDF processors cannot handle the `data:`-URIs.  

Maybe also ask for a feature addition in that direction? (For LuaLaTeX see here: [tracker.luatex.org/my_view_page.php](http://tracker.luatex.org/my_view_page.php).)

**Comment by jgm** [comment] 2015-07-10 00:36
+++ Kurt Pfeifle [Jul 09 15 17:28 ]:
>     [....] good way to fix this, unless LaTeX have some way to embed
>     binary image data in a source file.
>
>   How does the direct HTML => PDF conversion work ? -- Surely by
>   extracting the embedded data: images into separate, temporary files.
>
>   It should be similar for HTML => LaTeX then, maybe by providing an
>   extra command line switch,\
>   --extract-data-uris, or by extending the --extract-media=<dir> from
>   EPUB/DOCX/ODT(soon) also to HTML?

`--extract-media` is (currently) used only for the media
that occur as files in zipped containers (docx, epub, odt).
It might be worth considering extending it to data: URIs.
We'd need to evaluate all the consequences of that.

**Comment by jgm** [comment] 2015-07-10 00:49
Closing this in favor of #2289.

**Closed by jgm** 2015-07-10 00:49 UTC
