### ISSUE TITLE
Tables in docx come up with width 30.48cm

### ISSUE THREAD

**Issue by danni** [jgm/pandoc#956] opened 2013-08-19 06:46 UTC
Tables appear with width of 30.48cm.

Looking at the document in Libreoffice this causes the table to expand off the side of the page.

**Comment by bkasel** [comment] 2016-06-14 20:49
Hi, while looking for a solution to my problem with table widths, I found that this issue seems to be a duplicate of #515

**Comment by jgm** [comment] 2016-06-15 01:34
Closing in favor of #515.

**Closed by jgm** 2016-06-15 01:34 UTC
