### ISSUE TITLE
Loop encountered in expanding macro quote

### ISSUE THREAD

**Issue by hugoroy** [jgm/pandoc#5083] opened 2018-11-15 16:43 UTC
Pandoc version: 2.4
Compiled with pandoc-types 1.17.5.4, texmath 0.11.1.2, skylighting 0.7.4

After upgrading my system, compiling a document from markdown to latex no longer worked. I obtained the error: "Loop encountered in expanding macro quote"

Unfortunately, the document I am working on is fairly complex, and confidential. I cannot simply share it here. The command uses the --standalone option and several filters (pandoc-citeproc, and pandoc-latex-environment among other simple filters).

**Comment by jgm** [comment] 2018-11-15 17:42
We can't do anything with this unless there's a way to
reproduce the problem.

The error is produced when pandoc sees it's in a loop
in expanding latex macros.  So it has to do with the
latex macros in your document.

Perhaps you can construct a minimal working example
that reproduces the problem without confidential
information.  Try stripping things out of your
document bit by bit and get the smallest test case
possible that still shows the problem.  (Start by
removing the filters.) Then anonymize it.

If you can't do this, we'll just have to close this,
because there's no way to go forward...

**Comment by hugoroy** [comment] 2018-11-15 17:56
↪ John MacFarlane / 2018-11-15, 18:43 (CET):
> The error is produced when pandoc sees it's in a loop
> in expanding latex macros.  So it has to do with the
> latex macros in your document.


Thanks for the hint.


> Perhaps you can construct a minimal working example
> that reproduces the problem without confidential
> information.  Try stripping things out of your
> document bit by bit and get the smallest test case
> possible that still shows the problem.  (Start by
> removing the filters.) Then anonymize it.


Yes, I will try this and focus on the latex parts.


> If you can't do this, we'll just have to close this,
> because there's no way to go forward...


Of course, I totally understand.

**Closed** 2018-11-26 22:39 UTC
Labels: closing candidate, format:LaTeX
