### ISSUE TITLE
Markdown -> odt : table not rendered

### ISSUE THREAD

**Issue by ngirard** [jgm/pandoc#5991] opened 2019-12-14 22:00 UTC
The following test.md file, when rendered as text or html, produces a table as expected. 
But when calling `pandoc test.md -o test.odt`, no table appears in the produced odt file.

test.md:
```markdown
# Lorem ipsum

1) Lorem ipsum
   
   | Name               | Description        |
   | -------------------|--------------------|
   | `param_1`          | Lorem ipsum        |
   | `param_2`          | Lorem ipsum        |

2) Dolor sit amet
```

**Comment by mb21** [comment] 2019-12-15 10:31
Probably a duplicate of https://github.com/jgm/pandoc/issues/3430 ?

**Closed** 2019-12-15 11:49 UTC
