### ISSUE TITLE
PDF: `--fail-if-warnings` fails to fail when resource not found

### ISSUE THREAD

**Issue by ResponSySS** [jgm/pandoc#4455] opened 2018-03-15 19:28 UTC
```
$ pandoc --version
pandoc 2.1.2
Compiled with pandoc-types 1.17.3.1, texmath 0.10.1.1, skylighting 0.6
```

# Source
```
---
title: "Misère du Féminisme"
author: revue La Guerre Sociale (Dominique Karamazov)
---

« Ras le viol », « Terre des hommes, viol de nuit», « La drague, c'est le viol » ... Les slogans féministes prennent le relais des gros titres de la presse à sensation. Un nouveau cheval de bataille a suceédé à l'avortement. Inscriptions murales, manifestations, batailles judiciaires, débats, procès et ripostes sauvages se développent.

![L'anti-viol, Cosmopolitan - juillet 1977](./anti-viol.jpg)
```

# Commands used

## Ignore `--fail-if-warnings` (PDF)
```
$ pandoc --fail-if-warnings -s in.md -o out.pdf`

[WARNING] Could not fetch resource './anti-viol.jpg': replacing image with description
```
(success)

## Does not ignore `--fail-if-warnings` (EPUB)
```
$ pandoc --fail-if-warnings -s in.md -o out.epub`

[WARNING] Could not fetch resource './anti-viol.jpg': PandocResourceNotFound "./anti-viol.jpg"
Failing because there were warnings.
```
(it returns 3)

**Comment by jgm** [comment] 2018-03-15 19:45
Thanks for the report.

This is because we have to run some things in Text.Pandoc.PDF
in IO rather than PandocIO.  It would be good to chage that,
but as I recall this is problematic because of the type of
`withTemp`.

**Comment by jgm** [comment] 2019-03-01 19:22
#5343 was a duplicate of this issue.

It has now been fixed.

**Closed by jgm** 2019-03-01 19:22 UTC
