### ISSUE TITLE
Using --slide-level option looses content

### ISSUE THREAD

**Issue by nicoulaj** [jgm/pandoc#3914] opened 2017-09-11 10:54 UTC
The  `--slide-level` option behaves quite surprisingly, as it discards any content from sections above the configured slide level (with all slides output types: beamer, dzslides, reaveal, etc)

For instance, with this document:
```
Section 1
======

Lorem ipsum dolor sit amet

Section 2
======

Section 2.1
------------
Lorem ipsum dolor sit amet

Section 2.2
------------
Lorem ipsum dolor sit amet
```

If I run: `pandoc document.md -s -o document.html -t slidy --slide-level=2`
 => I get a slide for each subsection, but text from "Section 1" is lost

If I run: `pandoc document.md -s -o document.html -t slidy --slide-level=1`
 => No text is lost, but I only get one slide for "Section 1", and one for "Section 2".

What I really want is one slide for "Section 1", one for "Section 2", one for "Section 2.1", and one for "Section 2.2", and the current set of options does not allow that (except not using this option at all, and manually inserting line separators everywhere in the document).

Pandoc version:
```
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.5, texmath 0.9.4.1, skylighting 0.1.1.5
```

**Comment by mb21** [comment] 2017-09-11 11:26
Duplicate of #816

**Closed** 2017-09-12 11:19 UTC
