### ISSUE TITLE
Highlights in inline code with syntax highlighting

### ISSUE THREAD

**Issue by schar** [jgm/pandoc#7560] opened 2021-09-09 18:25 UTC
Inline code attributes allow code highlighting, as described [here](https://pandoc.org/MANUAL.html#extension-inline_code_attributes). However, though my `.theme` file has a background color set, inline code is not rendered with any background (non-inline code blocks are rendered as expected). I would like to combine inline code syntax highlighting with background color, and don't see a way to do this. Take this md code:

```
`<$>`{.haskell}
```

Pandoc renders this to tex as `\VERB|\OperatorTok{\textless{}$\textgreater{}}|`. When I postprocess the tex file by wrapping this in a `\tcbox` from `tcolorbox` and crucially changing the `$` to `\$` (following hints I have found, e.g. [here](https://github.com/jgm/skylighting/issues/122)), I get the output I'm looking for. I would like this to be how my inline code is automatically rendered in tex, but anything I can see to try (e.g., redefining `\VERB`) does not seem workable.

**Comment by jgm** [comment] 2021-09-09 19:46
What pandoc version, what output format?
I think this is essentially a duplicate of https://github.com/jgm/skylighting/issues/122

**Comment by schar** [comment] 2021-09-09 19:55
Output is beamer tex. Pandoc version is 2.14.2.

**Comment by jgm** [comment] 2021-09-10 04:22
See the linked issue for the problems we've encountered.

**Comment by mb21** [comment] 2021-11-19 09:43
Closing in favour of jgm/skylighting#122

**Closed by mb21** 2021-11-19 09:43 UTC
Labels: enhancement
