### ISSUE TITLE
JATS conversion throws the error

### ISSUE THREAD

**Issue by Opussci** [jgm/pandoc#8407] opened 2022-10-31 23:54 UTC
I am trying to convert with pandoc this JATS file (https://peerj.com/articles/8236.xml). The file is created by some other tool than Pandoc (XSL transformation) and I try to convert it to some other formats, i.e. HTML and Docx. Pandoc throws the error: Invalid XML: ParseError {errorContexts = ["text content"], errorMessage = "Failed reading: takeWhile1", errorPosition = 236:52 (9688)}. 
@tarleb It seems to me that there are differences in the declarative part before the front part but could that be the only cause of this issue?

**Comment by jgm** [comment] 2022-11-01 04:23
What pandoc version are you using?  ANd what full command line?
I don't get an error on this file with the latest release of pandoc, using `pandoc -f jats 8236.xml`.

**Comment by tarleb** [comment] 2022-12-18 10:12
I can't reproduce the error either, so I'm assuming that this was a temporary error or that it has been fixed. Closing.

**Closed by tarleb** 2022-12-18 10:12 UTC
Labels: reader, format:JATS
