### ISSUE TITLE
pandoc chokes on odp/ods files

### ISSUE THREAD

**Issue by ngoonee** [jgm/pandoc#7973] opened 2022-03-19 22:30 UTC
**Explain the problem.**
Include the exact command line you used and all inputs necessary to reproduce the issue.  Please create as minimal an example as possible, to help the maintainers isolate the problem.  Explain the output you received and how it differs from what you expected.

When running `pandoc file.odp` it shows the following:-
[WARNING] Could not deduce format from file extension .odp
  Defaulting to markdown
[WARNING] fileodp is not UTF-8 encoded: falling back to latin1.

Same thing happens to .ods files. CPU usage gets pegged to 100%, memory usage climbs till the OOM starts killing stuff. This did not use to happen (2.14.2)

**Pandoc version?**
What version of pandoc are you using, on what OS?

I'm using 2.15 on Arch Linux (the current version in the repos). Have also tested with 2.17.1.1 (binary version downloaded from the Arch User Repository) and this is still an issue.

**Comment by jgm** [comment] 2022-03-20 06:04
What is an opd file? And what made you think that pandoc could convert opd files?  The format is not listed in the manual.

As the warning message indicates, pandoc defaults to treating input as markdown when the format can't be determined.  Since this is evidently a binary format, this doesn't work well...

**Comment by ngoonee** [comment] 2022-03-20 11:23
odp files (not opd) are OpenOffice Presentation files. ods files are OpenOffice Spreadsheet files. These same files worked fine with 2.14.2 (in the sense that pandoc did not hang on it and escalate memory consumption continuously). To be honest I don't think pandoc actually produced anything useful (there's an open issue regarding support for odp files after all) but pegging one CPU to 100% and continuous memory leakage is regressive behaviour compared to 2.14.2.

For further background just to explain how I came across this, rangerfm uses pandoc to produce text-previews of files while browsing. This generally works well, and pandoc is used for document-type files (including odp and ods since they just handle all openoffice formats the same). I could just work around this bug by avoiding the pandoc calls for those filetypes, but the behaviour observed is a bug all the same.

**Comment by jgm** [comment] 2022-03-20 17:08
Pandoc doesn't support those formats (and never did -- in 2.14.2, it would have simply given you an error message saying that the file was not UTF-8 encoded, and exited).

Since then, pandoc has changed so that if a file is not UTF-8 encoded, pandoc tries to interpret it as Latin1.  So then you get a gigantic "markdown" file consisting of random characters, and this can throw the parser in a loop.  (There's another issue open for pathological behavior of the markdown parser on certain inputs; the commonmark reader does better.)

Closing, not a bug.

**Closed by jgm** 2022-03-20 17:08 UTC
Labels: bug

**Comment by ngoonee** [comment] 2022-03-20 23:20
> 

Thanks, I guess this is the tool's behaviour going forward then. Will request rangerfm to modify their script to not use pandoc for the offending filetypes then.
