### ISSUE TITLE
wrong option and preset in Windows installer

### ISSUE THREAD

**Issue by donovaly** [jgm/pandoc#2708] opened 2016-02-10 10:14 UTC
The pandoc Windows installer offers a wrong option and preset:
- If the user who executes the installer has admin permissions, the preset option should be to install for all users of the system (that is the idea of an admin account). Currently the default is to install only for the current user.
- If the user who executes the installer has no admin permissions, the current preset option to install for the current user is correct. But currently the installer offers you also the option to install for all users (when clicking the Advanced button). This will of course fail. So if the user does not have admin permissions the option to install for all users must be disabled

**Comment by jgm** [comment] 2016-02-10 17:46
@nkalvi thoughts on this?

**Comment by nkalvi** [comment] 2016-02-10 18:51
I agree. 

I haven't spent much time to familiarize myself with WiX yet. 
@donovaly If you're familiar with WiX Toolkit, could you take a look at it? 
Otherwise I'll try to improve it sometime next week.

**Comment by donovaly** [comment] 2016-02-11 00:20
> @donovaly If you're familiar with WiX Toolkit

No, I am only familiar with the installer scripting language NSIS( that I use for the installer of the program LyX. As LyX supports now Pandoc as file converter I stumbled over the issue reported here.)

However, if you give me a pointer where too look, I will have a look. It should not be too difficult to fix this since the detection of user permissions is a standard task for installers.

**Comment by jgm** [comment] 2016-02-11 01:07
Does NSIS produce an msi or does it have its own installer
format?

+++ donovaly [Feb 10 16 16:20 ]:

**Comment by nkalvi** [comment] 2016-02-11 01:37
@donovaly http://wixtoolset.org/documentation/ is what I used mostly. You may want to check https://github.com/jgm/pandoc/issues/2205 for some background if you have time.

Yes, it is a standard task for installers - and I think it can be done easily in WiX.
Only situation I haven't figured out is when user installation is not permitted on a server (via policy).

**Comment by donovaly** [comment] 2016-02-12 02:35
Thanks nkalvi, I had a look but Wix is completely different from the scripting system I use.
It was therefore quicker for me to create a new installer using NSIS (https://en.wikipedia.org/wiki/Nullsoft_Scriptable_Install_System)

Here is the installer for Pandoc 1.16.0.2:
http://ftp.lyx.de/Pandoc/

The features are:
- automatic detection of user permissions. If Pandoc is installed for all users the appropriate folder is used to install Pandoc. If it should only be installed for the current user the correct user folder is used
- the installer is translatable. It already comes with English and German strings. The correct language is automatically detected by checking the Windows locale settings.
- pandoc is correctly registered in the registry (meaning not only with a hash key) A hash key has the disadvantage that other programs like e.g. LyX cannot detect Pandoc since the hash key will change with every release of Pandoc) You will now find pandoc e.g. under
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Pandoc11602
- check if the same Pandoc version is already installed, warn if an older Pandoc should be installed while a newer one is already there, etc.

To compile the installer by yourself,
- download the ZIP-file from my site
- install NSIS 2.50
- download the large strings build for NSIS: http://nsis.sourceforge.net/Special_Builds and patch the NSIS files (this is necessary because some users have a HUGE windows PATH variable)
- double click on the file setup.nsi that you extracted from my ZIP
- the uninstaller leaves no traces

I hereby spend the installer to Pandoc, meaning that I grant permission to use it under the GPL v2 or newer and that you can do with the code whatever you want.
I can also offer to maintain the installer if you like.

The installer could have a nice icon and/or banner image but I could not find an official pandoc icon etc. is there any?

**Comment by nkalvi** [comment] 2016-02-12 03:09
@donovaly I did a quick test under Windows 10 Enterprise as admin/user and it looks very nice!

**Comment by donovaly** [comment] 2016-02-12 08:20
Wow that was quick. You were perhaps too quick because I first uploaded the wrong version. Please refer to what you find at my page now.

If you want to use the installer I will split it into 2 source code files The workflow for you would then to
* copy Pandoc's files to the dist folder (you can change the folde and its name of course if you like)
* edit the settings file with a text editor to update the version number of pandoc
* execute the setup.nsi file to build the installer. This can be automated with a script

P.s. The copyright year at the pandoc homepage and in the copyright.txt file is still 2014

**Comment by nkalvi** [comment] 2016-02-12 09:57
@donovaly I tested only the installation part and path settings after installation - and I like it (f.ex. path changes do not require re-login). 
I'll wait for @jgm to create 'signed' versions before testing more. I haven't looked at the installer source.

**Comment by jgm** [comment] 2016-02-16 04:50
We switched to WiX specifically so we could create an msi for the installer.  This was requested by @sheremetyev, if I recall (it was also his idea to use WiX).  @sheremetyev, do you have any comments on the proposal to switch to a nsis installation script, which creates an exe rather than a msi?  IF you think it's desirable to keep creating an msi, do you have ideas about the issues raised above could be fixed within WiX?

**Comment by donovaly** [comment] 2016-02-16 10:22
> We switched to WiX specifically so we could create an msi for the installer.

What do you mean? For the user and the functionality if the installer is a  stand-alone executable or a Windows installer package. There are different competitors on the market. Windows installer is one of them, NSIS is another one. The important thing is that you can easily build in the features you need and that you can easily maintain the installer in case there are bug reports.
NSIS has hereby the advantage that it is OpenSource and that bugs are fixed quickly due to an active community. If WiX suits your needs then of course use it. However, from the reply to my bug report I got the feeling that you don't know how to correct the bug in the existing WiX installer. And therefore I came up with an installer that fixes the problem and that shows some further improvements. It is your decision what to use as long as it fixes the bug.

**Comment by jgm** [comment] 2016-02-16 17:21
I don't use Windows at all myself; I don't know much about Windows, and I'm not an expert with WiX. So I rely on Windows users to guide me in this.  One such user requested that we distribute an msi rather than an exe installer (which we used to have).

If you look at http://stackoverflow.com/questions/1858434/build-nsis-script-as-a-msi-package you'll see some people saying that an msi is needed for certain purposes.  I have no idea why.  For this reason I pinged @sheremetyev, who orginally suggested producing an msi and using WiX.  Perhaps he can also help fix the issue with the current WiX generated installer.

Btw, WiX is also open-source.  I would assume that it is powerful enough to fix this issue, but it will take someone with more knowledge of Windows system administration than me to go through the documentation and figure out how.

**Comment by nkalvi** [comment] 2016-02-16 17:31
@jgm I will try to address this issue in the next couple of days.

**Comment by sheremetyev** [comment] 2016-02-17 22:11
@jgm msi is preferred installation mechanism on Windows. It supports centralised management of software in corporate environment.

**Comment by donovaly** [comment] 2016-02-17 23:40
> msi is preferred installation mechanism on Windows. It supports centralised management of software in corporate environment.

Who said this. I am writing installers for 10 years now and for example contributed the former installer of the program JabRef. It is a matter of taste what you are using. InstallShield and Inno Setup are also a very good solutions:
https://en.wikipedia.org/wiki/List_of_installation_software
I provide a very complex installer for the program LyX since years and did not run into any limitation with NSIS.

However, it is of course up to you to decide what you prefer. For a normal user it is very important that Pandoc is correctly installed depending on the user rights. This is my initial bug report. How this is technically achieved is not relevant for the user. I just made a proposal for a better installer since I am in this business and it only cost me one hour.
For me as packager it is also important to detect Pandoc in the Windows registry which is currently not easy. For you the possibility to translate the installer might be important. I think that also WiX offers this. So if you stay with WiX fix the bugs and if possible translate the installer and I am happy.

**Comment by nkalvi** [comment] 2016-02-20 02:14
@jgm I couldn't find a way to check for 'real' admin user within MSI/WiX - checking the `Privileged` property wasn't helpful (returns 1 for both admin and regular user). We could change the default to "All Users" or we could have two buttons, one for current user and the other for all (instead of the `Advanced` option).

**Comment by jgm** [comment] 2016-02-20 21:10
Having two buttons sounds reasonable to me.  I don't know if
it would address the OP's concern, though.

+++ nkalvi [Feb 19 16 18:14 ]:

**Comment by nkalvi** [comment] 2016-02-22 18:51
@jgm Could you please take a look at https://gist.github.com/nkalvi/f3847fad9fca6f962c66 when you have time? Changes are:

1. Scope selection in the first screen. Since I couldn't detect the user is 'real' admin user, default is still `per user`.
2. Scope is limited to `per machine` on servers. Though not perfect (couldn't detect `DisableMSI` policy), it should handle https://github.com/jgm/pandoc/issues/2389 better.
3. For `per machine`, location can be changed by selecting `Advanced`.
3. Localization: modified templates from WiX toolkit support localization very well. A short sample localization file for en-us is used.
4. Dialog elements are moved to their own files.

![2016-02-22](https://cloud.githubusercontent.com/assets/2199312/13228476/3ede482e-d96a-11e5-93d5-46dead434252.png)

**Comment by jgm** [comment] 2016-06-20 18:15
@nkalvi see https://groups.google.com/d/msgid/pandoc-discuss/9080213c-723b-449a-aa7a-648d623581b8%40googlegroups.com
for an issue a user is having after this change.  Any ideas?

**Comment by nkalvi** [comment] 2016-06-20 18:19
I'll look into it later today.

**Comment by nkalvi** [comment] 2016-06-21 02:55
@jgm 
It was caused by ignoring properties set on command-line while setting defaults for workstations. I think changing these lines in https://github.com/jgm/pandoc/blob/master/windows/pandoc.wxs#L160 to the following will solve it. I'll test it and get back to you in a day or so (don't have access to the tools now).

```xml
    <SetProperty Id="ALLUSERS" Value="{}" Before="FindRelatedProducts" Action="CASetPuaPackage">
      (NOT ALLUSERS = 1) AND MsiNTProductType = 1
    </SetProperty>
    <SetProperty Id="MSIINSTALLPERUSER" Value="1" Before="FindRelatedProducts">
      (NOT ALLUSERS = 1) AND MsiNTProductType = 1
    </SetProperty>
```

**Comment by nkalvi** [comment] 2016-06-22 22:36
@jgm Could you please update `pandoc.wxs` from here: https://gist.github.com/nkalvi/28e4687497212abe1023
and build a new version and ask the user to test it?

I'm rebuilding my Windows build setup with stack and it is taking long time; but I have done some limited testing with MSI with the changes and it seems to work as expected with the command-line.

**Comment by jgm** [comment] 2016-06-23 18:10
The appveyor ci should create an msi automatically -
unfortunately it's currently broken until the latest
texmath propagates to stackage's hackage mirror.

+++ nkalvi [Jun 22 16 15:36 ]:

**Closed** 2016-11-19 22:34 UTC
