### ISSUE TITLE
Images in docx not displayed in Windows

### ISSUE THREAD

**Issue by mickley** [jgm/pandoc#2650] opened 2016-01-13 15:47 UTC
When opening a docx from the docx writer in Windows 7, images aren't displayed.  Instead there is a red x with the text "The picture can't be displayed."

Tested with Windows versions of Word 2007, Word 2010, and Word 2016, and no custom .docx template.  

The same file works fine on OSX Word 2015 and displays the image correctly.

A minimal example: 

```
## Figures

![Here's a caption for our figure.](samplefigure.png)
```

This produces the following XML

```
<w:p>
    <w:pPr>
        <w:pStyle w:val="FigureWithCaption" />
    </w:pPr>
    <w:r>
        <w:drawing>
            <wp:inline>
                <wp:extent cx="5334000" cy="4000500" />
                <wp:effectExtent b="0" l="0" r="0" t="0" />
                <wp:docPr descr="" id="1" name="Picture" />
                <a:graphic>
                    <a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture">
                        <pic:pic>
                            <pic:nvPicPr>
                                <pic:cNvPr descr="samplefigure.png" id="0" name="Picture" />
                                <pic:cNvPicPr>
                                    <a:picLocks noChangeArrowheads="1" noChangeAspect="1" />
                                </pic:cNvPicPr>
                            </pic:nvPicPr>
                            <pic:blipFill>
                                <a:blip r:embed="rId22" />
                                <a:stretch>
                                    <a:fillRect />
                                </a:stretch>
                            </pic:blipFill>
                            <pic:spPr bwMode="auto">
                                <a:xfrm>
                                    <a:off x="0" y="0" />
                                    <a:ext cx="5334000" cy="4000500" />
                                </a:xfrm>
                                <a:prstGeom prst="rect">
                                    <a:avLst />
                                </a:prstGeom>
                                <a:noFill />
                                <a:ln w="9525">
                                    <a:noFill /><a:headEnd />
                                    <a:tailEnd />
                                </a:ln>
                            </pic:spPr>
                        </pic:pic>
                    </a:graphicData>
                </a:graphic>
            </wp:inline>
        </w:drawing>
    </w:r>
</w:p>
<w:p>
    <w:pPr>
        <w:pStyle w:val="ImageCaption" />
    </w:pPr>
    <w:r>
        <w:t xml:space="preserve">
            Here&#39;s a caption for our figure.
        </w:t>
    </w:r>
</w:p>

```

samplefigure.png is a PNG saved by R.  I've also tried with a pdf and the new width and height attributes.

I've also tried adding the same figure into a word document, saving it, and then moving the image in the word/media folder inside the docx to my pandoc-generated docx to replace rID22.png.  No changes.

**Comment by jgm** [comment] 2016-01-13 16:37
I'm afraid I don't have Word for Windows to test with.  Can anyone else reproduce this?

**Comment by sunk818** [comment] 2017-01-25 00:06
I can't reproduce the issue.

Contents of samplefigure.md:
`## Figures
![Here's a caption for our figure.](samplefigure.png)`

samplefigure.png is in the same directory as the md file.

c:\temp> `pandoc -s samplefigure.md -t docx -o samplefigure.docx`

The .docx created embedded the image inside the Word document (.docx).

If I were to take guess, your red x sounds like a localized issue. Are you using Internet Explorer? I'm using Chrome and it was fine. You might try ./samplefigure.png just to be explicit in your path.

![samplefigure](https://cloud.githubusercontent.com/assets/6989799/22272349/67e8fb7c-e24e-11e6-8d09-005557a7966e.png)
[samplefigure.docx](https://github.com/jgm/pandoc/files/728252/samplefigure.docx)

**Comment by jgm** [comment] 2017-08-26 04:22
Closing as "can't reproduce"

**Closed by jgm** 2017-08-26 04:22 UTC
Labels: format:Docx, writer
