### ISSUE TITLE
Recognize zero-width space in .org file as word boundary.

### ISSUE THREAD

**Issue by jiucenglou** [jgm/pandoc#7135] opened 2021-03-10 12:45 UTC
Since org-mode does not allow one to make part of a word bold or italics [without customization](https://stackoverflow.com/a/24540651/531199), one trick is to put in [zero-width space](https://www.fileformat.info/info/unicode/char/200b/index.htm) surrounding the style delimiters, as shown in the following .

    The C​/c/​O is last enzyme in the respiratory electron transport chain of cells located in the membrane.

When pandoc reads in  the .org file containing the above sentence, pandoc recognizes the two zero-width spaces as part of an entire word instead of as word boundaries, thus keeping the forward slashes rather than converting them to underlines. Would you consider to make pandoc recognize zero-width spaces as word boundaries ?

**Comment by tarleb** [comment] 2021-03-10 14:27
Thanks for the report. I believe this is a duplicate of #6070, so closing in favor of that issue.

**Closed by tarleb** 2021-03-10 14:27 UTC
Labels: format:Org-mode, reader
