### ISSUE TITLE
LaTeX template package conflict (grffile XeLaTeX)

### ISSUE THREAD

**Issue by PunkPhysicist** [jgm/pandoc#5890] opened 2019-11-09 01:52 UTC
In the current default.latex template, the legacy package grffile is loaded with graphicx. However, this seems to not work with xelatex (i.e. images will not be loaded).  

My solution was to just not load grffile and everything works fine.

Version: pandoc 2.7.3-64

**Comment by wilx** [comment] 2019-11-09 22:10
I think this is a duplicate of already solved #5848.

**Comment by mb21** [comment] 2019-11-11 10:08
Closing in favour of #5848

**Closed by mb21** 2019-11-11 10:08 UTC
