### ISSUE TITLE
Jira: anchor links inside tables render incorrectly in Pandoc markdown target

### ISSUE THREAD

**Issue by W1M0R** [jgm/pandoc#6404] opened 2020-05-27 14:00 UTC
Given [this Jira markdown](https://pandoc.org/try/?text=%7C%7CParameter%7C%7CUsage%7C%7CDescription%7C%7CDetails%7C%7C%0A%7C%5Busername%7C%23JIRA-123%5D%7CRequired%7CThe+username%7CJIRA-123%7C&from=jira&to=markdown&standalone=0) containing a Jira anchor link inside a table, Pandoc produces the incorrect Pandoc markdown.

Ideally, the Jira anchor link `[username|#JIRA-123]` should result in `[username](#JIRA-123)` Pandoc markdown, and not break the table.

@tarleb Do you agree regarding my observations on this?

**Comment by tarleb** [comment] 2020-06-13 20:38
This is curious: The preview shows this as links, but after creating a ticket, the output actually agrees with pandoc's.

The problem is probably that we can't know which issue names exist, and the produced markup differs if there is an issue with the name of the link target. I'm not happy about it, but I don't think there's anything we can do here.

**Comment by mb21** [comment] 2020-06-14 07:31
guess we could assume the ticket exists?

**Comment by mb21** [comment] 2020-06-14 08:06
ah, on closer reading, this is the same issue as https://github.com/jgm/pandoc/issues/6407 ?

**Comment by tarleb** [comment] 2020-06-14 08:12
Agree. Closing in favor of that issue.

**Closed by tarleb** 2020-06-14 08:12 UTC
Labels: format:Jira, reader
