### ISSUE TITLE
Brackets [ ] are not escaped when converting docx > markdown

### ISSUE THREAD

**Issue by kromkrom** [jgm/pandoc#1953] opened 2015-02-18 12:15 UTC
pandoc 1.13.2 @ Windows 7
Using `pandoc.exe -f docx %1 -t markdown_github -o %1.md --atx-headers` (markdown type and options may vary)
Brackets \[, \] are not escaped, thus text inside brackets is processed as link on GitHub wiki

**Comment by jkr** [comment] 2015-02-18 13:45
Hmm... the other readers (at least latex and html, which I just tested) don't seem to do this either. Brackets in markdown *may* just be brackets, unless followed by other stuff, so it's a bit more of a complicated rule (and in general, it's nice if markdown stays as readable as possible, even at the cost of more complicated parsing).

Anyway, this seems like it's more of a pandoc wide issue. ping @jgm 

If we have the following html:

```
<p>
Hello [foo](www.google.com)
</p>
```
Then roundtripping it through markdown produces different html:

```
echo "<p>Hello [foo](www.google.com) bar</p>" | \
pandoc -f html -t markdown | \
pandoc -f markdown -t html

<p>Hello <a href="www.google.com">foo</a> bar</p>
```
Is that expected (or optimal) behavior?

**Comment by kromkrom** [comment] 2015-02-18 13:57
I missed that: it is not a problem with just a pair of brackets, but with a pair of parenthesis after. I actually have this situation.
While converting from sources which do not use such notation as links it seems rational not to treat `[..] (..)` as links.
As for readability: it enough to escape the first bracket at least in GitHub wiki.

**Comment by jkr** [comment] 2015-02-18 14:42
Right, we don't want to treat them as links. But we might want to escape
them, if writing into markdown, if the markdown reader would then treat
them as links. So, it's not a question for any reader, but rather for the
markdown writer.

So here's a proposal, unless this has already been discussed and
rejected in the past:

 - if bracketed inlines are followed (without a space) by bracketed or
   italicized text, the markdown writer should escape the first pair of
   brackets.

 - We don't worry about implicit links with ommitted second brackets,
   since that would require us to parse the output as markdown before
   outputting it, which seems way too expensive.

**Comment by jgm** [comment] 2015-02-18 16:56
Of course, we could have escaped all `[` characters.  I chose not to do that.  My thought was that it is exceedingly unlikely that something of the form `[foo](bar)` would occur in regular text.  (It might occur in a text discussion Markdown syntax, but then it should be quoted in code backticks.) @kromkrom, can you show us the case where this actually occurred?  Even more unlikely that `[foo][bar]` would occur *along with* something that resolves to a reference link definition for `bar`.  So the benefit of escaping is far outweighed by the cost (the
ugliness of having lots of unnecessary escapes).

We could try to guess which `[` characters need escaping by looking ahead, as @jkr suggests.  But this would not be 100% accurate---shortcut reference links wouldn't be captured.  Not only that, but this would also fail to get cases like

    [hello <em>there</em>](url)

since the escaping routine runs on the content of a single `Str` element, and in this case the opening and closing brackets would be in separate `Str`s.

So, I'm inclined just to leave things as they are, unless I can be convinced that the `[...](...)` is going to come up with non-vanishing frequency in real texts.

+++ Jesse Rosenthal [Feb 18 15 06:42 ]:
>Right, we don't want to treat them as links. But we might want to escape
>them, if writing into markdown, if the markdown reader would then treat
>them as links. So, it's not a question for any reader, but rather for the
>markdown writer.
>
>So here's a proposal, unless this has already been discussed and
>rejected in the past:
>
> - if bracketed inlines are followed (without a space) by bracketed or
>   italicized text, the markdown writer should escape the first pair of
>   brackets.
>
> - We don't worry about implicit links with ommitted second brackets,
>   since that would require us to parse the output as markdown before
>   outputting it, which seems way too expensive.
>
>

**Comment by kromkrom** [comment] 2015-02-18 17:01
@jgm, in my case it was description of some language's phonetics: `[t͡ɕ] ("Russian ч")`. It renders: [t͡ɕ] ("Russian ч").

**Comment by jgm** [comment] 2015-02-18 17:23
I'd say the problem is with github's Markdown parser.  Your text would not be interpreted as a link by pandoc, or by any other Markdown parser I know of except github's and a lesser-known one in PHP:

http://johnmacfarlane.net/babelmark2/?normalize=1&text=%5Bt%CD%A1%C9%95%5D+(%22Russian+%D1%87%22)%0A

I think that [John Gruber's syntax description](http://daringfireball.net/projects/markdown/syntax#link) is clear that the parentheses in a link have to come *immediately* after the brackets (which to me implies no space):  "...use a set of regular parentheses immediately after the link text’s closing square bracket."

+++ Kirill Grushetsky [Feb 18 15 09:01 ]:

**Comment by kromkrom** [comment] 2015-02-18 17:25
Precisely, it is RedCarpet problem (since GFM parser uses it). Sorry for this not-a-bug!

**Closed** 2015-02-18 22:28 UTC
