### ISSUE TITLE
Build on Mac M1 (arm64) fails

### ISSUE THREAD

**Issue by StephanMeijer** [jgm/pandoc#8891] opened 2023-06-05 15:38 UTC
**Explain the problem.**

Building binaries for MacOS on arm64 locally fails because:

```
[56 of 56] Compiling Main
Linking /Users/steve/Projects/pandoc/dist-newstyle/build/aarch64-osx/ghc-9.2.7/pandoc-3.1.2/t/test-pandoc/build/test-pandoc/test-pandoc ...
Undefined symbols for architecture arm64:
  "_iconv", referenced from:
      _hs_iconv in libHSbase-4.16.4.0.a(iconv.o)
     (maybe you meant: _hs_iconv_close, _base_GHCziIOziEncodingziIconv_iconvEncoding15_bytes , _base_GHCziIOziEncodingziIconv_iconvEncoding7_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding3_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding13_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding5_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding1_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding4_info , _base_GHCziIOziEncodingziIconv_iconvEncoding7_info , _base_GHCziIOziEncodingziIconv_iconvEncoding14_bytes , _base_GHCziIOziEncodingziIconv_iconvEncoding9_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding8_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding10_bytes , _base_GHCziIOziEncodingziIconv_iconvEncoding_info , _base_GHCziIOziEncodingziIconv_iconvEncoding9_info , _hs_iconv , _base_GHCziIOziEncodingziIconv_iconvEncoding12_info , _base_GHCziIOziEncodingziIconv_iconvEncoding13_info , _base_GHCziIOziEncodingziIconv_iconvEncoding1_info , _base_GHCziIOziEncodingziIconv_iconvEncoding8_info , _base_GHCziIOziEncodingziIconv_iconvEncoding11_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding2_info , _base_GHCziIOziEncodingziIconv_iconvEncoding11_info , _base_GHCziIOziEncodingziIconv_iconvEncoding16_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding6_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding2_closure , _hs_iconv_open , _base_GHCziIOziEncodingziIconv_iconvEncoding6_info , _base_GHCziIOziEncodingziIconv_iconvEncoding16_info , _base_GHCziIOziEncodingziIconv_iconvEncoding12_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding4_closure )
  "_iconv_close", referenced from:
      _hs_iconv_close in libHSbase-4.16.4.0.a(iconv.o)
     (maybe you meant: _hs_iconv_close)
  "_iconv_open", referenced from:
      _hs_iconv_open in libHSbase-4.16.4.0.a(iconv.o)
     (maybe you meant: _hs_iconv_open)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`gcc' failed in phase `Linker'. (Exit code: 1)
Error: cabal: Failed to build test:test-pandoc from pandoc-3.1.2.
Failed to build exe:pandoc from pandoc-cli-0.1.1.
Failed to build test:test-pandoc-lua-engine from pandoc-lua-engine-0.2.
```

**Reproduction**

```
#!/bin/bash

if [ -z "${PANDOC_DIR+x}" ]; then
    echo "Please provide env PANDOC_DIR" > /dev/stderr
    exit 1
fi

set -eux

echo "RUNNING SCRIPT $0"

env

pwd

cd $PANDOC_DIR

brew update

brew install ghc cabal-install

cabal update

cabal build all -fembed_data_files -fserver -flua --dependencies-only

sh macos/make_macos_release.sh
```

**Pandoc version?**
Latest commit.

**Comment by jgm** [comment] 2023-06-28 00:17
Going to close this because there's no additional information and we can't really do anything with an issue we can't reproduce...

**Closed by jgm** 2023-06-28 00:17 UTC
Labels: bug
