### ISSUE TITLE
Pandoc-3.4 fails to build on MacOS

### ISSUE THREAD

**Issue by mouse07410** [jgm/pandoc#10215] opened 2024-09-25 03:48 UTC
**Explain the problem.**
Cannot build the current stable Pandoc v3.4 - fails in the "C compiler" step:
```text
$ cabal install pandoc-cli --overwrite-policy=always --flag lua53 -w ghc-9.8.2
Resolving dependencies...
Build profile: -w ghc-9.8.2 -O2
In order, the following will be built (use -v for more details):
 - base-compat-0.14.0 (lib) (requires build)
 - commonmark-extensions-0.2.5.5 (lib) (requires build)
 - constraints-0.14.2 (lib) (requires build)
 - crypton-1.0.0 (lib) (requires build)
 - case-insensitive-1.2.1.0 (lib) (requires build)
 - uuid-types-1.0.6 (lib) (requires build)
 - directory-1.3.8.5 (lib:directory) (requires build)
 - data-fix-0.3.4 (lib) (requires build)
 - hslua-objectorientation-2.3.1 (lib) (requires build)
 - hslua-cli-1.4.3 (lib) (requires build)
 - hslua-list-1.1.2 (lib) (requires build)
 - unicode-collation-0.1.3.6 (lib) (requires build)
 - unordered-containers-0.2.20 (lib) (requires build)
 - unix-compat-0.7.2 (lib) (requires build)
 - pem-0.2.4 (lib) (requires build)
 - psqueues-0.2.8.0 (lib) (requires build)
 - ordered-containers-0.2.4 (lib) (requires build)
 - scientific-0.3.8.0 (lib) (requires build)
 - asn1-types-0.3.4 (lib:asn1-types) (requires build)
 - async-2.2.5 (lib) (requires build)
 - these-1.2.1 (lib) (requires build)
 - time-compat-1.9.7 (lib) (requires build)
 - text-short-0.1.6 (lib) (requires build)
 - vector-algorithms-0.9.0.2 (lib) (requires build)
 - http-types-0.12.4 (lib) (requires build)
 - http-media-0.8.1.1 (lib) (requires build)
 - temporary-1.3 (lib) (requires build)
 - easy-file-0.2.5 (lib) (requires build)
 - process-1.6.24.0 (lib:process) (requires build)
 - alex-3.5.1.0 (exe:alex) (requires build)
 - file-embed-0.0.16.0 (lib) (requires build)
 - Glob-0.10.2 (lib) (requires build)
 - hslua-packaging-2.3.1 (lib) (requires build)
 - vault-0.3.1.5 (lib) (requires build)
 - semigroupoids-6.0.1 (lib) (requires build)
 - uniplate-1.6.13 (lib) (requires build)
 - indexed-traversable-instances-0.1.2 (lib) (requires build)
 - attoparsec-0.14.4 (lib) (requires build)
 - asn1-encoding-0.9.6 (lib) (requires build)
 - strict-0.5.1 (lib) (requires build)
 - text-iso8601-0.1.1 (lib) (requires build)
 - mono-traversable-1.0.20.0 (lib) (requires build)
 - typed-process-0.2.12.0 (lib) (requires build)
 - optparse-applicative-0.18.1.0 (lib) (requires build)
 - unliftio-0.2.25.0 (lib) (requires build)
 - hsc2hs-0.68.10 (exe:hsc2hs) (requires build)
 - toml-parser-2.0.1.0 (lib) (requires build)
 - Cabal-syntax-3.12.1.0 (lib) (requires build)
 - hslua-module-version-1.1.1 (lib) (requires build)
 - hslua-module-text-1.1.1 (lib) (requires build)
 - hslua-module-system-1.1.2 (lib) (requires build)
 - hslua-module-path-1.1.1 (lib) (requires build)
 - witherable-0.5 (lib) (requires build)
 - semialign-1.3.1 (lib) (requires build)
 - http-date-0.0.11 (lib) (requires build)
 - cassava-0.5.3.2 (lib) (requires build)
 - asn1-parse-0.9.5 (lib:asn1-parse) (requires build)
 - serialise-0.2.6.1 (lib) (requires build)
 - http-api-data-0.6.1 (lib) (requires build)
 - conduit-1.3.6 (lib) (requires build)
 - time-manager-0.1.0 (lib) (requires build)
 - zlib-0.7.1.0 (lib) (requires build)
 - network-3.2.3.0 (lib:network) (requires build)
 - old-time-1.1.0.4 (lib:old-time) (requires build)
 - Cabal-3.12.1.0 (lib) (requires build)
 - aeson-2.2.3.0 (lib) (requires build)
 - crypton-x509-1.7.7 (lib) (requires build)
 - libyaml-0.1.4 (lib) (requires build)
 - zip-archive-0.4.3.2 (lib) (requires build)
 - JuicyPixels-3.3.9 (lib) (requires build)
 - wai-3.2.4 (lib) (requires build)
 - streaming-commons-0.2.2.6 (lib) (requires build)
 - simple-sendfile-0.2.32 (lib) (requires build)
 - socks-0.6.1 (lib) (requires build)
 - recv-0.1.0 (lib) (requires build)
 - iproute-1.7.14 (lib) (requires build)
 - http-semantics-0.2.1 (lib) (requires build)
 - unix-time-0.4.15 (lib:unix-time) (requires build)
 - cabal-doctest-1.0.10 (lib) (requires build)
 - servant-0.20.2 (lib) (requires build)
 - aeson-pretty-0.8.10 (lib) (requires build)
 - ipynb-0.2 (lib) (requires build)
 - pandoc-types-1.23.1 (lib) (requires build)
 - hslua-aeson-2.3.1.1 (lib) (requires build)
 - doctemplates-0.11.0.1 (lib) (requires build)
 - crypton-x509-store-1.6.9 (lib) (requires build)
 - yaml-0.11.11.2 (lib) (requires build)
 - hslua-module-zip-1.1.3 (lib) (requires build)
 - wai-cors-0.2.7 (lib) (requires build)
 - conduit-extra-1.3.6 (lib) (requires build)
 - http-client-0.7.17 (lib) (requires build)
 - network-control-0.1.3 (lib) (requires build)
 - fast-logger-3.2.3 (lib) (requires build)
 - texmath-0.12.8.10 (lib) (requires build)
 - commonmark-pandoc-0.2.2.1 (lib) (requires build)
 - hslua-2.3.1 (lib) (requires build)
 - crypton-x509-validation-1.6.12 (lib) (requires build)
 - crypton-x509-system-1.6.7 (lib) (requires build)
 - xml-conduit-1.9.1.3 (lib:xml-conduit) (requires build)
 - http2-5.3.4 (lib) (requires build)
 - wai-logger-2.4.1 (lib) (requires build)
 - pandoc-lua-marshal-0.2.8 (lib) (requires build)
 - hslua-module-doclayout-1.1.1.2 (lib) (requires build)
 - tls-2.1.0 (lib) (requires build)
 - typst-0.6 (lib) (requires build)
 - skylighting-core-0.14.3 (lib) (requires build)
 - pandoc-3.4 (lib:xml-light) (requires build)
 - citeproc-0.8.1.1 (lib) (requires build)
 - warp-3.4.1 (lib) (requires build)
 - crypton-connection-0.4.1 (lib) (requires build)
 - skylighting-format-ansi-0.1 (lib) (requires build)
 - skylighting-format-latex-0.1 (lib) (requires build)
 - skylighting-format-context-0.1.0.2 (lib) (requires build)
 - skylighting-format-blaze-html-0.1.1.2 (lib) (requires build)
 - wai-extra-3.1.15 (lib) (requires build)
 - http-client-tls-0.3.6.3 (lib) (requires build)
 - skylighting-0.14.3 (lib) (requires build)
 - wai-app-static-3.1.9 (lib) (requires build)
 - pandoc-3.4 (lib) (requires build)
 - servant-server-0.20.2 (lib) (requires build)
 - pandoc-lua-engine-0.3.2 (lib) (requires build)
 - pandoc-server-0.1.0.8 (lib) (requires build)
 - pandoc-cli-3.4 (exe:pandoc) (requires build)
Starting     constraints-0.14.2 (lib)
Starting     uuid-types-1.0.6 (lib)
Starting     case-insensitive-1.2.1.0 (lib)
Starting     data-fix-0.3.4 (lib)
Starting     hslua-objectorientation-2.3.1 (lib)
Starting     hslua-cli-1.4.3 (lib)
Starting     hslua-list-1.1.2 (lib)
Starting     unix-compat-0.7.2 (lib)
Starting     unordered-containers-0.2.20 (lib)
Starting     ordered-containers-0.2.4 (lib)
Starting     scientific-0.3.8.0 (lib)
Starting     async-2.2.5 (lib)
Starting     pem-0.2.4 (lib)
Starting     asn1-types-0.3.4 (all, legacy fallback: cabal-version is less than 1.8)
Starting     commonmark-extensions-0.2.5.5 (lib)
Starting     psqueues-0.2.8.0 (lib)
Starting     base-compat-0.14.0 (lib)
Starting     directory-1.3.8.5 (all, legacy fallback: build-type is Configure)
Starting     unicode-collation-0.1.3.6 (lib)
Starting     crypton-1.0.0 (lib)
Building     data-fix-0.3.4 (lib)
Building     case-insensitive-1.2.1.0 (lib)
Building     base-compat-0.14.0 (lib)
Building     unix-compat-0.7.2 (lib)
Building     commonmark-extensions-0.2.5.5 (lib)
Building     hslua-objectorientation-2.3.1 (lib)
Building     uuid-types-1.0.6 (lib)
Building     async-2.2.5 (lib)
Building     ordered-containers-0.2.4 (lib)
Building     constraints-0.14.2 (lib)
Building     hslua-cli-1.4.3 (lib)
Building     scientific-0.3.8.0 (lib)
Building     psqueues-0.2.8.0 (lib)
Building     pem-0.2.4 (lib)
Building     unicode-collation-0.1.3.6 (lib)
Building     unordered-containers-0.2.20 (lib)
Building     asn1-types-0.3.4 (all, legacy fallback: cabal-version is less than 1.8)
Building     crypton-1.0.0 (lib)
Building     hslua-list-1.1.2 (lib)
Installing   data-fix-0.3.4 (lib)
Installing   hslua-cli-1.4.3 (lib)
Completed    data-fix-0.3.4 (lib)
Starting     these-1.2.1 (lib)
Completed    hslua-cli-1.4.3 (lib)
Starting     time-compat-1.9.7 (lib)
Starting     text-short-0.1.6 (lib)
Installing   case-insensitive-1.2.1.0 (lib)
Installing   async-2.2.5 (lib)
Completed    case-insensitive-1.2.1.0 (lib)
Building     these-1.2.1 (lib)
Completed    async-2.2.5 (lib)
Installing   uuid-types-1.0.6 (lib)
Installing   pem-0.2.4 (lib)
Completed    uuid-types-1.0.6 (lib)
Installing   hslua-objectorientation-2.3.1 (lib)
Building     time-compat-1.9.7 (lib)
Completed    pem-0.2.4 (lib)
Building     text-short-0.1.6 (lib)
Completed    hslua-objectorientation-2.3.1 (lib)
Installing   asn1-types-0.3.4 (all, legacy fallback: cabal-version is less than 1.8)
Completed    asn1-types-0.3.4 (all, legacy fallback: cabal-version is less than 1.8)
Installing   ordered-containers-0.2.4 (lib)
Installing   these-1.2.1 (lib)
Installing   unix-compat-0.7.2 (lib)
Installing   scientific-0.3.8.0 (lib)
Completed    ordered-containers-0.2.4 (lib)
Installing   constraints-0.14.2 (lib)
Building     directory-1.3.8.5 (all, legacy fallback: build-type is Configure)
Completed    these-1.2.1 (lib)
Completed    unix-compat-0.7.2 (lib)
Completed    scientific-0.3.8.0 (lib)
Installing   text-short-0.1.6 (lib)
Completed    constraints-0.14.2 (lib)
Completed    text-short-0.1.6 (lib)
Installing   psqueues-0.2.8.0 (lib)
Completed    psqueues-0.2.8.0 (lib)
Installing   time-compat-1.9.7 (lib)
Completed    time-compat-1.9.7 (lib)
Installing   directory-1.3.8.5 (all, legacy fallback: build-type is Configure)
Completed    directory-1.3.8.5 (all, legacy fallback: build-type is Configure)
Installing   unordered-containers-0.2.20 (lib)
Completed    unordered-containers-0.2.20 (lib)
Installing   unicode-collation-0.1.3.6 (lib)
Completed    unicode-collation-0.1.3.6 (lib)
Installing   commonmark-extensions-0.2.5.5 (lib)
Completed    commonmark-extensions-0.2.5.5 (lib)
Installing   base-compat-0.14.0 (lib)
Completed    base-compat-0.14.0 (lib)
Installing   crypton-1.0.0 (lib)
Completed    crypton-1.0.0 (lib)

Failed to build hslua-list-1.1.2.
Build log ( /Users/ur20980/.cabal/logs/ghc-9.8.2/hsl-lst-1.1.2-ca5285f7.log ):
Configuring library for hslua-list-1.1.2...
Preprocessing library for hslua-list-1.1.2...
Building library for hslua-list-1.1.2...
[1 of 1] Compiling HsLua.List

cbits/listmod.c:58:5: error:
     error: call to undeclared function 'lua_toclose'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
       58 |     lua_toclose(L, 3);
          |     ^
   |
58 |     lua_toclose(L, 3);
   |     ^

cbits/listmod.c:58:5: error:  note: did you mean 'lua_close'?
   |
58 |     lua_toclose(L, 3);
   |     ^

/opt/local/include/lua.h:145:21: error:
     note: 'lua_close' declared here
      145 | LUA_API void       (lua_close) (lua_State *L);
          |                     ^
    |
145 | LUA_API void       (lua_close) (lua_State *L);
    |                     ^

cbits/listmod.c:372:63: error:
     warning: expression result unused [-Wunused-value]
      372 |   for (const char **name = tablelib_functions; *name != NULL; *name++) {
          |                                                               ^~~~~~~
    |
372 |   for (const char **name = tablelib_functions; *name != NULL; *name++) {
    |                                                               ^
1 warning and 1 error generated.
`clang' failed in phase `C Compiler'. (Exit code: 1)
Error: [Cabal-7125]
Failed to build hslua-list-1.1.2 (which is required by exe:pandoc from pandoc-cli-3.4). See the build log above for details.
```

This happens with `--flag lua53` and without it, with GHC-9.10.1 and 9.8.2.
Pandoc v3.3 built fine with lua54 using GHC-9.8.2.

**Pandoc version?**
- Pandoc-3.4
- MacOS SOnoma 14.7
- Xcode-16.0
- GHC-9.10.1 and 9.8.2 (which succeeded to build pandoc-cli v3.3)

**Comment by jgm** [comment] 2024-09-25 04:10
Did the problem start with the Sonoma 14.7 / XCode 16 upgrade?  I am running 14.6 and it builds fine.

Can you *now* build pandoc-cli v3.3 or did this just work before (perhaps before the upgrade)?

**Comment by jgm** [comment] 2024-09-25 04:19
I think I see the problem.
@tarleb - looks like hslua-list in the last release started using `lua_toclose`, which is only in Lua 5.4!
commit a309427d3e6a5729a02e0c249ba605fc0281561d

This will mean that pandoc can only be compiled against Lua 5.4, which I don't think you intended.

**Comment by jgm** [comment] 2024-09-25 04:21
Workaround for this issue: use the following cabal flag:
```
--constrain 'hslua-list < 1.1.2'
```

**Comment by jgm** [comment] 2024-09-25 04:34
Note:  I don't think there is (currently) a `lua3` flag.

**Comment by tarleb** [comment] 2024-09-25 05:11
Previously this would have failed during linking, because the Haskell code already used some 5.4-only functions. This is the first case where we use such a function in C.
Medium- to long-term I'd like to go back to supporting older Lua versions and LuaJIT, but that'll be a good bit of work. For now I don't think it's a bug.

**Comment by jgm** [comment] 2024-09-25 05:48
So, does this mean that in order to build pandoc one needs to have lua 5.4 installed on one's system?  I thought we embedded the lua code directly in the hslua package (or one of its dependencies).

**Comment by tarleb** [comment] 2024-09-25 07:33
Right, we still bundle Lua 5.4 while offering the option to use the system's Lua installation *if* the system-wide install is Lua 5.4.

I noticed that the above build log doesn't mention building the `lua` package. That makes me think that the reason for the build failure might be a too permissive lower bound on `lua`. I'll check.

**Comment by tarleb** [comment] 2024-09-25 07:41
I've opened hslua/hslua#152 to track this.

**Comment by tarleb** [comment] 2024-09-25 07:46
Actually, `hslua-list` already depends on `hslua-core >= 2.2`, which means it *does* require Lua 5.4. So I'm a bit at a loss as to what exactly is happening here.

**Comment by tarleb** [comment] 2024-09-25 12:13
Interesting. So the generated pandoc is running Lua 5.4, but the compiler doesn't know about the Lua 5.4 functions.  What does `pkg-config --cflags lua` return?

**Comment by tarleb** [comment] 2024-09-25 12:21
And one more info please: could you run `cabal freeze --constraint='hslua-list <1.1.2'` and post the output here?

**Comment by tarleb** [comment] 2024-09-26 10:56
I tried with a fresh install of MacOS Sonoma 14.7 and GHC 9.8.2 but couldn't reproduce the issue. Pandoc-cli was built sucessfully using the given command.

Cabal works quite differently on MacOS than on Linux, which I had forgotten about. On my try, the interesting files where in `~/.local/state/cabal/store/ghc-9.8.2/l-2.3.3-*/cabal-hash.txt`. I'm not sure this might all interact with cabal flags and dylibs, but I imagine that this could play a role in the compilation failure.

I'm closing this issue for now, because it doesn't seem to be a pandoc issue. However, it would be nice to get to the bottom of this, knowing about this kind of quirks might help in the future.

I'll also leave the hslua issue open. It doesn't seem like an hslua-list bug, but if we can fix it there, then all the better.

**Closed by tarleb** 2024-09-26 10:56 UTC
Labels: bug
