### ISSUE TITLE
beamer template prevents included graphics from being scaled up, resulting in unexpected figure size in pdf file

### ISSUE THREAD

**Issue by bozito** [jgm/pandoc#4935] opened 2018-09-26 13:03 UTC
Tested with  pandoc 1.19.2.1 .
The beamer template introduces the following line in the tex file:
`\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}`
that prevents any included graphic from being scaled up (ie included graphic in the pdf is physically larger than the original image). Nowhere in the man pandoc such limitation is explained and the explanations differ from the actual result.

I attach everything you need to reproduce this bug:

- test.md.txt (.txt as .md is not a supported format for attachments) : to be compile using `pandoc -s test.md.txt -t beamer -o test.pdf`
- test.pdf : the beamer pdf I obtain with incorrectly scaled images.
- test_expected_beamer.pdf : the expected result (included graphics with the same width actually have the same width). It is obtained by commenting out `\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}` or by typing directly a beamer tex fils by hand.
- cheese.jpg, cheese_x0.5.jpg and cheese_x2.jpg : the images necessary to compile test.md.txt . These are identical images but with different physical sizes: 100x67, 200x133 and 400x266

[test.md.txt](https://github.com/jgm/pandoc/files/2419733/test.md.txt)
[test.pdf](https://github.com/jgm/pandoc/files/2419735/test.pdf)
[test_expected_beamer.pdf](https://github.com/jgm/pandoc/files/2419736/test_expected_beamer.pdf)
![cheese](https://user-images.githubusercontent.com/8871892/46081379-a7dae680-c19c-11e8-9ad8-7100f1f5741e.jpg)
![cheese_x0 5](https://user-images.githubusercontent.com/8871892/46081386-ac9f9a80-c19c-11e8-8333-226d830b6d89.jpg)
![cheese_x2](https://user-images.githubusercontent.com/8871892/46081393-b0332180-c19c-11e8-9226-1e33a7c7dd23.jpg)

**Comment by mb21** [comment] 2018-09-26 14:06
Can you try with the newest pandoc release?

**Comment by bozito** [comment] 2018-09-26 14:49
Nope, I can't at the moment for several reasons:

1. I need to stick to 1.19.2.1 as there is a regression bug with more recent versions of pandoc that breaks my workflow (did not have time to report it for the moment).
2. I did not manage to get different versions of pandoc running simultaneously on my computer using cabal. Somehow, cabal cannot resolve dependencies on my computer (ie the method described here https://pandoc.org/installing.html#quick-cabal-method does not work for me).

So I have to set up a virtual machine and install everything on it to do the test with the last pandoc.
I can't at the moment.

**Comment by jgm** [comment] 2018-09-26 16:50
bozito <notifications@github.com> writes:

> No, I need cabal to get two different version on my computer without 
> conflicts (on Linux Ubuntu 16.04).
> See here: https://groups.google.com/forum/#!topic/pandoc-discuss/krcyPFtNHEs

I don't see why. We provide a statically linked linux
binary in a tarball. Unpack the tarball wherever you
like, and, if you want, rename the binary. It won't
conflict with anything else you have installed.

There have been many changes to pandoc since 1.19.x,
so please check your issue with the latest version,
or we can't help you.

If there is a regression in later versions that
prevents you from using them, we'd definitely like
to know about that, too (though perhaps it too is
fixed in the latest release?).

**Comment by mb21** [comment] 2018-09-26 17:30
I just tested with pandoc 2.3 and the result is as expected: see [test3.pdf](https://github.com/jgm/pandoc/files/2420881/test3.pdf)

Thus closing this.

**Closed by mb21** 2018-09-26 17:30 UTC

**Comment by bozito** [comment] 2018-09-26 17:50
Le 26/09/2018 à 18:51, John MacFarlane a écrit :
> bozito <notifications@github.com> writes:
>
>> No, I need cabal to get two different version on my computer without
>> conflicts (on Linux Ubuntu 16.04).
>> See here: https://groups.google.com/forum/#!topic/pandoc-discuss/krcyPFtNHEs
> I don't see why. We provide a statically linked linux
> binary in a tarball. Unpack the tarball wherever you
> like, and, if you want, rename the binary. It won't
> conflict with anything else you have installed.
Argh, I didn't know that.
I just tried and with pandoc 2.3 : it works as expected.
>
> There have been many changes to pandoc since 1.19.x,
> so please check your issue with the latest version,
> or we can't help you.
Done, fixed.
>
> If there is a regression in later versions that
> prevents you from using them, we'd definitely like
> to know about that, too (though perhaps it too is
> fixed in the latest release?).
I'll go find this my notes about this regression and see whether it's 
fixed with version 2.3.
It it is not, I'll open another issue.
>
>
>
>
