### ISSUE TITLE
Improvement on pdflatex absence notification

### ISSUE THREAD

**Issue by Xia0ben** [jgm/pandoc#3666] opened 2017-05-12 15:13 UTC
Hello there !

Just a little suggestion : when installing pandoc on a system that doesn't already have pdflatex installed, and then trying to do a little markdown to pdf conversion (ex : "pandoc myfile.md -o myfile.pdf"), you get the following message : "pandoc: pdflatex not found. pdflatex is needed for pdf output."

Maybe it would be better to add something like : "pdflatex is part of the texlive-latex-base package : for ubuntu users (for example), please install it with "sudo apt-get install texlive-latex-base" ". Since pdflatex is not a package, some might try (I did :D) to do a quick "sudo apt-get install pdflatex", only to realize their mistake. Another approach would be to include pdflatex in the depencies, no ?

Thank you very much for your attention ;-).

Pandoc version : pandoc 1.16.0.2
Ubuntu version : Ubuntu 16.04 LTS

**Comment by Xia0ben** [comment] 2017-05-12 15:21
Quick edit : ran into another "problem of the same kind" :

Right after that, I got the "! Font T1/cmr/m/n/10=ecrm1000 at 10.0pt not loadable: Metric (TFM) file not found." message : looked up the message on google and directly found the related Github issue and the fix ("sudo apt-get install texlive-fonts-recommended") : adding it in the error message would improve user experience in the same way I believe ;-).

**Comment by mb21** [comment] 2017-05-13 16:57
Including instructions for how to install (and configure) LaTeX, XeLaTeX, wkhtmltopdf etc. for every supported OS is probably out of scope for pandoc.

btw, if you run into issues in the future, try the latest pandoc release (the ones in apt-get tend to be quite old)...

**Closed by mb21** 2017-05-13 16:57 UTC

**Comment by jgm** [comment] 2017-05-15 14:54
I agree that this is out of scope.

Note that we have something about installing latex already
in the install instructions for OSX and Windows:
http://pandoc.org/installing.html

We don't for linux; the problem is that there are so many
distributions and the instructions would be different for
each.

If you want to suggest that the official debian package
include texlive-fonts-recommended in its recommended
(or better: suggested) packages, then you might submit a bug
report to Debian's tracker.  Currently some texlive packages
are in suggested, but not that one.
https://packages.qa.debian.org/p/pandoc.html

We don't have any 'suggests' or 'recommends' in the minimal deb
we distribute in the releases page.  It might be worth
adding these as suggests.

+++ Xia0ben [May 12 17 08:21 ]:

**Comment by jgm** [comment] 2017-05-15 14:57
PS.  debian suggests texlive-latex-recommended rather than
texlive-latex-base.  For xelatex you also need
texlive-xetex.

**Comment by Xia0ben** [comment] 2017-05-17 14:03
Thank you very much for your answers, it's true that adding the instructions for every os would be unconsiderate, I didn't think about it on the moment, silly me (ノ*°▽°*).
@jgm : your suggestion about the debian package would solve this indeed : I'll look into it this week-end if I have some free time !
