### ISSUE TITLE
fb2 produced by pandoc doesn't validate

### ISSUE THREAD

**Issue by vbwagner** [jgm/pandoc#2424] opened 2015-09-28 13:01 UTC
PAndoc 1.12.4.2 produces incorrect FB2 metainfomramation.

Consider following example

```
  ---
  author: Victor Wagner
  title: The example fb2
  language: en
  abstract: The example FB2
  ---
  Chapter One
  ==========
   This is a text of  the chapter 0ne
```

I expect that command

```
  pandoc -o example.fb2 example.mkd 
```

Would produce file which would pass validation using

```
  xmllint --schema FictionBook2.1xml example.fb2
```

Unfortunately, I recieve lots of errors.

example.fb2:2: element book-title: Schemas validity error : Element '{http://www.gribuser.ru/xml/fictionbook/2.0}book-title': This element is not expected. Expected is ( {http://www.gribuser.ru/xml/fictionbook/2.0}genre ).
example.fb2:2: element program-used: Schemas validity error : Element '{http://www.gribuser.ru/xml/fictionbook/2.0}program-used': This element is not expected. Expected is ( {http://www.gribuser.ru/xml/fictionbook/2.0}author ).
example.fb2:2: element annotation: Schemas validity error : Element '{http://www.gribuser.ru/xml/fictionbook/2.0}annotation': This element is not expected. Expected is one of ( {http://www.gribuser.ru/xml/fictionbook/2.0}epigraph, {http://www.gribuser.ru/xml/fictionbook/2.0}section ).

I.e. 
1. No genre specified. FB2 requires at least one genre.
2. author should go before book-title, not vice versa
3. Document creation date is required in the document-info
4. id is required
5. annotation tag should go into the title-info and contain an abstract, not into first page in the body.

**Comment by jgm** [comment] 2015-10-04 00:25
Pinging @astanin who wrote the FB2 writer

**Comment by astanin** [comment] 2015-10-04 09:07
I'll look into this.

@vbwagner What is this FictionBook2.1xml schema file that you use? Is it the same as [FictionBook2.xsd](http://gribuser.ru/xml/fictionbook/2.0/xsd/FictionBook2.xsd)?

**Comment by vbwagner** [comment] 2015-10-05 11:45
FictionBook 2.1 is updated version, which includes support for tables, and 'code' (preformatted fixed witdth text). Sometime ago I'v complained that pandoc formats something as 'code' element, which doesn't present in the FictionBook 2 element. and was advised by LiveJournal user sastanin 
(weren't it you?) to switch to 2.1 version. 

See: http://vitus-wagner.livejournal.com/905518.html?thread=29317422#t29317422

This schema can be found in fictionbook wiki:
http://www.fictionbook.org/index.php/Eng:XML_Schema_Fictionbook_2.1

However. on my test example, which doesn't contain tables or code blocks, validation against FictionBook2.0 scheme gives same errors as against FictionBook 2.1

Problems really are:

1. pandoc doesn't put all known metainformation into fb2 file. Especially annoying is omission of <lang> element in the document-info, because TTS plugin for FBReader uses it to choose language to read book aloud.

2. Order of <book-title> and <author> in the <title-info> is wrong.

3. use of tag <annotation> inside <body> is wrong. Annotation should go into title-info (and be filled from 'abstract' variable of  YAML metainfo block.

4. <genre> is mandatory in the both FictionBook schemas. I suggest use 'tags' variable on YAML to fill it and use some generic one as default.

It would be really nice to some fb-backend specific command-line arguments simular to --epub-metadata and --epub-cover-image to set metadata which cannot be represented inside markdown file.

**Comment by jgm** [comment] 2015-10-05 17:12
+++ Victor Wagner [Oct 05 15 04:45 ]:
>   It would be really nice to some fb-backend specific command-line
>   arguments simular to --epub-metadata and --epub-cover-image to set
>   metadata which cannot be represented inside markdown file.

You don't really need command-line options for this.
Arbitrary metadata can now be represented in pandoc markdown YAML
metadata blocks.

**Comment by vbwagner** [comment] 2015-10-05 18:26
> Arbitrary metadata can now be represented in pandoc markdown YAML metadata blocks.

There is some problems with this approach

1.  If we want to generate several formats from the same source, we need different sets of metadata.
For instance, I'm generating epub and fb2 from my texts. And some metainformation which is representable in epub is not supported in fb2 and vice versa. 

So, we end up substituting own set of metadata for each format anyway. Currently --epub-metadata switch allows to specify metadata, common for all formats, such as title and author, in the markdown file itself, and add Doublin-Core specific items  for epub only.

2. If we are using format-specific file to add extra metadata, backend need not to be aware of every possible metadata item. It can just parse everything it finds in metadata file as well-formed XML and add those items which are defined in the markdown.

**Comment by jgm** [comment] 2015-10-05 19:05
+++ Victor Wagner [Oct 05 15 11:26 ]:
>     Arbitrary metadata can now be represented in pandoc markdown YAML
>     metadata blocks.
>
>   There is some problems with this approach
>    1. If we want to generate several formats from the same source, we
>       need different sets of metadata. For instance, I'm generating epub
>       and fb2 from my texts. And some metainformation which is
>       representable in epub is not supported in fb2 and vice versa.

You can add metadata using the --metadata command line flag.
Besides, what does it hurt if the document contains some
metadata that is not relevant in all formats?  Normally
it will just be ignored in the other formats.

**Comment by jgm** [comment] 2015-11-20 04:43
@astanin what do you think? Can you fix the issues 1-4 identified above, or do you disagree about the diagnosis?

**Comment by labdsf** [comment] 2017-11-01 10:13
Partially fixed it by removing `<annotation>` from `<body>`, which was not annotation at all. Authors and date is placed into `<description>` anyway.

**Comment by labdsf** [comment] 2017-11-01 10:32
Also added "unrecognised" genre.

**Comment by murrrf** [comment] 2018-06-12 11:20
Some problems still require manual editing of the file after conversion.

1. The title and abstract should go after the authors, not before them.
2. The last paragraph of the annotation (unique in the absence of others) is not framed by <p> </ p> tags.
3. The genre is "unrecognised" in the output file, even if the correct genre of the book is specified in the metadata.

**Comment by labdsf** [comment] 2018-06-12 11:54
@murrrf 
> The title and abstract should go after the authors, not before them.
Fixed

> The last paragraph of the annotation (unique in the absence of others) is not framed by </ p> tags.

Cannot reproduce, result of `pandoc test/fb2/reader/meta.fb2 -t fb2 -s` looks good. Can you provide an example? My guess is that you have Plain instead of Para in the source or something like that, but not sure.

> The genre is "unrecognised" in the output file, even if the correct genre of the book is specified in the metadata.

There is currently no way to specify genre in metadata. Unrecognised is a quick fix to make the output valid. Maybe file it as a separate issue?

**Comment by murrrf** [comment] 2018-06-12 12:05
I used the following sequence of actions:
1. wget https://raw.githubusercontent.com/jgm/pandoc/master/test/fb2/meta.markdown
2. pandoc -f markdown -t fb2 meta.markdown | xmllint --format -
And got the following result:
```
<?xml version="1.0" encoding="UTF-8"?>
<FictionBook xmlns="http://www.gribuser.ru/xml/fictionbook/2.0" xmlns:l="http://www.w3.org/1999/xlink">
  <description>
    <title-info>
      <genre>unrecognised</genre>
      <book-title>Book title</book-title>
      <annotation><p>This is the abstract.</p>It consists of two paragraphs.</annotation>
    </title-info>
    <document-info>
      <program-used>pandoc</program-used>
    </document-info>
  </description>
  <body>
    <title>
      <p>Book title</p>
    </title>
  </body>
</FictionBook>
```

**Comment by labdsf** [comment] 2018-06-12 12:10
It is Plain, indeed:
```
$ pandoc test/fb2/meta.markdown -t native -s
Pandoc (Meta {unMeta = fromList [("abstract",MetaBlocks [Para [Str "This",Space,Str "is",Space,Str "the",Space,Str "abstract."],Plain [Str "It",Space,Str "consists",Space,Str "of",Space,Str "two",Space,Str "paragraphs."]]),("title",MetaInlines [Str "Book",Space,Str "title"])]})
[]
```

**Comment by murrrf** [comment] 2018-06-12 12:15
However, how to achieve the desired result?

**Comment by labdsf** [comment] 2018-06-12 12:19
I will fix it to convert all Plain to Para in abstract, but the fact that it is read this way by Markdown reader, probably because newline is missing at the end of the abstract, seems like a bug in Markdown reader. The FB2 writer should be made more robust too, though.

**Comment by murrrf** [comment] 2018-06-12 12:21
Thank you.

**Comment by tarleb** [comment] 2021-05-14 19:04
@astanin, @link2xt could you have another look and see if we can fix the remaining issues somehow?

**Comment by jgm** [comment] 2021-05-14 19:28
meta.markdown now converts properly with two Paras in the abstract; maybe something got fixed in the markdown reader since this issue was submitted.

genre is taken from `genre` in metadata, defaulting to `unrecognised`.

That's all the issues as far as I can see, so let's close this.

**Closed by jgm** 2021-05-14 19:28 UTC
Labels: format:FB2, writer
