### ISSUE TITLE
markdown code block style chage

### ISSUE THREAD

**Issue by starsareintherose** [jgm/pandoc#7754] opened 2021-12-16 21:08 UTC
**Describe your proposed improvement and the problem it solves.**
I try to use this, but not work, style not changed
```
pandoc -f markdown -t markdown -o string.h.md.out string.h.md
```

the following is a code block, how can I convert it to ``` style

    #include <stdio.h>
    #include <string.h>
    #include <stdlib.h>
    int main (int argc, char const *argc[]){
        char s[] = "hello";
        char *p = strchr (s, 'l');
        char c =*p;
        *p ='\d';
        char *t = (char*)malloc(strlen(p)+1);
        strcpy(t,p);
        printf("%s\n",t);
        free(t);
       
        return 0;
    }

the plain text is here 
```

    #include <stdio.h>
    #include <string.h>
    #include <stdlib.h>
    int main (int argc, char const *argc[]){
        char s[] = "hello";
        char *p = strchr (s, 'l');
        char c =*p;
        *p ='\d';
        char *t = (char*)malloc(strlen(p)+1);
        strcpy(t,p);
        printf("%s\n",t);
        free(t);
       
        return 0;
    }

```
**Describe alternatives you've considered.**

**Comment by jgm** [comment] 2021-12-16 21:10
Duplicate of #5280

**Closed by jgm** 2021-12-16 21:10 UTC
Labels: enhancement
