### ISSUE TITLE
strange error when calling hierarchicalize on linux

### ISSUE THREAD

**Issue by simonmichael** [jgm/pandoc#4679] opened 2018-05-31 14:09 UTC
We are chasing a strange error with the lua hierarchicalize function on https://github.com/simonmichael/hledger/pull/781. Here's the example from https://pandoc.org/lua-filters.html#module-pandoc.utils:
```
local blocks = {
  pandoc.Header(2, pandoc.Str 'first'),
  pandoc.Header(2, pandoc.Str 'second'),
}
local elements = pandoc.utils.hierarchicalize(blocks)
print(table.concat(elements[1].numbering, '.')) -- 0.1
print(table.concat(elements[2].numbering, '.')) -- 0.2
```
With pandoc 2.2.1 on my mac (installed with homebrew) it works:
```
$ echo | pandoc-2.2.1 --lua-filter a.lua
0.1
0.2

```
With pandoc 2.2.1 on my ubuntu machine (installed with stack) it gives this four-fold error:
```
$ echo | pandoc-2.2.1 --lua-filter a.lua
Error running filter a.lua:
Error during function call: could not read argument 1: Could not read list: Could not get Block value: expected table but got nil.
```
I am baffled. Could anyone explain what's going on here ?

**Comment by simonmichael** [comment] 2018-05-31 14:29
On my failing machine, I believe pandoc is built with hslua-0.9.5.1 as that's the only version installed.

**Comment by mb21** [comment] 2018-05-31 15:08
Works on my mac with pandoc 2.2.1 built with stack from source.

**Comment by ehildenb** [comment] 2018-05-31 16:05
On an ubuntu machine, also not getting problems:

```
[hildenb2@ci-fsl scratch]% ~/.local/bin/pandoc --version
pandoc 2.1.2
Compiled with pandoc-types 1.17.3.1, texmath 0.10.1.2, skylighting 0.6
Default user data directory: /home/hildenb2/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

[hildenb2@ci-fsl scratch]% uname -a
Linux ci-fsl 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

[hildenb2@ci-fsl scratch]% echo | ~/.local/bin/pandoc --lua-filter a.lua              
0.1
0.2
```

**Comment by jgm** [comment] 2018-05-31 16:46
This works fine for me on my debian stretch system.
@tarleb can you reproduce this?

**Comment by simonmichael** [comment] 2018-05-31 17:08
A shorter example:
```
print(pandoc.utils.hierarchicalize( {pandoc.Header(1, pandoc.Str 'first')} ))
```

**Comment by ehildenb** [comment] 2018-05-31 17:22
@simonmichael output of `uname -a`?

**Comment by simonmichael** [comment] 2018-05-31 18:14
$ uname -a
Linux joyful.com 4.15.12-x86_64-linode105 #1 SMP Thu Mar 22 02:13:40 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tarleb** [comment] 2018-05-31 20:07
That's most curious. It worked for me, and I have no clear explanation for what might be going wrong. @simonmichael, could there be a Lua file somewhere that overwrites the default `pandoc.Str` function? What happens if you wrap `pandoc.Str 'first'` in curly braces, does that help somehow?

**Comment by simonmichael** [comment] 2018-05-31 20:27
Not that I know of; no. Everything else about pandoc and even lua filters is working normally.

**Comment by tarleb** [comment] 2018-05-31 20:45
I'm at a total loss, sorry. All I know is that hslua error messages need improving. Badly.

We have a [test for hierarchicalize](https://github.com/jgm/pandoc/blob/master/test/lua/test-pandoc-utils.lua#L5), and run it on Ubuntu Travis via Travis CI. I'll let it sink in over night, that might help.

**Comment by simonmichael** [comment] 2018-05-31 20:51
Trace statements in Text.Pandoc.Lua.Util.typeCheck show:
```
Error during function call: could not read argument 1: Could not read list: Could not get Block value: expected table but got nil.
idx: StackIndex {fromStackIndex = -1}
actual: TypeNil
expected: TypeTable
```

**Comment by simonmichael** [comment] 2018-05-31 21:04
And that's being called by Text.Pandoc.Lua.StackInstances.peekBlock. I guess it's looking for a block on the lua stack but the stack is empty.

**Comment by mb21** [comment] 2018-06-01 07:34
but why: `expected: TypeTable` ?

I guess you could try `stack clean` and rebuild again, since until now this could be reproduced on only exactly one machine...

**Comment by tarleb** [comment] 2018-06-02 09:20
> but why: `expected: TypeTable` ?

Lua has only one way to structure data, namely tables. So when pandoc is trying to retrieve a Block from Lua, it's looking for a table.  It's a mystery to me why it doesn't find one in this case.

@simonmichael, could you try a few things to help us narrow down the problem?  I'd be interested to learn whether any of the below commads errors:

``` lua
pandoc.utils.hierarchicalize {}
pandoc.utils.hierarchicalize { pandoc.Para {} }
pandoc.utils.hierarchicalize { pandoc.Para { pandoc.Str "" } }
print(pandoc.utils.stringify(pandoc.Header(1, "Testing")))
```

Also, does the following work for you?

``` sh
pandoc --lua-filter <(echo 'function Header(h) return pandoc.Header(1, "Works") end') <<< '# foo'
```

**Comment by simonmichael** [comment] 2018-06-02 15:14
Here's a stack trace:
```
FromLuaStack Block 1
idx: StackIndex {fromStackIndex = -1}
CallStack (from -prof):
  Text.Pandoc.Lua.Util.typeCheck (src/Text/Pandoc/Lua/Util.hs:(109,1)-(114,79))
  Text.Pandoc.Lua.StackInstances.peekBlock (src/Text/Pandoc/Lua/StackInstances.hs:(226,1)-(253,36))
  Text.Pandoc.Lua.StackInstances.peek (src/Text/Pandoc/Lua/StackInstances.hs:91:3-18)
  Foreign.Lua.Types.FromLuaStack.toList.go (src/Foreign/Lua/Types/FromLuaStack.hs:(141,3)-(144,20))
  Foreign.Lua.Types.FromLuaStack.toList (src/Foreign/Lua/Types/FromLuaStack.hs:(138,1)-(144,20))
  Foreign.Lua.Types.FromLuaStack.peek (src/Foreign/Lua/Types/FromLuaStack.hs:131:3-43)
  Foreign.Lua.FunctionCalling.toHsFun.getArg (src/Foreign/Lua/FunctionCalling.hs:(95,7)-(97,71))
  Foreign.Lua.FunctionCalling.toHsFun (src/Foreign/Lua/FunctionCalling.hs:(93,3)-(97,71))
  Foreign.Lua.FunctionCalling.toHaskellFunction (src/Foreign/Lua/FunctionCalling.hs:(109,1)-(111,25))
  Foreign.Lua.FunctionCalling.pushHaskellFunction (src/Foreign/Lua/FunctionCalling.hs:157:1-76)
  Text.Pandoc.Lua.Util.addFunction (src/Text/Pandoc/Lua/Util.hs:(86,1)-(90,17))
  Text.Pandoc.Lua.Module.Utils.pushModule (src/Text/Pandoc/Lua/Module/Utils.hs:(50,1)-(58,10))
  Text.Pandoc.Lua.Module.Utils.CAF:lvl13_r9t2A (<no location info>)
actual: TypeNil
expected: TypeTable
Error running filter /home/simon/src/hledger.org/b.lua:
Error during function call: could not read argument 1: Could not read list: Could not get Block value: expected table but got nil.
```

@tarleb, only the first and last work:
```
$ pandoc --lua-filter <(echo 'pandoc.utils.hierarchicalize {}') <<< '# foo'
<h1 id="foo">foo</h1>

$ pandoc --lua-filter <(echo 'pandoc.utils.hierarchicalize { pandoc.Para {} }') <<< '# foo'
Error running filter /dev/fd/63:
Error during function call: could not read argument 1: Could not read list: Could not get Block value: expected table but got nil.

$ pandoc --lua-filter <(echo 'pandoc.utils.hierarchicalize { pandoc.Para { pandoc.Str "" } }') <<< '# foo'
Error running filter /dev/fd/63:
Error during function call: could not read argument 1: Could not read list: Could not get Block value: expected table but got nil.

$ pandoc --lua-filter <(echo 'print(pandoc.utils.stringify(pandoc.Header(1, "Testing")))') <<< '# foo'
Error running filter /dev/fd/63:
Error during function call: could not read argument 1: Expected an AST element, but could not parse value as such.

$ pandoc --lua-filter <(echo 'function Header(h) return pandoc.Header(1, "Works") end') <<< '# foo'
<h1>Works</h1>
```

**Comment by tarleb** [comment] 2018-06-03 18:19
Thanks for the testing this, @simonmichael. I'm still stumped. Historically, most problems with hslua were due to faulty assumtions about architecture, so it's likely that this is also what's happening here. (E.g., the hslua test-suite fails when using the *lua_32bits* flag on a amd64 system, which I'm currently working on fixing.) Maybe stack compiles the pandoc binary for 32bit systems, which *might* explain the problem.

Running the hslua test-suite on your machine might be informative.  If it fails on your machine, then we can be reasonably certain that it is not a problem with pandoc but with hslua and move the issue over there.

Also, one more question: what does `print(math.maxinteger)` in a Lua filter give you? Anything different that 9223372036854775807?

**Comment by simonmichael** [comment] 2018-06-03 19:13
Thanks @tarleb. After checking out hslua 0.9.5.2 and bumping the stack resolver to what I have installed (nightly-2018-06-02), I get one failing test:
```
Linking .stack-work/dist/i386-linux/Cabal-2.2.0.1/build/test-hslua/test-hslua ...
hslua-0.9.5.2: copy/register
Installing library in /home/simon/src/hslua/.stack-work/install/i386-linux/nightly-2018-06-02/8.4.3/lib/i386-linux-ghc-8.4.3/hslua-0.9.5.2-gH9adZy92VKG9SDF0Vxog
Registering library for hslua-0.9.5.2..
hslua-0.9.5.2: test (suite: test-hslua)

Progress 19/20: hslua-0.9.5.2hslua
  Haskell version of the C API
...
   C functions
      Registering a C function and calling it from Lua:           FAIL
        test/Foreign/LuaTest.hs:162:
        greeting function failed
        expected: Right ["Caffeine","induced","nonsense"]
         but got: Right []
...
1 out of 113 tests failed (0.58s)
```

math.maxinteger is as expected:
```
$ pandoc --lua-filter <(echo 'function Header(h) return pandoc.Header(1, "Works") end') <<< '# foo'
9223372036854775807
```

**Comment by tarleb** [comment] 2018-06-03 19:44
Thank you, this is most helpful! It seems that the underlying bug is hslua/hslua#63. I'm looking into it.

As a temporary work-around, you could try installing pandoc with `stack install pandoc --flag=hslua:lua_32bits`.

**Comment by simonmichael** [comment] 2018-06-03 23:31
The workaround works! Thank you.

**Comment by tarleb** [comment] 2018-09-24 19:17
We've updated hslua; this should be fixed now.

**Closed by tarleb** 2018-09-24 19:17 UTC
Labels: lua-filters, status:waiting-for-upstream
