### ISSUE TITLE
While converting html to docx using pandoc 1.19.2.1 it gives illegal content on windows MS word and works fine with libreoffice

### ISSUE THREAD

**Issue by dbissa94** [jgm/pandoc#3520] opened 2017-03-21 12:51 UTC
Asking a question?
Please use the pandoc-discuss mailing list instead:
https://groups.google.com/forum/#!forum/pandoc-discuss
This tracker is for bug reports and enhancement requests.

Reporting a bug?
Please include your pandoc version and an example that allows us
to reproduce the problem (complete input, exact command line
used, expected and actual output).  The smaller the example, the
better.

**Comment by jgm** [comment] 2017-03-21 13:53
Sorry, we can't do anything with this bug report.  You need to provide us with a better description of the problem, and detailed instructions on how to reproduce it.

Note that the template text in the issue report is meant to be deleted and replaced by your own description of the issue.  You've just left it.  In this case, the relevant part is:

> Reporting a bug?
> Please include your pandoc version and an example that allows us
> to reproduce the problem (complete input, exact command line
> used, expected and actual output). The smaller the example, the
> better.

Those are your instructions as a bug reporter.

**Comment by jgm** [comment] 2017-03-25 19:20
Closing due to insufficient information.  Feel free to open a new report if you can supply enough information for us to reproduce the problem.

**Closed by jgm** 2017-03-25 19:20 UTC
