### ISSUE TITLE
docx writer: table width

### ISSUE THREAD

**Issue by daroczig** [jgm/pandoc#515] opened 2012-05-18 11:30 UTC
I puzzled why `docx` writer produces a too wide table from a simple table like:

```
h1  h2  h3
--- --- ---
1   2   3
4   5   6
```

I have checked a few times but this table seems to have correct syntax. `pdf` writer produces the table as expected but `docx` ends up with a table really wide so just the first column can be seen on the page.

There are no issues when I try the above example as a "multiline table":

```
-----------
h1  h2  h3
--- --- ---
1   2   3

4   5   6
----------
```

~~Although the header is coerced to be only one character wide so the header's two characters are shown on two lines. (making columns wider solves that)~~ 

I am quite sure I miss something, any help would be really appreciated.

**Comment by omerida** [comment] 2015-02-25 16:54
I can replicate this and it seems to be specific rendering in LibreOffice. My colleagues confirmed that that the table widths are fixed if they view the same DOCX file in Word or Pages.

In LibreOffice Writer, a simple table like the one below, is rendered wider than the page (with a table width of 12" actually).

~~~~
| 100s | 10s | 1s |
|:----:|:---:|:--:|
|   7  |  4  | 7  |
~~~~

While a grid table, has a much smaller overall width.

~~~~
+------+-----+----+
| 100s | 10s | 1s |
+======+=====+====+
|   7  |  4  | 7  |
+------+-----+----+
~~~~

**Comment by arnaldorusso** [comment] 2015-05-14 13:41
I have also evidenced the same problem with libreoffice.
Is there any workaroud that could be fixed inside a template.docx while using `--reference-docx=template.docx`? setting something inside Tables style?

Cheers

**Comment by jgm** [comment] 2015-05-18 17:36
I'll reopen this issue.

Here is the opendocument produced by pandoc for your simple table:
```
<table:table table:name="Table1" table:style-name="Table1">
  <table:table-column table:style-name="Table1.A" />
  <table:table-column table:style-name="Table1.B" />
  <table:table-column table:style-name="Table1.C" />
  <table:table-header-rows>
    <table:table-row>
      <table:table-cell table:style-name="Table1.A1" office:value-type="string">
        <text:p text:style-name="P1">100s</text:p>
      </table:table-cell>
      <table:table-cell table:style-name="Table1.A1" office:value-type="string">
        <text:p text:style-name="P2">10s</text:p>
      </table:table-cell>
      <table:table-cell table:style-name="Table1.A1" office:value-type="string">
        <text:p text:style-name="P3">1s</text:p>
      </table:table-cell>
    </table:table-row>
  </table:table-header-rows>
  <table:table-row>
    <table:table-cell table:style-name="Table1.A1" office:value-type="string">
      <text:p text:style-name="P4">7</text:p>
    </table:table-cell>
    <table:table-cell table:style-name="Table1.A1" office:value-type="string">
      <text:p text:style-name="P5">4</text:p>
    </table:table-cell>
    <table:table-cell table:style-name="Table1.A1" office:value-type="string">
      <text:p text:style-name="P6">7</text:p>
    </table:table-cell>
  </table:table-row>
</table:table>
```

And, for the grid table version:

```
<table:table table:name="Table1" table:style-name="Table1">
  <table:table-column table:style-name="Table1.A" />
  <table:table-column table:style-name="Table1.B" />
  <table:table-column table:style-name="Table1.C" />
  <table:table-header-rows>
    <table:table-row>
      <table:table-cell table:style-name="Table1.A1" office:value-type="string">
        <text:p text:style-name="Table_20_Heading">100s</text:p>
      </table:table-cell>
      <table:table-cell table:style-name="Table1.A1" office:value-type="string">
        <text:p text:style-name="Table_20_Heading">10s</text:p>
      </table:table-cell>
      <table:table-cell table:style-name="Table1.A1" office:value-type="string">
        <text:p text:style-name="Table_20_Heading">1s</text:p>
      </table:table-cell>
    </table:table-row>
  </table:table-header-rows>
  <table:table-row>
    <table:table-cell table:style-name="Table1.A1" office:value-type="string">
      <text:p text:style-name="Table_20_Contents">7</text:p>
    </table:table-cell>
    <table:table-cell table:style-name="Table1.A1" office:value-type="string">
      <text:p text:style-name="Table_20_Contents">4</text:p>
    </table:table-cell>
    <table:table-cell table:style-name="Table1.A1" office:value-type="string">
      <text:p text:style-name="Table_20_Contents">7</text:p>
    </table:table-cell>
  </table:table-row>
</table:table>
```

**Comment by nkalvi** [comment] 2015-05-18 19:38
@jgm 
It looks like the problem happens when a simple table is output as docx (`pandoc simple-table.txt -o simple-table.docx`); when output as OpenDocument (`pandoc simple-table.txt -o simple-table.odt`) it looks fine. 
Perhaps @DawidLoubser can confirm this.

This is what I can see in docx output:

*simple table*
```xml
    <w:body>
        <w:tbl>
            <w:tblPr>
                <w:tblStyle w:val="TableNormal" />
                <w:tblW w:type="pct" w:w="0.0" />
                <w:tblLook w:firstRow="1" />
            </w:tblPr>
```

*grid table*
```xml
    <w:body>
        <w:tbl>
            <w:tblPr>
                <w:tblStyle w:val="TableNormal" />
                <w:tblW w:type="pct" w:w="1319.4444444444446" />
                <w:tblLook w:firstRow="1" />
            </w:tblPr>
```

This is how LibreOffice writes the docx after reformatting the table to have automatic widths:
```xml
    <w:body>
        <w:tbl>
            <w:tblPr>
                <w:tblStyle w:val="TableNormal"/>
                <w:tblW w:w="1392" w:type="dxa"/>
```

So it looks like, when specifying widths for simple tables, either the type should be `w:type="auto"` or if it is `pct` a proper value needs to be given.

I found this helpful: http://officeopenxml.com/WPtableWidth.php

**Comment by nkalvi** [comment] 2015-05-19 00:54
Tested a bit more with LibreOffice (4.4.3.2) - it looks like setting auto-width in table properties doesn't seem to help. It looks like others have also run into the same issue: https://github.com/python-openxml/python-docx/issues/75

I wonder whether bringing this up in LibreOffice forums will help.

In the meantime, Pandoc could set an appropriate value for table width for simple tables.

**Comment by DawidLoubser** [comment] 2015-05-20 16:35
I agree with @nkalvi that some sort of automated setting of table / column widths - even if it's silly defaults (100%, with each column having an equal portion) would be useful.

My particular problems - where my input is docbook XML - have been addressed by explicitly setting table / column widths in the docbook (using %) - tables are now correctly rendered both to PDF (Latex) and to .docx

*You probably get this often, but thank you @jgm for a wonderful piece of software !*

**Comment by jgm** [comment] 2015-05-20 16:53
We can't set the width the same as for the grid table.  Grid tables in pandoc encode information about widths, but simple tables don't.  So we don't have this information.

What about removing the `<w:tblW w:type="pct" w:w="0.0" />` entirely?  Would it work then?

**Comment by nkalvi** [comment] 2015-05-21 05:54
Removing `<w:tblW w:type="pct" w:w="0.0" />` entirely results in same kind of rendering in LibreOffice (4.4.3.2). 

I tried a few different options, but it looks like 'proper' rendering requires a positive value for either the table width or for the column width(s).

**Comment by jgm** [comment] 2016-11-27 20:53
I don't really see a solution to this one.  The current output provides optimal results in docx when viewed with Word.  Word itself computes the optimal size of the simple table (and its columns).  Computing, say, even column widths and hard-coding them would lead to far-less optimal tables in Word.  I don't think it's worth doing that just to get docx tables that will look nice in LibreOffice.

If anyone thinks of a solution, please feel free to reopen this (or another issue linking to it).

**Closed by jgm** 2016-11-27 20:53 UTC
Labels: Format: Docx
