### ISSUE TITLE
Columns of Tables in Latex overlap

### ISSUE THREAD

**Issue by ibutra** [jgm/pandoc#2165] opened 2015-05-20 13:56 UTC
Columns of tables generated in Latex with pandoc overlap as can be seen here:

![tableoverlap](https://cloud.githubusercontent.com/assets/2822422/7727396/c52e2080-ff08-11e4-966e-42c5b0a342d8.png)
This does not depend on the type of table used in markdown.

The line should read like this:

| Reserved | 28:28 | Reserved for future use. Should always be set to 0|

**Comment by jgm** [comment] 2015-05-20 15:14
Please give a specific example we can use to reproduce this:  full input file, full command line, and tell us your pandoc version.  I haven't seen this.

**Comment by ibutra** [comment] 2015-05-30 15:49
Sorry for the delay:

Pandoc Version: 1.13.2.1

I currently can't give you the whole file because it is part of an assignment and I am not allowed to publish it yet, here is an excerpt:

```Markdown
lients should always check the StatusCode and use caution if the returned code is not good.
In detail the bits of the StatusCode are assigned as shown in table \ref{tab:statuscode}:

+------------------+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|      Field       |  Bits |                                                                                                                                        Description                                                                                                                                         |
+==================+=======+============================================================================================================================================================================================================================================================================================+
| Severity         | 31:30 | These bits encode the overall status of the response. The bits are assigned as follows:                                                                                                                                                                                                    |
|                  |       |                                                                                                                                                                                                                                                                                            |
|                  |       | * __Good (00)__: Indicates the request was processed and the response is valid                                                                                                                                                                                                             |
|                  |       | * __Uncertain (00)__: The request was partially successful and the results should be used with caution                                                                                                                                                                                     |
|                  |       | * __Bad Failure (10)__: Processing the request failed and the results can not be used                                                                                                                                                                                                      |
|                  |       | * __Reserver (11)__: This status code is reserved for future use. Should be interpreted as _Bad Failure_                                                                                                                                                                                   |
+------------------+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Reserved         | 29:29 | This bit is reserved for the OPC UA Client API. It must always be 0 if transported over the transport layer but can be set if needed by the API on the Client internally                                                                                                                   |
+------------------+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Reserved         | 28:28 | Reserved for future use. Should always be set to 0                                                                                                                                                                                                                                         |
+------------------+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SubCode          | 16:27 | A numerical value representing different conditions as defined in DIN 62541-6                                                                                                                                                                                                              |
+------------------+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| StructureChanged | 15:15 | This bit indicates whether the structure of the accessed data has changed. The client should re-request the Metadata associated with the value. This bit is set for example if the serialized representation of complex data being requested changed.                                       |
+------------------+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SemanticsChanged | 14:14 | Indicates that the Metadata for this value has changed and needs to be requested by the client. This could happen if the type of a variable changed.                                                                                                                                       |
+------------------+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Reserved         | 12:13 | Reserved for future use. Should always be set to 0                                                                                                                                                                                                                                         |
+------------------+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| InfoType         | 10:11 | Classifies the type of the InfoBits                                                                                                                                                                                                                                                        |
+------------------+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| InfoBits         | 0:9   | Information bits providing additional information. The semantics of these bits depend on the InfoType bits. They can contain information about value errors, e.g. min/max values as well as overflows. In addition, they can hold information about the type of requested historical data. |
+------------------+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

Table: The StatusCode Bitfield [@Anonymous:xgDhjK8r,p. 148] \label{tab:statuscode}

In addition to the StatusCode, the serviceDiagnostics field can provide additional Information about requests processed by the server.
```

As you can see I am using the fignos filter but the problem persists without the filter. To build the document I use this makefile:

```
default:
	pandoc -o paper.tex paper.md --filter pandoc-fignos --biblatex
	pandoc -o abstract.tex abstract.md --biblatex
	sed -i '' 's/autocite/cite/g' paper.tex
	sed -i '' 's/autocite/cite/g' abstract.tex
	sed -i '' 's/includegraphics{F\//includegraphics\[width=\\textwidth\]{/g' paper.tex
	pdflatex -interaction=nonstopmode seminar; bibtex seminar; pdflatex -interaction=nonstopmode seminar;
```

I believe it is a problem with the surrounding template (seminar.tex) which uses the _lni_(that is Lni) documentclass.
Other than that, seminar.tex is a very simple tex file with only 4 usepackages:
```
\documentclass[english]{lni}

\IfFileExists{latin1.sty}{\usepackage{latin1}}{\usepackage{isolatin1}}

\usepackage{graphicx}
\usepackage[utf8]{inputenc}
\usepackage{longtable,booktabs}


\author{author}
\title{\small{Seminar} \\ \vspace{0.5cm} \Large{DIN EN 62541-4: OPC Unified Architecture - \\ Part 4: Services}}

\begin{document}
\maketitle

\begin{abstract}
\input{abstract}
\end{abstract}

\input{paper}

\bibliography{references}

\end{document}
```
And an author tag as well as a title.
Followed by begindocument and \input of my files.

**Comment by jgm** [comment] 2015-05-30 16:54
One thing I notice is that your table is extremely wide.  Since pandoc calculates relative widths, you should use the `--columns` option to give the width in characters of your longest text line.  This should help pandoc to calculate relative widths in a smarter way.  I don't guarantee it will solve your problem, but that's the first thing I'd try.

**Comment by nkalvi** [comment] 2015-05-30 23:16
@jgm 
`--columns` affects only the wrapping of lines in the output; it doesn't affect the table column widths.
Table column widths seem to calculated by `widthsFromIndices`, which doesn't take `--columns` into account.

Parsing.hs:
```haskell
-- Calculate relative widths of table columns, based on indices
widthsFromIndices :: Int      -- Number of columns on terminal
                  -> [Int]    -- Indices
                  -> [Double] -- Fractional relative sizes of columns
widthsFromIndices _ [] = []
widthsFromIndices numColumns' indices =
  let numColumns = max numColumns' (if null indices then 0 else last indices)
```

markdown-reader:
```haskell
    numColumns <- getOption readerColumns
    let widths = if (indices == [])
                    then replicate (length aligns) 0.0
                    else widthsFromIndices numColumns indices
```
So in this case `indices= [0,19,28,313]` and default `readerColumns = 72`, 
results in narrower column widths based on `313`, though the last column will be wrapped.

A sample row from the output (ex. first column's relative width: 19/313 * scaling factor 0.913 = 0.06):
```latex
\begin{minipage}[t]{0.06\columnwidth}\raggedright\strut
StructureChanged
\strut\end{minipage} &
\begin{minipage}[t]{0.03\columnwidth}\raggedright\strut
15:15
\strut\end{minipage} &
\begin{minipage}[t]{0.83\columnwidth}\raggedright\strut
This bit indicates whether the structure of the accessed data has
changed. The client should re-request the Metadata associated with the
value. This bit is set for example if the serialized representation of
complex data being requested changed.
\strut\end{minipage}\tabularnewline
```

Calculating relative widths based on `--columns` would give better results.

**Comment by jgm** [comment] 2015-05-31 19:32
+++ nkalvi [May 30 15 16:16 ]:
>@jgm
>`--columns` affects only the wrapping of lines in the output; it doesn't affect the table column widths.
>Table column widths seem to calculated by `widthsFromIndices`, which doesn't take `--columns` into account.

Yes it does.

>markdown-reader:
>```haskell
>    numColumns <- getOption readerColumns
>    let widths = if (indices == [])
>                    then replicate (length aligns) 0.0
>                    else widthsFromIndices numColumns indices
>```

In pandoc.hs, readerColumns is populated with the value of `--columns`,
defaulting to 72 if this is not specified.

**Comment by nkalvi** [comment] 2015-05-31 20:39
Thanks @jgm, now I see that.
But, as you can see specifying a column size smaller than 313 in this case wouldn't affect the column widths at all. 

Since columns will be wrapped to fit,  column width calculation needs to consider it. 
With proportional fonts, I'm not sure whether specifying `--columns` will fit all cases. 
Allowing a way to specify relative column widths may help in cases like this. 
F.ex. with relative widths *[0.25, 0.09, 0.57]* instead of *[0.06, 0.03, 0.83]* will result in:

![screen shot 2015-05-31 at 4 37 35 pm](https://cloud.githubusercontent.com/assets/2199312/7903733/6e6bd1d0-07b3-11e5-9b0c-3d852b783371.png)

**Comment by jgm** [comment] 2015-06-01 09:26
+++ nkalvi [May 31 15 13:39 ]:
>Thanks @jgm, now I see that.
>But, as you can see specifying a column size smaller than 313 in this case wouldn't affect the column widths at all.
>
>Since columns will be wrapped to fit,  column width calculation needs to consider it.
>With proportional fonts, I'm not sure whether specifying `--columns` will fit all cases.
>Allowing a way to specify relative column widths may help in cases like this.
>F.ex. with relative widths *[0.25, 0.09, 0.57]* instead of *[0.06, 0.03, 0.83]* will result in:

Pandoc calculates relative widths, based on the relative widths in the
source (Markdown) document.  `--columns` is taken into account here: so,
for `--columns=100`, if you have a table with column widths 30, 30, and
20, the relative widths would be [0.3, 0.3, 0.2].  They don't need to
add up to 1, because if the source table is narrower than the text
width, we want that to be respected in the output.

So if the OP wants a table with reasonable column widths, the thing
to do is to reproduce those relative widths in the source document,
instead of having super-long lines for column 3.

**Comment by nkalvi** [comment] 2015-06-01 12:57
@jgm Thank you very much for kindly explaining this - I appreciate it very much.

Though users can reformat super long lines, I think it would be superb if Pandoc can do it for them :smile: 

Here's very a crude attempt at a possible solution, to show what I was suggesting - please take a look when you have time.
```Haskell
widthsFromIndices numColumns' indices =
  let numColumns = max numColumns' (if null indices then 0 else last indices)
      lengths' = zipWith (-) indices (0:indices)
      lengths  = reverse $
                 case reverse lengths' of
                      []       -> []
                      [x]      -> [x]
                      -- compensate for the fact that intercolumn
                      -- spaces are counted in widths of all columns
                      -- but the last...
                      (x:y:zs) -> if x < y && y - x <= 2
                                     then y:y:zs
                                     else x:y:zs
      lengths'' = map (\x -> (if x < numColumns' then x else numColumns')) lengths
      totLength = sum lengths''
      quotient = fromIntegral totLength
      fracs = map (\l -> (fromIntegral l) / quotient) lengths'' in
  tail fracs
```

Trying this with the given case, only the first column needs to be padded slightly (to accommodate very long words) - here's the modified source
```markdown
Clients should always check the StatusCode and use caution if the returned code is not good.
In detail the bits of the StatusCode are assigned as shown in table \ref{tab:statuscode}:



+------------------------+--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|      Field             |  Bits  |                                                                                                                                        Description                                                                                                                                         |
+========================+========+============================================================================================================================================================================================================================================================================================+
| Severity               |  31:30 | These bits encode the overall status of the response. The bits are assigned as follows:                                                                                                                                                                                                    |
|                        |        |                                                                                                                                                                                                                                                                                            |
|                        |        | * __Good (00)__: Indicates the request was processed and the response is valid                                                                                                                                                                                                             |
|                        |        | * __Uncertain (00)__: The request was partially successful and the results should be used with caution                                                                                                                                                                                     |
|                        |        | * __Bad Failure (10)__: Processing the request failed and the results can not be used                                                                                                                                                                                                      |
|                        |        | * __Reserver (11)__: This status code is reserved for future use. Should be interpreted as _Bad Failure_                                                                                                                                                                                   |
+------------------------+--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Reserved               |  29:29 | This bit is reserved for the OPC UA Client API. It must always be 0 if transported over the transport layer but can be set if needed by the API on the Client internally                                                                                                                   |
+------------------------+--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Reserved               |  28:28 | Reserved for future use. Should always be set to 0                                                                                                                                                                                                                                         |
+------------------------+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SubCode                |  16:27 | A numerical value representing different conditions as defined in DIN 62541-6                                                                                                                                                                                                              |
+------------------------+--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| StructureChanged       |  15:15 | This bit indicates whether the structure of the accessed data has changed. The client should re-request the Metadata associated with the value. This bit is set for example if the serialized representation of complex data being requested changed.                                      |
+------------------------+--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SemanticsChanged       |  14:14 | Indicates that the Metadata for this value has changed and needs to be requested by the client. This could happen if the type of a variable changed.                                                                                                                                       |
+------------------------+--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Reserved               |  12:13 | Reserved for future use. Should always be set to 0                                                                                                                                                                                                                                         |
+------------------------+--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| InfoType               |  10:11 | Classifies the type of the InfoBits                                                                                                                                                                                                                                                        |
+------------------------+--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| InfoBits               |  0:9   | Information bits providing additional information. The semantics of these bits depend on the InfoType bits. They can contain information about value errors, e.g. min/max values as well as overflows. In addition, they can hold information about the type of requested historical data. |
+------------------------+--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

Table: The StatusCode Bitfield [@Anonymous:xgDhjK8r,p. 148] \label{tab:statuscode}

In addition to the StatusCode, the serviceDiagnostics field can provide additional Information about requests processed by the server.
```

OP (from `pandoc 2165padded.txt -o 2165padded.pdf`):

![screen shot 2015-06-01 at 8 49 57 am](https://cloud.githubusercontent.com/assets/2199312/7913135/4749bb16-083b-11e5-9c7c-a71efeb33071.png)

**Comment by ibutra** [comment] 2015-06-08 07:54
Hi,

I was able to fix the table by shortening the long lines by hand as suggested. Thank you for that and for the explanations given.

I do agree with @nkalvi however, that this could be done by pandoc.
Furthermore I noticed, if I shorten the lenght of the last column I still get an overlap in the first two columns with the two long *Changed words. This is independent of my --columns setting.

**Comment by nkalvi** [comment] 2015-06-08 10:28
@ibutra It looks like the first column needs to be padded with spaces to avoid overlapping, 
f.ex. <pre>| StructureChanged       |</pre> 
The result seems to be better, as shown in the earlier post. I think some manual padding is needed in some cases, despite the columns setting.

**Comment by jgm** [comment] 2015-06-08 12:17
+++ Stefan Rakel [Jun 08 15 00:54 ]:
>   Hi,
>
>   I was able to fix the table by shortening the long lines by hand as
>   suggested. Thank you for that and for the explanations given.
>
>   I do agree with [1]@nkalvi however, that this could be done by pandoc.
>   Furthermore I noticed, if I shorten the lenght of the last column I
>   still get an overlap in the first two columns with the two long
>   *Changed words. This is independent of my --columns setting.

That's probably because the relative column width is still
so narrow that LaTeX can't fit the words.  Try making this
column a bit wider in the source.

**Comment by lspitzner** [comment] 2019-07-09 23:34
#5639 might be interesting to you. Presuming this is still relevant after a couple of years...

**Comment by stingshen** [comment] 2023-03-06 03:13
If table cell contains referece, the generated table column width may not correct. For example:

```markdown
| Parameter         | Required | Type                                                                             | Description                                               |
| ----------------- | -------- | -------------------------------------------------------------------------------- | --------------------------------------------------------- |
| earlystoppingspec | No       | [org.kubeflow.v1beta1.EarlyStoppingSpec](org.kubeflow.v1beta1.earlystoppingspec) | this is an example description that exceeds column width. |
```

generates:

![image](https://user-images.githubusercontent.com/6214067/223011217-53d22522-7425-4713-ac5b-95e65818ed7a.png)

**Comment by jgm** [comment] 2023-03-06 03:23
See the manual for pipe tables; in this case (when content lines are long) the relative widths will be taken from the separator lines, so you can adjust these as needed without changing the content lines.

**Comment by stingshen** [comment] 2023-03-06 12:07
> See the manual for pipe tables; in this case (when content lines are long) the relative widths will be taken from the separator lines, so you can adjust these as needed without changing the content lines.

Thank you for the reply. But it isn't quite suitable in our use case.

My goal is to automatically convert OpenAPI swagger to PDF. My initial plan is to write a program that converts swagger to markdown, formats with prettier and uses pandoc to generate PDF. It is hard to programatically estimate column width because the character isn't monospaced.

Maybe it isn't the right way to generate PDF...

**Comment by jgm** [comment] 2023-03-06 16:41
@stingshen you might try using reference links; that will help with the width issue.
```
[org.kubeflow.v1beta1.EarlyStoppingSpec]
```
with this later in the doc:

```
[org.kubeflow.v1beta1.EarlyStoppingSpec]: the-url
```

**Comment by Julynx** [comment] 2024-04-03 08:28
A possible workaround is to use the following CSS to force columns to automatically adjust their width:

```css
/* style.css */
col {
  width: auto !important;
}
```

Then passing `--css style.css`

This only works from MD -> HTML -> PDF though. 

If your workflow is MD -> Latex -> PDF you'll have to find another solution.

**Comment by jgm** [comment] 2024-04-03 15:44
Closing this, since pandoc is behaving as documented and there's no clear suggestion for any change.

**Closed by jgm** 2024-04-03 15:44 UTC
Labels: format:Markdown, reader
